### ISSUE TITLE
issue with GCP HPA

### ISSUE THREAD

**Issue by marklonquist** [DataDog/datadog-agent#10182]
Hi

We have the following metric query:
`avg:gcp.pubsub.subscription.num_undelivered_messages{project_id:HIDDEN,subscription_id:HIDDEN}.rollup(30)`

Working fine in datadog (notebook here):
![image](https://user-images.githubusercontent.com/1456819/145595869-eea74645-b7c1-41b3-aad7-57cd43d19730.png)

however, we keep getting errors on our HPA:
`unable to get external metric default/datadogmetric@default:bt-olympus-inventory-svc-num-undelivered-messages/nil: unable to fetch metrics from external metrics API: Internal error occurred: DatadogMetric is invalid, err: Outdated result from backend, query: avg:gcp.pubsub.subscription.num_undelivered_messages{project_id:oHIDDEN,subscription_id:HIDDENt}.rollup(30)`

our datadog metric:
```apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: $CIRCLE_PROJECT_REPONAME-num-undelivered-messages
  namespace: $CLUSTER_NAMESPACE
spec:
  query: avg:gcp.pubsub.subscription.num_undelivered_messages{project_id:HIDDEN,subscription_id:HIDDEN}.rollup(30)
```

and our HPA:
```apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: $CIRCLE_PROJECT_REPONAME
  namespace: $CLUSTER_NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $CIRCLE_PROJECT_REPONAME
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: External
    external:
      metric:
        name: datadogmetric@$CLUSTER_NAMESPACE:$CIRCLE_PROJECT_REPONAME-num-undelivered-messages
      target:
        type: AverageValue
        averageValue: 10
```

What we are trying to do is get the current average undelivered messages (averaged by number of pods) and then scale if we go above a given threshold.

Any help is appreciated. :-)

**Comment by marklonquist** [comment]
okay so it seems like it's actually a correct query, but it's only valid while there is messages in the subscription.

Is there a way to make it return "0" if the query is not returning anything, so the HPA is always valid?

**Comment by vboulineau** [comment]
Hey @marklonquist,

The issue is probably because the metrics you're using is coming from GCP Crawlers. You'll need to extend the max age to match this. Change the `external_metrics_provider.max_age` variable to `600` (default value is `120`, in seconds).
