### ISSUE TITLE
log4j vulnerability not fixed in 7.32.3-jmx image

### ISSUE THREAD

**Issue by Pacobart** [DataDog/datadog-agent#10252]
We need an image with log4j patched to 2.16.0

Scan results of the datadog/agent:7.32.3-jmx image from dockerhub show log4j 2.12.2 is installed.

![Screen Shot 2021-12-15 at 5 09 42 PM](https://user-images.githubusercontent.com/10999360/146284384-0426ee37-256f-4c6a-a756-e451f7bbfa1c.png)

**Comment by mscanlon72** [comment]
I believe this was called out by Datadog [here](https://www.datadoghq.com/log4j-vulnerability/).

**Comment by sgnn7** [comment]
@Pacobart See my comment about 2.12.2 [here](https://github.com/DataDog/datadog-agent/issues/10221#issuecomment-994219011) but I think the main issue here is that the scanners haven't yet updated their definitions about the [2.12.2 version not being vulnerable to this CVE](https://logging.apache.org/log4j/2.x/). 

I'll close this issue for now but feel free to reopen if I missed something.

**Comment by sgnn7** [comment]
Hey @Pacobart,
Following up here with an update that we have just released [agent versions `7.32.4` and `6.32.4`](https://github.com/DataDog/datadog-agent/releases) that completely remove `log4j` as a dependency from `jmxfetch` which should make the scanners much happier.
