### ISSUE TITLE
Segfault when using the Docker integration

### ISSUE THREAD

**Issue by macat** [DataDog/datadog-agent#1030]
When using the latest docker image (beta 7), I am getting the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xbe258a]

goroutine 100 [running]:
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*DockerCollector).processEvent(0xc4203da570, 0x0)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_main.go:97 +0x7a
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*DockerCollector).Stream(0xc4203da570, 0x7fb85a4751a0, 0xc4203da570)
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/docker_main.go:68 +0x9f
created by github.com/DataDog/datadog-agent/pkg/tagger.(*Tagger).registerCollectors
	/builds/datadog/datadog-agent/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/tagger.go:185 +0x436
```

**Describe what happened:**
Deployed Datadog agent in a Kubernetes 1.8.6 cluster. (Docker 0.13)

**Describe what you expected:**
Running agent

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes 1.8.6
Kops 1.8
Docker 0.13

**Comment by CharlyF** [comment]
Hey @macat, thank you for opening this up!

That's interesting, I believe we will need to look into the logs from your agent(s).

Could you confirm how you deployed the agent(s) ? (is it through a Daemonset ?)

The best would be to share your manifest with us as well as send over a `flare`. The flare is a bundle of logs and configs that is forwarded to our support team for us to get more context around the issue.
You can create a flare by running: `sudo -u dd-agent -- datadog-agent flare <caseid>` 
_leave caseid empty if you don't have a case open with us already._

Thanks again.
.C

**Comment by xvello** [comment]
`processContainerEvent` can return [a `nil` event with a `nil` error](https://github.com/DataDog/datadog-agent/blob/6.0.0-beta.7/pkg/util/docker/event_pull.go#L46). We should also check `event == nil` and `continue` instead of sending it in the channel, like we do in [events_pull.go](https://github.com/DataDog/datadog-agent/blob/6.0.0-beta.7/pkg/util/docker/event_pull.go#L113-L116)

**Comment by macat** [comment]
Config is here: https://github.com/DataDog/datadog-agent/issues/1037

Usually the container fails after a few minutes, but there were nodes without a failure after roughly a day. On some nodes the agent failed over 200 times.

```
NAME                                                    READY     STATUS             RESTARTS   AGE
dd-agent-44v6v                                          1/1       Running            50         1d
dd-agent-84hvl                                          1/1       Running            53         9h
dd-agent-8bj92                                          0/1       CrashLoopBackOff   214        1d
dd-agent-94f8x                                          1/1       Running            78         9h
dd-agent-9mmbf                                          1/1       Running            0          1d
dd-agent-dwk8h                                          1/1       Running            197        1d
dd-agent-f5sf4                                          1/1       Running            2          1d
dd-agent-g6bc8                                          1/1       Running            0          1d
dd-agent-jj2s9                                          1/1       Running            0          1d
dd-agent-jkcm8                                          0/1       CrashLoopBackOff   224        1d
```

**Comment by CharlyF** [comment]
Hey @macat, thanks a bunch.
I was able to reproduce the issue - This should fix it https://github.com/DataDog/datadog-agent/pull/1041.

We just released a build for the beta, but the next beta will embed this fix (coming up in the next few days).
In the meantime, I built a backport with the fix
`datadog/agent-dev:tagger-nil-event-processing`.

I can confirm that this fixed the problem on my end, would you mind trying it out ?

Sorry for the headache and thank you for bringing it up to our attention.

**Comment by macat** [comment]
I can confirm, this is fixed. Not seeing failures after 10 minutes.
