### ISSUE TITLE
Panic with "sync: unlock of unlocked mutex"

### ISSUE THREAD

**Issue by michaeleisel** [DataDog/datadog-agent#10401]
I'm running datadog-agent via serverless-plugin-datadog version 3.4.0 (not sure what version of datadog-agent, but that's the latest version of serverless-plugin-datadog). I saw the following crash occur recently for an AWS Lambda job, out of the blue, with "sync: unlock of unlocked mutex": https://gist.github.com/michaeleisel/b49e22ed771d511003f37adb2b03f94b

**Comment by maxday** [comment]
Thanks for reporting this @michaeleisel
The full panic error log is definitely super helpful. 
We will look into it and be back to you

**Comment by sapei** [comment]
I also got the same exception like @michaeleisel. The logs can be seen on https://gist.github.com/sapei/dc6c2c58e287a02554e69992ce1542b7. 

I use a container image with AWS Lambda. My compiled golang codes is added to the base image public.ecr.aws/lambda/provided:al2. Additionally I download the datadog extension from the lambda layer (arn:aws:lambda:eu-central-1:464622532012:layer:Datadog-Extension:16) and put the executable datadog-agent under /opt/extensions/.

In my golang codes, I use github.com/DataDog/datadog-lambda-go version 1.3.0.

**Comment by nhinsch** [comment]
Hi @michaeleisel and @sapei, we believe this issue should be fixed in version 17 of the Lambda extension. Please let us know if you continue to observe the issue.

**Comment by nhinsch** [comment]
@michaeleisel If you are using Serverless plugin, update to version 3.5.0 to include the new version of the Lambda extension.

**Comment by michaeleisel** [comment]
🙏
