### ISSUE TITLE
Serverless Agent Crash - There's a race between the Daemon and Server Workers

### ISSUE THREAD

**Issue by cube2222** [DataDog/datadog-agent#10524]
**Describe what happened:**
The Daemon crashes with a fairly cryptic index out of bounds error.

After digging through the code it looks like the default Flushing strategy will do a periodic metrics ServerlessFlush() which just directly runs flush() on all the workers. The workers are normally working during that and handling samples.

This way even though the worker processes are reading from channels and are single threaded, ServerlessFlush() additionally causes a parallel flush to happen on all workers. This gets down to directly operating on Sample Batches without any synchronization from 2 threads simultaneously.

In our case it happens a few times per million invocations and brings the whole Lambda down with it, which almost immediatelly kills the processing of the current invocation in the underlying Lambda handler.

We'll probably be able to fix it for ourselves by setting the DD_SERVERLESS_FLUSH_STRATEGY to `end`, thus removing the concurrent non-synchronized flushing.

In practice - if I diagnosed the issue well - this can be solved by:
1. Adding a mutex for synchronization.
2. Sending the forced flush to the workers over a channel, like all other messages (packets and stop) reach them.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/7013055/149216259-67bb87d3-c126-4a5a-929b-709cdfa22206.png">

**Steps to reproduce the issue:**
It's a race, it'll probably be hard to reproduce without running millions of executions on Lambda.

**Comment by sgnn7** [comment]
@cube2222 Thanks for reporting this. What agent version is the screenshot referring to?

**Comment by cube2222** [comment]
The Lambda extension public.ecr.aws/datadog/lambda-extension:16 @sgnn7

**Comment by cube2222** [comment]
@sgnn7 Hey, just wanted to bump this as it's a critical issue for us. The Serverless Agent is basically broken - we're getting panics because of this issue regularly, crashing our Lambdas mid-execution.

The `end` flushing strategy doesn't help that much either (which is fairly obvious after understanding how it works), and results in an abysmal performance overhead (tripling execution time for fast Lambdas).

Please prioritize this, even if only with a stopgap solution - adding a mutex around the offending slice operations. We'd like to avoid having to fork the datadog agent to make it work.

**Comment by nhinsch** [comment]
Update from our side: we are actively investigating this issue and we hope to fix this as soon as we can.

**Comment by nhinsch** [comment]
Hi @cube2222, this issue should be fixed in extension v21. Please let us know if you continue to see any panics.
