### ISSUE TITLE
ddnpm.sys (Datadog Network Filter) version 1.2.1.0 crashed windows 2012r2 Server

### ISSUE THREAD

**Issue by harrypuru** [DataDog/datadog-agent#10551]
One of windows Server crashed and memory dump pointed to datadog network filter driver,
0: kd:arm64> lmvm ddnpm
Browse full module list
start             end                 module name
fffff806`bb610000 fffff806`bb653000   ddnpm      (no symbols)           
    Loaded symbol image file: ddnpm.sys
    Image path: \??\C:\Program Files\Datadog\Datadog Agent\bin\agent\driver\ddnpm.sys
    Image name: ddnpm.sys
    Browse all global symbols  functions  data
    Timestamp:        Thu Aug 19 10:34:19 2021 (611DE653)
    CheckSum:         00047256
    ImageSize:        00043000
    Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4
    Information from resource tables:
Machine is not a possible execution machine
Unable to get current machine context, HRESULT 0x8000FFFF

**Comment by brycekahle** [comment]
@harrypuru We fixed a problem with the NPM Windows driver in `7.34.0` if you want to give that version a try. If you still experience the issue, then please contact our support where you can send them a crash dump.

**Comment by harrypuru** [comment]
Thanks @brycekahle. Even after upgradation to 7.34.0 system crashed resurfaced. Thanks, Harry
