### ISSUE TITLE
Installation of datadog-agent is not providing full overview of kubernetes resources

### ISSUE THREAD

**Issue by nickkostov** [DataDog/datadog-agent#10608]
**Describe what happened:**
I have installed the datadog agent following this documentation: https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset 

I have tried the three installation types but with no luck.

Currently deployment happens through terraform for the agent but not all functionalities are working.

**Describe what you expected:**
I am expecting when I go to datadog application to see pods, clusters, Deployments, Replica Sets and other kubernetes related resources. I can only see containers.

**Steps to reproduce the issue:**

Follow guideline for Daemon set:

https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset 

**Additional environment details (Operating System, Cloud provider, etc):**

We are provisioning our cluster with Amazon EKS, I am not looking forward monitoring AWS resources only the EKS resources that are on it.

**Comment by kaitlavs** [comment]
Hi @nickkostov 

Enabling the collection of resources through the orchestrator explorer requires having both the process-agent and cluster-agent running, as well as enabling `DD_ORCHESTRATOR_EXPLORER_ENABLED` and updating the cluster agent RBAC. The instructions for this can be found here: https://docs.datadoghq.com/infrastructure/livecontainers/configuration/?tab=daemonset#kubernetes-resources

If the daemonset you are using already contains all the information mentioned in the above documentation, then the cluster-agent container and process-agent container logs will be able to provide more insight into what might be occurring. A common error is: `Orchestrator explorer enabled but no cluster name set: disabling`. Please make sure you have configured `DD_CLUSTER_NAME` if the agents cannot automatically detect one.

If you need additional assistance, please reach out to [our support team](https://docs.datadoghq.com/help/) with a description of this issue. We will require [a flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7#dedicated-containers) from both the process-agent container and the cluster agent container. Thanks!

**Comment by nickkostov** [comment]
Hey, I have enabled both of these features but still over here I do not find anything:
![image](https://user-images.githubusercontent.com/35745114/152769620-2110e711-19fe-44a7-a033-871fa4f71e39.png)

**Comment by nickkostov** [comment]
I have managed to install both the datadog agent and cluster agent using terraform. 
Now it is working as intended. Thank you for the attention!

**Comment by lin-weichen** [comment]
hey @nickkostov , could you tell more about how did you install both the datadog agent and cluster agent using terraform? Thank you!
