### ISSUE TITLE
Better logging for all datadog agent

### ISSUE THREAD

**Issue by xvello** [DataDog/datadog-agent#1061]
The current logging logic we use has a number of issues, for example:

- Not easy to process: https://github.com/DataDog/datadog-agent/issues/971
- High volume and inconsistent levelling: https://github.com/DataDog/datadog-agent/issues/1049

Although everyone tries to leave the codebase in a better state every day (see https://github.com/DataDog/datadog-agent/pull/963), we need to:

- improve our current logging facilities to make them easier to read and filter (for users, support and developpers)
- have common guidelines describing what should be logged at what level, to have a consistent level of information
- share this code and logging style across all agents so the overall user experience is consistent

This issue is here as a central point of discussion on this topic. Every contributor should list here:

- the things the current facility does well for them
- their current pain points (as a developper / as a user)
- improvements that should be considered

**Comment by xvello** [comment]
## Good points
- everything goes to `stdout`, easy to collect in dockerized setups

## Current pain points
- volume in `debug` level is way too high, I develop with `Warnf`s that I downgrade before merging
- some warning/errors are to be downgraded to info/debug
- `grep`-ing the logs to look for AD debug lines is pretty hard, as only the file name is prefixed. We should add package and/or topic information to grep efficiently

## Potential improvements
- memory profiling shows `Debugf` incurs mallocs even if the log level is set to `info`. Might just be a configuration issue, but should be tested in the selected logging facility

**Comment by mfpierre** [comment]
## Current pain points

* For the `diagnose` command [we're replacing the logger](https://github.com/DataDog/datadog-agent/blob/c7e5cd2d1f20e7ff79617a42c10e695a99032a0d/pkg/diagnose/runner.go#L25-L32) to redirect the output to a writer and by doing this we can capture "other" logs not diagnose related, some sort of channel system might help.

* The current logging configuration is XML-based and IMHO it's a [pain point as well](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/log.go#L43-L76)

## Potential improvements

* Colorizing output 🌈 (possible with current logger, but tedious config)

**Comment by mfpierre** [comment]
Most of consistency issues have been fixed for 6.11 let's close this and interate on the common logger if improvements are needed
