### ISSUE TITLE
Bug in order of precedence used to load python checks

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/datadog-agent#1064]
### Bug

When a custom check is in `/etc/datadog-agent/checks.d`, we expect it to be loaded with a higher precedence than a check shipped as a wheel. Instead, the agent currently loads the wheel-packaged check with a higher precedence.

This bug has been there for quite some time, but is only really noticeable on a regular install of the agent since we started shipping `integrations-core` checks as wheels in #1048 (so in particular it doesn't really affect the latest `beta.8`).

### Cause

The bug is here: https://github.com/DataDog/datadog-agent/blob/6.0.0-beta.8/pkg/collector/py/loader.go#L55-L60

For a `foo` check, the python loader always tries to load the `datadog_checks.foo` module before the `foo` module. That logic doesn't work well because we actually want to load custom checks with a higher precedence than wheel-packaged checks.

### Potential fix

Unfortunately I don't see an easy fix to this, the only ways I see would be to either:
* stop relying on a regular python import to load python checks, or
* first check if the module is present in the custom checks' folder to determine which module name should be imported, and then try to import that module

Both fixes sound pretty ugly to me to be honest. Any other ideas @truthbk?

**Comment by masci** [comment]
This is an issue only if you try to overwrite a core check with a custom module - the current behaviour is correct, a custom check should not share the name with a core check or if it does, it should be ignored. This is a requirement to introduce the secured update mechanisms for core checks.

**Comment by olivielpeau** [comment]
If this is the expected behavior, let's make sure that it's well documented as this is a pretty significant breaking change from Agent 5 (and previous beta releases of Agent 6). We ourselves override core-provided checks with custom checks on our own deployment of the Agent on our infra, and I know it's something our support team often suggests to customers.

@masci: could you expand a bit more on why this behavior is a requirement for the secure updates of core checks? I'm not sure I understand how the 2 are related.

**Comment by masci** [comment]
Looped back with product security, this is not a requirement for the secure wheels project actually, sorry for the noise.

Let's focus on discussing how breaking would it be releasing the current implementation and what does it mean to add the feature back.

**Comment by olivielpeau** [comment]
After discussion, we've determined that the order of precedence of checks we want for Agent 6, going forward, is roughly:

1. wheel-packaged checks in core locations
2. bundled checks in core locations
3. custom check locations

This basically means that a custom check should _not_ have the same name as a core-provided check anymore.

We have to do 2 things for `beta.9`:
1. fix the behavior on master: it's a bit inconsistent because custom check locations have precedence over bundled checks in core locations
2. document the change in the repo's docs

Assigning this to @truthbk, but feel free to re-assign to me if you don't have the time to take care of it.

**Comment by olivielpeau** [comment]
#1087 has made the behavior consistent on master.

I'll work on documenting this breaking change before `beta.9` is out.
