### ISSUE TITLE
How to check logs agent metrics?

### ISSUE THREAD

**Issue by kei6u** [DataDog/datadog-agent#10685]
Hi,
How can I see these logs agent metrics?

https://github.com/DataDog/datadog-agent/blob/fc37bdd247d9147ad1d7953df4004c9a5963c912/pkg/logs/metrics/metrics.go#L14-L76

I'm glad if you just tell me the documentations.

**Comment by sgnn7** [comment]
Hi @kei6u!

As you can tell from the code prefixes, these are `expvar`s. They should be available as JSON on `http://localhost:5000/debug/vars`. Keep in mind though that this URL doesn't work outside of the machine that the agent is running on unless specifically configured for it. 

I'll close this issue but feel free to reopen if that didn't answer your question.

**Comment by kei6u** [comment]
@sgnn7 
Thank you your quick response. I will try it.

Btw, could you tell me why you don't support sending logs agent metrics to the backend like [APM metrics sent by the Datadog Agent](https://docs.datadoghq.com/tracing/troubleshooting/agent_apm_metrics/#pagetitle)? 
Actually, I want to add this feature, if it is acceptable.

I sometimes want to check these metrics on the Datadog UI because these metrics help to isolate whether there is a problem with the Agent or the datadog backend when logs disappearances happen.

**Comment by sgnn7** [comment]
@kei6u It is possible to do this so if you want to send this data, you should be able to use an [`expvar`s check](https://docs.datadoghq.com/integrations/go_expvar/?tab=host) to scrape and forward them as metrics but there may be a cost to sending this data. You can also [generate some simple metrics about logs on the backend already](https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/).

**Comment by kei6u** [comment]
@sgnn7 
You suggestions can help me, but they needs implementations.

Here is my context of this request.
Customers sometime ask supports why logs were disappeared. In this case, many of them don't implement [Generate Metrics from Ingested Logs](https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/) and [expvars check](https://docs.datadoghq.com/integrations/go_expvar/?tab=host) yet. Besides, even if they implement it after trouble, I don't think the metric can be used for troubleshooting.
I would appreciate logs metrics which we can use it just by installing the agent. It really help troubleshooting.

I would like to get [existing logs metrics](https://github.com/DataDog/datadog-agent/blob/fc37bdd247d9147ad1d7953df4004c9a5963c912/pkg/logs/metrics/metrics.go#L14-L76) via [DogStatsD](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent#pagetitle) like [APM metrics](https://github.com/DataDog/datadog-agent/blob/7f09e26e56c9a6fcff362f93a9e16c9698d06243/pkg/trace/metrics/client.go#L23-L25).

I thought I'd create a PR, but I'd like to check first if you agree with my idea.
I would appreciate your advice! 😊
