### ISSUE TITLE
build on ARM

### ISSUE THREAD

**Issue by blasagna** [DataDog/datadog-agent#1069]
**Describe what happened:**
Attempting to build the project on a Raspberry Pi 3 resulted in these errors:
```
~/go/src/github.com/DataDog/datadog-agent $ invoke agent.build --build-exclude=snmp
# github.com/DataDog/datadog-agent/pkg/collector/py
pkg/collector/py/datadog_agent.go:148: type [1073741824]*C.char larger than address space
pkg/collector/py/datadog_agent.go:148: type [1073741824]*C.char too large
```

Is it currently possible to compile on (32-bit) ARM platforms, or cross-compile for them?

**Comment by masci** [comment]
@blasagna yes that's possible even if through an undocumented feature (docs will come soon).

You can build what we call the "Puppy Agent", a lightweight version of the full Agent that cross compiles to different platforms at the price of having less features (most notably, the Python engine is missing, meaning you can't execute Python checks on Puppy).

To build the Puppy:
```
~/go/src/github.com/DataDog/datadog-agent $ invoke agent.build --puppy
```

You can cross compile like any other Go project:
```
~/go/src/github.com/DataDog/datadog-agent $ GOOS=linux GOARCH=arm GOARM=5 invoke agent.build --puppy
```

Let me know if this helps, we want ARM architectures to be first-class citizens so any feedback is appreciated!

**Comment by tuangeek** [comment]
I had a similar problem
`pkg/collector/py/datadog_agent.go:148: type [1073741824]*C.char larger than address space
pkg/collector/py/datadog_agent.go:148: type [1073741824]*C.char too large`

But building Puppy worked:
```
invoke agent.build --puppy
Successfully wrote /home/pi/go/src/github.com/DataDog/datadog-agent/cmd/agent/dist/datadog.yaml
```

Thanks @masci

**Comment by blasagna** [comment]
Thanks @masci , building puppy worked for me as well

**Comment by masci** [comment]
Cool, closing for now, feel free to re-open if you experience issues on the ARM platforms.

**Comment by tmcgann** [comment]
I attempted to cross-compile from my Mac and experienced a different issue:

```bash
$ env GOOS=linux GOARCH=arm GOARM=5 invoke agent.build
go build github.com/DataDog/datadog-agent/vendor/github.com/sbinet/go-python: build constraints exclude all Go files in /Users/taylor/projects/go/src/github.com/DataDog/datadog-agent/vendor/github.com/sbinet/go-python
```

But once I added the `--puppy` option, the build worked for me as well.

**Comment by probert-mtv** [comment]
For the record, I have the same problem on a i686 box (Debian 8.11) with Go 1.10.3. i386.

```
# invoke agent.build --build-exclude=snmp,systemd
# github.com/DataDog/datadog-agent/pkg/collector/py
pkg/collector/py/datadog_agent.go:159: type [1073741824]*_Ctype_char larger than address space
pkg/collector/py/datadog_agent.go:159: type [1073741824]*_Ctype_char too large
pkg/collector/py/datadog_agent.go:263: type [1073741824]*_Ctype_char larger than address space
pkg/collector/py/datadog_agent.go:263: type [1073741824]*_Ctype_char too large
```

Building the Puppy version works.
