### ISSUE TITLE
Reno linting might not run on all PRs

### ISSUE THREAD

**Issue by xvello** [DataDog/datadog-agent#1078]
If CircleCI already ran its pipeline for a given git commit, it won’t re-run when we open a PR. That means the reno linting will not run if there’s no commit after creating the PR.

**Comment by hush-hush** [comment]
If there are no PR, we don't check that a new release note has been committed but we do lint all the existing ones. Worst case scenario: a PR is merged without release notes.

We could try to see if one was committed in a diff with master, but some PR aren't based on master.

What do you think ?

**Comment by xvello** [comment]
Indeed, I don't think failing on master is worth our time.
I'd go with communicating that as a current known issue (we can pretty easily check during review), but keeping it in mind if for the next time we work on that topic.

**Comment by masci** [comment]
Also this https://discuss.circleci.com/t/circle-pull-request-not-being-set/14409 doesn't seem as likely to happen, but it could happen
