### ISSUE TITLE
datadog-agent should listen on udp6 ::1:8125

### ISSUE THREAD

**Issue by DanielOliverRJ** [DataDog/datadog-agent#10828]
**Describe what happened:**

1. We used `localhost` as the target for our sending our stats to the Datadog agent.
2. Sometimes `localhost` is resolved as `::1` instead of `127.0.0.1`.  Stats sent to `::1` are not received by the Datadog.

**Describe what you expected:**

I would expect Datadog to bind to the udp6 port, so that stats sent to `::1:8125` are be processed in the same way as stats updates sent to `127.0.0.1:8125`

I suspect this would also apply to other listeners, but haven't checked.

**Steps to reproduce the issue:**

Success: `echo -n "custom_metric:60|g|#shell" >/dev/udp/127.0.0.1/8125`
Failure: `echo -n "custom_metric:60|g|#shell" >/dev/udp/::1/8125`

**Additional environment details (Operating System, Cloud provider, etc):**

CentOS 7 and 8

**Comment by sgnn7** [comment]
Hi @DanielOliverRJ,
The agent uses whatever address gets resolved by `localhost` on the machine which can be non-deterministic in some circumstances between IPv4 and IPv6 and `localhost` can be invalid in IPv6 contexts. Can you ensure your agent uses an [explicit `bind_host` address](https://github.com/DataDog/datadog-agent/blob/729162b115e91331040de46450626cdd28ef1ece/pkg/config/config_template.yaml#L1586-L1587) instead of `localhost` and see if that fixes your issue?

**Comment by DanielOliverRJ** [comment]
Hi @sgnn7,

I can confirm that if I change `bind_host` to `::1`, then udp6 packets are processed, but udp4 packets are not.  My expectation would be that both would work.

I'm not familiar with the quirks of golang.  When I wrote the ticket, I had assumed the fix would be a case of setting a dual-stack flag on the listening socket.  Having Googled since, it looks like the [ListenUDP()](https://github.com/DataDog/datadog-agent/blob/0454961e636342c9fbab9e561e6346ae804679a9/pkg/dogstatsd/listeners/udp.go#L62) would work as expected if was just listening on the wildcard socket, but I can't see if there is a correct answer for binding to just `localhost`.

This is clearly an issue you're aware of, so I'll let you resolve as you see fit.

**Comment by ioquatix** [comment]
I spent several days trying to figure out why this isn't working on my default IPv6 system (`localhost` -> `::1`).

It seems like without `dogstatsd_non_local_traffic: true`, metrics are accepted but ignored.


Submitting metrics to `127.0.0.1` works but submitting them to `localhost`, while appears to work, actually fails.

Is it safe to set `dogstatsd_non_local_traffic: true`?
