### ISSUE TITLE
AWS EKS: logs and metrics hostname is set to ec2 instance id instead of pod name

### ISSUE THREAD

**Issue by rarecrumb** [DataDog/datadog-agent#11000]
I'd like to be able to prefer the kubernetes pod name instead of the EC2 instance id everywhere the "hostname" tag is set.

**Output of the info page (if this is a bug)**
```
  Hostnames
  =========
    cluster-name: x
    ec2-hostname: ip-10-0-1-56.us-west-2.compute.internal
    host_aliases: [ip-10-0-1-56.us-west-2.compute.internal-x]
    hostname: i-09688e9c3c636a6a2
    instance-id: i-09688e9c3c636a6a2
    socket-fqdn: datadog-z4m6g
    socket-hostname: datadog-z4m6g
    host tags:
      cluster_name:x
      kube_cluster_name:x
    hostname provider: aws
    unused hostname providers:
      azure: azure_hostname_style is set to 'os'
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: GCE metadata API error: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname
```

**Describe what happened:**
When running in Kubernetes, logs and metrics default to the EC2 instance id as the "hostname".

**Describe what you expected:**
I expect logs and metrics to show the pod name as the "hostname" tag.

**Steps to reproduce the issue:**
Install datadog helm chart and enable logging, metric collection and process collection.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, EKS, datadog helm chart, v7 agent, etc

**Comment by mikebryant** [comment]
We have a similar issue

Per [the eks docs](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html):

> Amazon EC2 [resource-based naming](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-rbn) is not supported with Amazon EKS. You must use IP address-based naming for your subnets and instances.

So all of our EC2 hosts are set to use IP address-based naming, and we'd like the Datadog view of this to match Kubernetes.

It's causing issues for us with our opentelemetry data, which has the host-name coming through correctly matching the EC2 settings of IP-based names, and now in Datadog it can't match up the processes to the traces as the hostnames are different.

We'd like the hostname to show up as the ec2-hostname
