### ISSUE TITLE
Feature: Ingest journald logs from boot

### ISSUE THREAD

**Issue by nairb774** [DataDog/datadog-agent#11072]
**Describe what happened:**

Right now when using the [journald log source](https://docs.datadoghq.com/integrations/journald/?tab=containerized), it seems to only start picking up logs from the point in time that the agent first starts.

Assuming I followed the code correctly (big if), it looks like this observation is corroborated by this code: https://github.com/DataDog/datadog-agent/blob/55da4f3c2a2dfce0f7e57c1fcb5c590636c53a88/pkg/logs/internal/tailers/journald/tailer.go#L123

**Describe what you expected:**

Some way to configure where the journald log source starts from so we can get logs from the "very beginning", or as close to as possible.

For deeper context, we are running the agent as a daemon set on kubernetes, with the desire to use it to pull in host level logs off the Bottlerocket OS node. This means that the datadog agent starts running some period of time after the node starts[1], and it would be useful to have the logs pulled in from the start of the host. We have been seeing instances where nodes are taking longer than average (few extra minutes) to get into a working state, but with no easy access to the earlier logs, we don't really have visibility into _why_ the node might be misbehaving. It would be possible to break into the node, but having the logs always available would be a great step forward.

In addition to the greater debugging ability, having logs covering the whole boot would improve visibility into verifying the correct state of the system from a security and integrity perspective.

**Additional environment details (Operating System, Cloud provider, etc):**

Agent is running as a DaemonSet on Bottlerocket OS nodes using a EKS 1.19 control plane.

**Comment by gh123man** [comment]
Thanks for the feature request. This should be possible and your use case makes sense. 
We are tracking this and I'll update this thread when we implement it.

**Comment by gh123man** [comment]
This will be available in `7.38.0`
