### ISSUE TITLE
Missing changelog for DCA 1.18 and 1.19

### ISSUE THREAD

**Issue by grosser** [DataDog/datadog-agent#11183]
see https://github.com/DataDog/datadog-agent/blob/main/CHANGELOG-DCA.rst
1.18 is out and 1.19 is rc-2 but no changelog added

**Comment by CharlyF** [comment]
Hi @grosser - That's my bad, I have both:
1.18 https://github.com/DataDog/datadog-agent/pull/11138
1.19 https://github.com/DataDog/datadog-agent/commit/db4987f4e502dea29b320764dd6c856d95b16db2

I will merge (and rebase) as soon as the code base is unfrozen. Thanks for opening this.

**Comment by CharlyF** [comment]
Published the releases and merged the changelogs. Thanks again for the report.
