### ISSUE TITLE
Permission denied when collecting Docker logs from file

### ISSUE THREAD

**Issue by sugovsek** [DataDog/datadog-agent#11473]
**Describe what happened:**

After configuring the host agent to collect Docker logs, it fails to do so because

```
open /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log: permission denied
```

And there are no logs in Datadog. I find this a bit confusing, since the documentation states:

> The Agent tails containers from the Docker socket if it cannot access the logs file path.

And then:

> Docker container log collection from a file is an alternative to collection over the Docker socket. File based collection offers better performance than socket based collection.

> In versions 7.27.0/6.27.0+, you can configure the Agent to collect Docker container logs from a file. In versions 6.33.0+/7.33.0+, the Agent collects Docker container logs from a file by default.

And then:

> Note: When you install the Agent on the host, the Agent does not have permission to access /var/lib/docker/containers. Therefore, the Agent collects logs from the Docker socket when it is installed on the host.

According to the logs, the above doesn't seem to be the case - it tries to access  `/var/lib/docker/containers`. If this is because of the above comment (_In versions 6.33.0+/7.33.0+, the Agent collects Docker container logs from a file by default_), then this needs to be clarified.

Also, if the host agent _should_ collect from the files, it needs to be clarified how to resolve the issue with permissions.

The agent user is otherwise added to the `docker` group, can connect to Docker socket and seems to be collecting container metrics without any issues.

**Steps to reproduce the issue:**

- install host agent from source based on the generated bash script on the website: `DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=*** DD_SITE="datadoghq.eu" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"`
- change the `datadog.yaml` to the following:
```
logs_enabled: true
listeners:
    - name: docker
config_providers:
    - name: docker
      polling: true
logs_config:
    container_collect_all: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

OS: CentOS Linux release 8.3.2011

```
datadog-agent version
Agent 7.34.0 - Commit: 7861858 - Serialization version: v5.0.9 - Go version: go1.16.12
```

**Comment by djmitche** [comment]
The check for access is [here](https://github.com/DataDog/datadog-agent/blob/44e648f89681de7de16b3de249fdb022e44fb09f/pkg/logs/input/docker/launcher_nix.go#L24-L34), specifically looking for 'x' access on the directory itself.  Is there some other issue that might be preventing access, which isn't captured by that check?

Note that you can force the socket by setting `logs_config.docker_container_use_file` to false.

**Comment by sugovsek** [comment]
I got it to work by using the above setting, thanks. I'd still prefer it if it read from the log files though, for better performance.

The warn initially described actually comes from: https://github.com/DataDog/datadog-agent/blob/7.34.x/pkg/logs/input/file/scanner.go#L268

Full relevant logs:
```
Mar 28 18:45:07 cs8-o19.localdomain agent[3955484]: 2022-03-28 18:45:07 CEST | CORE | INFO | (pkg/logs/input/file/scanner.go:350 in handleTailingModeChange) | Tailing mode changed for file:/var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log. Was: end: Now: beginning
Mar 28 18:45:07 cs8-o19.localdomain agent[3955484]: 2022-03-28 18:45:07 CEST | CORE | INFO | (pkg/logs/input/file/scanner.go:265 in startNewTailer) | Starting a new tailer for: /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log (offset: 0, whence: 0) for tailer key /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28
Mar 28 18:45:07 cs8-o19.localdomain agent[3955484]: 2022-03-28 18:45:07 CEST | CORE | INFO | (pkg/logs/input/file/tailer_nix.go:29 in setup) | Opening /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log for tailer key /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28
Mar 28 18:45:07 cs8-o19.localdomain agent[3955484]: 2022-03-28 18:45:07 CEST | CORE | WARN | (pkg/logs/input/file/scanner.go:268 in startNewTailer) | open /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log: permission denied
```

**Comment by djmitche** [comment]
Interesting that it passed the check I linked (for /var/lib/docker/containers) and failed the next. What are the permissions on /var/lib/docker/containers and /var/lib/docker/containers/40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28?

**Comment by sugovsek** [comment]
Level 1:
```
drwx-----x.  5 root root  4096 Mar 28 22:15 containers
```

Level 2:
```
drwx-----x. 4 root root 4096 Mar 24 10:30 40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28
drwx-----x. 4 root root 4096 Mar 28 16:47 9bcfeef7ae00769bd1e2a097b71e47181cd4f1807faa778cf67507f897d24e68
drwx-----x. 4 root root 4096 Dec  6 17:30 cf99c6014f7592343a867541d494e31df28de3b51ce3ecb9cac89ccc898c12b2
```

Level 3:
```
-rw-r-----. 1 root root 89782 Mar 28 22:30 40d5a91c5f6e490bfac5f7abb2a7098e8552a5c6e01155026b3e7129bb5e2d28-json.log
drwx------. 2 root root  4096 Mar 24 10:30 checkpoints
-rw-------. 1 root root  4149 Mar 24 10:30 config.v2.json
-rw-r--r--. 1 root root  1526 Mar 24 10:30 hostconfig.json
-rw-r--r--. 1 root root    13 Mar 24 10:30 hostname
-rw-r--r--. 1 root root   174 Mar 24 10:30 hosts
drwx-----x. 3 root root  4096 Mar 24 10:30 mounts
-rw-r--r--. 1 root root    38 Mar 24 10:30 resolv.conf
-rw-r--r--. 1 root root    71 Mar 24 10:30 resolv.conf.hash
```

**Comment by atonse** [comment]
We have the same issue. We're using vanilla docker but all our containers are deployed by Nomad. Does that matter? I hope not.

**Comment by djmitche** [comment]
Apologies for missing the followup here!  There's a lot of traffic on this repo, so sometimes things slip by :(

I have the following locally:
```
root@tereshkova:~# ls -ald /var/lib/docker/containers
drwx--x--- 8 root root 4096 May 24 17:55 /var/lib/docker/containers
root@tereshkova:~# ls -ald /var/lib/docker/containers/1b4f*
drwx--x--- 4 root root 4096 May 26 19:59 /var/lib/docker/containers/1b4f3d4b7d5f5bef18d84323230ab0df6032897a5920bbb810e6d03795fd91df
```
and the difference appears to be in the group permissions?  It seems that `checkReadAccess` succeeded on your system because, indeed, it has o+x (which is an unusual permission!).  On my system, running the agent on the host itself, I have to put the agent user in the `root` group.  But, I think the more common way to run the agent in a Docker environment is to run it in its own container, mounting `/var/lib/docker/containers` into that container.  The agent runs as root within the container, so it can read the files that way.

It seems there are two fixes here:
 * update the permissions on those files to include `rx` for the user running the agent (either g+rx and ensure the user is in that group, or o+rx)
 * the access check should be checking for `rx`; if it did so, it would fail in this situation and fall back to socket tailing.  But, again, `x` without `r` is pretty unusual!

**Comment by djmitche** [comment]
Closing as it seems that correcting the permissions on the docker directories is the right fix here, or if that's difficult, switching to socket mode (`logs_config.docker_container_use_file: false`)
