### ISSUE TITLE
Is there have benchmark between udp and unixsock?

### ISSUE THREAD

**Issue by zdyj3170101136** [DataDog/datadog-agent#12141]
I want to choose one protocol between udp and unixsock.
And there is not enough evidence to make me decision.

**Comment by sgnn7** [comment]
Hi @zdyj3170101136,
DogstatsD over unix socket (UDS) is more performant, has better error messages, and better suited for high-throughput scenarios. The benchmarks are highly sensitive to the type of deployment and the clients you may be using but to answer your question overall UDS is able to noticeably process metrics faster.

I'll close this question but feel free to reopen if needed.
