### ISSUE TITLE
Strange "X: telemetry.Proxy: http: proxy error:" logs appearing in our lambda logs

### ISSUE THREAD

**Issue by ahernandez2-rbi** [DataDog/datadog-agent#12448]
I'm tracking down some error log entries that are coming up in DataDog:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/93784872/174438478-edc61fb7-8698-4576-a986-ba3286723723.png">

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/93784872/174438695-c7e38d25-e790-48a5-b99d-0c7e2c8a6d80.png">

Based on the log message this looks like a Go message, so I wanted to check if it could be coming from the DataDog agent. Our app is written in Node and hosted in AWS Lambda using the DataDog Lambda Layers.

If this is the DD Agent, is it really an error? If not, how can I suppress it? It is quite verbose as you can tell from the second graph.

**Comment by tianchu** [comment]
@ahernandez2-rbi Thanks for your report! You can safely ignore those telemetry.Proxy errors, they are noises. We are going to disable that in next release (PR WIP) of dd-trace-js. Meanwhile if you want to avoid the noises, you can set env var `DD_TRACE_TELEMETRY_ENABLED` to `false` on your Lambda functions.
