### ISSUE TITLE
polling metrics postgresql.locks through datadog agent

### ISSUE THREAD

**Issue by DharveshAtish** [DataDog/datadog-agent#12588]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
postgresql.locks metric weren't showing up for lock happening on pg% tables which arguably shouldn't be excluded from the lock query. i understand and conceive that it should exclude postgresql dictionary tables but not pg% (for instance, when testing with pg_bench, you can have table like pgbench_branches, pgbench_history etc...), but you can also have normal table starting 'pg', even if i agree its not best practice.

see below for the lock query that datadog-agent used.

`SELECT mode,
       locktype,
       pn.nspname,
       pd.datname,
       pc.relname,
       count(*) AS lock_count
  FROM pg_locks l
  JOIN pg_database pd ON (l.database = pd.oid)
  JOIN pg_class pc ON (l.relation = pc.oid)
  LEFT JOIN pg_namespace pn ON (pn.oid = pc.relnamespace)
 WHERE {relations}
   AND l.mode IS NOT NULL
   AND pc.relname NOT LIKE 'pg_%%'
 GROUP BY pd.datname, pc.relname, pn.nspname, locktype, mode with relations matching: ( relname ~ '.*' AND relkind = ANY(array['r','p']) );`

**Describe what you expected:**
The underscore wildcard (_) in `NOT LIKE 'pg_%%'` is used to represent one character or number, it should be escape like this `NOT LIKE 'pg\_%%'` 

**Steps to reproduce the issue:**
should be reproducible though any datadog-agent querying a PostgreSQL database for lock metrics.

**Additional environment details (Operating System, Cloud provider, etc):**
[os / kernel]
CentOS Linux release 7.9.2009 (Core)
Linux 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[Datadog-agent]
Agent 7.36.0 - Commit: c1180f8 - Serialization version: v5.0.19 - Go version: go1.17.6

[postgresql server version]
 PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**Comment by alexandre-normand** [comment]
Hey @DharveshAtish ! Thanks for the bug report. I created an internal ticket for this and we'll update the issue when it's fixed. You're also welcome to submit a PR if you feel so inclined but the bug report is already very much appreciated ❤️ .

**Comment by EmmaOnThursday** [comment]
hi @DharveshAtish! A fix for this has been merged. Thanks again for the careful bug report, we really appreciate it.
