### ISSUE TITLE
Windows Server 2019 - Performance Counter Errors Created Every 15 Seconds

### ISSUE THREAD

**Issue by abner-diaz** [DataDog/datadog-agent#12899]
[Agent_Status__20220728.txt](https://github.com/DataDog/datadog-agent/files/9208063/Agent_Status__20220728.txt)

**Output of the info page (if this is a bug)**
```
Version: 7.37.1 
Flavor: agent 
PID: 7892 
Check Workers: 4 
Agent start: 2022-07-28 04:26:59.223 CDT / 2022-07-28 09:26:59.223 UTC (1659000419223) 
Log Level: info 
Config File: C:\ProgramData\Datadog\datadog.yaml 
Conf.d Path: C:\ProgramData\Datadog\conf.d 
Checks.d Path: C:\ProgramData\Datadog\checks.d 
```

**Describe what happened:**
We're getting a significant amount of errors in the Event Logs when DataDog Agent is running.

![image](https://user-images.githubusercontent.com/94029731/181480726-ea0dc2c9-68cc-4600-bdf2-67625aa089ca.png)

![image](https://user-images.githubusercontent.com/94029731/181481809-9c02a8ef-8b58-4f2f-a9c0-f6939fb42437.png)

```
The Open procedure for service "WmiApRpl" in DLL "C:\WINDOWS\system32\wbem\wmiaprpl.dll" failed with error code The device is not ready.. Performance data for this service will not be available.

Unable to open the Server service performance object. The first four bytes (DWORD) of the Data section contains the status code.

The Open procedure for service "WmiApRpl" in DLL "C:\WINDOWS\system32\wbem\wmiaprpl.dll" failed with error code The device is not ready.. Performance data for this service will not be available.
```
**Describe what you expected:**
No errors.

**Steps to reproduce the issue:**
We've installed 7.37.1 running as a domain service account.  It has been joined to the local Performance Monitor group.

**Additional environment details (Operating System, Cloud provider, etc):**
Windows Server 2019

**Comment by abner-diaz** [comment]
This looks a lot like https://github.com/DataDog/datadog-agent/issues/11145.

**Comment by VAndreyuk** [comment]
Same here after updating to version 7.38.0.1 

![image](https://user-images.githubusercontent.com/27011310/181664200-058b3f17-1d70-4119-ada1-f0a25c8f727d.png)

Can confirm that downgrading to 7.33.1 helps. 

Thank you @abner-diaz for saving my time on broken version search!

**Comment by abner-diaz** [comment]
How is this completed? The issue persists even after the fix in https://github.com/DataDog/datadog-agent/issues/11145 was implemented.

**Comment by iglendd** [comment]
@abner-diaz this is a bit nuanced issue, the explanation, plans and work around is mentioned in the other issue comment https://github.com/DataDog/datadog-agent/issues/13605#issuecomment-1258546654
