### ISSUE TITLE
Debian agent installation failed due to sudo: command not found

### ISSUE THREAD

**Issue by LuWang1983** [DataDog/datadog-agent#12929]
**Describe what happened:**
Hi, we currently use Datadog as our observability tool. 
We run our apps in docker containers and deploy them to Google cloudrun (Fully Managed and I'm aware that the AMP feature is not supported). We wanted to try to install the agent in the dockerfile to collect traces (that is, if the agent is supported that way).

We use `debian:bullseye-slim` in a base image for our docker builds. Each application pulls the base image and runs separately as a cloudrun service. See below for code snippet.
Dockerfile.base:
```
FROM debian:bullseye-slim as audiowaveform-builder
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        cmake \
        curl \
...
```
Dockerfile for one application:
```
FROM base image url
ENV NODE_ENV=production

# install Datadog agent to collect traces
RUN DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=<emitted> DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
```
**Describe what you expected:**
I expect the docker build to succeed with Datadog agent successfully installed. 

**Steps to reproduce the issue:**
We use nx build for docker build. When I run it, I get the following error (See screenshot). 
I read the install script and it seems like it removes the `$sudo_cmd` prefix if it's empty or the output is `command not found`, but the error suggested that it hit the else statement in the next line with the `$sudo_cmd` prefix again, which I believe exits the script. 
![Screen Shot 2022-07-31 at 11 26 28 AM](https://user-images.githubusercontent.com/63315158/182051555-120117c3-b282-47e9-9ed4-9ad50d8dcdca.png)

Not sure if this is a known issue or if it's the debian version. Would love to get some help on this. Thank you!

**Additional environment details (Operating System, Cloud provider, etc):**
I ran the install script for mac OsX on my computer and it succeeded as expected. And I can open the agent gui.

**Comment by djmitche** [comment]
Does installing sudo in the Docker image work around the issue?

**Comment by LuWang1983** [comment]
Sorry this issue may be stale. Installing sudo requires access to the container shell because it requires a password or root permission and it's just not the best practice when running docker containers. Also, unfortunately we use cloudrun fully managed service for our infrastructure and it doesn't give us the access to the container shell. We are pulling in OpenTelemetry to solve our tracing data in cloudrun. Closing this issue as there's not much Datadog can do at this point.

**Comment by LuWang1983** [comment]
I was at the Dash conference and discovered that now Datadog allows the agent to be installed with the containerized application on CloudRun. I missed the demo so am not sure how exactly it works but that's a pretty exciting improvement.
