### ISSUE TITLE
pkg/trace/watchdog: TestCPUHigh flaky

### ISSUE THREAD

**Issue by katiehockman** [DataDog/datadog-agent#12944]
`TestCPUHigh` appears to be flaky in the CI. It failed when run against https://github.com/DataDog/datadog-agent/pull/12850

```
=== Failed
=== FAIL: watchdog TestCPUHigh (1.02s)
    info_test.go:62: CPU (1 goroutines): {0.3192979730441577}
    info_test.go:68: 
        	Error Trace:	/Users/runner/go/src/github.com/DataDog/datadog-agent/pkg/trace/watchdog/info_test.go:68
        	            				/Users/runner/go/src/github.com/DataDog/datadog-agent/pkg/trace/watchdog/info_test.go:73
        	Error:      	Condition failed!
        	Test:       	TestCPUHigh
        	Messages:   	cpu avg is too low, got 0.319298
```

Some questions from discussion with @knusbaum 
> I've seen the last one (TestCPUHigh) failing on the mac os runs, but nowhere else. It raises a bunch of questions:
> - What does the UserAvg CPU measure? Is it fraction of one core or fraction of the entire CPU?
> - Is the loop actually hitting the CPU how we expect? There's a select statement in there that could be causing the loop to run much slower than we expect.
> - If we're burning 1 core, why do we expect .5 to be the average?
> - Are we measuring the same thing on different platforms. Does 0.5 on linux mean the same thing as 0.5 on mac?
>
> As a summary, what are we trying to measure, and are we actually measuring it? Also, is it valuable to make this measurement at all, or should we just eliminate these tests?

**Comment by ajgajg1134** [comment]
## Bottom line up front
I think the only value of this test is ensuring that we aren't accidentally using percents as whole integers, e.g. mixing `0.25` and `25`. This test makes some assumptions about how to pin a core at 100% that I don't believe are true all the time making this test flaky. I will make a PR that keeps the core value of the test but makes it far less flakey.

## Answers to questions

- What does the UserAvg CPU measure? Is it fraction of one core or fraction of the entire CPU?

The comments on UserAvg CPU indicate it's core based measurement. Meaning a value of `1` indicates total usage of a single core, on a multicore machine the userAvg could be up to the total number of cores.

- Is the loop actually hitting the CPU how we expect? There's a select statement in there that could be causing the loop to run much slower than we expect.

It seems like this definitely does do a good amount of work (Tested locally), but I suppose depending on other parallel workloads and the go routine scheduler it could possibly be doing less work

- If we're burning 1 core, why do we expect .5 to be the average?

I think the idea is that we can't be sure we're burning a full core so the program uses `.5` as a middleground that it expects the number to be larger than at _least_ that. I think the comment "A very simple ++ loop should be enough to stimulate one core and make it over 50%" is an assumption that can periodically fail making this test flaky.

- Are we measuring the same thing on different platforms. Does 0.5 on linux mean the same thing as 0.5 on mac?

It appears we are measuring the same things, we rely on https://github.com/shirou/gopsutil for fetching the user avg cpu usage on our process and it appears to be consistent in defining 0.5 as half of a single core (as defined by "user time" by `time` utilities) Admittedly the documentation for this in OSX / MacOS is incredibly limited so it's possible this is wrong, but it doesn't appear to be.
