### ISSUE TITLE
[ network metric ] Can't find corresponding network metrics in 'Metric Explorer'

### ISSUE THREAD

**Issue by BlueBlue-Lee** [DataDog/datadog-agent#12962]
I've been experimenting with datadog recently. AndI find some issues.

In 'Network performance' dashboard，you use metrics `sum:network.bytes_written`， but I can't find the metric in 'Metric Explorer' dashboard.

Could you please tell me the reason?

**Comment by djmitche** [comment]
Hi $github_user, thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the datadog-agent open source repository. For your request, please contact our [support](http://docs.datadoghq.com/help/), who may be better able to answer your question.

Thanks.
