### ISSUE TITLE
[BUG] Serverless key retrieval functions passed in wrong order

### ISSUE THREAD

**Issue by mattcanty-ikigai** [DataDog/datadog-agent#13068]
**Agent Environment**
Introduced here: https://github.com/DataDog/datadog-agent/pull/12155
Serverless v27 (probably introduced earlier)

**Describe what happened:**
The extension was printing some weird log, pointing me in the direction of KMS. After exhausting that route, I started looking at the codebase of the extension/agent to see exactly what was happening.

I found this line here, which is a duplicate of the line above:
https://github.com/DataDog/datadog-agent/blob/43b360c5d1d415a2c0e2d534a167119706fbaf03/cmd/serverless/env.go#L42 Where it says KMS, it should say SecretsManger (I raised PR for this - https://github.com/DataDog/datadog-agent/pull/13067). This is why I was spending time looking at KMS.

But then I also noticed that the passing of functions is in the wrong order.

**Describe what you expected:**

**This**
https://github.com/DataDog/datadog-agent/blob/43b360c5d1d415a2c0e2d534a167119706fbaf03/cmd/serverless/env.go#L60
**Should be this**
`for envKey, envVal := range getSecretEnvVars(envVars, readAPIKeyFromKMS, readAPIKeyFromSecretsManager) {`

**Steps to reproduce the issue:**
None

**Additional environment details (Operating System, Cloud provider, etc):**
AWS/Lambda/Python

**Comment by IvanTopolcic** [comment]
Thanks for the report! I can see how this bug in particular could have been a nightmare and I'm sorry for the debugging experience 😅 

I've gone ahead and opened a [PR that fixes this](https://github.com/DataDog/datadog-agent/pull/13075), as well as ran tests on your PR. I'll try to merge them in by the end of the day.

**Comment by mattcanty-ikigai** [comment]
Thanks @IvanTopolcic 

What do you think the turn around is likely to be on the merged change making it to a release in https://github.com/DataDog/datadog-lambda-extension ?

**Comment by IvanTopolcic** [comment]
I think you can expect a release for this on Monday as we're under a code freeze currently.
