### ISSUE TITLE
[BUG] fatal error: dogstatsd agent container restart

### ISSUE THREAD

**Issue by rahul342** [DataDog/datadog-agent#13112]
**Agent Environment**
Agent 7.38.0 - Commit: 253542c - Serialization version: v5.0.23 - Go version: go1.17.11

**Describe what happened:**
Recently updated to the latest agent and noticed restarts. Hasn't been too often but seems like some race condition?

```
fatal error: concurrent map iteration and map write

goroutine 427 [running]:
runtime.throw({0x4daa46f, 0x0})
	/goroot/src/runtime/panic.go:1198 +0x71 fp=0xc000a45568 sp=0xc000a45538 pc=0x1896351
runtime.mapiternext(0xc000a455f0)
	/goroot/src/runtime/map.go:858 +0x4eb fp=0xc000a455d8 sp=0xc000a45568 pc=0x186d94b
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).updateChecksTelemetry(0xc000cba840)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/aggregator/aggregator.go:815 +0xa9 fp=0xc000a45680 sp=0xc000a455d8 pc=0x3868e49
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).Flush(0xc000cba840, {{{0xc0b523aae722608c, 0x5dff8de71c4d, 0x78fb640}, 0xc005f400c0, 0x0}, {0x555dbe0, 0xc003468f80}, {0x555dbc0, 0xc003468e80}})
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/aggregator/aggregator.go:669 +0x15f fp=0xc000a45708 sp=0xc000a45680 pc=0x386755f
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).run(0xc000cba840)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/aggregator/aggregator.go:688 +0x49a fp=0xc000a45fc8 sp=0xc000a45708 pc=0x3867afa
github.com/DataDog/datadog-agent/pkg/aggregator.(*AgentDemultiplexer).Run·dwrap·16()
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/aggregator/demultiplexer_agent.go:266 +0x26 fp=0xc000a45fe0 sp=0xc000a45fc8 pc=0x386d4a6
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000a45fe8 sp=0xc000a45fe0 pc=0x18cb3e1
created by github.com/DataDog/datadog-agent/pkg/aggregator.(*AgentDemultiplexer).Run
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/aggregator/demultiplexer_agent.go:266 +0x33b

goroutine 1 [chan receive, 1722 minutes]:
github.com/DataDog/datadog-agent/cmd/agent/app.run(0x77890e0, {0x4d18259, 0x0, 0x0})
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/app/run.go:157 +0x20d
github.com/spf13/cobra.(*Command).execute(0x77890e0, {0x7e63e08, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x7785c60)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/main.go:19 +0x25
```
Full logs. 
[agent.log.tar.gz](https://github.com/DataDog/datadog-agent/files/9329204/agent.log.tar.gz)

**Describe what you expected:**
No restarts

**Steps to reproduce the issue:**
Not sure.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS

**Comment by scottopell** [comment]
This looks similar to an issue that has a pending fix in https://github.com/DataDog/datadog-agent/pull/13110

Do you have the config option `dogstatsd_metrics_stats_enable` set to `true`? (You can confirm with `agent config`)
If so, could you try disabling it and see if the issue goes away?

**Comment by rahul342** [comment]
@scottopell thank you for checking!

`dogstatsd_metrics_stats_enable` is set to `false` per `agent config`

Separately, twice I have gotten `CrashLoopBackOff` on `agent` with port 5555 already in use. Deleting the pod made the error go away after k8s started a new pod. I was waiting for it to happen again to report, but wondering if this too has been reported already? (couldn't find while searching issues)

Thank again!

**Comment by scottopell** [comment]
Ah, seems to be a slightly separate issue then. If you could open a support ticket we can investigate this more.

As to your second issue, I'm not aware of any existing reports for that, do you only see that occur after the agent has crashed due to the `concurrent map` error?

**Comment by rahul342** [comment]
> Ah, seems to be a slightly separate issue then. If you could open a support ticket we can investigate this more.

Sure thing.


> As to your second issue, I'm not aware of any existing reports for that, do you only see that occur after the agent has crashed due to the concurrent map error?

Don't think so.
