### ISSUE TITLE
Agent health health check via exposing HTTP health check port DD_HEALTH_PORT

### ISSUE THREAD

**Issue by wkul9429** [DataDog/datadog-agent#13123]
I running the Datadog agent in an AWS ECS instance along with my java application container. I have the following configs set for Datadog agent container {"ECS_FARGATE":true,"DD_HEALTH_PORT":5555}. 

I am doing a health check of datadog agent from my application container via a rest-client. since the multiple containers within a task are in awsvpc

I want to know if it is a bad practice or a better way to do it.

Sample response

` "Healthy": [
        "healthcheck",
        "tagger-pull",
        "ad-config-provider-container",
        "metadata-host",
        "metadata-agent_checks",
        "metadata-inventories",
        "aggregator",
        "workloadmeta-store",
        "ad-servicelistening",
        "ad-containerprovider",
        "metadata-resources",
        "tagger-store",
        "ad-ecsfargatelistener",
        "collector-queue-15s",
        "dogstatsd-main",
        "workloadmeta-puller",
        "tagger-workloadmeta",
        "collector-queue-20s"
    ],
    "Unhealthy": null`

**Comment by ahmed-mez** [comment]
Hi @wkul9429 

Thanks for the question! Looks like ECS can do that for you based on [this documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_HealthCheck.html). 

The Agent sample tasks documented [here](https://docs.datadoghq.com/integrations/ecs_fargate/?tab=awscli) don't provide a health config example. This is something we will improve!

**Comment by wkul9429** [comment]
Thank @ahmed-mez isn't there a way to check the agent container status (healthy, up and running) inside the ECS container via application container, since my application docker container has a depends on configuration for datadog-agent agent as below

          DependsOn:
            - Condition: HEALTHY
              ContainerName: datadog-agent

**Comment by ahmed-mez** [comment]
I think it's a question for ECS, but the [ECS metadata API](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint.html) can give you info about the containers in the task.

In any case, I'd recommend that you rely on the built-in ECS functionalities (i.e the [ECS health checker](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-healthcheck.html)) to the check the Agent's health and status.

I'm going to close this issue as I believe the initial question has been answered, thanks! :)

**Comment by cahillsf** [comment]
hi @wkul9429! wanted to reach back out to let you know that we have a health check configuration documented for the Datadog agent container in [Fargate for the EC2 launch type](https://docs.datadoghq.com/containers/amazon_ecs/?tab=awscli#create-an-ecs-task)(step 4), and have added the health check to our docs for the Fargate launch type in [this PR](https://github.com/DataDog/integrations-core/pull/12854)
