### ISSUE TITLE
Compile agent without SystemD

### ISSUE THREAD

**Issue by skhaz** [DataDog/datadog-agent#13127]
Is it possible to compile Datadog's agent without SystemD?

Currently, I have the following error

```
#12 24.91 # github.com/coreos/go-systemd/sdjournal
#12 24.91 /root/go/pkg/mod/github.com/coreos/go-systemd@v0.0.0-20180202092358-40e2722dffea/sdjournal/journal.go:27:11: fatal error: systemd/sd-journal.h: No such file or directory
#12 24.91    27 | // #include <systemd/sd-journal.h>
#12 24.91       |           ^~~~~~~~~~~~~~~~~~~~~~
#12 24.91 compilation terminated.
```

**Comment by scottopell** [comment]
It is possible, you should be able to exclude the `systemd` build tag as described [here](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/agent_build.md#be-modular)

eg: `invoke agent.build --build-exclude=systemd,python`

**Comment by skhaz** [comment]
Thank you!
