### ISSUE TITLE
[BUG] agent status output is displayed as log

### ISSUE THREAD

**Issue by jbfavre** [DataDog/datadog-agent#13187]
With Datadog agent 7.38.2, `agent status` output is displayed as a regular log.
This make json output processing harder

**Agent Environment**
`agent version`
> Agent 7.38.2 - Commit: ba442fd - Serialization version: v5.0.23 - Go version: go1.17.11

`agent status --json`
> 2022-08-22 11:45:12 UTC | CORE | INFO | (cmd/agent/app/status.go:163 in requestStatus) | {[VERY LONG JSON OBJECT],"version":"7.38.2"}

**Describe what happened:**

We're using Datadog  agent deployed in kubernetes. A common way to get agent status is to use following command:
```
kubectl  exec -ti datadog-agent -c agent -- agent status --json
```
With 7.38.2, I have to:
* specify DD_LOG_LEVEL to ensure LOG_LEVEL is either DEBUG or INFO (our agent use DD_LOG_LEVEL=WARNING which prevent `agent status` output to be displayed.
* Since agent status output is displayed as a regular log, I have to parse the output to remove the log "prefix" `2022-08-22 11:45:12 UTC | CORE | INFO | (cmd/agent/app/status.go:163 in requestStatus) | ` before getting a json object and being able to process it.

**Describe what you expected:**
* When using the `--json` command line option, I expect to get straight a json object I can process without doing anything more.
* When invoquing the status command, I expect to get the output displayed, no matter the DD_LOG_LEVEL value.

**Comment by sgnn7** [comment]
Hi @jbfavre,
This issue is already known and [has been fixed](https://github.com/DataDog/datadog-agent/pull/13117) in the repository. The fix is included as part of Agent v7.39.0 release which should be available soon. I'll close this issue since there's nothing to be done but feel free to reopen it if needed.
