### ISSUE TITLE
[BUG] can't build datadog-agent image

### ISSUE THREAD

**Issue by yutingcaiyt** [DataDog/datadog-agent#13283]
**Agent Environment**
7.34.0, my computer is mac

**Describe what happened:**
when I follow the https://docs.datadoghq.com/agent/guide/build-container-agent/?tab=amd to build a datadog-agent image, it fails with following information：
 > [release  1/17] RUN apt update   && apt full-upgrade -y   && apt install -y iproute2 libssl-dev   && rm -f /usr/sbin/runuser   && rm -f /usr/lib/x86_64-linux-gnu/libdb-5.3.so:
#6 1.044 
#6 1.044 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#6 1.044 
#6 1.836 Ign:1 http://archive.ubuntu.com/ubuntu impish InRelease
#6 2.760 Ign:2 http://security.ubuntu.com/ubuntu impish-security InRelease
#6 2.921 Ign:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease
#6 3.004 Err:4 http://security.ubuntu.com/ubuntu impish-security Release
#6 3.004   404  Not Found [IP: 91.189.91.39 80]
#6 3.188 Ign:5 http://archive.ubuntu.com/ubuntu impish-backports InRelease
#6 3.492 Err:6 http://archive.ubuntu.com/ubuntu impish Release
#6 3.492   404  Not Found [IP: 185.125.190.39 80]
#6 3.727 Err:7 http://archive.ubuntu.com/ubuntu impish-updates Release
#6 3.727   404  Not Found [IP: 185.125.190.39 80]
#6 4.718 Err:8 http://archive.ubuntu.com/ubuntu impish-backports Release
#6 4.718   404  Not Found [IP: 185.125.190.39 80]
#6 4.731 Reading package lists...
#6 4.832 E: The repository 'http://security.ubuntu.com/ubuntu impish-security Release' does not have a Release file.
#6 4.832 E: The repository 'http://archive.ubuntu.com/ubuntu impish Release' does not have a Release file.
#6 4.832 E: The repository 'http://archive.ubuntu.com/ubuntu impish-updates Release' does not have a Release file.
#6 4.832 E: The repository 'http://archive.ubuntu.com/ubuntu impish-backports Release' does not have a Release file.

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by marceloboeira** [comment]
@yutingcaiyt this seems to be the same as: https://github.com/DataDog/datadog-agent/issues/12855

**Comment by yutingcaiyt** [comment]
In my case, I want to build the image by cloning the repository, not run the existed image. And after I cloning the repository, I've tried to checkout 7.38.0 which should  be the new version, but it still goes wrong. So in this case, I think the Dockerfile may need to modify.

**Comment by marceloboeira** [comment]
Yes, the version of ubuntu is not supported anymore. You can add a setup to the Dockerfile to fix the sources with:

```Dockerfile
...
RUN sed -i 's|\/archive\.ubuntu\.com|/old-releases.ubuntu.com|g' /etc/apt/mirrorlist
RUN apt update
...
```

It needs to be before `apt update` otherwise it doesn't work.

**Comment by yutingcaiyt** [comment]
I've tried to add this into Dockerfile, this is DockerFile I changed from version 7.34.0：
`FROM ubuntu:21.10 AS baseimage
ARG CIBUILD
RUN if [ "$CIBUILD" = "true" ]; then \
  sed -i 's#http://archive.ubuntu.com#http://us-east-1.ec2.archive.ubuntu.com#g' /etc/apt/sources.list; \
  fi
RUN sed -i 's|\/archive\.ubuntu\.com|/old-releases.ubuntu.com|g' /etc/apt/sources.list
RUN apt update

COPY faccessat/faccessat.c   /tmp/faccessat.c
COPY faccessat/faccessat.sym /tmp/faccessat.sym
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y gcc
RUN gcc -pipe -Wall -Wextra -O2 -shared -o /tmp/libfaccessat.so /tmp/faccessat.c -Wl,--version-script=/tmp/faccessat.sym
`
but when I build, it shows error like this：
`E: The repository 'http://security.ubuntu.com/ubuntu impish-security Release' does not have a Release file.
W: GPG error: http://old-releases.ubuntu.com/ubuntu impish InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://old-releases.ubuntu.com/ubuntu impish InRelease' is not signed.
W: GPG error: http://old-releases.ubuntu.com/ubuntu impish-updates InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://old-releases.ubuntu.com/ubuntu impish-updates InRelease' is not signed.
W: GPG error: http://old-releases.ubuntu.com/ubuntu impish-backports InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://old-releases.ubuntu.com/ubuntu impish-backports InRelease' is not signed.`

it mentions that gpgv should be installed, but I have tried to add 'apt install gpgv' before or after the "RUN sed -i 's|\/archive\.ubuntu\.com|/old-releases.ubuntu.com|g' /etc/apt/sources.list", it didn't work.

**Comment by yutingcaiyt** [comment]
I resolved the previous problem, but it still can't complete.

Step 24/57 : RUN find / -maxdepth 1 -type f -name 'datadog-agent*_amd64.deb' ! -name "$DD_AGENT_ARTIFACT" -exec rm {} \;  && find / -maxdepth 1 -name 'datadog-agent*_amd64.deb' -exec dpkg -X {} . \; | egrep '.*'  && rm -rf usr etc/init lib     opt/datadog-agent/sources     opt/datadog-agent/embedded/share/doc     opt/datadog-agent/embedded/share/man     opt/datadog-agent/embedded/lib/libcurl.so.4.4.0     usr/lib/x86_64-linux-gnu/libsystemd.so.0.21.0     opt/datadog-agent/embedded/lib/python*/site-packages/future/backports/test  && if [ "$PYTHON_VERSION" = "2" ]; then         rm -rf             opt/datadog-agent/embedded/bin/2to3-3*             opt/datadog-agent/embedded/bin/easy_install-3*             opt/datadog-agent/embedded/bin/idle*             opt/datadog-agent/embedded/bin/pip3*             opt/datadog-agent/embedded/bin/pydoc*             opt/datadog-agent/embedded/bin/python3*             opt/datadog-agent/embedded/bin/pyvenv*             opt/datadog-agent/embedded/include/python3*             opt/datadog-agent/embedded/lib/*python3* || true ;    fi  && if [ "$PYTHON_VERSION" = "3" ]; then         rm -rf             opt/datadog-agent/embedded/bin/pip2*             opt/datadog-agent/embedded/bin/python2*             opt/datadog-agent/embedded/include/python2*             opt/datadog-agent/embedded/lib/*python2* || true ;    fi  && find opt/datadog-agent/ -iname "*.a" -delete  && if [ -z "$WITH_JMX" ]; then rm -rf opt/datadog-agent/bin/agent/dist/jmx; fi  && ln -s /opt/datadog-agent/embedded/ssl etc/ssl  && mkdir conf.d checks.d
 ---> Running in 7aa6405eefc1
The command '/bin/sh -c find / -maxdepth 1 -type f -name 'datadog-agent*_amd64.deb' ! -name "$DD_AGENT_ARTIFACT" -exec rm {} \;  && find / -maxdepth 1 -name 'datadog-agent*_amd64.deb' -exec dpkg -X {} . \; | egrep '.*'  && rm -rf usr etc/init lib     opt/datadog-agent/sources     opt/datadog-agent/embedded/share/doc     opt/datadog-agent/embedded/share/man     opt/datadog-agent/embedded/lib/libcurl.so.4.4.0     usr/lib/x86_64-linux-gnu/libsystemd.so.0.21.0     opt/datadog-agent/embedded/lib/python*/site-packages/future/backports/test  && if [ "$PYTHON_VERSION" = "2" ]; then         rm -rf             opt/datadog-agent/embedded/bin/2to3-3*             opt/datadog-agent/embedded/bin/easy_install-3*             opt/datadog-agent/embedded/bin/idle*             opt/datadog-agent/embedded/bin/pip3*             opt/datadog-agent/embedded/bin/pydoc*             opt/datadog-agent/embedded/bin/python3*             opt/datadog-agent/embedded/bin/pyvenv*             opt/datadog-agent/embedded/include/python3*             opt/datadog-agent/embedded/lib/*python3* || true ;    fi  && if [ "$PYTHON_VERSION" = "3" ]; then         rm -rf             opt/datadog-agent/embedded/bin/pip2*             opt/datadog-agent/embedded/bin/python2*             opt/datadog-agent/embedded/include/python2*             opt/datadog-agent/embedded/lib/*python2* || true ;    fi  && find opt/datadog-agent/ -iname "*.a" -delete  && if [ -z "$WITH_JMX" ]; then rm -rf opt/datadog-agent/bin/agent/dist/jmx; fi  && ln -s /opt/datadog-agent/embedded/ssl etc/ssl  && mkdir conf.d checks.d' **returned a non-zero code: 1**

**Comment by vboulineau** [comment]
The Ubuntu error should not be a problem with newer Agent version
