### ISSUE TITLE
[BUG] Datadog agent sometimes times out connecting to amazon msk broker.

### ISSUE THREAD

**Issue by bpastiu** [DataDog/datadog-agent#13518]
**Agent Environment**
7.38.0

**Describe what happened:**
We are monitoring MSK clusters using a fargate task in AWS ECS. We do this on multiple environments and is working fine. However on one particular environment it is timing out with this error:
`"HTTPConnectionPool(host='<broker-id>.kafka.us-east-1.amazonaws.com', port=11001): Read timed out. (read timeout=10.0)"`
I've rechecked the the security groups, IAM policies and everything and it should work fine. 
I've also turned on Debug logs for a bit and saw that it's not happening all the time and that it actually does an HTTP request on that endpoint and returns a 200 so this is intermitent.
I looked at this file:
https://github.com/DataDog/integrations-core/blob/master/amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example
to find some config options and tried to set the: `@param read_timeout - number` to something higher than 10. Unfortunately, I tried to set it via an env var (DD_READ_TIMEOUT) but the agent complained it's unknown.

**Comment by vickenty** [comment]
Hi @bpastiu, thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the integrations-core open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/) and send them your [logs](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare).

Thanks.
