### ISSUE TITLE
[BUG] can't collect logs but the log_collector status is OK

### ISSUE THREAD

**Issue by yutingcaiyt** [DataDog/datadog-agent#13590]
**Agent Environment**
version: 7.34.0,  deployed on k8s with DeamanSet way

**with "datadog-agent status" command, I can see the Status is OK, but it seems that the log was not be  sent to server**
-------------------------------------------------
    - Type: file
      Identifier: 991668ee6cc5644e3736470d94e290fcb80a53dedcc42fcdd18a3828271bde25
      Path: /var/log/pods/online_solar-account-84c5d47d96-qbgvp_695989bf-e910-4ae7-b025-6aadcea90ade/http-server/*.log
      Status: OK
        1 files tailed out of 1 files matching
      Inputs:
        /var/log/pods/online_solar-account-84c5d47d96-qbgvp_695989bf-e910-4ae7-b025-6aadcea90ade/http-server/0.log
      BytesRead: 1.432902e+06
      Average Latency (ms): 0
      24h Average Latency (ms): 0
      Peak Latency (ms): 0
      24h Peak Latency (ms): 0

**Describe what you expected:**
Is there any possible problem would cause this case?

**Comment by vickenty** [comment]
Hi @yutingcaiyt, thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the integrations-core open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/) and send them your [logs](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare).

Thanks.
