### ISSUE TITLE
Windows ddtray.exe shortcut needs to run as administrator

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/datadog-agent#1364]
**Describe what happened:**

1. Installed Agent 6.0 on Windows 2016.
1. Selected the "Datadog Agent Manager" shortcut from the start menu
1. System tray icon has greyed out Configure option

**Describe what you expected:**

Configure to be enabled

**How to Fix**
Set the "Run this program as administrator" option on the shortcut's compatibility tab.

This is required because `C:\ProgramData\Datadog` is restricted to admins.

**Comment by truthbk** [comment]
Addressed in #1370, closing! Should be fixed in the next release, thank you for reporting this 
@rlaveycal

**Comment by derekwbrown** [comment]
Reopening this issue.  Reverted the referenced PR due to related security concerns.

**Comment by rlaveycal** [comment]
An alternative would be to create a datadog_admin group and permission the directory to give that group change access. Then an admin could add users to that group. Should avoid the need to run the tray as admin.

**Comment by clarkb7** [comment]
fixed in
* https://github.com/DataDog/datadog-agent/pull/8438

systray requires admin privileges to run, however if launched unelevated it will attempt to elevate itself.
