### ISSUE TITLE
[BUG] agent causes pid exhaustion with version 7.39.0

### ISSUE THREAD

**Issue by alexb-img** [DataDog/datadog-agent#13649]
After upgrading to datadog-agent version 7.39.0 for our Kubernetes monitoring, the agent process is producing an excessive number of processes. These processes accumulate is a short space of time eg less than 1 minute, and once the system limit (i.e. /proc/sys/kernel/pid_max) is reached, new processes cannot spawn resulting in general system instability.

The instability presents itself as errors in other Kubernetes internal components and also workloads running on the cluster, including (but not limited to):

* failed to create new OS thread (have 4 already; errno=11) runtime: may need to increase max user processes (ulimit -u) fatal error: newosproc

Logging on the node after the event we see a few defunct processes :

$ ps -ef|grep 30915
user 11568  3548  0 12:52 pts/0    00:00:00 grep 30915
root     30915 30877  0 Sep23 ?        00:24:32 datadog-cluster-agent start
root     30954 30915  0 Sep23 ?        00:00:00 [entrypoint.sh] <defunct>
root     30971 30915  0 Sep23 ?        00:00:00 [datadog-cluster] <defunct>
root     30982 30915  0 Sep23 ?        00:00:00 [getconf] <defunct>
root     30988 30915  0 Sep23 ?        00:00:00 [hostname] <defunct>

We can't currently directly observe the processes existing as they are created and destroyed in a short time < 30 seconds.

Similar to https://github.com/DataDog/datadog-agent/issues/12997

**Agent Environment**
Agent version 7.39.0

**Describe what happened:**
We observe container start errors when the OS pid limit is hit.

**Describe what you expected:**
No pid exhaustion

**Steps to reproduce the issue:**
Unknown as it is not happening in all environments

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS v1.21.5

**Comment by alexb-img** [comment]
It was determined that a different process leaking the pid.

**Comment by mstrent** [comment]
We are still investigating, but seem to be seeing PID exhaustion in our environment as well on 7.40.1. No zombie processes like the 7.38.0 bug. Only change in the environment is Datadog.
