### ISSUE TITLE
how to [auto-]create authToken for GUI

### ISSUE THREAD

**Issue by n0mer** [DataDog/datadog-agent#1380]
GUI homepage says "no authorization token".

Documentation page https://github.com/DataDog/datadog-agent/blob/master/docs/agent/gui.md says that "The GUI generates and saves a token in your browser which is used for authenticating all communications with the GUI server."

datadog.yaml, after migration from dd-agent v5,  contains property `auth_token_file_path`; there is no mention of `auth_token_file_path` in datadog.yaml.example - so i'm wondering whether this is related. Found `auth_token` file.

Docs https://docs.datadoghq.com/agent/#using-the-gui says nothing about authToken.

So, by using chrome extension "edit this cookie", i created cookie `authToken` with contents from `/etc/datadog-agent/auth_token` file, and were able to access gui.

Is it the suggested way to authenticate to datadog-agent web GUI? How gui supposed to `save token in my browser`?

**Comment by arbll** [comment]
Hi @n0mer,

Accessing the GUI should be as easy as typing `datadog-agent launch-gui` in your command prompt on windows/mac (it is disabled by default on linux). This command will open your browser with a crafted url containing your token that will set the cookie on its own.

Note that for security reasons, you need to run the command as the same user that runs the agent or it won't be able to read the `auth_token`.

**Comment by n0mer** [comment]
@arbll i am using ssh tunnel to make server's port available on my desktop, so i'm just accessing http://localhost:$port in browser.

Can you please provide the URL syntax? Because i do not have X subsystem on remote server:

```bash
datadog-agent launch-gui
Error: error opening GUI: exec: "xdg-open": executable file not found in $PATH
```

**Comment by arbll** [comment]
Unfortunately I don't think there is a straightforward way to authenticate in your configuration.

Here is the logic of the `launch-gui` command, it contains the URL syntax : https://github.com/DataDog/datadog-agent/blob/2b03fff4d06eadd27dee3c9128bafef2958fde59/cmd/agent/app/launchgui.go#L54-L72

**Comment by n0mer** [comment]
@arbll anyway, setting 'authToken' cookie via chrome extension works.

Thanks for clarification.
