### ISSUE TITLE
[BUG] Collector: Error initializing Python: GLIBC_2.25 not found. Agent_version: 7.39.1 on RHEL7 aarch64

### ISSUE THREAD

**Issue by gibney-ronin** [DataDog/datadog-agent#13841]
## [BUG] Collector: Error initializing Python: GLIBC_2.25 not found. Agent_version: 7.39.1 on RHEL7 aarch64

**Agent Environment**

(See below for details)

**Describe what happened:**

Running `datadog-agent status` shows that the checks collector is unable to run.

**Describe what you expected:**

I expect for the datadog custom checks functionality to be working OK.

**Steps to reproduce the issue:**

Install and run this version of datadog agent on this server architecture.

**Additional environment details (Operating System, Cloud provider, etc):**

(See below)

```
===============
Agent (v7.39.1)
===============

  Status date: 2022-10-11 22:18:51.386 GMT (1665526731386)
  Agent start: 2022-10-11 21:46:17.786 GMT (1665524777786)
  Pid: 1663
  Go Version: go1.17.11
  Python Version: n/a
  Build arch: arm64
  Agent flavor: agent
  Check Runners: 5
  Log Level: INFO


Host Info
  =========
    bootTime: 2022-10-11 21:46:06 GMT (1665524766000)
    hostId: e66936d9-190e-4784-90f4-14b2febf39a3
    kernelArch: aarch64
    kernelVersion: 5.4.17-2136.311.6.1.el7uek.aarch64
    os: linux
    platform: oracle
    platformFamily: rhel
    platformVersion: 7.9
    procs: 187
    uptime: 18s
    virtualizationRole: guest


Metadata
  ========
    agent_version: 7.39.1
    cloud_provider: Oracle
    install_method_installer_version: datadog_role-4.15.0
    install_method_tool: ansible
    install_method_tool_version: ansible-2.12.5


=========
Collector
=========
  Error initializing Python
  =========================
    - could not load runtime python for version 3: Unable to open three library: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/datadog-agent/embedded/lib/libpython3.8.so.1.0)



$ ldd --version && uname -a
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Linux kafka-01 5.4.17-2136.311.6.1.el7uek.aarch64 #2 SMP Thu Sep 22 19:41:24 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux



2022-10-07 00:43:50 GMT | CORE | INFO | (pkg/collector/python/init.go:322 in resolvePythonExecPath) | Using '/o
pt/datadog-agent/embedded' as Python home
2022-10-07 00:43:50 GMT | CORE | INFO | (pkg/collector/python/init.go:389 in Initialize) | Initializing rtloade
r with Python 3 /opt/datadog-agent/embedded
2022-10-07 00:43:50 GMT | CORE | ERROR | (pkg/collector/embed_python.go:19 in pySetup) | Could not initialize Python: could not load runtime python for version 3: Unable to open three library: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/datadog-agent/embedded/lib/libpython3.8.so.1.0)
```

**Comment by scottopell** [comment]
Hi!

Thanks for the detailed report! Can we get a few more details about how the agent was installed? If you could give the specific package that was installed by ansible (and which package version) that would be helpful.

Additionally could you run `objdump -T /opt/datadog-agent/embedded/lib/libpython3.8.so.1.0 | grep GLIBC_ | head` and put the output here?

Thanks!

**Comment by scottopell** [comment]
After some more discussion with the team, this is expected for `rpm` packages on aarch64, our minimum supported glibc version for aarch64 `rpm` is 2.26. We'll be adding better documentation around glibc versioning so this is more discoverable.

If you'd like to support run on older glibc versions on aarch64 please reach out to support so we can get a feature request created.

Closing this for now as expected behavior.
