### ISSUE TITLE
Participating in hacktoberfest?

### ISSUE THREAD

**Issue by jlosito** [DataDog/datadog-agent#13877]
I was wondering if this project was participating in [hacktoberfest](https://hacktoberfest.com/)? I see that some of the other repositories within the DataDog organization are but not arguably the core project. In order to participate in hacktoberfest, I believe it's a matter of adding a topic to the project named hacktoberfest.

**Comment by djmitche** [comment]
Thanks for asking!

While we welcome anyone's participation in the repository, it's not especially well-suited to the kinds of contributions involved in hacktoberfest -- there aren't a lot of "issues that have a well-defined scope and are self-contained", to quote the hacktoberfest docs.

As you've noted, several other DD repositories _are_ well-suited, so I'm glad to hear they're participating!
