### ISSUE TITLE
Datadog Agent Manager impaired usability in Internet Explorer

### ISSUE THREAD

**Issue by f0o** [DataDog/datadog-agent#1390]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```

Agent Info

Version: 6.0.0 
PID: 3056 
Check Workers: 1 
Log File: 
Log Level: info 
Config File: c:\programdata\datadog\datadog.yaml 
Conf.d Path: c:\programdata\datadog\conf.d 
Checks.d Path: c:\programdata\datadog\checks.d 


System Info

System UTC Time: 2018-03-05 10:31:46.242289 UTC 
NTP Offset: -0.107891952s 
Go Version: 1.9.1 
Python Version: 


Host Info

Boot Time: 2018-01-10 21:15:22.000000 UTC
 OS: windows
 Platform: Microsoft Windows Server 2008 R2 Standard
 Platform Family: Server
 Platform Version: 6.1.7601 Build 7601
 Procs: 75
 Uptime: 4.624491e+06

Hostnames

Hostname: EMSTEST
 Socket-Fqdn: SP-WIN-EMS-02
 Socket-Hostname: SP-WIN-EMS-02



JMX Status


Initialized Checks

No initialized checks 

Failed Checks

No failed checks 


Forwarder


API Keys Status

https://6-0-0-app.agent.datadoghq.com,*************************4f449: API Key valid



DogStatsD

Checks Metric Sample: 12096
 Event: 1
 Events Flushed: 1
 Number Of Flushes: 166
 Series Flushed: 9198
 Service Check: 1660
 Service Checks Flushed: 1816
```

**Additional environment details (Operating System, Cloud provider, etc):**
Windows Server 2008 R2 SP1
Default Internet Explorer 11.0.9600.18893

**Steps to reproduce the issue:**
1. Install datadog 6.0.0 msi as per instructions of https://app.datadoghq.com/account/settings#agent/windows
2. Start Datadog Agent Manager
3. Go to Checks -> Manage Checks
4. Look at console for the error, page becomes unusable as well

**Describe the results you received:**
Unhandled Exception: SCRIPT438: Object doesn't support property or method 'endsWith'
in javascript.js, Line 301, Column: 7

**Describe the results you expected:**
Lists checks and allows editing and creation of checks as per official docs

**Additional information you deem important (e.g. issue happens only occasionally):**
Reproducible all the time

**Comment by truthbk** [comment]
Thank you for reporting this @f0o - should be addressed here: https://github.com/DataDog/datadog-agent/pull/1392

**Comment by f0o** [comment]
@truthbk Thanks for the quick PR and merge :)

Any idea when the new MSI is available?

**Comment by masci** [comment]
@f0o 6.0.1 will be out mid week
