### ISSUE TITLE
[Flaky Test] `FuzzHandleTraces*` tests are very flaky

### ISSUE THREAD

**Issue by ajgajg1134** [DataDog/datadog-agent#13934]
It seems this is due to the `timing` package spinning up a goroutine on `init` that accesses the `metrics` client. Many tests will overwrite the metrics client with a test version (thus creating a data race and failing the test)

**Comment by gbbr** [comment]
Which `init`? Do you mean [this](https://github.com/DataDog/datadog-agent/blob/64b4e45/pkg/trace/metrics/timing/timing.go#L26) ?

**Comment by ajgajg1134** [comment]
Yep! That line exactly.
