### ISSUE TITLE
[BUG] Serverless-init doesn't wait for child process to handle SIGTERM before terminating

### ISSUE THREAD

**Issue by crea1** [DataDog/datadog-agent#13940]
**Agent Environment**
Serverless-init: `datadog/serverless-init:beta4-alpine`
Datadog Java Agent: 0.111.0

**Describe what happened:**
Using serverless-init as described in cloud run documentation, we encountered that even though the code seems to handle `SIGTERM` signals, sending it to the child process, serverless-init quits before the child process gets time to process it.

I believe the reason is due to this code
https://github.com/DataDog/datadog-agent/blob/main/cmd/serverless-init/initcontainer/initcontainer.go#L89

We can see the signal is sent to the underlying process, but in the next `if sig == syscall.SIGTERM` there is a `os.Exit(0)`. This seems to happen so fast that the underlying process doesn't receive the signal. To test this we sent `SIGINT` instead so the last if statement never was reached. In this test we could actually see that the signal was indeed received by our java application.

**Describe what you expected:**
I expected the `SIGTERM` signal to be sent to underlying process, and give it time to handle it. As described in the docs, cloud run gives the container 10s to do a graceful shutdown before the container is killed. https://cloud.google.com/run/docs/container-contract#instance-shutdown

**Steps to reproduce the issue:**
Have a container using serverless-init and send a `SIGTERM` to this container. This happens when deploying a new version or scaling down. 

Our Dockerfile. It takes a parameter to start a bash script which runs `java -jar app.jar` with some additional java parameters. For instance `-javaagent:dd-java-agent.jar`
```Dockerfile
FROM eclipse-temurin:17-alpine
COPY --from=datadog/serverless-init:beta4-alpine /datadog-init /app/datadog-init
ENTRYPOINT ["/app/datadog-init"]
```

Example of java class handling `SIGTERM`.
```java
import sun.misc.Signal;
import sun.misc.SignalHandler;
 
public class ExampleSignalHandler {
    public static void main(String... args) {
      Signal.handle(new Signal("TERM"), sig -> {
        System.out.println("Received SIGTERM");
        System.exit(0);
    });
    // Start application
    }
}
```

**Additional environment details (Operating System, Cloud provider, etc):**
Cloud provider: GCP 
Running on :Cloud Run 
Base Image: `eclipse-temurin:17-alpine`

**Comment by kspector** [comment]
@crea1 I am experiencing this as well, though I was unable to catch `SIGINT` or any other trappable signals in the child process due to what I strongly presume to be the `process` pointer being nil when passed into the `handleSignals` function.

I just [opened a PR](https://github.com/DataDog/datadog-agent/pull/14973) for the team to hopefully review and advise upon soon

**Comment by crea1** [comment]
@kspector Interesting! I'm not too familiar with go myself, but seems like that could be an issue. 

The way we were able to trap sigint was to use [dumb-init](https://github.com/Yelp/dumb-init) as ENTRYPOINT. This gives a possibility to rewrite SIGTERM (15) to SIGINT (2). We did all this using mavens jib plugin, but it should create a docker file like this:

```docker
ENTRYPOINT ["/usr/bin/dumb-init","--rewrite","15:2","--"]
CMD ["/app/datadog-init"]
CMD ["start-java-app.sh"]
```
At that point our signal handler in the java application was able to get the signal (now rewritten to SIGINT), and we could do a graceful shutdown.

**Comment by crea1** [comment]
I have tested now with `datadog/serverless-init:beta7-alpine`, and it seems to me that things are working as expected. My application receives `SIGTERM` from cloud run and can handle all it needs to to gracefully shut down. I believe this issue can be closed.

Thank you @kspector 💯
