### ISSUE TITLE
[BUG] panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by zander-canva** [DataDog/datadog-agent#13976]
**Agent Environment**

Running Datadog serverless in Python on AWS Lambda.
[Datadog lambda extension v24](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v24)

**Describe what happened:**
Submitting custom metrics from Python using the `lambda_metric` function. However, sometimes, there is an integer divide by zero error. This seems to occur when there is a large volume of metrics being submitted.

The stack trace looks like this:

```
panic: runtime error: integer divide by zero
goroutine 921 [running]:
github.com/DataDog/datadog-agent/pkg/serializer/internal/metrics.SketchSeriesSlice.SplitPayload(...)
/tmp/dd/datadog-agent/pkg/serializer/internal/metrics/sketch_series_list.go:330
github.com/DataDog/datadog-agent/pkg/serializer/internal/metrics.SketchSeriesList.SplitPayload({{0x16b5098, 0xc0015725c0}}, 0x1)
/tmp/dd/datadog-agent/pkg/serializer/internal/metrics/sketch_series_list.go:318 +0x292
github.com/DataDog/datadog-agent/pkg/serializer/split.Payloads({0x7f3962727258, 0xc00198c190}, 0xb8, 0x4175ea)
/tmp/dd/datadog-agent/pkg/serializer/split/split.go:117 +0x59d
github.com/DataDog/datadog-agent/pkg/serializer.Serializer.serializePayloadInternal({{0x16d60b0, 0xc0007d24a0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x1, 0x1, 0x1, ...}, ...)
/tmp/dd/datadog-agent/pkg/serializer/serializer.go:199 +0x35
github.com/DataDog/datadog-agent/pkg/serializer.Serializer.serializePayloadProto({{0x16d60b0, 0xc0007d24a0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x1, 0x1, 0x1, ...}, ...)
/tmp/dd/datadog-agent/pkg/serializer/serializer.go:195 +0xb3
github.com/DataDog/datadog-agent/pkg/serializer.(*Serializer).SendSketch(0xc0007d80a0, {0x16b5098, 0xc0015725c0})
/tmp/dd/datadog-agent/pkg/serializer/serializer.go:361 +0x2fc
github.com/DataDog/datadog-agent/pkg/aggregator.(*ServerlessDemultiplexer).ForceFlushToSerializer.func3({0x16b5098, 0xc0015725c0})
/tmp/dd/datadog-agent/pkg/aggregator/demultiplexer_serverless.go:126 +0x4c
github.com/DataDog/datadog-agent/pkg/metrics.Serialize.func2()
/tmp/dd/datadog-agent/pkg/metrics/iterable_metrics.go:137 +0x6f
created by github.com/DataDog/datadog-agent/pkg/metrics.Serialize
/tmp/dd/datadog-agent/pkg/metrics/iterable_metrics.go:135 +0x196
```

It seems like this occurs due to the length of `sl` being zero here:
https://github.com/DataDog/datadog-agent/blob/main/pkg/serializer/internal/metrics/sketch_series_list.go#L331-L335

**Describe what you expected:**
The extension to run without crashing

**Steps to reproduce the issue:**
Submit large volumes of metrics using the `lambda_metric` function. Occurs fairly consistently when 180,000 or so metrics are submitted, however, it sometimes occurs even when fewer metrics being submitted.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS Lambda Python
```
DD_LOGS_INJECTION = false
DD_SERVERLESS_LOGS_ENABLED = false
```

**Comment by DDuongNguyen** [comment]
Hi There, Thank you for opening up an issue regarding our agent. This is currently a known issue that is getting patched by our team and we will reach out once there is a fix on it. You can also check in on when the fix will be merged here:
https://github.com/DataDog/datadog-agent/pull/13453

For more official tracking and more automated update, you can also create a ticket using our service [here](https://a.cl.ly/jkuWB70e):
https://help.datadoghq.com/hc/en-us

That way if there are other changes or relevant update, we can keep you up to date accordingly. Please make sure to include this Github issue URL so it would be easier for us to track too.

Thanks!

**Comment by delenamalan** [comment]
@DDuongNguyen are there any temporary workarounds you can suggest?

**Comment by davylough** [comment]
@DDuongNguyen Having this same issue after upgrading datadog-lambda-js from 6.78.0 to 6.84.0, and now we have no metrics. Is the only mitigation at the moment to rollback to the previous version?
