### ISSUE TITLE
Update repo title to "Datadog Agent 6"

### ISSUE THREAD

**Issue by sylr** [DataDog/datadog-agent#1405]
When you begin with Datadog it's really not obvious which repo is which version so it would be nice if the Owner of this repo could update the title from "Datadog Agent" to "Datadog Agent 6".

Also updating the README.md would be nice, I'll push a PR.

**Comment by masci** [comment]
Hi @sylr and thanks for your feedback.

While I agree we should get rid of any ambiguity about the two Agents and their respective source repositories, I don't think it's a good idea to brand this software with a major version number that will eventually change.

I'm going to make more obvious that https://github.com/DataDog/dd-agent contains the code for the old release line of the Datadog Agent and now that 6.0.0 is GA I can also add a link pointing to this repo.
