### ISSUE TITLE
[BUG] Web requests with status 200 appear as errors on Datadog Logs view

### ISSUE THREAD

**Issue by mykola42** [DataDog/datadog-agent#14288]
Web requests with status `200` are marked as `Error` on Datadog Logs view

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/5482411/201415100-836ccbc2-544f-4133-9372-0a5ecdf5ee55.png">

<img width="927" alt="Pasted_Image_11_11_22__11_23_AM" src="https://user-images.githubusercontent.com/5482411/201415330-0314eae7-ec3b-4165-bb4e-57bdb16fd904.png">

**Agent Environment**

Datadog agent was deployed to K8s cluster by Helm chart `datadog-3.3.0`

**Describe what happened:**
A Ruby application successfully serves web requests but in Datadog Logs they appear as errors.

Curl shows that requests succeed
```
curl -vv MY_ELB.us-east-2.elb.amazonaws.com
*   Trying MY_IP:80...
* Connected to MY_ELB.us-east-2.elb.amazonaws.com (MY_IP) port 80 (#0)
> GET / HTTP/1.1
> Host: MY_ELB.us-east-2.elb.amazonaws.com
> User-Agent: curl/7.84.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 50
<
```

**Describe what you expected:**
In Datadog logs, requests with status 200 shouldn't be marked as `Error` and should be marked as `Ok` instead.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by vickenty** [comment]
Hi @mykola42, thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the datadog-agent open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/).

**Comment by alexanderbaumann-toast** [comment]
@mykola42 did you get help with this?

**Comment by helissonomc** [comment]
@alexanderbaumann-toast did you manage to find the reason for this?
