### ISSUE TITLE
[BUG] line 1: cannot unmarshal !!map into string

### ISSUE THREAD

**Issue by TomMettam** [DataDog/datadog-agent#14295]
I've built datadog-agent from source using the provided instructions.

I used the example datadog.yaml script provided in https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml

When I run the agent, I get:

`Error: unable to load Datadog config file: While parsing config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into string`

**Comment by TomMettam** [comment]
Instead, I copied the file from `cmd/agent/dist/datadog.yaml` and used that, which works fine.

Therefore this page is incorrect: https://docs.datadoghq.com/agent/guide/agent-configuration-files/?tab=agentv6v7

"Note: [A full example of the datadog.yaml file is available in the datadog-agent GitHub repository](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml)."

**Comment by sgnn7** [comment]
Hey @TomMettam,
The expectation when building your own Agent is that you use the built config file generated based on the tags passed to your build (which you found). The note in the general docs is mostly around seeing the available options and not using the full template as-is. I'll see about us adding this caveat note to our docs.

**Comment by TomMettam** [comment]
The instructions specifically say **"Create a development datadog.yaml configuration file in dev/dist/datadog.yaml, containing a valid API key: api_key: <API_KEY>"** - but they don't mention where to get that config file from.

The instructions also don't mention how to "invoke install" to get everything moved to the right place (such as the build shared libraries which it fails to load), or how to get the bundled integrations installed..

**Comment by sgnn7** [comment]
@TomMettam I clarified the documentation in both the online docs and agent repo docs on this. Thanks for your report!
