### ISSUE TITLE
datadog agent, help deployment set agent variable jmx_statsd_client_queue_size

### ISSUE THREAD

**Issue by Ceva** [DataDog/datadog-agent#14390]
Good day,
I would like to modify variable jmx_statsd_client_queue_size.
In standard installation its simple, but I can't find a way to do that when  datadog deployed using helm chart.
Would you be so kind to let me know if that is possible?

**Comment by vickenty** [comment]
Hi @Ceva, thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the datadog-agent open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/).

Thanks.
