### ISSUE TITLE
[BUG] `journald` integration `exlude_units` is not respected

### ISSUE THREAD

**Issue by Kyslik** [DataDog/datadog-agent#14451]
**Agent Environment**
```
  Metadata
  ========
    agent_version: 7.36.1
    cloud_provider: AWS
```

**Describe what happened:**

Because of already fixed issue in #12604 we tried to stop ingesting certain logs from `systemd` unit `proc-sys-fs-binfmt_misc.automount` it did reduce overall number of logs/spam; but not all of them.

```
$ agent status
  journald
  --------
    - Type: journald
      ExcludeUnits: proc-sys-fs-binfmt_misc.automount
...
```

Logs in DD:

```
journald {
    ...
    CODE_FILE src/core/automount.c
    CODE_FUNCTION automount_dispatch_io
    CODE_LINE 985
    PRIORITY 6
    SYSLOG_FACILITY 3 
    SYSLOG_IDENTIFIER systemd
    UNIT proc-sys-fs-binfmt_misc.automount <---- ?
}
```

**Describe what you expected:**

No logs from unit `proc-sys-fs-binfmt_misc.automount` be ingested at all.

Perhaps this was fixed in https://github.com/DataDog/datadog-agent/releases/tag/7.37.0?

**Steps to reproduce the issue:**

Follow [docs](https://docs.datadoghq.com/integrations/journald/?tab=containerized#filter-journal-units) and use `exclude_units`

```
...
          exclude_units:
            - proc-sys-fs-binfmt_misc.automount
...
```

And perhaps observe if logs are ingested 🤷🏻 .

**Additional environment details (Operating System, Cloud provider, etc):**

EKS, k8s 1.22.

**Comment by carlosroman** [comment]
This isn't a bug on the Logs Agent as what you're seeing is actually the output from `init.scope` Systemd Unit rather than from `proc-sys-fs-binfmt_misc.automount`. You can validate this by running
`journalctl -u proc-sys-fs-binfmt_misc.automount` which will show you the log output of that Unit.

In the log sample in DD you'll see that the entry looks like:

```
journald {
   ...
   _HOSTNAME   my-host
   _SYSTEMD_UNIT   init.scope
   ...
   CODE_FILE src/core/automount.c
   CODE_FUNCTION automount_dispatch_io
   CODE_LINE 985
   PRIORITY 6
   SYSLOG_FACILITY 3 
   SYSLOG_IDENTIFIER systemd
   UNIT proc-sys-fs-binfmt_misc.automount 
}
```

The Logs Agent actually filters on the value of `_SYSTEMD_UNIT` which is the actual Systemd Unit that is creating the log entry. `UNIT` here is just a field that `init.scope` logs. The fields that begin with `_` is the data that Journald is telling us about the Unit. The others are just data the Unit has logged.

**Comment by Kyslik** [comment]
There is no key `_SYSTEMD_UNIT` in logs I am looking at:

```
journald {	
    _BOOT_ID X
    _CAP_EFFECTIVE x
    _CMDLINE X
    _COMM systemd
    _EXE /usr/lib/systemd/systemd
    _GID 0
    _HOSTNAME X
    _MACHINE_ID X
    _PID 1
    _SOURCE_REALTIME_TIMESTAMP 1669634886783449
    _SYSTEMD_CGROUP /
    _TRANSPORT journal
    _UID 0
    CODE_FILE src/core/automount.c
    CODE_FUNCTION automount_enter_running
    CODE_LINE 759
    PRIORITY 6
    SYSLOG_FACILITY 3
    SYSLOG_IDENTIFIER systemd
    UNIT proc-sys-fs-binfmt_misc.automount
}
```

I tried adding `init.scope` in the Excluded Units list and it seems to be working.

**Comment by carlosroman** [comment]
Glad to hear excluding `init.scope` reduced the number of logs/spam. I'll close the issue but feel free to open it again if you have any other problems with the Journald tailer.

**Comment by Kyslik** [comment]
I kid you not; it's back (and yes, no changes in the configuration for past day...).

<img width="1342" alt="Screen Shot 2022-11-29 at 11 49 31" src="https://user-images.githubusercontent.com/2067589/204516358-e237f695-781e-4971-a6ff-9b8d5126272a.png">
<img width="1624" alt="Screen Shot 2022-11-29 at 11 49 51" src="https://user-images.githubusercontent.com/2067589/204516368-fff33a7c-ccde-4988-845a-660ccd9a794d.png">

**Comment by Kyslik** [comment]
I think it's not the `init.scope` being excluded; it's the restart of the agent that "worked"...

**Comment by Kyslik** [comment]
I think it's not the `init.scope` being excluded; it's the restart of the agent that "worked"... I restarted agent(s) on one of the clusters 45 minutes ago and the log spam is gone on that cluster.

> I'll close the issue but feel free to open it again if you have any other problems with the Journald tailer.

@carlosroman I can not re-open the issue.

**Comment by Kyslik** [comment]
https://github.com/DataDog/datadog-agent/blob/95e1e892fdaa21911bed770d63332ef57baf0d06/pkg/logs/internal/tailers/journald/tailer.go#L167-L170

So if we don't have `_SYSTEMD_UNIT` to begin with... it can't be ignored. However I don't understand why would it work for a while - after restart. Probably something with https://github.com/DataDog/datadog-agent/blob/95e1e892fdaa21911bed770d63332ef57baf0d06/pkg/logs/internal/tailers/journald/tailer.go#L138

See image below... I restarted agent on one of our environments and we can observe the downward trend:

<img width="1347" alt="Screen Shot 2022-11-29 at 13 13 04" src="https://user-images.githubusercontent.com/2067589/204526537-e7af5141-7638-45dd-886e-91e64f7a6010.png">

---

I will turn off the journald tailer instead. This is probably "fixed" in newer versions of DD-agent.
