### ISSUE TITLE
Kubernetes static pods will cause lots of tagger warnings

### ISSUE THREAD

**Issue by andor44** [DataDog/datadog-agent#1447]
We run some parts of our k8s infrastructure (kube-proxy, master components, etc.) as 
[static pods](https://kubernetes.io/docs/tasks/administer-cluster/static-pod/), i.e. they're defined in a yaml file on the node itself and the kubelets are pointed to these files.

It seems that agent 6 doesn't know how to deal with these and we see a large amount of warnings, repeated periodically:

```
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kubelet: container docker://2137690133[redacted] not found in podList
[ AGENT ] 2018-03-13 12:41:19 UTC | WARN | (tagger.go:246 in Tag) | error collecting from kube-service-collector: container docker://2137690133[redacted] not found in podList
```

In this case the docker container ID belongs to the node-local kube-proxy. While it doesn't seem like this is breaking anything, the agent is repeating this a **lot** (about 80-90% of the agent log is just this message).

**Comment by hatemosphere** [comment]
+1, we have the same problem

**Comment by mfpierre** [comment]
Hey, thanks for the report, it's actually a bug in kubernetes where the pod list does not update the status of static pods.

We made a fix https://github.com/DataDog/datadog-agent/pull/1345 that we'll be included in the next (6.1) release, we're also workin on fixing the behaviour in kubernetes

**Comment by rltvty** [comment]
can you push a 6.1.0_rc1 image to docker hub, so I can try out this fix?

**Comment by mfpierre** [comment]
Hey @rltvty we just pushed a `6.1.0-rc.1` tag on https://hub.docker.com/r/datadog/agent/ if you want to test it out.

**Comment by andor44** [comment]
Tested with the above rc, we no longer see these messages 🙌

**Comment by mausch** [comment]
I no longer see this since upgrading to 6.1.0 :+1:

**Comment by mfpierre** [comment]
Thanks for the feedback, as 6.1 is now released I'm closing this.

**Comment by JulienBalestra** [comment]
As @mfpierre mentioned:
> Hey, thanks for the report, it's actually a bug in kubernetes where the pod list does not update the status of static pods

@andor44 you can find more info here: https://github.com/kubernetes/kubernetes/issues/61717
