### ISSUE TITLE
Prometheus URL has very high latency during deployment

### ISSUE THREAD

**Issue by SyedAanif** [DataDog/datadog-agent#14629]
We are running a Spring Boot `v2.5.12` with Spring Cloud `v2020.0.5` micro-service on Kubernetes `v1.23.8` cluster with deployments managed by Helm3.
The cluster is monitored by a Datadog agent `v0.91.0`. 

During the deployment phase of the pods, the `/management/prometheus` URL latency is as high as `10-15s`, which causes overall degradation of the service SLOs for a brief period of `1-2min`.
The annotations specified in deployment template are given below:
```
annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/{{ .Chart.Name }}.init_configs: |
          [{}]
        ad.datadoghq.com/{{ .Chart.Name }}.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:{{ .Values.container.management.port | default 9002 }}/management/prometheus",
              "namespace": "",
              "metrics": ["*"]
            }
          ]
```

**What would be the recommendations from your team to overcome this performance issue?**

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
