### ISSUE TITLE
[BUG] dogstatsd does not work with admission controller configured for sockets 

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-agent#14638]
**Agent Environment**
Kubernetes with DCA 1.20

**Describe what happened:**
Dogstatsd does not seem to work with `DD_TRACE_AGENT_URL` as injected by the admission controller.

**Describe what you expected:**
Dogstatsd should configure itself in the same way that the trace agent does.  Alternatively, the admission controller should inject a configuration compatible with dogstatsd.

**Steps to reproduce the issue:**
* Enable the admission controller in `socket` mode
* Deploy an app with dogstatsd
* Observe that dogstatsd does not communicate over the socket indicated by `DD_TRACE_AGENT_URL`

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes 1.22 on EKS; ruby agent v1.20

**Comment by jcogilvie** [comment]
To work around this I have taken to manually defining `DD_DOGSTATSD_SOCKET` on each of my services.  I suspect that either:

* the admission controller should also inject `DD_DOGSTATSD_SOCKET`
* the admission controller and the agents should inject/accept a corollary to DD_TRACE_AGENT_URL (perhaps DD_METRICS_URL)
* or, the admission controller and the agents should accept a parameter for the path to the *directory* containing both the dsd and the apm sockets, and assume default socket names (and/or allow additional configuration to set the socket names)

**Comment by vickenty** [comment]
Hi @jcogilvie, thanks for using Datadog.

This issue tracker is primarily used to track bugs in the Agent codebase to completion. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.

**Comment by jcogilvie** [comment]
Respectfully @vickenty, my experience with this was very much a bug.

Consider:
- the Admission Controller [documentation](https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=operator) indicates that it injects environment variables "to configure *DogStatsD and APM tracer libraries* into the user’s application containers."
- the Admission Controller [documentation](https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=operator#configure-apm-and-dogstatsd-communication-mode) specifically calls out in a header that the communication mode affects both APM and DogStatsD 
- using admission controller in `hostip` mode injects `DD_AGENT_HOST` which is used by both dogstatsd and apm agent
- switching to `socket` mode, even as UDS becomes the default, breaks metrics 
- the documentation does not mention this limitation

I would respectfully ask you to reopen this until at least the documentation is corrected.

**Comment by vboulineau** [comment]
Hi @jcogilvie,

Your report seems indeed legit, re-opening the ticket.

**Comment by clamoriniere** [comment]
hi @jcogilvie 

to add to the investigation. Which dogstatsd client language are you using?

**Comment by jcogilvie** [comment]
Several. Ruby, golang, Java, js. This specifically was noted on a Ruby service because it was our prototype for testing UDS but I believe the problem crosses languages based on some GitHub issue archaeology I did when I filed it.

**Comment by chen-anders** [comment]
Also just hit this issue; I would've expected something like `DD_DOGSTATSD_SOCKET` to be injected if `admissionController.configMode` was set to `socket`.

**Comment by kramuenke-catch** [comment]
Hi Datadog team,

we recently got bitten by this limitation too when we upgraded helm charts to >= 3.22.0 which now auto-configures `admissionController.configMode`. Due to our config it switched from hostip to socket.

**Comment by dan-lind** [comment]
Just ran into this as well. Are there any known workarounds besides setting the statsd socket path on every single deployment?

**Comment by MarounMaroun** [comment]
In my case, if I enable the admission controller, APM works, DogStatsD doesn't. If I remove it, and manually configure the `DD_AGENT_HOST` to be the host IP (in K8s environment), then runtime works and APM doesn't.

What would be the solution in this case?

**Comment by MarounMaroun** [comment]
I eventually solved the issue by removing the manually set `DD_AGENT_HOST`:

```yaml
- env:
  - name: DD_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```
