### ISSUE TITLE
Build on FreeBSD 11

### ISSUE THREAD

**Issue by mrgz** [DataDog/datadog-agent#1467]
Hello, I am trying to build the agent v6 for FreeBSD 11, from source. The environment has the following configuration:

FreeBSD 11.0-RELEASE-p15 with the following ports / libs installed:
go-1.10 (from ports)
python27-2.7.14_1 (from ports)
invoke 0.22.1 (installed via pip)

The last step from the README.md, "invoke agent.build --build-exclude=snmp", triggers the following error:
```
# github.com/DataDog/datadog-agent/pkg/metadata/v5
pkg/metadata/v5/payload_other.go:16:2: undefined: ExternalHostPayload
# github.com/DataDog/datadog-agent/vendor/github.com/DataDog/gohai/platform
vendor/github.com/DataDog/gohai/platform/platform_common.go:33:22: undefined: getArchInfo
```

edit: fixed Markdown

**Comment by masci** [comment]
@mrgz can you try if your build works on my branch `massi/freebsd` from #1468 ?

**Comment by mrgz** [comment]
@masci Yes, the build works from this branch. Good!
