### ISSUE TITLE
[BUG] Systemd warning isn't helpful

### ISSUE THREAD

**Issue by mnot** [DataDog/datadog-agent#14688]
I'm hitting [this warning
](https://github.com/DataDog/datadog-agent/blob/d89b62e607a618f32b80320e5ee92e2a3da7d126/pkg/collector/corechecks/systemd/systemd.go#LL367):

> Dec 10 06:58:22 xxx agent[2232301]: 2022-12-10 06:58:22 UTC | CORE | WARN | (pkg/collector/corechecks/systemd/systemd.go:367 in submitBasicUnitMetrics) | Error getting unit unitProperties: prosody.service
> Dec 10 06:58:22 xxx agent[2232301]: 2022-12-10 06:58:22 UTC | CORE | WARN | (pkg/collector/corechecks/systemd/systemd.go:402 in submitPropertyMetricsAsGauge) | Error getting detailed properties for unit prosody.service

... but the actual error isn't captured, so I have no idea what's going wrong.

**Agent Environment**

Agent 7.39.1 - Commit: b384f7a - Serialization version: v5.0.26 - Go version: go1.17.11

**Describe what happened:**

Systemd unit checks don't provide details (e.g., `systemd.service.memory_usage`), and the error above appears in logs

**Describe what you expected:**

Systemd unit checks work, or at least a useful error appears in logs

**Steps to reproduce the issue:**

1. Install datadog-agent 
2. Configure systemd checks
3. Observe

**Additional environment details (Operating System, Cloud provider, etc):**

Arch linux; datadog-agent from AUR

**Comment by vickenty** [comment]
Thank you! This will be fixed in 7.43.0 with #14968
