### ISSUE TITLE
Check docker_daemon not found in Catalog

### ISSUE THREAD

**Issue by pbudzon** [DataDog/datadog-agent#1469]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

==============
Agent (v6.0.2)
==============

  Status date: 2018-03-16 13:10:08.566278 UTC
  Pid: 21802
  Python Version: 2.7.5
  Logs: 
  Check Runners: 1
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -0.000759971 s
    System UTC time: 2018-03-16 13:10:08.566278 UTC

  Host Info
  =========
    bootTime: 2018-03-12 09:52:05.000000 UTC
    kernelVersion: 3.10.0-693.21.1.el7.x86_64
    os: linux
    platform: centos
    platformFamily: rhel
    platformVersion: 7.4.1708
    procs: 163
    uptime: 357113
    virtualizationRole: guest
    virtualizationSystem: xen

  Hostnames
  =========
    (...)

=========
Collector
=========

  Running Checks
  ==============
 (...)

  Loading Errors
  ==============
    docker_daemon
    -------------
      Core Check Loader:
        Check docker_daemon not found in Catalog
        
      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so
        
      Python Check Loader:
        No module named docker_daemon
        
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  CheckRunsV1: 24
  IntakeV1: 3
  RetryQueueSize: 0
  Success: 51
  TimeseriesV1: 24

  API Keys status
  ===============
    https://6-0-2-app.agent.datadoghq.com,*************************2c146: API Key valid

==========
Logs Agent
==========

  Logs Agent is not running

=========
DogStatsD
=========

  Checks Metric Sample: 4619
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 24
  Series Flushed: 3372
  Service Check: 354
  Service Checks Flushed: 361
  Dogstatsd Metric Sample: 61


```

**Describe what happened:**

After updating to latest datadog agent (using ansible-galaxy role to install), docker_daemon integration stopped working. Configuration of the check is correct, as described on https://docs.datadoghq.com/integrations/docker_daemon/ and the integration is enabled (it used to work before, without issues).

**Describe what you expected:**

docker_daemon integration to work correctly.

**Steps to reproduce the issue:**

1. Install dd-agent 6.0.2
2. Configure docker_daemon check.
3. Restart agent and see status.

**Additional environment details (Operating System, Cloud provider, etc):**

This issue: https://github.com/DataDog/chef-datadog/issues/503 reports that docker_daemon is no longer recognised as a check by dd-agent v6?!

My `/etc/datadog-agent/conf.d/docker_daemon.yaml`:
```
init_config: null
instances:
-   url: unix://var/run/docker.sock
    new_tag_names: true
```

**Comment by pbudzon** [comment]
It seems the check was renamed to "docker" instead of "docker_daemon" which is not reflected in the docs, nor is there any helpful message about this shown when trying to use "docker_daemon".

**Comment by mfpierre** [comment]
Hi @pbudzon & thanks for your report, as you guessed the check has been rewritten to go and is now called "docker".

We had some code to convert the old check config to the new one that was mistakenly removed, we'll add this back #1473 in the next version (6.1) and try to document this change in a clearer way.

**Comment by zimmertr** [comment]
Has this also happened with `dns_check`? I'm seeing the same error. 

```
Dir: /root 
Usr: root - Mon 28,  9:58AM > /opt/datadog-agent/bin/agent/agent status | grep dns
    dns_check
        Check dns_check not found in Catalog
        No module named dns_check
```

**Comment by fanysoft** [comment]
similar issue here with sqlserver
from status : 
```
sqlserver Core Check Loader: Check sqlserver not found in Catalog
JMX Check Loader: check is not a jmx check, or unable to determine if it's so
Python Check Loader: No module named sqlserver
```
I have my config at MacOS in /opt/datadog-agent/etc/conf.d/sqlserver.d/conf.yaml

**Comment by tonytuba** [comment]
I am seeing the same issue as user "fanysoft".  

`Datadog's network integration is reporting:
Instance #initialization[ERROR]:{"Core Check Loader":"Check network not found in Catalog","JMX Check Loader":"check is not a jmx check, or unable to determine if it's so","Python Check Loader":"Cannot change thread mode after it is set."}
Datadog's sqlserver integration is reporting:
Instance #initialization[ERROR]:{"Core Check Loader":"Check sqlserver not found in Catalog","JMX Check Loader":"check is not a jmx check, or unable to determine if it's so","Python Check Loader":"Cannot change thread mode after it is set."}
Datadog's disk integration is reporting:
Instance #initialization[ERROR]:{"Core Check Loader":"Check disk not found in Catalog","JMX Check Loader":"check is not a jmx check, or unable to determine if it's so","Python Check Loader":"Cannot change thread mode after it is set."}`

**Comment by zivanovicb1** [comment]
From Web UI:

`
Loading Errors
apm
Core Check Loader: Could not configure check APM Agent: APM agent disabled through main configuration file
JMX Check Loader: check is not a jmx check, or unable to determine if it's so
Python Check Loader: No module named apm
docker
Core Check Loader: Check docker not found in Catalog
JMX Check Loader: check is not a jmx check, or unable to determine if it's so
Python Check Loader: No module named docker
`

I get pretty much the same the thing when i run `datadog-agent status`

**Comment by maheshjq** [comment]
I"m seeing this for 'ibm_mq'  Agent (v7.28.1).  Appreciate your help on this. 

 Loading Errors
  ==============
    ibm_mq
    ------
      Core Check Loader:
        Check ibm_mq not found in Catalog

      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so

      Python Check Loader:
        unable to import module 'ibm_mq': No module named 'ibm_mq'

**Comment by mvellasco** [comment]
Also seeing this issue for apm on Agent(v7.29.1): 

```
Loading Errors
  ==============
    apm
    ---
      Core Check Loader:
        Check apm not found in Catalog
```
Appreciate the assistance as well.

**Comment by Shashwat-05** [comment]
Also seeing this for Datadog Cluster Agent (v7.43.1)
`  Loading Errors
  ==============
    redisdb
    -------
      Core Check Loader:
        Check redisdb not found in Catalog
`
