### ISSUE TITLE
[BUG] Lambda ENV variables are not working with Proxy as expected

### ISSUE THREAD

**Issue by xrn** [DataDog/datadog-agent#14790]
Hey,

Following https://docs.datadoghq.com/agent/proxy and https://docs.datadoghq.com/agent/logs/proxy

I have created Nginx Proxy with same settings as described in 1st link. Than created very simple lambda which returns just a single log. Lambda is using Extension v35

1. Option datadog.yaml

If I will use in my lambda yaml config 

```
logs_config:
    use_http: true
    logs_dd_url: 172.31.88.133:3838
    logs_no_ssl: true
 ```
 
 With Lambda EVN variables
 
 ```
DD_API_KEY	***
DD_ENV	TEST
DD_LOGS_ENABLED	true
DD_SERVICE	test
DD_SITE	datadoghq.eu
DD_TRACE_ENABLED	true
```

Everything is fine I am getting logs in DD console on my account

2. Option only Lambda ENV variables 

If I will remove datadog.yaml and add instead 3 parameters to ENV following https://docs.datadoghq.com/agent/logs/proxy and https://github.com/DataDog/datadog-agent/blob/deb7fce8f668a4bca6697e76d0b77cb67d7f46f7/pkg/config/config_template.yaml

```
DD_API_KEY	****
DD_ENV	TEST
DD_LOGS_CONFIG_DD_URL	172.31.88.133:3838
DD_LOGS_CONFIG_LOGS_NO_SSL	true
DD_LOGS_CONFIG_USE_HTTP	true
DD_LOGS_ENABLED	true
DD_SERVICE	test
DD_SITE	datadoghq.eu
DD_TRACE_ENABLED	true
```

I do not receive any log in my DD console.

Also here is a quote from 1st link

```
Environment variables have precedence over values in the datadog.yaml file. If the environment variables are present with an empty value, for example: DD_PROXY_HTTP="", the Agent uses the empty values instead of lower-precedence options.
```

**Comment by ian28223** [comment]
Can you try `DD_LOGS_CONFIG_LOGS_DD_URL=172.31.88.133:3838`

**Comment by xrn** [comment]
Hey @ian28223, 

Looks like you are correct it is working. And indeed this is how it is described in a documentation. my mistake:

This is how it should looks like

```
DD_API_KEY	***
DD_ENV	TEST
DD_LOGS_CONFIG_LOGS_DD_URL	172.31.88.133:3838
DD_LOGS_CONFIG_LOGS_NO_SSL	true
DD_LOGS_CONFIG_USE_HTTP	true
DD_LOGS_ENABLED	true
DD_SERVICE	test
DD_SITE	datadoghq.eu
DD_TRACE_ENABLED	
```

Thanks!
