### ISSUE TITLE
Confusing warning: trace writer payload rejected by edge: 403 Forbidden

### ISSUE THREAD

**Issue by allanpaiste** [DataDog/datadog-agent#14875]
After upgrading to latest version of dd-trace node package, we have been experiencing loads of similar errors in logs:

```text
2022-12-28 14:50:55 UTC | TRACE | WARN | (run.go:261 in Warnf) | Trace writer payload rejected by edge: 403 Forbidden
```

When tracing this down from the code-base it does look as if this is shown when some event type is not supported. 

We're only seeing this in staging where we do not have DD_TRACE_ENABLED configured which makes me wonder if this is expected behaviour of the extensions (when initiated and having some environment variables not provided or tracing turned off?).

**Comment by allanpaiste** [comment]
Solution already found. In our case it was an issue of our API key (DD_API_KEY) being connected to an account created for domain **datadoghq.eu** where the default setup will probably communicate with **datadoghq.com** instead.

Solved by defining: `DD_SITE=datadoghq.eu`

**Comment by matthiasthomas** [comment]
> Solution already found. In our case it was an issue of our API key (DD_API_KEY) being connected to an account created for domain **datadoghq.eu** where the default setup will probably communicate with **datadoghq.com** instead.
> 
> Solved by defining: `DD_SITE=datadoghq.eu`

Thanks @allanpaiste - Took me forever to solve this one.
