### ISSUE TITLE
Feature Request: Docker Image variant stripped

### ISSUE THREAD

**Issue by bobbytables** [DataDog/datadog-agent#1495]
In our environment we deploy docker image tags with the variant changed to indicate a new version For example: `namely.registry.land/namely/our-awesome-app:v123` on a deploy, `v123` will go to `v1234`.

The reason this is a problem is in our dashboards on datadog.com, we can't filter on `docker_image` tags because they change on deploys.

It would be nice to have another `docker_image` tag that omits the variant portion of the image. So our dashboards can filter on just `namely.registry.land/namely/our-awesome-app` so deploys dont break graphs.

**Comment by xvello** [comment]
Hi!

The `image_name` and `short_image` are probably what you are looking for. The tag part of the image name is in `image_tag`.

Depending on your orchestrator, more tags are also available. The [metrics summary](https://app.datadoghq.com/metric/summary) is a great tool to see what tags are available for a metric.

**Comment by bobbytables** [comment]
Oh look at that! My bad, didnt see these. I was looking for `docker_` prefixes while searching.
