### ISSUE TITLE
logs group by pattern is not working properly

### ISSUE THREAD

**Issue by vipulJain05** [DataDog/datadog-agent#15040]
The number of logs for one of the services shows 9.56k error logs but when I grouped them by pattern, it displays only 4 logs and many actual logs are missing in actual patterned logs, which is a high discrepancy in data.
Please see attached screenshots.

![Screenshot 2023-01-12 at 10 28 20 AM](https://user-images.githubusercontent.com/47937063/211980896-80515743-bef1-43a9-9a65-f6b515686da0.png)
![Screenshot 2023-01-12 at 10 29 00 AM](https://user-images.githubusercontent.com/47937063/211981125-cb98a5eb-e15b-4ace-a18f-2d88e8953138.png)

**Comment by brandonmwest** [comment]
Hi there, please contact Datadog support for help with this unless you have some evidence that there is a problem with the Datadog agent itself. Thanks
