### ISSUE TITLE
datadog-agent too CPU intensive in kubernetes context

### ISSUE THREAD

**Issue by sylr** [DataDog/datadog-agent#1507]
**Describe what happened:**

datadog-agent agent processes deployed in kubernetes via a DaemonSet use far too much CPU resources for a simple collection agent.

```
bastion1:~$ for i in $(cat screenrc-k8s2-euw-dev | awk '{print $5;}'); do echo $i ====; ssh $i "ps auxf | grep 'agent start' | grep -v grep"; done
k8s-agent-57301243-0 ====
root      42511 18.0  2.1 2025376 359276 ?      Ssl  Mar20 563:36      |       |   \_ agent start
k8s-agent-57301243-1 ====
root      70128 15.4  0.7 1672532 131100 ?      Ssl  Mar20 548:11      |       |   \_ agent start
k8s-agent-57301243-2 ====
root       3496 18.6  1.0 1812308 170000 ?      Ssl  Mar16 1589:01      |       |   \_ agent start
k8s-master-57301243-0 ====
root     101188 19.3  2.6 979988 107716 ?       Ssl  Mar15 1903:57              |   \_ agent start
k8s-master-57301243-1 ====
root     125442 19.1  2.4 979188 100672 ?       Ssl  Mar15 1891:00              |   \_ agent start
k8s-master-57301243-2 ====
root     111621 19.1  2.6 1111060 108376 ?      Ssl  Mar15 1887:51              |   \_ agent start
```

Here a ps output that shows the agent on 6 hosts that all use around 18% of CPU.

**Describe what you expected:**

A much less CPU intensive agent.

**Additional environment details (Operating System, Cloud provider, etc):**

Kubernetes.

**Comment by CharlyF** [comment]
Hey @sylr,

Thanks for opening this!
Any chance you can open a ticket with the [support team](support@datadoghq.com) and forward the following info from within a pod running the agent:
- `curl http://localhost:5000/debug/pprof/goroutine?debug=2`
- `curl -s http://localhost:5000/debug/vars`
- `agent status`

These outputs will help us get more context, most are listed in https://github.com/DataDog/datadog-agent/blob/master/docs/dev/tools.md.

Finally, could you share more details on the checks that you are running, how you deployed the agents, the machines and the versions of kubernetes and docker ?

Thank you very much.
Charly

**Comment by sylr** [comment]
@CharlyF Support request 136515

**Comment by CharlyF** [comment]
Thanks!
We'll follow up with you on the ticket.

**Comment by andor44** [comment]
We're seeing similar behavior in k8s. CPU usage seems to be a direct function of the number of (running) containers on the host.

![image](https://user-images.githubusercontent.com/496456/38315921-d2419d3a-3829-11e8-8c62-c3d534013a89.png)

Nodes with a few containers have CPU usage below 10%, nodes with tens of containers have CPU usage in the double digits.

**Comment by SleepyBrett** [comment]
We see this and also see high usage on the agent that is on the same node as the ksm pod. That agent pod is also crashing .. a lot.

**Comment by andor44** [comment]
In the past few versions CPU usage has improved a bit, now on 6.2.1 we're seeing CPU usage stable in the 5-10% range, and can confirm @SleepyBrett's observation too. In our case the one node running KSM is quite an outlier at around 25% CPU.

**Comment by sylr** [comment]
Datadog installed

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.12    0.00    2.74   16.57    0.00   77.57

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00  151.00    0.50  6916.00    12.00    91.46     2.60   14.01   14.05    0.00   6.27  95.00
sdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdd               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdc               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

Datadog removed

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.09    0.00    1.45    0.19    0.00   95.27

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.50     0.00    12.00    48.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdd               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdc               0.00     1.00    0.00    1.50     0.00   188.00   250.67     0.02   12.00    0.00   12.00  12.00   1.80
```

**Comment by techdragon** [comment]
I've noticed higher iowait correlated with agent issues coincidental with periods where in the agent stops sending to DataDog's servers. The AWS CloudWatch metrics are the only real clue to the behaviour unfortunately as I filtered out the agent's logs from my log collection pipeline due to its noise level.
