### ISSUE TITLE
Please expose `DD_PROCESS_CONFIG_EXPVAR_PORT`

### ISSUE THREAD

**Issue by cloudbustinguk** [DataDog/datadog-agent#15191]
Hey all,

Much like #1670, we would like to have the ability to override `process_config.expvar_port` via envvar. From looking at the code, it doesn't appear that this is bound at all.

More context: Port 6062 is almost always bound-to by one of Spark java processes, and means the driver won't come up as Datadog's `process-agent` already did a `bind()`. While we _can_ update the Spark config to move the port as per [these instructions](https://docs.databricks.com/notebooks/ipywidgets.html#:~:text=By%20default%2C%20ipywidgets%20occupies%20port%206062.%20With%20Databricks%20Runtime%2011.2%20and%20above%2C%20if%20you%20run%20into%20conflicts%20with%20third%2Dparty%20integrations%20such%20as%20Datadog%2C%20you%20can%20change%20the%20port%20using%20the%20following%20Spark%20config%3A):

```
By default, ipywidgets occupies port 6062. With Databricks Runtime 11.2 and above, if you run into conflicts with third-party integrations such as Datadog, you can change the port using the following [Spark config](https://docs.databricks.com/clusters/configure.html#spark-configuration):

spark.databricks.driver.ipykernel.commChannelPort <port-number>

For example:

spark.databricks.driver.ipykernel.commChannelPort 1234
```

.. it shouldn't be that we have to change the actual platform we're trying to monitor instead of the platform doing the monitoring.

For those currently suffering, writing the following to the `datadog.yaml` will solve this for now, but it's not ideal (port chosen close to the default range but not to far as to risk some other service):

```bash
printf "process_config\n  expvar_port: 6163\n" >> /etc/datadog-agent/datadog.yaml
```

Do you take PRs?

Cheers

**Comment by bzillins** [comment]
I'd like to second this request as this needs to be set on spark driver nodes to prevent a port conflict.

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.

Thanks!
