### ISSUE TITLE
[BUG] Error Sidekiq Integration 

### ISSUE THREAD

**Issue by RachalCassity** [DataDog/datadog-agent#15251]
**Agent Environment**

**Describe what happened:**
We are attempting to integrate Sidekiq by using the dogstatsd mapper profiles. The following code was added to the datadog-agent/values.yaml. When creating metric mappers, only the wildcard match type is permitted.

```
      - name: DD_DOGSTATSD_MAPPER_PROFILES
        value: >
          [{"prefix":"sidekiq.","name":"sidekiq","mappings":[{"match":"sidekiq\\.sidekiq\\.(.*)","match_type":"regex","name":"sidekiq.$1"},{"match_type":"regex","name":"sidekiq.jobs.perform","match":"sidekiq\\.jobs\\.(.*)\\.perform","tags":{"worker":"$1"}},{"name":"sidekiq.jobs.worker.$2","match":"sidekiq\\.jobs\\.(.*)\\.(count|success|failure)","match_type":"regex","tags":{"worker":"$1"}}]}]
```

The configuration for helm charts was found in this [document](https://docs.datadoghq.com/integrations/airflow/?tab=containerized#containerized).

We are receiving this error:
`2023-01-23 07:00:54 UTC | CORE | WARN | (pkg/dogstatsd/server.go:409 in NewServer) | Could not create metric mapper: invalid wildcard match pattern `sidekiq\.jobs\.(.*)\.perform`, it does not match allowed match regex `^[a-zA-Z0-9\-_*.]+$``

In the [mapper.go ](https://github.com/DataDog/datadog-agent/blob/main/pkg/dogstatsd/internal/mapper/mapper.go#L101) configuration, this error should only be showing when there is a wildcard match type.

**Describe what you expected:**
We expected not to have an regex error and for sidekiq metrics to be sent to Datadog.

**Steps to reproduce the issue:**
Attempt sending the configuration with the sidekiq integration instructions.

**Additional environment details (Operating System, Cloud provider, etc):**

appVersion: "7.38.2"
dependencies:
  - name: datadog
    version: "3.0.1"
    repository: "https://helm.datadoghq.com"

**Comment by vickenty** [comment]
This mapper config is correct and works as expected on 7.38.2, so this doesn't seem to be a bug in the agent.

Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
