### ISSUE TITLE
CreateContainerConfigError on datadog agent

### ISSUE THREAD

**Issue by sezerozann** [DataDog/datadog-agent#15293]
During the configuration datadog Agent yaml file. I have faced with an issue at the installation of helm. Pod is successfully pulling the datadog agent image. However, It's stacking in the "CreateContainerConfigError" state as in shown in the below image. 

![image](https://user-images.githubusercontent.com/48368663/215094294-78b4da2c-8f35-442b-a5ab-8e4cfdf08d09.png)

Then I have checked the pod description and on the event part it show below below fail. 

![image](https://user-images.githubusercontent.com/48368663/215094399-a7aa2423-87b2-4ac3-9a65-96cf018e2c15.png)

I have checked the datadog documentations. It's happening due to configuration file. On configuration file I have set clusterName, apiKey, appKey successfully. However, I didn't get why I'm getting this error on that pod. Can anyone help me for this issue?

Thanks in Advance

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
