### ISSUE TITLE
[BUG] Setting invalid regex on DD_APM_REPLACE_TAGS causes trace-agent crash

### ISSUE THREAD

**Issue by bradam12** [DataDog/datadog-agent#15303]
**Agent Environment**
`Agent 7.42.0 - Commit: 1b72bcf - Serialization version: v5.0.46 - Go version: go1.18.9`

**Describe what happened:**
I'm setting `DD_APM_REPLACE_TAGS` on `agents.containers.traceAgent.env` following [these docs](https://docs.datadoghq.com/tracing/configure_data_security/?tab=kubernetes#scrub-sensitive-data-from-your-spans). I had some bad regex in the pattern match, which caused trace-agent container to immediately terminate with exit 1 status code. Even setting debug level to DEBUG, no logs are outputted indicating there's an issue with the regex. 

After fixing the regex it worked, of course, but ideally the agent would catch this error gracefully.

**Describe what you expected:**
Gracefully decline invalid regex in `DD_APM_REPLACE_TAGS`, either ignoring the single bad config group, or rejecting the env var entirely with an error message displayed in the logs.

**Steps to reproduce the issue:**
Set DD_APM_REPLACE_TAGS envvar on trace-agent. My particular regex had an extra closing `)` after `anotherthing`.
Set logLevel to DEBUG (optional)
Observe trace-agent container crashing with no log output, exit code 1.
```
env:
  - name: DD_APM_REPLACE_TAGS
    value: '[
              {
                "name": "resource.name",
                "pattern": "/users/(.+?)(/(page1|otherpage|something|anotherthing))|$)",
                "repl": "/users/[user]$2"
              }
            ]'
```

**Additional environment details (Operating System, Cloud provider, etc):**
GKE 1.24.8
`Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8-gke.2000", GitCommit:"63bd400145c58fe450325af1d249c3072fed68ef", GitTreeState:"clean", BuildDate:"2022-12-07T09:33:04Z", GoVersion:"go1.18.8b7", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by ahmed-mez** [comment]
Thank you for opening the isse @bradam12 ! The crash is expected, we want the user to be aware asap when a critical config like `DD_APM_REPLACE_TAGS` is invalid.
What's not expected though is that the error wasn't printed, opened https://github.com/DataDog/datadog-agent/pull/15566 to fix it.
