### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'snowflake'

### ISSUE THREAD

**Issue by mfarouks** [DataDog/datadog-agent#15350]
**Agent Environment**
Agent 7.42.0

**Describe what happened:**
I'm setting the base docker image to `FROM datadog/agent:7` and running snowflake custom queries
Tried to rebuild the image got an error `ModuleNotFoundError: No module named 'snowflake'`

**Describe what you expected:**
Expecting custom metrics from snowflake custom queries

**Steps to reproduce the issue:**
Setup snowflake connection.
Add custom queries or even let the default one enabled

**Additional environment details (Operating System, Cloud provider, etc):**
Operating System: Linux
Cloud provider: AWS
Operating on : ECS Fargate

**Comment by iliakur** [comment]
@mfarouks thanks for the report! The fix for this [has been merged](https://github.com/DataDog/datadog-agent/pull/15242) and v7.42.1 will include it.
