### ISSUE TITLE
[BUG] Medium Security Vulnerability

### ISSUE THREAD

**Issue by brandocomando** [DataDog/datadog-agent#15367]
**Agent Environment**
latest datadog agent container image

**Describe what happened:**
Scanned container with snyk and found fixable vulnerabilityy
https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMCONTAINERDCONTAINERDPKGCRISTREAMINGREMOTECOMMAND-3164748

**Describe what you expected:**
Synk scan would report no issues

**Steps to reproduce the issue:**
Scan conatiner image with snyk

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
