### ISSUE TITLE
Metric on my horizontalPodAutoscaler is different than the one in metrics explorer on prod env

### ISSUE THREAD

**Issue by fbarrerafalabella** [DataDog/datadog-agent#15411]
Hi, I have 2 different environments, staging and prod, in both I have configured the same horizontalPodAutoscaler, with different values and for each cluster I have a different clusterAgent, with different values, the thing is that in staging the metrics explore shows the same value that my hpa gets but for prod for example the metrics explorer says I have 15 nginx.net.request_per_s and in my hpa it says it is on 806m, why is this happening, I have the same configuration on each agent

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
