### ISSUE TITLE
Add AWS SSM Support for API KEY

### ISSUE THREAD

**Issue by justin-watkinson-electric** [DataDog/datadog-agent#15467]
## Expected Behavior

When using the datadog serverless plugin, I want to ensure that in the AWS console contains no plaintext credentials.  For this situation, it is preferred that we keep secrets in the AWS Systems Manager Parameter Store as an encrypted (SecureString secret), as opposed to AWS Secrets Manager.

By the nature of how the serverless plugin works, it is helpful to have the secret available by way of the Datadog agent as early on in the invocation as possible, without externalized hooks/call-outs.  A native implementation would provide the same wrapper feature without having to do it ourselves in custom fashion.

Related ticket:  https://github.com/DataDog/serverless-plugin-datadog/issues/340

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.

Thanks!
