### ISSUE TITLE
datadog-agent doesn't report HTTP 1.1 transcation if client doesn't send FIN for some reason

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [DataDog/datadog-agent#15530]
**Agent Environment**

Linux version 5.15.0-60-generic (buildd@lcy02-amd64-054) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023

linux kernel: 5.15.0-60-generic

**Describe what happened:**

When I use a browser to access port 8080 of java, the HTTP response contains TIMEOUT 60s. After the timeout, the java program sends FIN, but the browser does not close, and CLOSE_WAIT appears on the browser, and after a while, the java program will Send an RST to the browser to forcibly close the unclosed connection of the browser.

**Describe what you expected:**

Where the DATADOG code goes wrong:

```
static __always_inline bool http_closed(http_transaction_t *http, skb_info_t *skb_info, u16 pre_norm_src_port) {
    if (skb_info && skb_info->tcp_flags&(TCPHDR_FIN|TCPHDR_RST)) {
        if (http->tup.sport == 8080 || http->tup.dport == 8080 || http->tup.sport == 9093 || http->tup.dport == 9093) {
            log_trace("http_closed function:  http->owned_by_src_port=%ld; pre_norm_src_port:%d\n",
            http->owned_by_src_port, pre_norm_src_port);
        }
    }
    return (skb_info && skb_info->tcp_flags&(TCPHDR_FIN|TCPHDR_RST) &&
            // This is done to avoid double flushing the same
            // `http_transaction_t` to userspace.  In the context of a regular
            // TCP teardown, the FIN flag will be seen in "both ways", like:
            //
            // server -> FIN -> client
            // server <- FIN <- client
            //
            // Since we can't make any assumptions about the ordering of these
            // events and
[ck-log.zip](https://github.com/DataDog/datadog-agent/files/10703042/ck-log.zip)
 there are no synchronization primitives available to
            // us, the way we solve it is by storing the non-normalized src port
            // when we start tracking a HTTP transaction and ensuring that only the
            // FIN flag seen in the same direction will trigger the flushing event.
            http->owned_by_src_port == pre_norm_src_port);
}
```

**Steps to reproduce the issue:**

Start the java application:
```
java -Xmx512m -Xms512m -Djava.security.egd=file:/dev/./urandom -jar apm-test-0.0.1-SNAPSHOT.jar
```
Use Google Chrome to access:
```
http://localhost:8080/test200
```
[ck-log.zip](https://github.com/DataDog/datadog-agent/files/10703046/ck-log.zip)

You will find that datadog HTTP Transport are never reported.

There are logs in the file.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by guyarb** [comment]
Hey @LeiZhang-Hunter, thank you for reporting the bug
Can you please share the source code (or an example source code) so we can reproduce the issue?
(I've seen you shared a jar file, but I prefer not to run any unknown binary)

**Comment by LeiZhang-Hunter** [comment]
Java source code:
[apm-test.zip](https://github.com/DataDog/datadog-agent/files/10730593/apm-test.zip)

**Comment by guyarb** [comment]
hey @LeiZhang-Hunter, we merged a fix
please report back if you are still facing issues.
