### ISSUE TITLE
Updating dd-agent user from nologin to login

### ISSUE THREAD

**Issue by PritishDeb** [DataDog/datadog-agent#15939]
Is there any concern updating the dd-agent from /sbin/nologin to /bin/bash?
Or it is recommended to not alter the dd-agent user?

Thanks!

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
