### ISSUE TITLE
[Suggestion] Reduce the parameters in the method and create a struct.

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [DataDog/datadog-agent#15971]
There are too many functions with the same parameter and too many with more than 4 arguments.
Clean code book Uncle Bob, which is just a guide to better ways of writing code recommends that for more than 3 arguments you create an object.

https://github.com/DataDog/datadog-agent/blob/91a50b9adb977bfe2295bb21b98fbe3abea9756c/pkg/aggregator/sender.go#L23

```go
	Gauge(metric string, value float64, hostname string, tags []string)
	GaugeNoIndex(metric string, value float64, hostname string, tags []string)
	Rate(metric string, value float64, hostname string, tags []string)
	Count(metric string, value float64, hostname string, tags []string)
	MonotonicCount(metric string, value float64, hostname string, tags []string)
	MonotonicCountWithFlushFirstValue(metric string, value float64, hostname string, tags []string, flushFirstValue bool)
	Counter(metric string, value float64, hostname string, tags []string)
	Histogram(metric string, value float64, hostname string, tags []string)
	Historate(metric string, value float64, hostname string, tags []string)
```

**Comment by carlosroman** [comment]
Thank you submitting this suggestion. At the moment we can't change the signature of that method as it will break the contract we have with other services using it. We need to keep breaking changes to a minimum in the Agent so for now we have decided to turn down this suggestion.
