### ISSUE TITLE
No way to disable syslog output

### ISSUE THREAD

**Issue by pvalsecc** [DataDog/datadog-agent#1606]
**Describe what happened:**

I've tried several ways to disable log output to syslog, but found nothing that works. Looking at the code, there should be a way to disable them using the `log_to_syslog` config option to `false` or something but I still have logs in `/var/log/syslog` coming from the agent.

**Describe what you expected:**

Only logs in `/var/log/datadog/`

**Steps to reproduce the issue:**

Try to disable syslog output.

**Additional environment details (Operating System, Cloud provider, etc):**

Linux Ubuntu 18.10 rc with datadog-agent 6.1.3-1.

**Comment by pvalsecc** [comment]
Works like a charm. I had to edit the config for the 3 services though.

Thanks

**Comment by eldy** [comment]
This is how i did:
into datado.yaml, i set
log_to_syslog=false
but also 
log_to_console=false

Logs is still done into /var/log/datadog/*.log files but no more in syslog.

**Comment by arslan70** [comment]
> This is how i did:
> into datadog.yaml, i set
> `log_to_syslog=false`
> but also
> `log_to_console=false`
> 
> Logs is still done into /var/log/datadog/*.log files but no more in syslog.

This doesn't work for me unfortunately

**Comment by vjcalel** [comment]
@olivielpeau Systemd only start/stop services. It has nothing to do with where the application wants to send the log. Lots of other services like graylog, postgres, ufw also uses journald but at the same offers to log into a specific file/folder /var/log/<app-name>. 

Please implement the feature. Stopping journald logs means you won't get important logs from kernel which is not acceptable.
