### ISSUE TITLE
[Feature Request] Allow installing DataDog agent on M2 Macbooks without Rosetta 2

### ISSUE THREAD

**Issue by ryanhugh** [DataDog/datadog-agent#16147]
Right now, the datadog-agent for Mac requires Rosetta 2 to be installed. It would be great if you could add support for the arm64 M2 architecture natively, without the need for Rosetta. 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/5777995/225692467-1a827896-3c28-4331-91f0-620af5e2ecc9.png">

Btw, is it possible to compile the agent from source for arm64 for Mac?

Thanks!

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.

Thanks!

**Comment by rdesgroppes** [comment]
We have good news for you: starting with version 7.70, the Rosetta 2 requirement will be lifted when installing the native version of the Agent for AArch64/ARM64 on macOS, which is in the works. To do this, you'll need to use the latest installation script according to the instructions found at: https://docs.datadoghq.com/agent/basic_agent_usage/osx/
