### ISSUE TITLE
Datadog http config issue

### ISSUE THREAD

**Issue by abilashksv** [DataDog/datadog-agent#1624]
**[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (tagger.go:150 in tryCollectors) | docker tag collector successfully started
[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (tagger.go:150 in tryCollectors) | kubelet tag collector successfully started
[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (runner.go:92 in NewRunner) | Runner started with 1 workers.
[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (collector.go:51 in NewCollector) | Embedding Python 2.7.14 (default, Apr 19 2018, 16:51:59) [GCC 4.7.2]
[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (autoconfig.go:62 in SetupAutoConfig) | Registering kubelet config provider
[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (file.go:69 in Collect) | File Configuration Provider: searching for configuration files at: /etc/datadog-agent/conf.d
[ AGENT ] 2018-04-23 17:35:41 UTC | INFO | (file.go:69 in Collect) | File Configuration Provider: searching for configuration files at: /opt/datadog-agent/bin/agent/dist/conf.d
[ AGENT ] 2018-04-23 17:35:41 UTC | WARN | (file.go:73 in Collect) | Skipping, open /opt/datadog-agent/bin/agent/dist/conf.d: no such file or directory
[ AGENT ] 2018-04-23 17:35:42 UTC | ERROR | (autoconfig.go:248 in getChecksFromConfigs) | Unable to load the check: unable to load any check from config 'http'
[ AGENT ] 2018-04-23 17:35:43 UTC | WARN | (check.go:243 in Configure) | could not get a check instance with the new api: __init__() takes at least 4 arguments (4 given)
[ AGENT ] 2018-04-23 17:35:43 UTC | WARN | (check.go:244 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the constructor
[ AGENT ] 2018-04-23 17:35:43 UTC | WARN | (check.go:269 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_config` function from the 'datadog_agent' packa
ge (postgres).*
```
(Paste the output of the info page here)
```

**Describe what happened:**
When we tried to enable http to monitor a url we got this error and http monitor was not working

**Describe what you expected:**
should monitor the external url provided

**Steps to reproduce the issue:**
 my-http-config: |-
    init_config:
    instances:
      - name: datazoom_app
        url: http://any-url/
        timeout: 1
add the above config to your datadog yaml file and restart the pod.

**Additional environment details (Operating System, Cloud provider, etc):**

cloud - GCE
Setup - Kubernetes
Host OS - ubuntu 16.04

**Comment by olivielpeau** [comment]
Hi @abilashksv, this looks like an issue with the name of the check that you configured: it should be `http_check` instead of `http`. Make sure that in your Agent manifest the `configMap` is configured so that the written yaml file is `http_check.yaml` or `http_check.d/conf.yaml`. Please refer to the documentation here: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#custom-integrations

Thanks! If you're still having issues, feel free to contact our support team and [send a flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare).
