### ISSUE TITLE
OTLP Logs Injestion

### ISSUE THREAD

**Issue by jamiewinder** [DataDog/datadog-agent#16285]
I think I'm correct in understanding that the OTLP Collector support in Datadog Agent is limited to receiving traces and metrics. 

Is receiving logs through the same means supported (or planned)?

**Comment by dineshg13** [comment]
@jamiewinder This is planned. We don't have exact timeline for same.

**Comment by dineshg13** [comment]
This is supported as docs suggest. Please try out and let us know.
