### ISSUE TITLE
Best practice to run both cluster-agent and agent in Kubernetes?

### ISSUE THREAD

**Issue by lkysow** [DataDog/datadog-agent#1633]
Hi, I'm not sure if I should be running both the agent and the cluster-agent or just the agent? Looks like the agent handles Kubernetes events now so is there any point running the `cluster-agent`?

**Comment by CharlyF** [comment]
Hey @lkysow,

Thank you for reaching out and big apologies for the delay here.
The cluster agent is indeed in charge of collecting the Kubernetes events as well as expose the cluster level metadata and soon will have many more powerful features.
It's role is to act as a proxy between the agents and the API Server to separate concerns and alleviate the agents' impact on the API server in large workloads.

Nevertheless, the DCA (Datadog Cluster Agent) is not yet in GA but will soon be in beta.
I would be very happy to chat with you if you have any interests in using it :).

Best,
Charly

**Comment by lkysow** [comment]
Hi Charly,
I'm not working on this project anymore so can't help you test out DCA unfortunately. Happy to hear this is the direction you're taking though because using configmaps to do leader election is pretty hacky when a simple 1 replica deployment would suffice. Plus this would also fix the weirdness that all your cluster stats are coming from a single host.

**Comment by CharlyF** [comment]
Indeed, that is the intent! 
I'm going to close this issue but feel free to reach out to me directly should you have more questions :).
Thanks again for your interest.

Best,
Charly
