### ISSUE TITLE
[BUG] Unable to read authentication token file

### ISSUE THREAD

**Issue by ljsinclair** [DataDog/datadog-agent#16559]
**Agent Environment**

* Agent v7
* Ubuntu (running in WSL2 on WIndows 10)
* Logged in as administrator user (non ROOT)

**Describe what happened:**

1. Datadog not successfully connecting to datadoghq
2. Datadog reports error "Error: unable to read authentication token file: open /etc/datadog-agent/auth_token: no such file or directory"

**Describe what you expected:**

* Datadog connects successfully to datadoghq
* Datadog does not report errors

**Steps to reproduce the issue:**

* Installed Datadog-Agent via the New account UI

Result: Agent installed and started up correctly:

```
* Starting the Datadog Agent...

  Your Datadog Agent is running and functioning properly.
  It will continue to run in the background and submit metrics to Datadog.
  If you ever want to stop the Datadog Agent, run:

      sudo systemctl stop datadog-agent

  And to run it again run:

      sudo systemctl start datadog-agent
```

* Run `sudo datadog-agent status`

Result:
```
Error: unable to read authentication token file: open /etc/datadog-agent/auth_token: no such file or directory
```

**Additional environment details (Operating System, Cloud provider, etc):**

* Host system = windows 10
* WSL2 running Ubuntu
* Datadog installed into WSL2 Ubuntu
* Docker installed on WSL2 but not running any containers

**Comment by azaky** [comment]
I have the same exact issue. I was able to fix this by manually setting `hostname` in `/etc/datadog-agent/datadog.yaml`.

Running from Windows 11, WSL2 Ubuntu 22.04, Agent version 7.46.0.

**Comment by fagianijunior** [comment]
I have the same issue running as sidecar on ECS fargate.

**Comment by wemersonferreira** [comment]
Hi everyone, I'm having the same issue, this problem started when I updated datadog agent from 7.38.2 to 7.49.1. I can't use the same soluction as @azaky because we have a fleet of hots, we don't have the exacle hostname for all.
 My orchestration is EKS with EC2 linux2.

**Comment by tofi86** [comment]
Happens for me as well when upgrading from 7.45.1 to 7.49 or even 7.49.1.

`hostname` has already been declared manually in `/etc/datadog-agent/datadog.yaml`

**Comment by 2rs2ts** [comment]
Happening for me too. Why is this marked as completed when there is no resolution?

**Comment by 2rs2ts** [comment]
We figured the problem out. At some point, the docker image was changed so that it didn't declare these directories as `VOLUME`s in the Dockerfile, and since the docker image runs as non-root by default, you run into this funny case in Kubernetes where, because the uid in the container doesn't have permission to write to kubelet's dir where it creates `emptyDir`s, you can't write to any `emptyDir`s unless you give your container the `DAC_OVERRIDE` capability or you run it as root. When you download manifests from datadog's docs site, you will see they configure it to run as root, but that seemed like using a sledgehammer to drill a hole in a wall, so we just gave our agent the capability necessary.

Apparently, other features of the agent require even more capabilities, so running as root removes the most roadblocks for you, so, pick your poison, I guess.

**Comment by baltox61** [comment]
[2rs2ts](https://github.com/2rs2ts) so what did you do to give it the necessary capabilities

**Comment by 2rs2ts** [comment]
@baltox61 it seems to depend on the exact stuff your container is doing, but, you at least have to give the container `DAC_OVERRIDE`. (Forgive me for being inexact. We've had to deal with other issues and so our capabilities list isn't just this one capability for this one issue; I just know for sure that `DAC_OVERRIDE` is needed.)

Alternatively you can just run the container as root, which is the default configuration when you pull a manifest from DataDog's docs site. The image itself says not to run as root, but the manifest they provide on their docs site overrides the `securityContext` to make the container run as root. (I have, at times, wondered if we should just run as root... even though that's not considered a best practice, it also isn't good to give containers `DAC_OVERRIDE`. It's kind of nuts that they introduced such a major security regression.)

If you are asking "how does one give a container extra capabilities in Kubernetes," then it's all in the `securityContext`: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by lboix** [comment]
> I have the same issue running as sidecar on ECS fargate.

I also have this issue setuping Datadog NPM module in a sidecar container and fixed it like this :
- https://github.com/DataDog/documentation/pull/26276/files
