### ISSUE TITLE
My data will not turn on it is just there but you can't turn the mobile data on

### ISSUE THREAD

**Issue by Dianna531963** [DataDog/datadog-agent#1657]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by Dianna531963** [comment]
I bought the phone from a person and they got it home to me and the icon is there but you can't turn it on please help

**Comment by olivielpeau** [comment]
Hi @Dianna531963. This is not the correct place to ask for support for your phone, we do not sell or manufacture phones. Please contact your phone vendor or manufacturer.
