### ISSUE TITLE
[BUG] system-probe leaks shared library probe resources

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#16646]
The `soRegistry.Register` calls made by `soWatcher` are made once per mapping while the `soRegistry.Unregister` calls are made once per process (see [this file](https://github.com/DataDog/datadog-agent/blob/3069e62833c52cb2f19ae6802e5366a7eb70d681/pkg/network/protocols/http/shared_libraries.go)). This results in `soRegistry`'s reference counts not reaching 0 for libraries with multiple mappings in a single process and the corresponding resources leaking.

There are two flavors `soRegistry.Register` calls:
1. Initial scanning [here](https://github.com/DataDog/datadog-agent/blob/3069e62833c52cb2f19ae6802e5366a7eb70d681/pkg/network/protocols/http/shared_libraries.go#L196) definitely has the issue because [this library call](https://github.com/DataDog/datadog-agent/blob/3069e62833c52cb2f19ae6802e5366a7eb70d681/pkg/network/protocols/http/shared_libraries.go#L186) returns an item per mapping and not per library path - see [Process.MemoryMaps in DataDog/gopsutil](https://github.com/DataDog/gopsutil/blob/9be8505857772f6c4c963b0d59ae3b83c3c372cb/process/process_linux.go#L474-L513)
2. The call on [this line](https://github.com/DataDog/datadog-agent/blob/3069e62833c52cb2f19ae6802e5366a7eb70d681/pkg/network/protocols/http/shared_libraries.go#L257) may also be affected, but I haven't looked at the source of the events on [w.loadEvents.DataChannel](https://github.com/DataDog/datadog-agent/blob/3069e62833c52cb2f19ae6802e5366a7eb70d681/pkg/network/protocols/http/shared_libraries.go#L227) to confirm

Loading the same library more than once is not uncommon. E.g. datadog-agent does this:
```
$ kubectl --context awscmhqa3 --namespace datadog exec -it datadog-agent-qt87n --container agent -- bash
root@datadog-agent-qt87n:/# grep -P '(libgnutls.so|libssl.so|libcrypto.so)' /proc/1/smaps
7f64e3ef4000-7f64e3f6b000 r--p 00000000 00:1cf 1319173                   /opt/datadog-agent/embedded/lib/libcrypto.so.1.1
7f64e3f6b000-7f64e40f1000 r-xp 00077000 00:1cf 1319173                   /opt/datadog-agent/embedded/lib/libcrypto.so.1.1
7f64e40f1000-7f64e417f000 r--p 001fd000 00:1cf 1319173                   /opt/datadog-agent/embedded/lib/libcrypto.so.1.1
7f64e417f000-7f64e41ad000 r--p 0028b000 00:1cf 1319173                   /opt/datadog-agent/embedded/lib/libcrypto.so.1.1
7f64e41ad000-7f64e41b0000 rw-p 002b9000 00:1cf 1319173                   /opt/datadog-agent/embedded/lib/libcrypto.so.1.1
7f64e4266000-7f64e4282000 r--p 00000000 00:1cf 1319221                   /opt/datadog-agent/embedded/lib/libssl.so.1.1
7f64e4282000-7f64e42cd000 r-xp 0001c000 00:1cf 1319221                   /opt/datadog-agent/embedded/lib/libssl.so.1.1
7f64e42cd000-7f64e42e7000 r--p 00067000 00:1cf 1319221                   /opt/datadog-agent/embedded/lib/libssl.so.1.1
7f64e42e7000-7f64e42ef000 r--p 00081000 00:1cf 1319221                   /opt/datadog-agent/embedded/lib/libssl.so.1.1
7f64e42ef000-7f64e42f4000 rw-p 00089000 00:1cf 1319221                   /opt/datadog-agent/embedded/lib/libssl.so.1.1
root@datadog-agent-qt87n:/# 
exit
```

TODO expand on the impact, extended downtime, and architectural issue with using a daemonset

**Comment by deadok22** [comment]
Other than the fd leak, `soWatcher`'s logic is inherently racy: the register/unregister events are delivered asynchronously (which means they can be observed out of order), and events can be lost. Implementing some sort of periodic pruning of the registry would be worthwhile. Perhaps, it'd be best to handle that in a separate issue?

**Comment by deadok22** [comment]
I just spotted one more flavor of leaks.

If a process loads more than one of the supported libs (libssl.so, libcrypto.so, libgnutls.so), only 1 of the pid->soRegistration is kept - the rest registrations become orphaned - see https://github.com/DataDog/datadog-agent/blob/3069e62833c52cb2f19ae6802e5366a7eb70d681/pkg/network/protocols/http/shared_libraries.go#L108

**Comment by guyarb** [comment]
> one more flavor o

we have different `soWatcher` instances for each regex, so the scenario cannot happen

**Comment by guyarb** [comment]
@deadok22, thanks for reporting the issue and having a great investigation around it!
We'll deep dive into it and fix it

**Comment by deadok22** [comment]
Thanks @guyarb!

> we have different soWatcher instances for each regex, so the scenario cannot happen

These lines seems to say otherwise?
https://github.com/DataDog/datadog-agent/blob/2d575240bd0f1582f848308ac978971ad2dda3ca/pkg/network/protocols/http/ebpf_ssl.go#L296-L312

**Comment by guyarb** [comment]
@deadok22 indeed, great catch!
