### ISSUE TITLE
expose expvar in env variable

### ISSUE THREAD

**Issue by bartwalczak1** [DataDog/datadog-agent#1670]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
expvar is blocking port 5000, right now this is only configurable via datadog conf file. 

**Describe what you expected:**
Proper approach is to have this configurable in kube resource manifest via environment variable, so there's no need to pre-bake complete config file and mount it.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
aws, kubernetes.

**Comment by truthbk** [comment]
This is indeed correct, `expvar_port` is *not* bound to an environment variable `DD_EXPVAR_PORT`. We should fix this. Thanks for the feedback @bartwalczak1

**Comment by antoinepouille** [comment]
This was merged https://github.com/DataDog/datadog-agent/pull/1877, adding the env var, which will be available in the next release `6.4.0`
