### ISSUE TITLE
[BUG]  On the same physical machine, there are two PODs,  the POD accesses another POD through the Service, and the HTTP data is missing.

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [DataDog/datadog-agent#16716]
**Agent Environment**

CentOS Linux release 7.9.2009 (Core)
5.4.221-1.el7.x86_64
K8S-PODA:  172.16.33.246 (node:vm50)
K8S-PODB:  172.16.161.180 (node:vm50)
K8S-service:greeter-server-nodeport-3-6-1-41-1    NodePort    10.101.20.121    <none>        50051:32159/TCP       
PODA -> PODB

**Describe what happened:**
Because PODA accesses PODB through Service, there is no NAT conversion between PODA and PODB，So the two sets of data do not match.

```
{ "laddr":{
        "ip":"172.16.33.246",
        "port":34347,
        "containerId":"",
        "hostId":"0",
        "hostName":""
    },
    "raddr":{
        "ip":" 10.101.20.121 ",
        "port":50051,
        "containerId":"",
        "hostId":"0",
        "hostName":""
    }}
```

```
{ "laddr":{
        "ip":"172.16.33.246",
        "port":34347,
        "containerId":"",
        "hostId":"0",
        "hostName":""
    },
    "raddr":{
        "ip":" 172.16.161.180 ",
        "port":50051,
        "containerId":"",
        "hostId":"0",
        "hostName":""
    }}
```

There is a problem， when GetHTTPAggregationsAndTags is aggregated, and TCP data and HTTP data cannot be aggregated

**Describe what you expected:**
There is a problem， when GetHTTPAggregationsAndTags is aggregated, and TCP data and HTTP data cannot be aggregated

**Steps to reproduce the issue:**
Put the two PODs on the same physical machine and access them through Service

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by guyarb** [comment]
Hey @LeiZhang-Hunter thanks for filing the issue

1. What agent version are you using?
2. Please share details on the setup you have so we can try and reproduce it if needed

**Comment by LeiZhang-Hunter** [comment]
> Hey @LeiZhang-Hunter thanks for filing the issue
> 
> 1. What agent version are you using?
> 2. Please share details on the setup you have so we can try and reproduce it if needed

The problem did not occur, I temporarily closed
