### ISSUE TITLE
[BUG] flare code incorrectly adds security-agent.yaml as system-probe.yaml and overwrites it

### ISSUE THREAD

**Issue by sbailliez** [DataDog/datadog-agent#16717]
**Agent Environment**
7.43.2

**Describe what happened:**
the flare code is packaging the security-agent.yaml as system-probe.yaml and then overwriting the system-probe.yaml in the config. This is causing confusion when investigating issues with support.

See https://github.com/DataDog/datadog-agent/blame/a231a91b69f1b395b311ecf4a8b677aa611bebaa/pkg/flare/archive.go#L350

```go
fb.CopyFileTo(filepath.Join(confDir, "security-agent.yaml"), filepath.Join("etc", "system-probe.yaml"))
```

**Describe what you expected:**

security-agent.yaml being packaged as such

```go
fb.CopyFileTo(filepath.Join(confDir, "security-agent.yaml"), filepath.Join("etc", "security-agent.yaml"))
```

**Steps to reproduce the issue:**

Send a flare

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by paulcacheux** [comment]
Hello,

Thanks a lot for your report, pin pointing the exact issue.
I will let you know in which agent version we will include the fix into.

Thanks again !
