### ISSUE TITLE
RBAC manifests in Github don't match official docs

### ISSUE THREAD

**Issue by julianvmodesto** [DataDog/datadog-agent#1682]
In comparing the RBAC manifests below, it seems that the ClusterRole doesn't match between the docs here on Github and the official Datadog agent docs.

https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/rbac/clusterrole.yaml
https://docs.datadoghq.com/integrations/faq/using-rbac-permission-with-your-kubernetes-integration/

**Comment by mfpierre** [comment]
Hey @julianvmodesto, indeed there are a bunch of changes that are merged on master but not yet "released" that's why some recent changes are not yet in sync with documentation.

We'll make sure to update the doc when 6.2 is released (ping @l0k0ms)

**Comment by l0k0ms** [comment]
Hello, 

Doc PrR is on its way, thanks for the feedback :)

Best regards,
Pierre
