### ISSUE TITLE
How to disable Infrastructure host metrics collection but Keep APM enabled ? 

### ISSUE THREAD

**Issue by suresh-naik-tfs** [DataDog/datadog-agent#16877]
Hi, 

We are running Datadog agents in K8 container environment as a daemon sets, we are wondering if it's possible to stop collecting(or completely turning off) Infrastructure Host metrics collection but still keep APM enabled on the agent.

Thanks,
Suresh Naik

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
