### ISSUE TITLE
systemd problem on install

### ISSUE THREAD

**Issue by undiabler** [DataDog/datadog-agent#1706]
**Describe what happened:**
I've noticed that on Centos 7.4 and 7.5(maybe others too) systemd cant find .service file
.service file is located here `/lib/systemd/system/datadog-agent.service`
so I move it to `/usr/lib/systemd/system/datadog-agent.service` and everything works as expected

**Describe what you expected:**
service path should be `/usr/lib/...`

**Steps to reproduce the issue:**
- add datadog repo `https://yum.datadoghq.com/stable/6/x86_64/`
- install datadog
- try to run systemctl start datadog-agent

**Additional environment details (Operating System, Cloud provider, etc):**
on DigitalOcean Centos 7.4+
and manual installed Centos 7.5

**Comment by olivielpeau** [comment]
Hi @undiabler, thanks for reporting this issue.

It appears that the RedHat docs does list `/usr/lib/systemd/` as the directory where packages should drop systemd unit files (ref. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/chap-Managing_Services_with_systemd#tabl-Managing_Services_with_systemd-Introduction-Units-Locations). I'll open a PR to make our package reflect this.

That said I've tried reproducing the issue on a clean DigitalOcean VM (running the base image CentOS 7.5) and wasn't able to: it appears that the agent works fine as-is there. The `/lib` directory is a symlink to `/usr/lib` so the service file does end up in `/usr/lib/` without user intervention.

Do you know of something specific to your environment that could be explaining the difference in behavior?

**Comment by undiabler** [comment]
```
drwxr-xr-x.   3 root root   21 May  8 06:47 lib
lrwxrwxrwx.   1 root root    9 Mar  2 14:59 lib64 -> usr/lib64
```
is seems like there is no symlink for lib path by default
`CentOS Linux release 7.4.1708 (Core) `
`3.10.0-693.17.1.el7.x86_64`
have you tested on x64 ?

**Comment by olivielpeau** [comment]
Thanks for the info, I did test on x64 (see below for more details).

In any case, I've opened https://github.com/DataDog/datadog-agent/pull/1711 to address this, I'll see if we can ship it in a bugfix release (`6.2.1`) or wait for `6.3.0`.

I have the exact same versions of CentOS and of the kernel on my environment:

```
# cat /etc/system-release
CentOS Linux release 7.4.1708 (Core)
# uname -r
3.10.0-693.17.1.el7.x86_64
```
but:
```
lrwxrwxrwx.  1 root root    7 Mar  2 14:59 lib -> usr/lib
lrwxrwxrwx.  1 root root    9 Mar  2 14:59 lib64 -> usr/lib64
```

Could be related to an installed rpm package that changes the `/lib` symlink to a directory on your environment. On mine, only the `filesystem` pkg owns `/lib`:
```
# rpm -qf /lib
filesystem-3.2-21.el7.x86_64
```
