### ISSUE TITLE
`agent` command needs an option to disable color codes

### ISSUE THREAD

**Issue by SleepyBrett** [DataDog/datadog-agent#1722]
**Describe what happened:**
when you run `agent configcheck` you get colorcoded output, which doesn't travel well. Please add an option to suppress color codes.

**Describe what you expected:**
Readable output outside of a terminal

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by mfpierre** [comment]
Hey @SleepyBrett thanks for the report,

There's a already global flag to disable color output when available:
`-n, --no-color         disable color output`

`agent configcheck -n` should do the trick, let me know if it doesn't.
