### ISSUE TITLE
Logs agent dont filter docker containers by name

### ISSUE THREAD

**Issue by undiabler** [DataDog/datadog-agent#1740]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

==============
Agent (v6.2.1)
==============

  Status date: 2018-05-28 16:10:13.072448 UTC
  Pid: 4600
  Python Version: 2.7.5
  Logs: Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    System UTC time: 2018-05-28 16:10:13.072448 UTC

  Host Info
  =========
    bootTime: 2017-07-11 18:16:16.000000 UTC
    kernelVersion: 3.10.0-514.21.1.el7.x86_64
    os: linux
    platform: centos
    platformFamily: rhel
    platformVersion: 7.3.1611
    procs: 295
    uptime: 2.7726836e&#43;07
    virtualizationRole: host
    virtualizationSystem: kvm

  Hostnames
  =========
    hostname: backend2
    socket-fqdn: back2.server.local
    socket-hostname: back2.server.local

=========
Forwarder
=========

  RetryQueueSize: 0
  Success: 0

  API Keys status
  ===============
    https://6-2-1-app.agent.datadoghq.com,*************************24fb5: API Key valid

==========
Logs Agent
==========

  custom
  ------
    Type: docker
    Status: OK
    Inputs: 3c32a33f06070adfc3340b40a008214176b8f9854929ff42fe899d2bbb9ee691 179b8902dad3dfac9d4e5f061696b8f94d1168ffd27d6e1122ecc5fc5d051574 
  
=========
DogStatsD
=========

  Event: 1

```

**Describe what happened:**
Datadog ignores `name:` directive for logs while filtering containers.                                                                                   

**Describe what you expected:**
I've expected to get one log source (in datadog stats and in UI on site) while using `name` in logs config.

**Steps to reproduce the issue:**
I've configured agent to collect logs from containers filtered by name
file `/etc/datadog-agent/conf.d/custom.yaml`
```
logs:
  - type: docker
    name: landstorage
    source: nginx
    service: docker
``` 
but as you see from stats I have two connected containers:
```
  Inputs: 3c32a33f06070adfc3340b40a008214176b8f9854929ff42fe899d2bbb9ee691 179b8902dad3dfac9d4e5f061696b8f94d1168ffd27d6e1122ecc5fc5d051574 
```
P/s `image:` is working as expected
```
  custom
  ------
    Type: docker
    Image: test/templater_storage:latest
    Status: OK
    Inputs: 3c32a33f06070adfc3340b40a008214176b8f9854929ff42fe899d2bbb9ee691 
```

**Additional environment details (Operating System, Cloud provider, etc):**
Centos 7.3.1611
DataDog agent v6.2.1

**Comment by undiabler** [comment]
Maybe [this bug](https://github.com/DataDog/datadog-agent/issues/1736) is one of cases described here. Datadog read self container logs too because cant filter containers by name. 
Also I've noticed that `image:` config for logs should include full tag, so **docker/image:latest** != **docker/image**

**Comment by NBParis** [comment]
Hello @undiabler ,

Thanks for reaching out.
The filtering by name and short image name should be working on the version of the agent that you have.
You can find more information about the short image name filtering in our [documentation](https://docs.datadoghq.com/logs/log_collection/docker/#option-1-configuration-file).
For the image filtering you should be able to use:
- `templater_storage`
- `test/templater_storage`
- `templater_storage:latest`
- `test/templater_storage:latest`

Therefore I would expect your configuration to work fine.
Would it be possible to have the output of the `docker ps -a` command ?

The `issue` you linked should not be related as it is about picking up configuration from container labels when the environment variable is not set.

Thanks a lot,
Nils

**Comment by NBParis** [comment]
Thanks @undiabler for all those details.

It seems indeed strange as it should work with your configuration.
I'll try to replicate and let you know of my findings.

Sorry for the trouble.
Nils

**Comment by undiabler** [comment]
Can you please run two containers with different names and try to filter one. 
According to you test everything is ok because its only one working container.

**Comment by NBParis** [comment]
Sure, i'll start the nginx container and do the same test.

I'll come back to you with the outcome.

**Comment by NBParis** [comment]
Hello @undiabler ,

I just wanted to come back to you on my latest tests.
For me it seems to work fine no matter how many containers I have running.
Here is an example with two running containers

**Docker containers**

```
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS                NAMES
e9419023f174        nginx                          "nginx -g 'daemon of…"   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp   docker-nginx
95013288e6d2        chentex/random-logger:latest   "/entrypoint.sh myte…"   3 days ago           Up 5 minutes                             gallant_shannon
```

**Datadog Agent configuration**

```
logs:
    - type: docker
    service: docker
    source: docker
    name: gallant_shannon
```

**Datadog Agent status**

```
    Type: docker
    Status: OK
    Inputs: 95013288e6d2d32b807e42ffed264c437b88429fff5af84136f4d0ecf595d1a4 
```

So there might be an issue with your configuration. To make sure we find the issue would it be possible to send us an email at support@datadoghq.com or answer to this tread with the following information:

- an [Agent Flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare)
- the result of the `docker inspect` command for both your containers

Thanks a lot.

**Comment by NBParis** [comment]
Hello, 

We have not heard back from you so we are going to close this issue. But feel free to reach out to support@datadoghq.com if you still observe a problem with the filtering by container name.
