### ISSUE TITLE
[BUG] 7.45 creates invalid datadog.yaml when DD_HOST_TAGS set

### ISSUE THREAD

**Issue by agile** [DataDog/datadog-agent#17570]
The `/etc/datadog-agent/datadog.yaml.example` file contains some new commented out block of configuration in the `snmp` section that includes a nested `tags:` field (around line 963) that gets uncommented by https://github.com/DataDog/datadog-agent/blob/2d93fc1092bfc7df858c211546ac5f8cd40eab6f/cmd/agent/install_script.sh#L778-L782 resulting in an invalid config preventing the agent from starting. Maybe a caret is needed on that regex to only replace comments at the head of the line.

**Agent Environment**

Prior release of 7.44.1 worked ok, installing release 7.45.0 breaks configuration

```
$ sudo systemctl status datadog-agent
● datadog-agent.service - Datadog Agent
   Loaded: loaded (/usr/lib/systemd/system/datadog-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2023-06-09 18:14:08 CDT; 12min ago
 Main PID: 3106 (code=exited, status=255)

Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Failed with result 'exit-code'.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Service RestartSec=100ms expired, scheduling restart.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Scheduled restart job, restart counter is at 2.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: Stopped Datadog Agent.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: Started Datadog Agent.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Main process exited, code=exited, status=255/n/a
Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Failed with result 'exit-code'.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Start request repeated too quickly.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: datadog-agent.service: Failed with result 'exit-code'.
Jun 09 18:14:08 random-machine-w-1 systemd[1]: Failed to start Datadog Agent.
```

**Describe what happened:**
```
export DD_INSTALL_ONLY=true
export DD_HOST_TAGS="foo:bar"
export DD_API_KEY=secret

curl -Lo /tmp/install_script.sh https://s3.amazonaws.com/dd-agent/scripts/install_script.sh
bash /tmp/install_script.sh
```

**Describe what you expected:**

Have a valid configuration installed

**Steps to reproduce the issue:**

Described above

**Additional environment details (Operating System, Cloud provider, etc):**
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.7 (Green Obsidian)
Release:        8.7
Codename:       GreenObsidian
```
Running on GCP

**Comment by KSerrania** [comment]
Hi @agile,

Thanks for reporting this issue!

As printed by the script: https://github.com/DataDog/datadog-agent/blob/5c8ef804d8e6407d6126cb7fa64dda72129dd039/cmd/agent/install_script.sh#L10-L15

https://s3.amazonaws.com/dd-agent/scripts/install_script.sh is deprecated. Could you please use its replacement,  https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh, which we updated this week to fix this issue: https://github.com/DataDog/agent-linux-install-script/pull/45?

**Comment by agile** [comment]
Thanks Kylian, we've updated our process to use the version specific script and confirm it resolves our issue.
