### ISSUE TITLE
cluster-agent image is having different digests and upload dates in Google Container Registry and Docker Hub

### ISSUE THREAD

**Issue by nilushancosta** [DataDog/datadog-agent#17574]
When I looked at the cluster-agent:7.43.1 image in Google Container Registry and Docker Hub, I noticed them having different image digests. Furthermore the image upload date is also different.

Google Container Registry Digest: `sha256:0f19dc746187341954e3569d2d0dd009d457e5b6a9e82e6d349491e9d07eaa13`
<img width="1017" alt="Screenshot 2023-06-12 at 11 13 24" src="https://github.com/DataDog/datadog-agent/assets/19643850/51f8530b-0b25-4c19-a2ed-968ca806250e">

Docker Hub image Digest: `sha256:e346f194a6aab29fd89d899287d697b83b309faaa624b5beabf50a85be9b6344`
<img width="1066" alt="Screenshot 2023-06-12 at 11 16 32" src="https://github.com/DataDog/datadog-agent/assets/19643850/c9b22df6-ad1a-4e62-87d4-ccd0ef28fa36">

Does anyone know why they have different digests and different upload dates?

**Comment by vboulineau** [comment]
Hello,

The manifests are the same. It's just that `gcr.io` displays the `sha` of the multi-arch manifest (`0f19dc746187341954e3569d2d0dd009d457e5b6a9e82e6d349491e9d07eaa13`) while DockerHub does display the list of images in the multi-arch manifest, in your screenshot the `sha` of the `linux/amd64` image.

The images are uploaded simultaneously to all registries but there's also a sync on top of that to ensure that all last X tags are synced everywhere.

**Comment by nilushancosta** [comment]
Thanks for the response @vboulineau . Now its clear
