### ISSUE TITLE
Some datadog.yaml config file items are ignored in Docker and Kubernetes

### ISSUE THREAD

**Issue by mnussbaum** [DataDog/datadog-agent#1761]
**Agent Info:**

```
Agent 6.2.0 - Commit: c620285 - Serialization version: 4.7
```

**Describe what happened:**

Setting `dogstatsd_non_local_traffic` in `/etc/datadog-agent/datadog.yaml` is ignored when running the agent in Docker and Kubernetes, and `DD_DOGSTATSD_NON_LOCAL_TRAFFIC` needs to be set instead. The config file line is included in the [example config](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L143), but doesn't seem to work as expected. If I set the config file line traffic heading to the agent's container from other containers is ignored until I set the env var.

Additionally, statsd metrics don't make it to Datadog HQ until I set the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` env vars, even though I configure the `proxy` settings in the `datadog.yaml` config file. 

**Describe what you expected:**

I would expect that just setting the config file items should be enough to control the settings I mentioned above, and that redundant env vars configs shouldn't be required as well.

**Steps to reproduce the issue:**

Run the agent in a container in a Kubernetes cluster and only set `dogstatsd_non_local_traffic` and `proxy` configs in the `datadog.yaml` config file, and not as env vars. Test if other apps can write statsd metrics to the agent that then make it to the Datadog UI.

**Comment by CharlyF** [comment]
Hey @mnussbaum, sorry to hear that you are having this issue.
Are you using a proxy to submit your metrics (regardless of using dogstatsd ?)

As for:
> until I set the HTTP_PROXY, HTTPS_PROXY and NO_PROXY env vars, even though I configure the proxy settings in the datadog.yaml config file.

I think this is tied to:
https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config.go#L325-L330
Which we had to introduce in 6.2 as a result of a bug in the upstream library that we use to set variables from different configuration sources.

As for `DD_DOGSTATSD_NON_LOCAL_TRAFFIC`, can you just share more details on your use case so we can dig further ? I'm not sure it's tied to the aforementioned but it's worth investigating separately.

**Comment by mnussbaum** [comment]
>  Are you using a proxy to submit your metrics (regardless of using dogstatsd ?)

Yes I am.

> As for DD_DOGSTATSD_NON_LOCAL_TRAFFIC, can you just share more details on your use case so we can dig further ? 

What more details are you interested in? I set `dogstatsd_non_local_traffic` in the `datadog.yaml` and it didn't trigger the agent to accept statsd metrics from outside the container, then I additionally set the `DD_DOGSTATSD_NON_LOCAL_TRAFFIC` env var and metrics were accepted from outside the container. I haven't yet tested if setting the env var alone would be enough. This very well might be a separate issue from the proxy settings, I mentioned them in the same issue since I had to set both contrary to the docs to make our statsd pipeline work again. Happy to provide any more details.

**Comment by CharlyF** [comment]
Okay thanks for confirming - Indeed it likely tied to the proxy setup.
Would you mind opening a ticket with the [support team](support@datadoghq.com) so we can better track this internally?
I am sharing this issue with my team so it can be treated as high priority.

**Comment by mnussbaum** [comment]
Thanks for jumping on the issue! Per request I've opened a ticket with support and I believe the case ID is 148650.

**Comment by antoinepouille** [comment]
This PR https://github.com/DataDog/datadog-agent/pull/1782 should indeed solve the issue in 6.3.0
@mnussbaum I'll close the issue for now, but can you confirm an agent update solves this matter?
