### ISSUE TITLE
Aerospike disabled on ARM instances

### ISSUE THREAD

**Issue by cris-nicola** [DataDog/datadog-agent#17968]
Hello,

I am evaluating the Im4gn (arm) instance types with aerospike and just worked out that datadog agent does not support ARM instances.
i can see [arm build meta-issue](https://github.com/DataDog/datadog-agent/issues/2499) 
`The aerospike and ibm_mq don't build on ARM and are thus blacklisted.`

i can also see [Remove aerospike dependency definition](https://github.com/DataDog/datadog-agent/pull/8428) adding the block for aerospike.

the code seems to [remove the arm on purpose](https://github.com/DataDog/datadog-agent/blob/9e0f035aa26abf52592fe1c9780d0a91ca647b8d/omnibus/config/software/datadog-agent-integrations-py2.rb#L105)

before i go down the rabbit hole is there any reason why aerospike monitoring is disabled on arm machines or is it just a remnant from a time when aerospike did not build on ARM?

thank you

**Comment by FlorentClarret** [comment]
Hello @cris-nicola 

Sorry for the delay. I can have a look at that. I'll keep you posted

**Comment by cris-nicola** [comment]
thank you!

**Comment by FlorentClarret** [comment]
👋 The aerospike integration will be shipped by default on ARM starting with Agent 7.49.0
