### ISSUE TITLE
[Feature request] Universal serverless-init

### ISSUE THREAD

**Issue by storm1er** [DataDog/datadog-agent#18160]
Hi,

[Following up with this zendesk ticket](https://help.datadoghq.com/hc/en-us/requests/1223515)

We have multiple container apps using multiple languages, (most non-arm) container.
The current serverless-init isn't suitable for log collection universally on this and a full datadog-agent on a scalable container app would be dangerous as it seems to be made for persistent hosts.

It would be interesting to have a universal serverless-init that takes stdout/stderr for log collection, [abstracted from any language/framework that serverless-init is limited to](https://docs.datadoghq.com/fr/serverless/azure_container_apps/?code-lang=go#:~:text=Install%20Agent%20with%20Dockerfile).

Thanks!

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.

Thanks!
