### ISSUE TITLE
[BUG] datadog/serverless-init: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by alex-pollan** [DataDog/datadog-agent#18183]
Three days ago in Azure pipelines (Azure agents pool) pulling the latest image `datadog/serverless-init` started to fail with this error:

```
[error]invalid from flag value datadog/serverless-init:latest: no matching manifest for linux/amd64 in the manifest list entries
```

The pipeline agent is ubuntu-latest (22.04)
```
Agent name: 'Azure Pipelines 3'
Current agent version: '3.220.5'
Operating System
Ubuntu
22.04.2
LTS
Runner Image
Image: ubuntu-22.04
Version: 20230710.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230710.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230710.1
Runner Image Provisioner
2.0.238.1
Current image version: '20230710.1.0'
```

**Comment by storm1er** [comment]
relates to https://github.com/DataDog/datadog-agent/issues/18160 ?

**Comment by storm1er** [comment]
The only images amd64 I see in their docker hub are from 10 months+
![image](https://github.com/DataDog/datadog-agent/assets/9821946/72e0200a-1696-487a-9931-4067bdacf081)

Are you encountering this issue since some days only?

**Comment by alex-pollan** [comment]
Hey, thanks for reaching out on this
Yes, last week it was working fine with "latest". 
So if you confirm that the amd64 images are old, then the issue must be on my side (azure pipeline agents)

Anyway, do you have plans to support multi-arch builds so these type of issues are no longer a problem?

**Comment by alex-pollan** [comment]
Something seems off here: I checked previous Azure DevOps builds where I was using this Docker command:

```
COPY --from=datadog/serverless-init /datadog-init /app/datadog-init
```

Note I was implicitly referencing the "latest" tag

and the produced Docker image manifest is for AMD64

```
docker manifest inspect --verbose ***.azurecr.io/byod.byodreactjstemplate:2023.6.29.5

{
        "Ref": "***.azurecr.io/byod.byodreactjstemplate:2023.6.29.5",
        "Descriptor": {
                "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                "digest": "sha256:6ff05affd7820a2307075cba136b94513a7997a32a5bf33612c28ea31cd652c7",
                "size": 1794,
                "platform": {
                        "architecture": "amd64",
                        "os": "linux"
                }
        },
        ...
```

How is it possible that `datadog/serverless-init` supported AMD64 then and now it does not?

**Comment by alex-pollan** [comment]
UPDATE: And today it is working again 😕 

```
COPY --from=datadog/serverless-init /datadog-init /app/datadog-init
```

![image](https://github.com/DataDog/datadog-agent/assets/4661568/572d52aa-c6cb-4978-8859-44c208dc6cdf)

the digest matches the latest:

![image](https://github.com/DataDog/datadog-agent/assets/4661568/abef513b-3389-48df-b4f9-4c79c04b6bd1)

I'm really confused about this issue!
