### ISSUE TITLE
[BUG] 7.46.0 workloadmeta failures under load

### ISSUE THREAD

**Issue by therc** [DataDog/datadog-agent#18208]
**Agent Environment**
7.46.0

**Describe what happened:**

1. Crazy user starts Argo workflows that result in 10K+ pods over several minutes
2. Some nodes end up running 100 pods or more
3. Agent crashes in multiple ways, probably due to race conditions:

```
fatal error: concurrent map iteration and map write

goroutine 504 [running]:
github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).GetKubernetesPodForContainer(0x51e2fc0?, {0xc00111981d, 0x40})
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:285 +0x155
```

or

```
panic: interface conversion: workloadmeta.Entity is nil, not *workloadmeta.KubernetesPod

goroutine 600 [running]:
github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).GetKubernetesPodForContainer(0x51e2fc0?, {0xc00114dead, 0x40})
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:286 +0x31a
```

There might be more. I noticed that quite a few failures are not preserved, as the agent seems not to handle perfectly its own logs across restarts.

**Describe what you expected:**
No crashes

**Steps to reproduce the issue:**
1. Hire our crazy user or, otherwise, run hundreds of pods on a single node

**Additional environment details (Operating System, Cloud provider, etc):**
We are running EKS 1.25, but I suspect this makes little difference.

I saw that this code is different in 7.47.0. There is a mutex now, which might help with concurrency, but is it enough to avoid the nil pointers?

**Comment by clamoriniere** [comment]
Hi @therc 

thanks for reporting this issue, We quickly looked at the code path and the bug seems to be fixed now on the `main` branch but also in the next version 7.47.0 that we are currently releasing (QA in progress). 

Fix PR: https://github.com/DataDog/datadog-agent/pull/16803 

How often the issue append with your crazy argo workload? Do you think it can be liveable to wait 7.47.0? knowing that older version (< 7.46.0 are also impacted).

**Comment by clamoriniere** [comment]
For production deployment we can't recommend to run an RC build.
hopefully final 7.47.0 should be not so fare.

**Comment by davidor** [comment]
Fixed in https://github.com/DataDog/datadog-agent/pull/16803
