### ISSUE TITLE
[SERVERLESS] Remote Configuration enabled in serverless mode

### ISSUE THREAD

**Issue by pvicente** [DataDog/datadog-agent#18529]
Hi, 

I'm running my app in serverless and I've successfully activate [APPSEC](https://docs.datadoghq.com/security/application_security/enabling/serverless?tab=custom) and APMS.

I would like to enabled [WAF in APPSEC](https://docs.datadoghq.com/security/application_security/how-appsec-works/#threat-detection-methods) and to do it, I tried to enable REMOTE_CONFIGURATION but I get

```
2023-08-01 14:23:41 UTC \| DD_EXTENSION \| ERROR \| could not update remote-config state: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:5001: connect: connection refused" | 2023-08-01 14:23:41 UTC \| DD_EXTENSION \| ERROR \| could not update remote-config state: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:5001: connect: connection refused"
-- | --
```

I've looked at [DD_REMOTE_CONFIGURATION_ENABLED in this repo and I cannot find that it's in any folder of serverless](https://github.com/search?q=repo%3ADataDog%2Fdatadog-agent%20DD_REMOTE_CONFIGURATION_ENABLED&type=code)

I can see that Datadog knows about my serverless configuration and tracing libraries but doesn't receive anything.

<img width="1800" alt="Screenshot 2023-08-01 at 16 47 29" src="https://github.com/DataDog/datadog-agent/assets/471109/49f02115-2567-42b2-95f2-7e50011e6f78">

Is there any plan to support it or do you have technical limitations to enable it in serverless mode?

Cheers,
Pedro

**Comment by BaptisteFoy** [comment]
Hi Pedro,

Today Remote Configuration is not supported on Serverless Functions or Serverless Container Managed Apps (see [Supported Environments](https://docs.datadoghq.com/agent/remote_config/?tab=configurationyamlfile#supported-environments)). If you'd like to open a feature request feel free to contact our support team

I'm closing this issue, but please reopen if you have any other concerns.

Cheers,
Baptiste
