### ISSUE TITLE
FR: Option to drop all command-line arguments from process & container metrics

### ISSUE THREAD

**Issue by bmoylan** [DataDog/datadog-agent#1862]
This is an FR for at least the **process agent** and the **docker integration**, and any other components which ship home the command line of running processes. We would like to use these integrations but can not afford to exfiltrate the full command line of our processes (which often contains sensitive and/or secret material).

Ideally there would be a `collect_cmdline_args` (or similar) boolean that, when switched to false, would send just the executable in place of the whole argument string.

I'm familiar with the scrubbing feature, which is great but doesn't work for us because we don't have an exhaustive list of places people might put secrets.

**Comment by bmoylan** [comment]
Implemented in https://github.com/DataDog/datadog-process-agent/pull/146

**Comment by olivielpeau** [comment]
Thanks @bmoylan for updating the issue! I'll go ahead and close it then
