### ISSUE TITLE
Building on Gentoo

### ISSUE THREAD

**Issue by jbeker** [DataDog/datadog-agent#1887]
**Describe what happened:**

I am running `invoke agent.build` and am getting the following output:
```
# github.com/DataDog/datadog-agent/pkg/collector/py
In file included from /usr/include/python2.7/Python.h:8:0,
                 from pkg/collector/py/api.h:11,
                 from pkg/collector/py/api.go:23,
                 from _cgo_export.c:3:
/usr/include/python2.7/pyconfig.h:1188:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/stdlib.h:24:0,
                 from _cgo_export.c:2:
/usr/include/features.h:225:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
Successfully wrote /opt/datadog-agent/go/src/github.com/DataDog/datadog-agent/cmd/agent/dist/datadog.yaml
```

While these just look like warnings, no `datadog-agent` is being created anywhere.

**Describe what you expected:**

I expected the agent to build :/

**Steps to reproduce the issue:**

* `invoke agent.build`

**Additional environment details (Operating System, Cloud provider, etc):**

* Gentoo linux from EngineYard
* Go 1.10.3

**Comment by xvello** [comment]
Hi @jbeker 

These warning are caused by the cpython headers, but the build should be successful. The artifact is generated in `bin/agent/agent`, could you please double-check it's here?

**Comment by jbeker** [comment]
Is it the `agent` binary? All the documentation says I am looking for `datadog-agent`?

**Comment by jbeker** [comment]
Never mind, I guess I was reading things wrong, it is `agent`
