### ISSUE TITLE
[BUG] No valid api key found, reporting the forwarder as unhealthy. 

### ISSUE THREAD

**Issue by suhjohn** [DataDog/datadog-agent#18909]
**Agent Environment**
```
FROM python:3.11

ARG DD_API_KEY
ENV DD_API_KEY=$DD_API_KEY \
    DD_LOGS_ENABLED=true \
    DD_SITE="datadoghq.com" \
    DD_BIND_HOST="127.0.0.1" \
    DD_HOSTNAME="some.hostname" \
    DD_AGENT_MAJOR_VERSION=7
RUN bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
CMD ["sleep", "infinity"]

```

**Describe what happened:**
Try going into the shell, then 

```
from datadog import initialize, statsd
import time

options = {
    'statsd_host':'127.0.0.1',
    'statsd_port':8125
}

initialize(**options)

while(1):
  statsd.increment('example_metric.increment', tags=["environment:dev"])
  statsd.decrement('example_metric.decrement', tags=["environment:dev"])
  time.sleep(10)

```

**Describe what you expected:**

The metric to be sent. Nothing is sent. Installer is buggy. 

I've found that the forwarder is not healthy.
In activity.log, I see:
```
2023-08-21 05:41:55 UTC | CORE | INFO | (comp/forwarder/defaultforwarder/default_forwarder.go:361 in Start) | Forwarder started, sending to 0 endpoint(s) with 1 worker(s) each: 
2023-08-21 05:41:55 UTC | CORE | ERROR | (comp/forwarder/defaultforwarder/forwarder_health.go:123 in healthCheckLoop) | No valid api key found, reporting the forwarder as unhealthy.

```
This is despite DD_API_KEY being set which I have confirmed in the container. 
My suspicion: did someone write code where the api key is not being set properly to the forwarder? Please fix this. 

**Steps to reproduce the issue:**

It's been this way since last year. 

**Additional environment details (Operating System, Cloud provider, etc):**

Docker

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
