### ISSUE TITLE
Option to filter out invalid UTF-8 logs rather than discard log

### ISSUE THREAD

**Issue by c-knowles** [DataDog/datadog-agent#1906]
Agent (v6.3.0)

**Describe what happened:**

Some invalid UTF-8 character in the docker logs is causing the datadog agent to discard a log and then infinite loop as it's picking up its own logs. Two separate problems but the first one is concern here.

```
{"log":".go:58 in run) | unable to encode msg  invalid UTF-8 string: [ AGENT ] 2018-06-28 13:12:57 UTC | ERROR | (processor\u0001\n","stream":"stdout","time":"2018-06-28T13:13:13.000952207Z"}

{"log":"[ AGENT ] 2018-06-28 13:13:13 UTC | ERROR | (processor.go:58 in run) | unable to encode msg  invalid UTF-8 string: [ AGENT ] 2018-06-28 13:13:12 UTC | ERROR | (processor.go:58 in run) | unable to encode msg  invalid UTF
-8 string: [ AGENT ] 2018-06-28 13:13:12 UTC | ERROR | (processor.go:58 in run) | unable to encode msg  invalid UTF-8 string: [ AGENT ] 2018-06-28 13:13:12 UTC | ERROR | (processor.go:58 in run) | unable to encode msg  invalid 
UTF-8 string: [ AGENT ] 2018-06-28 13:13:12 UTC | ERROR | (processor.go:58 in run) 
[....]
```

**Describe what you expected:**

Invalid characters are stripped where possible, perhaps an option for it. Wrapping in something like the answer to [this post](https://stackoverflow.com/questions/20401873/remove-invalid-utf-8-characters-from-a-string-go-lang) could be done if invalid characters are detected around [this point in the code](https://github.com/DataDog/datadog-agent/blob/866cbc5fa21fb1919587d421fbedf37637a9cabb/pkg/logs/processor/encoder.go#L110-L112)

**Steps to reproduce the issue:**

Docker 18.03.1-ce, Kubernetes 1.9.8, JSON docker logs, no particularly special containers - this happens across clusters and doesn't seem to correlate to any apps we're running so perhaps caused by a kube-system component.

**Comment by NBParis** [comment]
Hello @c-knowles ,

Thanks a lot for reporting this issue .

 As discussed per email, we are currently working on a quick fix to stop spamming the logs with an infinite error message and will deploy a new version of the agent as soon as possible.

The second step is then to better handle those UTF-8 invalid messages and we will definitely have a look at the link you provided.

Thanks.

**Comment by matheusmessora** [comment]
+1 here.
Another problem. When this infinite-loop occurs, the Datadog-agent starts to write some files inside the volume, causing a huge increase on disk usage/CPU until it reaches 100% used.
<img width="1255" alt="screen shot 2018-07-04 at 20 38 57" src="https://user-images.githubusercontent.com/615315/42296299-858a0408-7fca-11e8-8d17-556d3e53cace.png">

I need to kill the agent and start with a fresh one.

The loop occured after my application just thrown and exception to the system.out and Datadog agent capture it. There is something wrong in the exception causing this error.
I'll remove the stacktrace from the system.out to prevent the error.

**Comment by NBParis** [comment]
Hello @c-knowles and @matheusmessora , just wanted to let you know that the agent 6.3.2 is now out and it contains the fix for this issue.

Let us know how it goes.
