### ISSUE TITLE
datadog.yaml.d/ config directory to allow multiple automated deployment tools to operate concurrently

### ISSUE THREAD

**Issue by douglasatleaseplan** [DataDog/datadog-agent#19203]
Please implement a datadog.yaml.d/ directory which is used the same way that Apache allows conf.d/ to be used: additional config files in the folder are included in the config along side what is in datadog.yaml.

This would enable a central SRE team to deploy defaults and app teams to deploy app specific configs without ending up in an editing war between the deployment tooling.

**Comment by remeh** [comment]
Hello @douglasatleaseplan 

Unfortunately, current Agent configuration system won't support this.

Note that SRE teams can leverage using the environment variables to leverage the same kind of multiple people having to set some configuration flags: https://docs.datadoghq.com/agent/guide/environment-variables/
