### ISSUE TITLE
Logs reported before tags and kubernetes information populated

### ISSUE THREAD

**Issue by c-knowles** [DataDog/datadog-agent#1975]
**Describe what happened:**

- Agent 6.3.2 with log reporting enabled on Kubernetes as a Daemon Set using the helm chart
- Log exclusion filters we have are based mostly off Kubernetes labels coming through as tags
- Perform rolling update of worker nodes
- Receive large spike in logs with no Kubernetes labels as tags
- These logs are not excluded due to tags to filter them not being present
- Did not see any specific errors coming from the agent

**Describe what you expected:**

If information is not yet available to augment the logs such as Kubernetes labels, I'd expect log collection to pause if there's no particular error.

**Steps to reproduce the issue:**

Perform any update such as cycling a Kubernetes worker node or scale up a worker pool.

**Additional environment details (Operating System, Cloud provider, etc):**

AWS, Container Linux 1745.7.0.

**Comment by c-knowles** [comment]
BTW, sometimes the logs coming through in the datadog UI also don't have the docker tag information such as what the image_name. Looks like a similar problem. Eventually it seems to have cleared up as the indexed log count per minute has reduced back down again.

**Comment by NBParis** [comment]
Hello @c-knowles ,

Thanks for reporting.
Just to make sure I correctly understand the issue:

1. Sometimes container logs are not properly tagged with container metadata
2. During Spikes logs that should be excluded are still sent with no metadata

We will try to replicate the issue and investigate to fix this.
Meanwhile, it might be helpful to provide the agent flare and the result of the docker inspect of one of the container which should be excluded.
(Feel free to send those to support@datadoghq.com and reference this issue).

Thanks.

**Comment by c-knowles** [comment]
Hi @NBParis, I've flared to 155927. We've since discovered some hosts are not reporting any of the metadata anymore still with various errors in the logs:

```
datadog-master-datadog-cfrhr datadog [ AGENT ] 2018-07-12 08:06:29 UTC | ERROR | (integration_config.go:108 in buildLogSourcesFromDirectory) | Invalid file path: ..2018_07_12_08_06_19.133422244/docker.yaml 
datadog-master-datadog-cfrhr datadog [ AGENT ] 2018-07-12 08:06:29 UTC | ERROR | (auditor.go:127 in recoverRegistry) | open /opt/datadog-agent/run/registry.json: no such file or directory 
datadog-master-datadog-cfrhr datadog [ AGENT ] 2018-07-12 08:06:31 UTC | ERROR | (services.go:113 in ServicesForPod) | could not get services: no mapping for pod obfuscated-996f448c4-9wcc5 in namespace int
```

**Comment by dabcoder** [comment]
@c-knowles Thanks for all the info, we're following up on our side and with you on that ticket.

**Comment by sudermanjr** [comment]
I am seeing very similar errors and lack of kubernetes metadata using agent 6.3.3 (Also installed with Helm)

**Comment by dabcoder** [comment]
@sudermanjr Would you mind sending us a note on support@datadoghq.com with details of the issue you're experiencing? You can send us some agent logs with https://docs.datadoghq.com/agent/troubleshooting/?tab=agentv6#send-a-flare. 

@c-knowles Also sent you a note on the ticket 155927.

**Comment by sudermanjr** [comment]
For those reading this issue, Datadog support has been provided with logs and is looking into the issue.

**Comment by ajacquemot** [comment]
Hi,

This issue should be solved as we plugged the logs-agent to autodiscovery to collect new containers. The fix is available on the version `6.5` that will be released beginning of next week.
Waiting for your feedback.
Thanks

**Comment by NBParis** [comment]
Thanks @sudermanjr for your feedback.

@c-knowles Any update on your end with the latest version of the agent (6.5.2)?

**Comment by NBParis** [comment]
As it seems that everything is going well since version 6.5.x I'll go ahead and close this issue.

Feel free to reach out to support@datadoghq.com if you have any other questions or issues.

Thanks a lot.
