### ISSUE TITLE
Dotadadog agent output target change for another place

### ISSUE THREAD

**Issue by younid** [DataDog/datadog-agent#19825]
Hello,

Sorry to ask this here but I did not found where I can put my question.
I need help because I did not manage to found any information about the Dagadog Agent output target.
I'm trying to configure my Datadog Agent to send my logs to another place like AWS S3 or Logstash or a simple local file.
My Datadog Agent is already working fine with Datadog Server and I have all my logs and metrics visible with dashboards.
My need is to send a second copy of my logs using the same Dadagog Agent or configuring a second instance.
Could you please tell me how or where I can get such information ?

Thanks in advance for your help.

Regards

**Comment by younid** [comment]
Hello,

No body can help about this topic here ?
Please just let me know if it's the good place to ask or if there's a better place to do it.

Regards

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
