### ISSUE TITLE
[BUG] CORE | WARN | (pkg/util/cloudproviders/gce/gce_tags.go:49 in getCachedTags) | unable to get tags from gce and cache is empty: GCE metadata API error: Get "http://169.254.169.254/computeMetadata/v1/?recursive=true": dial tcp 169.254.169.254:80: connect: invalid argument

### ISSUE THREAD

**Issue by anvesh03** [DataDog/datadog-agent#19960]
**Agent Environment**
Agent version : 7.43.1
Agent running as host in EC2 instance

Log Frequency : 40logs/15mins

**Describe what happened:**
 I'm seeing the above line repeatedly in my logs. I'm unsure what -- if anything -- I should do about it. Thought it might be helpful to report it here.

**Describe what you expected:**
The warn messages should be removed.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
1.os: linux
platform: ubuntu
platformFamily: debian
platformVersion: 22.04
2.Agent version : 7.43.1
3.Agent running as host in EC2 instance
4.No,We are not running in GCI
5.Frequency : 40logs/15mins
6.Cloud Provider : AWS

**Comment by vickenty** [comment]
Hi, thank you for bringing this up. This issue was [fixed](https://github.com/DataDog/datadog-agent/pull/17701) in Datadog Agent version 7.47.0.
