### ISSUE TITLE
[BUG] 89-copy-customfiles.sh does not obey symlinks

### ISSUE THREAD

**Issue by sgatewood-da** [DataDog/datadog-agent#19989]
(Issue created to track https://github.com/DataDog/datadog-agent/pull/19988)

**Agent Environment**
```
===============
Agent (v7.46.0)
===============

  Pid: 1
  Go Version: go1.19.10
  Python Version: 3.8.17
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: debug
```

Installed from your helm chart `1.1.1`

**Describe what happened:**
I put a subdirectory `openmetrics.d` on the `[key].extraConfd.configMap.items` [property](https://github.com/DataDog/datadog-operator/blob/1a5623dde36f2cb48999b1b14909f8d431f83c4c/docs/configuration.v2alpha1.md?plain=1#L287C1-L287C1) and `89-copy-customfiles.sh` didn't put the file in `/etc/datadog-agent/conf.d/openmetrics.d/`. Instead the file is copied to `/etc/datadog-agent/conf.d/..2023_10_06_17_53_46.1947035202`

**Cause**
When the configmap is mounted, the subdirectory is a symlink. And `89-copy-customfiles.sh` does not obey symlinks. See https://github.com/DataDog/datadog-agent/pull/19988

**Comment by clamoriniere** [comment]
Hi @sgatewood-da 

thanks for opening this issue. 

Could you share with us, more information about your use case. 🙇 

* can you share an example of the `extraConfd.configMap` configuration?
* which benefit you see to have several files for the same integration?
* doest the check instances run against a Pod payload endpoints? local Node endpoints? 

Also in Kubernetes we are trying to advertise to user ["pod, service, endpoints" auto-discovery check configuration](https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2#configuration) we see several advantages:
* doesn't require to redeploy the agent to update a check configuration
* the check instance get the Pod/Container [out-of-the-box tags](https://docs.datadoghq.com/containers/kubernetes/tag/?tab=containerizedagent#out-of-the-box-tags)
* check instance follow the Pods lifecycle.

**Comment by sgatewood-da** [comment]
Looks like our PR [merged](https://github.com/DataDog/datadog-agent/pull/19988), so I'll go ahead and close this 🙏

Basically, we prefer `ad_identifiers` over the check annotations because then we can define configurations in our operator and reference them within our pod annotations. This allows us to update our datadog configurations without rolling our pods.

In other words from my teammate:

![image](https://github.com/DataDog/datadog-agent/assets/130372585/f063d080-4fa0-4bb2-8974-4f817907f151)
