### ISSUE TITLE
Document backwards incompatibility: v6 agent uses spaces for tags instead of commas

### ISSUE THREAD

**Issue by fotinakis** [DataDog/datadog-agent#1999]
**Describe what happened:**

We lost data of tags on metrics during upgrading from v5 -> v6 because it was not clear or documented that `DD_TAGS` env var for datadog-docker changed format from comma-separated to space separated.

**Describe what you expected:**

```
DD_TAGS=tag:one,tag:two
```
should have reported as `tag:one` and `tag:two`, but instead was reported as `tag:one_tag:two`.

**

The docs really need to be updated for users of docker-dd-agent that `TAGS` and `DD_TAGS` format has changed.

**Comment by miketheman** [comment]
Resolved via https://github.com/DataDog/datadog-agent/pull/3639
Recommend closing this issue.

**Comment by olivielpeau** [comment]
Correct, thanks for chiming in @miketheman (and nice to see you around :) )

Closing
