### ISSUE TITLE
[BUG] Tags assignment does not work for JSON logs

### ISSUE THREAD

**Issue by otwieracz** [DataDog/datadog-agent#20046]
**Agent Environment**

- AWS EKS cluster
- Managed by Pulumi
- Clojure application with custom JSON logging code (including trace correlation with `datadog.trace.api.CorrelationIdentifier/getTraceId` and `datadog.trace.api.CorrelationIdentifier/getSpanId`).
- Java tracing library is injected into the library and used to auto-instrument HTTP routes served by `Jetty`.

```ts
const datadogAgent = new k8s.helm.v3.Chart("datadog-agent", {
    chart: "datadog",
    version: "3.38.4",
    fetchOpts: {
        repo: "https://helm.datadoghq.com",
    },
    namespace: ns.metadata.name,
    values: {
        datadog: {
            apiKeyExistingSecret: datadogSecretName,
            appKeyExistingSecret: datadogSecretName,
            site: "datadoghq.com",
            targetSystem: "linux",

            /**
             * Enable monitoring features. Supported params listed here:
             * https://github.com/DataDog/helm-charts/blob/main/charts/datadog/README.md
             */
            apm: { enabled: true },
            //<editor-fold desc="enable Cluster event collection">
            collectEvents: true,
            leaderElection: true,
            rbac: { create: true },
            //</editor-fold>
            logs: {
                enabled: true,
                autoMultilineDetection: true
            },
            networkMonitoring: { enabled: true },
            orchestratorExplorer: { enabled: true },
            processAgent: {
                enabled: true,
                processCollection: true
            },
            tags: [
                `cluster:${pulumi.getStack().toLowerCase()}-eks`,
                `env:${envPrefix}`,
            ],
            dogstatsd: {
                tags: [
                    `cluster:${pulumi.getStack().toLowerCase()}-eks`,
                    `env:${envPrefix}`,
                ]
            }
        }
    }
});
```

**Describe what happened:**

- Original logs from service 
```
23-10-11 06:34:33 myservice-697464c64-wzfqb DEBUG [org.eclipse.jetty.util.log:160] - nil Logging to com.github.fzakaria.slf4j.timbre.TimbreLoggerAdapter@1ba144d0 via org.eclipse.jetty.util.log.Slf4jLog
23-10-11 06:34:33 myservice-697464c64-wzfqb INFO [org.eclipse.jetty.util.log:170] - nil Logging initialized @139299ms to org.eclipse.jetty.util.log.Slf4jLog

## At this poing, logging configuration gets applied by the service, `myservice` starts to print JSON logs instead of plaintext
{"file":"xxxr\/core.clj","hostname":"myservice-697464c64-wzfqb","dd.span_id":"0","@timestamp":1697006083067,"dd.trace_id":"0","line":81,"status":"info","namespace":"xxxx","message":"Starting Kafka Producer with config. {\"bootstrap.servers\" \"xxx\", \"request.timeout.ms\" 30000, \"linger.ms\" 1, \"client.id\" \"d4c29226-f5e4-xxxxxxxxxxxxxx\", \"max.block.ms\" 10000, \"retries\" 3, \"batch.size\" 16384, \"buffer.memory\" 33554432, \"acks\" \"all\", \"compression.type\" \"none\"}","error.stack":null}
```

**Logs as seen in DataDog**
- Before JSON logging gets enabled
![image](https://github.com/DataDog/datadog-agent/assets/108072/c16f4826-fcf9-4e03-87da-db2f4243401e)
- First line after JSON logging gets enabled
![image](https://github.com/DataDog/datadog-agent/assets/108072/0b5d8a4c-5b2d-4cdc-a53f-98547c0c2042)

Notice `env` and `cluster` tags, marked with green on first screenshot and missing on second screenshot.

**Describe what you expected:**

`env` and `cluster` tags should be added globally independently of whether the logs are in JSON or in plaintext format.

**Steps to reproduce the issue:**

- Assign tags in agent configuration
- Format logs as JSON

**Additional environment details (Operating System, Cloud provider, etc):**

- Kubernetes cluster running in AWS EKS.

**Comment by carlosroman** [comment]
In some environments, the initial logs from hosts might not include the correct tags. Try setting the environment variable `DD_LOGS_CONFIG_EXPECTED_TAGS_DURATION` to `10m` (or `logs_config.expected_tags_duration` in the `datadog.yaml`) as this will guarantee that all host tags are sent with the initial logs. This will cause the Agent to send more data for the first 10 minutes as it will send all host tags with each log entry.

**Comment by otwieracz** [comment]
I’ve received assistance from DataDog support. Turns out that including `hostname` key in JSON prevents statics tags from being included.

Removing `hostname` resolved the issue, `env` and `cluster` tags are now present.
