### ISSUE TITLE
Kubernetes event collection timeout is extremely low

### ISSUE THREAD

**Issue by mahmoudm** [DataDog/datadog-agent#2020]
Currently, the datadog-agent will never process any kubernetes events if it takes longer than 100ms to respond as per https://github.com/DataDog/datadog-agent/blob/master/pkg/util/kubernetes/apiserver/events.go#L27. There are two problems with this:

1) If you have enough load on your etcd that this call never sends events in less than 100ms, you will get stuck in a state where the datadog-agent just requests ALL of your events every 15 seconds/ configured interval and never actually processing them. We currently consistently run into this state in our production environments.

2) There's a bug in kubernetes/grpc where if you close the watch before it gets a chance to respond past the initial flush, you can leak grpc streams in the api-server > etcd client. In other words, since we turned on event collection via the new agent we consistently see the API server that the agent hits getting into a state where its events etcd client is in a permanently hanging state (i.e all requests to the events API will 504). This happens because there's a default max of 100 streams per http2 connection. I'm going to separately open the appropriate grpc/kubernetes issues to track fixing this, but this is another reason why this is severely impacting us and we were forced to completely disable the collection of events.

Proposal is that we make the event watch read timeout configureable such that we can increase it to a level that is more appropriate for our production load.

**Comment by mahmoudm** [comment]
here is the relevant kubernetes issue we are hitting due to the above behavior: https://github.com/kubernetes/kubernetes/issues/66312

**Comment by xvello** [comment]
Hi @mahmoudm 

https://github.com/DataDog/datadog-agent/pull/2034, released in 6.4.1 allows to configure the timeout.
Feel free to follow-up on this issue if the issue persists.
