### ISSUE TITLE
Double call to strings.TrimPrefix() in docker/filter.go?

### ISSUE THREAD

**Issue by jonathn** [DataDog/datadog-agent#2021]
Is the second TrimPrefix() unnecessary?

https://github.com/DataDog/datadog-agent/blob/7bad22ef148873291771b4acdade077e5adbf9f1/pkg/util/docker/filter.go#L47-L49

**Comment by sgnn7** [comment]
Hi @jonathn,
This code has substantially changed since this ticket was filed. Current code doesn't use the double trim: https://github.com/DataDog/datadog-agent/blob/d7f89cd94bc808072d51d906f53905c5cafec4b6/pkg/util/containers/filter.go#L98.
