### ISSUE TITLE
[BUG] slices.DeleteFunc

### ISSUE THREAD

**Issue by Deleplace** [DataDog/datadog-agent#21042]
Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [this code](https://github.com/DataDog/datadog-agent/blob/main/pkg/ebpf/btf.go#L243):

```
			// remove possible paths that do not match possible platforms
			slices.DeleteFunc(possiblePaths, func(s string) bool {
				pform := strings.Split(s, string(os.PathSeparator))[0]
				return !slices.Contains(kvp.platforms, pform)
			})
```

which doesn't do what it seems to do, and should look like this instead:

```
			// remove possible paths that do not match possible platforms
			possiblePaths = slices.DeleteFunc(possiblePaths, func(s string) bool {
				pform := strings.Split(s, string(os.PathSeparator))[0]
				return !slices.Contains(kvp.platforms, pform)
			})
```

I have not tried to execute it.

**Comment by paulcacheux** [comment]
@Deleplace thanks a lot for reporting this issue, you are fully right that our usage here is wrong. I opened https://github.com/DataDog/datadog-agent/pull/21077 that should fix it (and add a test for good measure). Thanks again !
