### ISSUE TITLE
Alternate name for ecs-agent

### ISSUE THREAD

**Issue by jhmartin** [DataDog/datadog-agent#2167]
Per https://github.com/DataDog/datadog-agent/blob/69894176f041c7060fe124b3b87b71bcac42a17a/pkg/util/ecs/ecs.go#L29, please make this option configurable as my ecs-agent is named differently.

**Comment by hkaj** [comment]
Hi @jhmartin
I added a task for this in our backlog. Feel free to contribute it if you have time though, we would happily review your PR!
Thanks
