### ISSUE TITLE
Link in github issue template 404s

### ISSUE THREAD

**Issue by nicbarker** [DataDog/datadog-agent#2175]
The above appears at the top of the github issue template when creating a new issue in this repository:
```
<!--
If you suspect your issue is a bug, please attach the output of the info page, see
https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information

-->
```

The link 404s and the 404 page has no link to any updated documentation for this particular topic.

**Comment by olivielpeau** [comment]
Thanks for reporting this @nicbarker! Fixed with https://github.com/DataDog/datadog-agent/pull/2179

**Comment by nicbarker** [comment]
Thanks @olivielpeau for the quick fix!
