### ISSUE TITLE
AttributeError: module 'pynvml' has no attribute 'nvmlDeviceGetComputeRunningProcesses_v2[Bug]

### ISSUE THREAD

**Issue by linuxredhatsumit** [DataDog/datadog-agent#21945]
The error you're encountering with the NVML (NVIDIA Management Library) integration in DataDog suggests an issue with the pynvml Python module. Specifically, the error AttributeError: module 'pynvml' has no attribute 'nvmlDeviceGetComputeRunningProcesses_v2' indicates that the pynvml module being used does not have the expected attribute nvmlDeviceGetComputeRunningProcesses_v2

**Agent Environment**
  nvml (1.0.8) , Agent (v7.50.1)

**Describe what happened:**
While executing the NVML integration within DataDog, I encountered an operational issue characterized by the following error message. This complication is hindering the proper functioning of the integration. 

Instance ID: nvml:nvml_integration:cca7b56f7c8701b9 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/nvml.d/conf.yaml
      Total Runs: 1
      Metric Samples: Last Run: 14, Total: 14
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 262ms
      Last Execution Date : 2024-01-09 07:14:09 UTC (1704784449000)
      Last Successful Execution Date : Never
      Error: module 'pynvml' has no attribute 'nvmlDeviceGetComputeRunningProcesses_v2'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1235, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/nvml/nvml.py", line 103, in check
          self.gather(instance)
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/nvml/nvml.py", line 116, in gather
          self.gather_gpu(handle, tags)
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/nvml/nvml.py", line 175, in gather_gpu
          compute_running_processes = NvmlCheck.N.nvmlDeviceGetComputeRunningProcesses_v2(handle)
      AttributeError: module 'pynvml' has no attribute 'nvmlDeviceGetComputeRunningProcesses_v2'
**Describe what you expected:**
The expectation was for the NVML integration to be set up successfully and to function without errors, thereby allowing for effective monitoring and management of NVIDIA GPU states.

**Steps to reproduce the issue:**
 sudo -u dd-agent -H datadog-agent integration install -t datadog-nvml==1.0.8
sudo -u dd-agent -H /opt/datadog-agent/embedded/bin/pip3 install grpcio pynvml
sudo systemctl restart datadog-agent
sudo datadog-agent status

**Additional details :**
I was able to fix it by editing /opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/nvml/nvml.py file with the     compute_running_processes = NvmlCheck.N.nvmlDeviceGetComputeRunningProcesses(handle)
But this has to work without this work around (removing _v2)

**Comment by linuxredhatsumit** [comment]
any update on this? is it fixed?

**Comment by FlorentClarret** [comment]
This is fixed with the version 1.0.9 of the integration https://github.com/DataDog/integrations-extras/pull/2160

**Comment by FlorentClarret** [comment]
Closing the issue, feel free to open it again in the integrations-extras repository if you're facing other issues with the 1.0.9 version.
