### ISSUE TITLE
GHSA-9763-4f94-gfch HIGH-level vulnerability in cloudflare/circl

### ISSUE THREAD

**Issue by estokes-vs** [DataDog/datadog-agent#22125]
**Agent Environment**
7.50.3

**Describe what happened:**
Trivy vulnerability scanner alerted to HIGH severity issue in container image that has a current fixed version available
![image](https://github.com/DataDog/datadog-agent/assets/80277826/4494bbc0-1c11-4af6-a32b-175af2ee1746)

**Describe what you expected:**
No "critical" or "high" vulnerabilities.

**Steps to reproduce the issue:**
Have trivy installed locally, build datadog-agent version 7.50.3 container locally, run trivy image <IMAGE_ID>

**Additional environment details (Operating System, Cloud provider, etc):**
Image pulled with FROM datadog/agent:7.50.3 in Dockerfile

**Comment by L3n41c** [comment]
Fixed by #21953.
