### ISSUE TITLE
[BUG] Podman 4.8+ no longer uses boltdb by default, breaking integration

### ISSUE THREAD

**Issue by hkrutzer** [DataDog/datadog-agent#22387]
**Agent Environment**
```
# datadog-agent version
Agent 7.50.3 - Commit: abce0cb - Serialization version: v5.0.100 - Go version: go1.20.12
```

**Describe what happened:**
```
2024-01-28 18:45:26 UTC | PROCESS | WARN | (pkg/workloadmeta/store.go:585 in func1) | error pulling from collector "podman": error opening database /var/lib/containers/storage/libpod/bolt_state.db, err: open /var/lib/containers/storage/libpod/bolt_state.db: permission denied
```

**Describe what you expected:**
Podman integration to work

**Steps to reproduce the issue:**
Install Podman v2.8.3, run a container
```
root@host1:/var/lib/containers/storage/libpod# podman -v
podman version 4.8.3
root@host1:/var/lib/containers/storage/libpod# pwd
/var/lib/containers/storage/libpod
root@host1:/var/lib/containers/storage/libpod# ls
root@host1:/var/lib/containers/storage/libpod#
```

See https://github.com/containers/podman/releases/tag/v4.8.0

>Podman 5.0 will deprecate the BoltDB database backend. Exact details on the transition to SQLite are still being decided - expect more news here soon.

and 

>Podman now defaults to sqlite as its database backend. For backwards compatibility, if a boltdb database already exists on the system, Podman will continue using it.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by tbavelier** [comment]
Thanks for the ping @hkrutzer , closing as completed by #24373 (coming with next Agent version `7.54.x`)
