### ISSUE TITLE
Can't override default frame_size for UDP buffers in logs_config

### ISSUE THREAD

**Issue by behos** [DataDog/datadog-agent#2271]
This might be just me doing something wrong, but I can't seem to be able to override the log_config.frame_size variable for UDP log listener.

I have added this in my datadog.yaml

```
logs_config:
  frame_size: 30000
```

I assumed that was the right place since the config name is "logs_config.frame_size" but to be sure, I tried adding this to my "logs" configurations as well with no success.

https://github.com/DataDog/datadog-agent/blob/dbdec93a04d629f18eeb491d30016da26652b69c/pkg/config/config.go#L279

What I suspect is going on is that the used value is evaluated before the config is loaded, meaning that there is no way to override it.

I'm not very familliar with golang, but maybe this global variable here is the culprit:

https://github.com/DataDog/datadog-agent/blob/master/pkg/logs/input/listener/listener.go#L15

Please help me override my frame size, my logs are too big :sweat_smile:

**Comment by ajacquemot** [comment]
Hi @behos,
Thanks for opening this issue, I'll investigate and keep you posted.

**Comment by ajacquemot** [comment]
Closing this issue as it's been resolved in `6.5.0`
