### ISSUE TITLE
Disk stats for mounted EBS drives are missing on EC2 instances

### ISSUE THREAD

**Issue by elmo-space** [DataDog/datadog-agent#2336]
**Output of the info page (if this is a bug)**
```
====================
Collector (v 5.27.0)
====================

  Status date: 2018-09-19 13:18:27 (12s ago)
  Pid: 884
  Platform: Linux-4.14.67-66.56.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.15, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: 0.0027 s
    System UTC time: 2018-09-19 13:18:40.032566
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: Not found
  
  Checks
  ======
  
    ntp (1.2.1)
    -----------
      - Collected 0 metrics, 0 events & 0 service checks
  
    disk (1.3.0)
    ------------
      - instance #0 [OK]
      - Collected 30 metrics, 0 events & 0 service checks
  
    network (1.6.1)
    ---------------
      - instance #0 [OK]
      - Collected 20 metrics, 0 events & 0 service checks
  
    mysql (1.4.0)
    -------------
      - instance #0 [OK]
      - Collected 172 metrics, 0 events & 2 service checks
      - Dependencies:
          - pymysql: 0.8.0
  
  
  Emitters
  ========
  
    - http_emitter [OK]

====================
Dogstatsd (v 5.27.0)
====================

  Status date: 2018-09-19 13:18:38 (1s ago)
  Pid: 877
  Platform: Linux-4.14.67-66.56.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.15, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 13
  Packet Count: 52
  Packets per second: 0.1
  Metric count: 22
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.27.0)
====================

  Status date: 2018-09-19 13:18:38 (2s ago)
  Pid: 876
  Platform: Linux-4.14.67-66.56.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.15, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 456 bytes
  Queue Length: 1
  Flush Count: 32
  Transactions received: 33
  Transactions flushed: 32
  Transactions rejected: 0
  API Key Status: API Key is valid
  

======================
Trace Agent (v 5.27.0)
======================

  Pid: 875
  Uptime: 133 seconds
  Mem alloc: 1768184 bytes

  Hostname: xxxxx
  Receiver: localhost:8126
  API Endpoint: https://trace.agent.datadoghq.com

  --- Receiver stats (1 min) ---


  --- Writer stats (1 min) ---

  Traces: 0 payloads, 0 traces, 0 bytes
  Stats: 0 payloads, 0 stats buckets, 0 bytes
  Services: 0 payloads, 0 services, 0 bytes
```

**Describe what happened:**
The system.disk metrics only get collected for the root device on ec2 instances.
Mounted EBS storages won't show up. Even if they are mounted as completely normal block devices with an ext4 filesystem on them.

**Describe what you expected:**
system.disk metrics for all mounted blockdevices.

**Steps to reproduce the issue:**
Install the datadog agent on an EC2 instance that has an external EBS storage mounted with an ext4 filesystem on it.
Look at the system.disk metric.

**Additional environment details (Operating System, Cloud provider, etc):**
Amazon EC2 with latest Amazon Linux.
Two EBS storages mounted.

**Comment by RedVortex** [comment]
Hi, can you send the output of (mask the host values and the Instance ID

`datadog-agent check disk | sed -r 's/"host": "[^"]+"/"host": "some.thing.com"/' | sed -r 's/Instance ID: disk:[^ ]+/Instance ID: disk:xxxxxx/'`

and also, what is the mount point of your volume ?

I also noticed I'm seeing the same behaviour on my side, I'm looking into this, must be a simple configuration issue I suppose, I'll let you know what I find.

Btw, here's the partial output of the device that doesn't get collected on my side. The mount point of this partition is under /home/developers/backup and it's a XFS filesystem.

```
{
      "metric": "system.disk.free",
      "points": [
        [
          1539200613,
          8.3811152e+07
        ]
      ],
      "tags": null,
      "host": "some.thing.com",
      "device": "/dev/nvme1n1p1",
      "type": "gauge",
      "interval": 0,
      "source_type_name": "System"
    }
  ]
}
=========
Collector
=========

  Running Checks
  ==============

    disk (1.3.0)
    ------------
        Instance ID: disk:xxxxxx [OK]
        Total Runs: 1
        Metric Samples: 72, Total: 72
        Events: 0, Total: 0
        Service Checks: 0, Total: 0
        Average Execution Time : 48ms
```

Output of df (without tmpfs) showing devices, mount points and filesystems

```
df -hPT | grep -v tmpfs
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1 xfs       150G   78G   73G  52% /
/dev/nvme1n1p1 xfs        80G   33M   80G   1% /home/developers/backup
```

**Comment by RedVortex** [comment]
After a few checks, it's most likely just a linux file permission problem (At least for me).

The dd-agent user cannot see the mounted volume because the directory where it is mounted belongs to another user (developers in my case) without read permissions to others.

Here's my output

```
sudo -u dd-agent df -hPT | grep -v tmpfs
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1 xfs       150G   78G   73G  52% /
```

```
sudo -u dd-agent ls -al /home/developers/backup
ls: cannot access /home/developers/backup: Permission denied
```

I'll adjust my permissions on my side to fix this or mount the volume somewhere else and that should fix it for me. Can you check if this explains your problem as well ?

**Comment by channelpilot** [comment]
It indeed was a permission problem.
Giving the dd-agent access to the directorys the storages are mounted on fixed the problem.
Thanks for the help.

**Comment by elmo-space** [comment]
It indeed was a permission problem.
Giving the dd-agent access to the directorys the storages are mounted on fixed the problem.
Thanks for the help.
