### ISSUE TITLE
Example config_template.yaml has broken links

### ISSUE THREAD

**Issue by FierceElements** [DataDog/datadog-agent#2342]
The following two lines contain broken links:

https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L537,L541

`https://github.com/DataDog/datadog-agent/blob/master/Dockerfilesagent/README.md`

Should be:

`https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/README.md`

**Comment by arbll** [comment]
Hey @FierceElements, thanks for the report! 

Both links are now fixed
