### ISSUE TITLE
[Bug] CoreDNS integration causes issues

### ISSUE THREAD

**Issue by pratikmallya** [DataDog/datadog-agent#2357]
Seeing errors like this in dd agent logs:
```logs
[ AGENT ] 2018-09-22 00:07:37 UTC | ERROR | (kubelet.go:97 in parseKubeletPodlist) | Can't parse template for pod coredns-3506319915-lfh6f: in instances: found non JSON object type, value is: '[map[prometheus_url:http://%%host%%:9153/metrics tags:[dns-pod:%%host%%]]]'
```
But the annotations are exactly those that were provided in the [docs for the coreDNS integration](https://docs.datadoghq.com/integrations/coredns/) page. Why does dd agent throw this error?

**Comment by chrisnankervis** [comment]
@pratikmallya I ran into the same issue this morning and fixed it with the following annotation object:

```
"annotations": {
  "ad.datadoghq.com/coredns.check_names": "[\"coredns\"]",
  "ad.datadoghq.com/coredns.init_configs": "[{}]",
  "ad.datadoghq.com/coredns.instances": "[{\"prometheus_url\":\"http://%%host%%:9153/metrics\", \"tags\":[\"dns-pod:%%host%%\"]}]"
}
```

The issue being that the value of the `ad.datadoghq.com/coredns.instances`key is wrapped in an unnecessary array.

Good luck!

**Comment by CharlyF** [comment]
Apologies for the long delay on this issue - You are correct @chrisnankervis.
@DataDog/baklava could we get this updated ?

Thanks for bringing this up to our attention.

Best,
.C

**Comment by jeremy-lq** [comment]
https://github.com/DataDog/integrations-core/pull/2701

**Comment by pratikmallya** [comment]
Closing as it seems to be fixed
