### ISSUE TITLE
Datadog Agent 7.52.1 use OpenSSL 3.0.8 with vulnerabilities

### ISSUE THREAD

**Issue by dpey2mtl** [DataDog/datadog-agent#24745]
Hello,

We use Datadog Agent 7.52.1 for Windows and the MDE return usage of OpenSSL 3.0.8 in the following libraries as Vulnerable component :

c:\program   files\datadog\datadog   agent\embedded3\lib\site-packages\confluent_kafka.libs\libcrypto-3-x64-635e87f2c9173c8128924a94337627b3.dll

c:\program files\datadog\datadog   agent\embedded3\lib\site-packages\confluent_kafka.libs\libssl-3-x64-a0018292260ae8557aa3cd7db7d50307.dll

And Datadog Agent use also the version OpenSSL 3.0.13:

c:\program   files\datadog\datadog agent\embedded3\dlls\libcrypto-3.dll

c:\program files\datadog\datadog   agent\embedded3\dlls\libssl-3.dll

Please help to resolve this issue.

Thanks
Best
Didier

**Comment by iliakur** [comment]
👋 @dpey2mtl thanks for bringing this to our attention.

I'll ask a quick question to clarify: is your issue with just the first OpenSSL version (3.0.8 coming from confluent kafka) or **also** with v3.0.13 that the agent uses?

**Comment by dpey2mtl** [comment]
Hello,
Thanks to answer.

The issue is simple update OpenSSL version (3.0.8 coming from confluent kafka) to resolve all vulnerabilities and provide only ONE up to date OpenSSL version.

Thanks

**Comment by iliakur** [comment]
@dpey2mtl thanks for the quick response.

Unfortunately the solution is not as simple as the issue. We are not the maintainers of the confluent kafka package, so we would have to repackage it to update the vendored openssl dependency. For technical reasons this is too tricky on windows. 

Please feel free to open an issue [with the confluent kafka maintainers](https://github.com/confluentinc/confluent-kafka-python/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). I will close this issue as there's nothing we can do, apologies :(
