### ISSUE TITLE
tag 6.6.0 is missing from docker hub

### ISSUE THREAD

**Issue by eastlondoner** [DataDog/datadog-agent#2522]
see here: https://hub.docker.com/r/datadog/agent/tags/

The tags for the latest builds are
`latest`
`latest-jmx`
`6.6.0-jmx`

The `6.6.0` tag is desired so users can pin their containers to that specific version and not get caught out when latest changes to point at something else.

**Comment by mfpierre** [comment]
Hey @eastlondoner, indeed the `6.6.0` tag was missing on the docker hub, thanks for spotting this!

We're not sure why it was missing, we suspect some docker hub issues that happened yesterday approximatively at the same time of the release https://status.docker.com/pages/history/533c6539221ae15e3f000031 but we'll keep an eye of this for next releases.

Anyway, we just pushed the tag again, sorry for the trouble 🙇

**Comment by eastlondoner** [comment]
thanks!
