### ISSUE TITLE
[BUG] Dogstatsd is not publishing units on Timers

### ISSUE THREAD

**Issue by aisamu** [DataDog/datadog-agent#25524]
Timing metrics show up on Datadog as unitless gauges, even though they're officially published as milliseconds (including on the wire).

The workaround is to set overrides on Datadog's UI, but it has to be done per metric, per aggregation (p95, avg, max, median).

This was observed/reproduced on various clients:
* Direct datagram via shell
* java-dogstatsd-client
* Micrometer's native Datadog-flavored statsd client

I've double-checked that all three were emitting equivalently-shaped payloads:
* `java-dogstatsd-client`, theoretically the standard
```java 
;; client is a NonBlockingStatsDClientBuilder
client.recordExecutionTime("test_metric_execution", 100)

;; Shows up as 
;; => 'test_metric_execution:100|ms'
;; on the wire
```
* Datagram, per [the docs](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics)
```shell
echo -n "test_metric_shell:1111|ms|#shell" >/dev/udp/localhost/8125
```

**Agent Environment**
```shell
$ datadog-agent version         
Agent 7.53.0 - Commit: 0eec38d - Serialization version: v5.0.111 - Go version: go1.21.9
```

**Describe what happened:**
Regardless of the method, timing metrics end up as unitless gauges.

**Describe what you expected:**
Timing metrics should be displayed with the correct unit of `milliseconds (ms)`.

**Steps to reproduce the issue:**
1. Emit a timing statsd metric using any client
```shell
# The simplest alternative
echo -n "test_metric_shell:1111|ms|#shell" >/dev/udp/localhost/8125
```
2. Visit Metrics Explorer to verify that the metric is displayed as a unitless gauge.
<img width="771" alt="Screenshot 2024-05-12 at 08 59 46" src="https://github.com/DataDog/datadog-agent/assets/431708/467a8170-4ea5-4130-928c-acb21db2c3f9">

**Additional environment details (Operating System, Cloud provider, etc):**
* Machine 1 (EC2 instance on AWS)
```shell
uname -a
Linux <hostname> 6.5.0-1018-aws #18~22.04.1-Ubuntu SMP Fri Apr  5 17:44:33 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

* Machine 2 (Local Macbook)
```shell
uname -a
Darwin <hostname> 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64 arm Darwin
```

**References**
- [Dogstatds Datagram](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics)
- [Statsd timing metric docs](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#timing) 
- A similar report https://github.com/micrometer-metrics/micrometer/issues/2528

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.

Thanks!

**Comment by aisamu** [comment]
I did open a support ticket!

The response on May 16, 2024:

> I have opened a feature request for our product team to review. I am going to mark this ticket as closed for now, but may reach out for additional details if we do move forward with this or a related feature. If there is an update on the status of this request, we will open a new ticket with you in order to provide updates.
