### ISSUE TITLE
On MacOS Sierra - binaries hard-terminated on launch

### ISSUE THREAD

**Issue by truthbk** [DataDog/datadog-agent#257]
Note that this is happens building on go `<1.8.1` (verified working on `1.8.1`), and is actually an xcode, macOS bug. But there is a workaround as described here: https://github.com/golang/go/issues/19734 and https://github.com/shirou/gopsutil/issues/339

Since our tooling currently building on `1.7.3` we should probably bear this in mind.

**Output Error Sample**

```
rake test
0 linting issues found in ./pkg
0 linting issues found in ./cmd
vet found 0 issues in ./pkg
vet found 0 issues in ./cmd
signal: killed
FAIL    github.com/DataDog/datadog-agent/pkg/aggregator 0.005s
```

**Additional environment details (Operating System, Cloud provider, etc):**
MacOS Sierra 10.12.4

**Steps to reproduce the issue:**
1. Build with 1.7.3 on OSX
2. Try to run the agent, or tests, benchmarking, or whatever (really).
3. Watch binary crash with: `signal: killed`

**Describe the results you received:**
See step 3 and output above.

**Describe the results you expected:**
Normal execution.

**Additional information you deem important (e.g. issue happens only occasionally):**
Most likely this is the following: https://github.com/golang/go/issues/19734

**Comment by masci** [comment]
Closing as we should just use go 1.8.1 or later, the README was updated accordingly
