### ISSUE TITLE
[BUG] miss makezero in slice init

### ISSUE THREAD

**Issue by alingse** [DataDog/datadog-agent#25971]
**Agent Environment**

**Describe what happened:**

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242970601/job/25426486285 

```
====================================================================================================
append to slice `customContextTags` with non-zero initialized length at https://github.com/DataDog/datadog-agent/blob/main/pkg/util/profiling/profiling.go#L80:24
append to slice `readers` with non-zero initialized length at https://github.com/DataDog/datadog-agent/blob/main/pkg/network/usm/sharedlibraries/testutil/fmapper/fmapper.go#L36:13
====================================================================================================
```
the  `customContextTags := make([]string, len(settings.CustomAttributes))` should be `customContextTags := make([]string, 0, len(settings.CustomAttributes))`

the `readers := make([]*mmap.ReaderAt, len(os.Args)-1)` should be `readers := make([]*mmap.ReaderAt, 0, len(os.Args)-1)`

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by L3n41c** [comment]
Hello @alingse,

Thanks for bringing those bugs to our attention !
The fixes for the two of them have now been merged.
