### ISSUE TITLE
[BUG] Logs resent when Datadog Agent restarted

### ISSUE THREAD

**Issue by ibmboy19** [DataDog/datadog-agent#26909]
**Agent Environment**

Datadog Helm: 3.66.0
Agent version: 7.54.0

**Describe what happened:**
When any node level agent restarted, applications logs on that node are resent.

**Describe what you expected:**
Logs should not resent.

**Steps to reproduce the issue:**
1. Restart one of the node level datadog agent
2. Explore logs will see logs duplicated.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by vickenty** [comment]
This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!
