### ISSUE TITLE
CPU Limit metrics from kube_state_metrics are not tagged with container Status

### ISSUE THREAD

**Issue by midN** [DataDog/datadog-agent#2692]
**Describe what happened:**
We are trying to build monitoring around CPU Limits on our cluster.
Based on the metrics we saw CPU Limit metric in DD being too large in comparison to actual running containers.
Checked kube_state_metrics and found Completed pods/cronjobs to be reported with CPU Limits.
Opened Issue in kube_state_metrics and confirmed that is expected behaviour and pods should be filtered out by Running state for monitoring purposes.

See https://github.com/kubernetes/kube-state-metrics/issues/568#issuecomment-439921645 for details.

**Describe what you expected:**
I expected `kubernetes_state.container.cpu_limit` to either report only Running pods or have a additional Status tag to be able to filter out only Running containers.

Due to this we are not able to setup monitoring around cpu_limits as it's including Completed pods.

**Steps to reproduce the issue:**
Run a cronjob, let it complete and see `kubernetes_state.container.cpu_limit` include it.

**Comment by hkaj** [comment]
Hi @midN thanks for reaching out. I believe https://github.com/DataDog/integrations-core/pull/2624 fixes your issue. Can you confirm?
It will go out with 6.8 (sometime next week) btw.

**Comment by midN** [comment]
@hkaj Confirmed, that fixed it, thanks!
