### ISSUE TITLE
Readonly volumes break downstream images

### ISSUE THREAD

**Issue by matthewduren** [DataDog/datadog-agent#2716]
**Describe what happened:**
As of #2436, downstream containers using FROM datadog/agent cannot augment /etc/datadog-agent or /tmp since they were declared in a VOLUME directive

**Describe what you expected:**
Since this fix was put in for readonly filesystems, a secondary docker image perhaps tagged :readonly should be offered.  Specifying a VOLUME action in a dockerfile that could be used by downstream projects can break a lot of stuff.  6.5.2 appears to be the newest tag on docker hub without declared volumes.

**Steps to reproduce the issue:**
FROM datadog/agent:latest
RUN cp /etc/datadog-agent/datadog-docker.yaml /etc/datadog-agent/datadog.yaml
RUN ls -la /etc/datadog-agent #Note that /etc/datadog-agent/datadog.yaml does not exist

**Comment by vboulineau** [comment]
Hello,

This has been finally changed in `7.26` and should solve the problem. Feel free to come back to us if you have any issue with this.
