### ISSUE TITLE
[BUG] Dual shipping lack of support for existing secret for apikey

### ISSUE THREAD

**Issue by nicolasbelanger** [DataDog/datadog-agent#27168]
**Describe what happened:**
Throughout the documentation in https://docs.datadoghq.com/agent/configuration/dual-shipping/, and https://docs.datadoghq.com/agent/configuration/dual-shipping/#dual-shipping-in-kubernetes specially, it is enforcing a clear text version of the apikey directly in the config, which is far from ideal generally speaking, but also prohibited in some stricter environments.

**Describe what you expected:**
Usage of existingSecret configuration, similar to https://github.com/DataDog/helm-charts/blob/main/charts/datadog/README.md?plain=1#L176

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by pgimalac** [comment]
Hello @nicolasbelanger, thanks for opening this issue !
I'm not entirely sure I understand, do you mean that you can't use the "secrets" feature to specify an API key to dual ship, or just that all examples in the documentation use clear text API keys ?

**Comment by tbavelier** [comment]
@nicolasbelanger It's rather a matter of documentation that could be updated : the "You must use" is wrong. You can absolutely use secrets to avoid having it in plain text by defining environment variables based on your secret.

Let's take for instance metrics dual-shipping to an additional organisation in the EU1 datacenter : https://docs.datadoghq.com/agent/configuration/dual-shipping/#environment-variable-configuration
It requires to set the environment variable `DD_ADDITIONAL_ENDPOINTS` with the value being the JSON converted from the YAML (https://docs.datadoghq.com/agent/guide/environment-variables/#general-use) : 
```yaml
additional_endpoints:
  "https://app.datadoghq.eu":
  - apikey4
```

```json
{
  "additional_endpoints": {
    "https://app.datadoghq.eu": [
      "apikey4"
    ]
  }
}
```
`additional_endpoints` being the YAML key, the variable we need to set is `DD_ADDITIONAL_ENDPOINTS` with value : `{"https://app.datadoghq.eu":["apikey4"]}`. You can use a secret to define this value : https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data.

You would use `datadog.env` (https://github.com/DataDog/helm-charts/blob/e1ec85127de74c8b876eef6a81bb1579d17b49bf/charts/datadog/values.yaml#L563-L578) or `datadog.envFrom` to set it up.

**Example steps to follow to dual-ship metrics to US1 and EU1 :**
```bash
k create secret generic dual-shipping --from-literal metrics='{"https://app.datadoghq.eu": ["XXXe6976"]}'
```
```yaml
datadog:
  [...]
  env:
  - name: DD_ADDITIONAL_ENDPOINTS
    valueFrom:
      secretKeyRef:
        name: dual-shipping
        key: metrics
```

**Validating the results**
```bash
❯ k describe pod dd-datadog-v4h4d | grep DD_ADD
      DD_ADDITIONAL_ENDPOINTS:                        <set to the key 'metrics' in secret 'dual-shipping'>  Optional: false
      DD_ADDITIONAL_ENDPOINTS:                         <set to the key 'metrics' in secret 'dual-shipping'>  Optional: false
      DD_ADDITIONAL_ENDPOINTS:                        <set to the key 'metrics' in secret 'dual-shipping'>  Optional: false
      DD_ADDITIONAL_ENDPOINTS:                         <set to the key 'metrics' in secret 'dual-shipping'>  Optional: false
❯ k exec -it dd-datadog-v4h4d -- agent config | grep additional_endpoints
Defaulted container "agent" out of: agent, trace-agent, process-agent, init-volume (init), init-config (init)
additional_endpoints: '{"https://app.datadoghq.eu": ["***************************e6976"]}'
  additional_endpoints: {}
  events_additional_endpoints: {}
❯ k exec -it dd-datadog-v4h4d -- agent status | grep "API Keys status" -A 5
Defaulted container "agent" out of: agent, trace-agent, process-agent, init-volume (init), init-config (init)
  API Keys status
  ===============
    API key ending with e4381: API Key valid
    API key ending with e6976: API Key valid

=========
```
As seen in the screenshot below, I'm getting the `kubernetes.cpu.usage.total` from my host in both US1 and EU1 datacenter at the same time : 
<img width="2554" alt="image" src="https://github.com/user-attachments/assets/f4d1857c-3bd4-4a98-8f40-4036e3f0e464">

With `datadog.envFrom`, you are able to add all the necessary environment variables with a single secret to dual-ship all the features you would like.

Let us know if the above is not clear / if we can close this issue.

**Comment by nicolasbelanger** [comment]
@tbavelier makes sense indeed.  Thanks for all these details, I totally overlooked the env and envFrom...

However, before closing, should the doc be more sepcific or less miss-leading?

**Comment by tbavelier** [comment]
Yes, the doc should probably be improved a little bit upon. I filed a card internally so the documentation team can take a look internally and I'll possibly drop a quick PR (our documentation repo is public), will be closing this issue as it's not related to the Agent itself.
