### ISSUE TITLE
[BUG] serverless init 1.2.3 is not sending logs

### ISSUE THREAD

**Issue by piotrekkr** [DataDog/datadog-agent#27502]
**Agent Environment**

serverless-init 1.2.3

**Describe what happened:**

We use docker image with datadog installed like this:
```
COPY --from=datadog/serverless-init:1 /datadog-init /app/datadog-init
```
Since today morning our deployments suddenly stopped receiving logs. After some investigation I noticed that there was release `1.2.3` 12h ago and since we dont use pinned minor version it probably installed latest one. After pinning to 

```
COPY --from=datadog/serverless-init:1.2.2 /datadog-init /app/datadog-init
```

and deploying again logs are working now. Looking more into issue we noticed that restarting container is actually flushing logs but this is the only situation that logs are actually sent.

**Describe what you expected:**

Logs are send and received.

**Steps to reproduce the issue:**

Use serverless-init 1.2.3

**Additional environment details (Operating System, Cloud provider, etc):**

Deployed on GCP

**Comment by atlasale** [comment]
I have the same issue here, deployed in Azure. This has wasted a whole work day.

**Comment by piotrekkr** [comment]
Yeah another argument for explicitly specify patch version for all dependencies. I wonder if there is some CI test that was checking if serverless-init actually send anything to datadog. If there is one then please fix it. If not, then add one please :pray:

**Comment by jcstorms1** [comment]
Thanks for letting us know and apologies for the inconvenience. I'll look into this right away.

**Comment by jcstorms1** [comment]
We've rerelease v1.2.2 as v1.2.4 to avoid any further issues. This will give us time to identify a root cause for this bug. Apologies again for any inconvenience.
