### ISSUE TITLE
Helm chart k8s deploy

### ISSUE THREAD

**Issue by willyyang** [DataDog/datadog-agent#2754]
I need some assistance with getting apm traces to show up using the stable Datadog helm chart ( https://github.com/helm/charts/tree/master/stable/datadog )

Is there anything that needs to be configured differently for cluster agents when collecting apm metrics ? 

I've set up the DD agent daemonset to match https://docs.datadoghq.com/tracing/setup/kubernetes/?tab=java using helm configurations.

When I just used the daemonset configs, I am able to see traces .

Daemonset , cluster agent , kube-state-metrics pod are all running with the following configs

```
helm upgrade datadog-monitoring \
       --debug ../datadog \
       --set clusterAgent.enabled=true \
       --set clusterAgent.metricsProvider.enabled=true \
       --set clusterAgent.replicas=1 \
       --set datadog.apmEnabled=true \
       --set datadog.collectEvents=true \
       --set datadog.datadog.confd=true \
       --set datadog.leaderElection=true \
       --set datadog.logsConfigContainerCollectAll=true \
       --set datadog.logsEnabled=true \
       --set datadog.processAgentEnabled=true \
       --set datadog.apiKey=apikey \
       --set datadog.appKey=appkey \
       --recreate-pods
```

Able to see logs and events but not apm traces.
Any tips would help thanks.

**Comment by CharlyF** [comment]
Hey @willyyang thanks for opening this up!
We recommend using a NodePort to send traces from your applications when deploying the agent in Kubernetes - As per this doc [here](https://docs.datadoghq.com/tracing/setup/kubernetes/?tab=java):

```
To send Traces from your application pods, uncomment the # hostPort: 8126 line in your datadog-agent.yaml manifest. This exposes the Datadog Agent tracing port on each of your Kubernetes nodes.
[...]
```

To this extent, I think you would need to use the `.daemonset.useHostPort` when creating the chart, as per:
https://github.com/helm/charts/blob/master/stable/datadog/templates/daemonset.yaml#L55

Let us know if that helps!
Best,
.C

**Comment by willyyang** [comment]
ty.

**Comment by alexindigo** [comment]
@CharlyF 
Checking deployed `dd-agent` container, seems like `--set datadog.apmEnabled=true` has no effect.

`datadog.yaml` still has 
```
apm_config:
  enabled: false
```

**Comment by alexindigo** [comment]
Nvm, figured it out.
https://github.com/helm/charts/blob/master/stable/datadog/templates/daemonset.yaml#L57-L64

**Comment by daparthi001** [comment]
@alexindigo I am still facing the issue with apm

apm_config:
  enabled: false

helm install --name datadog  --set datadog.apiKey=<> --set datadog.tags=name:ct-idp-qa --set datadog.apmEnabled=true --set datadog.nonLocalTraffic=true --set datadog.logsEnabled=true --set datadog.logsConfigContainerCollectAll=true --set datadog.processAgentEnabled=true --set systemProbe.enabled=true --set daemonset.useDedicatedContainers=true --set daemonset.containers.traceAgent.logLevel=debug --set daemonset.useHostPort=true stable/datadog --namespace datadog

**Comment by alexindigo** [comment]
@daparthi001 IIRC, it should be `datadog.apm.enabled=true`.
