### ISSUE TITLE
[BUG] datadog.agent.running metric smaller than running agent count 

### ISSUE THREAD

**Issue by exlee** [DataDog/datadog-agent#27677]
**Agent Environment**

- 7.55.1 as of 16.07.2024
- Agent in a tightly environment-limited container

**Describe what happened:**
Organization I'm working for launched sentinel service for our applications. It consists of multiple, almost identical within environment, nodes.  After deployment we noticed that one of the `counter` metrics - in one environment only - is misreported to approx. 50%.

All checks and indirect metrics confirmed that metric doesn't reflect true state. Problem seemed to be limited to `counter` metric as `gauge` metrics confirm processing. Other environments report metric correctly.

During investigation we found correlation to `datadog.agent.running` metric. It is also misreported in this environment and also to 50%.

Systems are almost identical. No errors are raised. Load is evenly distributed, as are the internal metrics and log patterns.  The only thing we found is missing `Container ID`, or similar, metric for Agent and concluded that this environment has cardinality lower than the Agent count.

I suspect that metrics might be de-duplicated in processing pipeline, since there are no differences between node pairs (same environment variables, same tags, etc.).

**Describe what you expected:**
- `datadog.agent.running` metric to report accordingly to running nodes
- notification (as Agent warning/in UI) about possible data duplication/de-duplication

**Steps to reproduce the issue:**
- Run multiple Agents in a non-distinguishable environment
- Observe `datadog.agent.running` metric

**Additional environment details (Operating System, Cloud provider, etc):**
Amazon ECS

Note: I cannot provide diagnostic nor detailed information up front since my access is limited, but I'll try to get answers for requests.

**Comment by hush-hush** [comment]
HI @exlee,

Could you please [open a ticket](https://help.datadoghq.com/hc/en-us/requests/new) with our support team which is best suited to help you setup your ECS environment.

Thanks.
