### ISSUE TITLE
systemd service template description includes unnecessary quotation marks

### ISSUE THREAD

**Issue by eedwards-sk** [DataDog/datadog-agent#2772]
**overview**:

the systemd template files used to install the agent have quotation marks around the `Description=` line of the `[Unit]` section, resulting in quotation marks in the actual service description

systemd service files are INI format and do not require quotation marks for values with spaces

**example**

`datadog-agent.service` from an `Ubuntu 16.04` installation

```
[Unit]
Description="Datadog Agent"
After=network.target
Wants=datadog-agent-trace.service datadog-agent-process.service
StartLimitIntervalSec=10
StartLimitBurst=5

[Service]
Type=simple
PIDFile=/opt/datadog-agent/run/agent.pid
User=dd-agent
Restart=on-failure
ExecStart=/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid

[Install]
WantedBy=multi-user.target
```

compare this to another service with a 'multi word' description, `uuidd.service`

```
[Unit]
Description=Daemon for generating UUIDs
Requires=uuidd.socket

[Service]
ExecStart=/usr/sbin/uuidd --socket-activation
Restart=no
User=uuidd
Group=uuidd

[Install]
Also=uuidd.socket
```

now compare the output from `systemctl show <service>` showing that the description does not require the quotation marks, and in fact results in extraneous quotes when included:

```
● datadog-agent.service - "Datadog Agent"
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-12-11 20:03:23 UTC; 3h 45min ago
```

vs

```
● uuidd.service - Daemon for generating UUIDs
   Loaded: loaded (/lib/systemd/system/uuidd.service; indirect; vendor preset: enabled)
   Active: inactive (dead)
```

**suggested change**:

simply remove quotation marks from the value for `Description=` in each file below

**affected files**:

https://github.com/DataDog/datadog-agent/blob/master/omnibus/config/templates/datadog-agent/systemd.service.erb
https://github.com/DataDog/datadog-agent/blob/master/omnibus/config/templates/datadog-puppy/systemd.service.erb
https://github.com/DataDog/datadog-agent/blob/master/omnibus/config/templates/datadog-dogstatsd/systemd.service.erb
https://github.com/DataDog/datadog-agent/blob/master/omnibus/config/templates/datadog-agent/systemd.trace.service.erb
https://github.com/DataDog/datadog-agent/blob/master/omnibus/config/templates/datadog-agent/systemd.network.service.erb
https://github.com/DataDog/datadog-agent/blob/master/omnibus/config/templates/datadog-agent/systemd.process.service.erb

**Comment by remeh** [comment]
Hi!
Thank you for your report and you're right, as far as I know they're not needed. 👍 
As you've submitted a PR to fix those values, I'm closing this issue.
