### ISSUE TITLE
[Question] How to stop to insert JAVA_TOOL_OPTIONS parameter 

### ISSUE THREAD

**Issue by steverao** [DataDog/datadog-agent#28057]
**Agent Environment**

CentOS Linux release 7.9.2009 (Core)

**Describe what happened:**

I installed the Agent by referring to https://docs.datadoghq.com/agent/basic_agent_usage/centos/
But I find it will insert JAVA_TOOL_OPTIONS parameter for my some command, such as `mvn -Pnative native:compile`
![image](https://github.com/user-attachments/assets/b71fae2a-b1cc-4fdd-a039-bad03e7302ad)

It causes I can static compile my application correctly. I found I stop the Agent like following:
![image](https://github.com/user-attachments/assets/8b360636-d72a-4a61-bd88-99d209aa9536)

But when I ran `mvn -Pnative native:compile`, it was inserted the `JAVA_TOOL_OPTIONS` continuously. What should I do to avoid it?

**Describe what you expected:**

Stop to insert dd-agent related JAVA_TOOL_OPTIONS parameter.

**Comment by tbavelier** [comment]
This is related to Single Step Instrumentation when you installed the Agent with the one-line installation script with `DD_APM_INSTRUMENTATION_ENABLED=host`. You would need to follow the steps from https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=linuxhostorvm#removing-apm-for-all-services-on-the-infrastructure to remove the insertion of `JAVA_TOOL_OPTIONS`: 
1. Run: `dd-host-install --uninstall`
2. Restart the services on the host or VM.

Closing as this is not directly related to the Agent, but feel free to open a support case https://www.datadoghq.com/support/ if the instructions above are not sufficient.
