### ISSUE TITLE
[BUG] Dead link in config_template.yaml (dtdg.co/flag-hostname-fqdn)

### ISSUE THREAD

**Issue by kyletaylored** [DataDog/datadog-agent#28176]
**Agent Environment**
Current (in this repo)

**Describe what happened:**
In the config_template.yaml file, there is a shortened link (https://dtdg.co/flag-hostname-fqdn) that points to a dead end in Github.

**Describe what you expected:**
Redirect should not 404.

**Steps to reproduce the issue:**
Go to https://dtdg.co/flag-hostname-fqdn

**Additional environment details (Operating System, Cloud provider, etc):**
See config_template.yaml: https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L103C24-L103C58

**Comment by pgimalac** [comment]
Hello @kyletaylored, thanks a lot for reporting this !
I'll open a fix.

This used to link to [hostname-resolution.md](https://github.com/DataDog/datadog-agent/blob/7.54.x/docs/agent/hostname-resolution.md) which links to the official Datadog documentation about agent hostname resolution https://docs.datadoghq.com/agent/faq/how-datadog-agent-determines-the-hostname/?tab=agentv6v7.

**Comment by pgimalac** [comment]
Hey @kyletaylored, https://dtdg.co/flag-hostname-fqdn now redirects to the official documentation page directly.
Don't hesitate to re-open this issue if it's not fixed for you !
