### ISSUE TITLE
Agent build from source code for ppc64le architecture

### ISSUE THREAD

**Issue by sgonchigar** [DataDog/datadog-agent#28180]
Hello, I had reached out to support and they had asked to build the agent from the source code and I am running into issues. The test is successful but I am unable to launch the agent.  Wondering what I am missing.

[root@appdev1 datadog-agent]# invoke test --targets=./pkg/collector/python
--- Setting rtloader paths to lib:/usr/lib/golang/bin/src/github.com/DataDog/datadog-agent/dev/lib64 | header:/usr/lib/golang/bin/src/github.com/DataDog/datadog-agent/dev/include | common headers:
--- Flavor base: unit tests
-----  Module '/usr/lib/golang/bin/src/github.com/DataDog/datadog-agent'
✓  pkg/collector/python (1.786s)

DONE 46 tests in 13.091s
All tests passed
Tests final status (including re-runs): ALL TESTS PASSED
**[root@appdev1 datadog-agent]# ./bin/agent/agent run -c bin/agent/dist/datadog.yaml
-bash: ./bin/agent/agent: No such file or directory**

-------
[root@appdev1 datadog-agent]# invoke test --targets=./pkg/aggregator
--- Setting rtloader paths to lib:/usr/lib/golang/bin/src/github.com/DataDog/datadog-agent/dev/lib64 | header:/usr/lib/golang/bin/src/github.com/DataDog/datadog-agent/dev/include | common headers:
--- Flavor base: unit tests
-----  Module '/usr/lib/golang/bin/src/github.com/DataDog/datadog-agent'
✓  pkg/aggregator/internal/tags (cached)
∅  pkg/aggregator/sender
✓  pkg/aggregator/internal/util (cached)
✓  pkg/aggregator/mocksender (cached)
✓  pkg/aggregator (cached)

DONE 135 tests in 1.488s
All tests passed
Tests final status (including re-runs): ALL TESTS PASSED
**[root@appdev1 datadog-agent]# ./bin/agent/agent run -c bin/agent/dist/datadog.yaml
-bash: ./bin/agent/agent: No such file or directory**

--------------
[root@appdev1 datadog-agent]# find -name agent
./Dockerfiles/agent
./Dockerfiles/agent/entrypoint.d/agent
./Dockerfiles/agent/s6-services/agent
./cmd/agent
./cmd/cluster-agent/api/agent
./cmd/security-agent/api/agent
./comp/agent
./comp/api/api/apiimpl/internal/agent
./comp/logs/agent
./comp/process/agent
./comp/trace/agent
./omnibus/resources/agent
./pkg/security/agent
./pkg/trace/agent
./rtloader/test/python/datadog_checks/base/utils/agent
./test/new-e2e/tests/windows/common/agent

**Comment by alopezz** [comment]
👋 Hi! Unfortunately we can't offer support for building the Agent for platforms that we don't officially support, so you would be mostly on your own, here; therefore, I'll proceed to close this issue.

For more guidance, you may have a look at these docs as a starting point, but that's as far as we can go:
- https://github.com/DataDog/datadog-agent#getting-started
- https://github.com/DataDog/datadog-agent/blob/main/docs/dev/agent_build.md
- https://github.com/DataDog/datadog-agent/blob/main/docs/dev/agent_omnibus.md
