### ISSUE TITLE
Process Collection Enabled in Runtime Config but Not Reflected in `datadog.yaml` related to `DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true`

### ISSUE THREAD

**Issue by LQss11** [DataDog/datadog-agent#28280]
I have been working on integrating Datadog process config within the installation process. I found that I could specify `DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED` as an environment variable, as you mentioned to enable process data collection. I am doing this using the following command before installation:
```sh
sudo tee /etc/datadog-agent/environment <<EOT
DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true
EOT
```
Then I ran this command to initialize agent:
```sh
DD_API_KEY="XXXXXXXXXXXXXXX" DD_SITE="datadoghq.com" bash -c "$(curl -L https://install.datadoghq.com/scripts/install_script_agent7.sh)"
```
Once installed, I tried to verify the configuration by running `datadog-agent config` and I got the following:

```yaml
process_config:
  process_collection:
    enabled: true
```
But I don't see any updates in the datadog.yaml config. To troubleshoot further, I checked the config in runtime using `datadog-agent flare` and realized that I have this:

- runtime_config_dump.yaml file
```yaml
  process_collection:
    enabled: true
```
- process_agent_runtime_config_dump.yaml file
```yaml
  process_collection:
    enabled: false
```
Additionally, this is what I can see in the Datadog portal VM config which seems to be weird:
```yaml
process_collection:
  enabled: true
```

# References:
- [Datadog Environment Variables Documentation](https://docs.datadoghq.com/agent/guide/environment-variables/#exceptions)
- [process-agent github ref](https://github.com/DataDog/datadog-agent/blob/main/cmd/process-agent/command/main_common.go#L68)

**Comment by pgimalac** [comment]
Hello @LQss11, thanks for opening an issue !

As explained in the [environment variable documentation](https://docs.datadoghq.com/agent/guide/environment-variables/#general-use), the datadog-agent processes can be configured through several ways, the main ones being the config file and environment variable.

For almost every config key, the value can be set using an environment variable, and the agent will properly resolve all provided configurations based on priority (default value < config file < environment variable).
Here `process_config.process_collection.enabled` can be set using `DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED` environment variable.

But this doesn't actually change the configuration file, this is a different mechanism to pass configurations, so the fact that you don't see updated to `datadog.yaml` is expected.

`runtime_config_dump.yaml` and `process_agent_runtime_config_dump.yaml` contain the resolved configuration respectively from the "datadog-agent" and the "process-agent", so these are the configurations actually used by both processes at runtime (taking into account default values as well as values provided in the config file and environment variables).

Now as for using `/etc/datadog/environment`, as explained in the [documentation](https://docs.datadoghq.com/agent/guide/environment-variables/#using-environment-variables-in-systemd-units), environment variables defined in that file will be loaded by the `datadog-agent.service` systemd unit, which is only the `datadog-agent` process.
In particular they are not loaded by `datadog-agent-process.service` (`process-agent` process).

I'm discussing with the team owning installation methods to understand why every other service doesn't load the environment, they actually have an [open PR](https://github.com/DataDog/datadog-agent/pull/20771) to fix that, so we might be able to have that in 7.57.0 or 7.58.0 depending on the timeline.

I'll keep you updated once I know more.

**Comment by pgimalac** [comment]
As a workaround for now, you can just add `process_config.process_collection.enabled: true` in the config file, which is read by every agent process.
