### ISSUE TITLE
[BUG] Datadog Agent Documentation 404 in Github

### ISSUE THREAD

**Issue by PaulMotsuk** [DataDog/datadog-agent#28721]
**Agent Environment**
Error in the GIT repository for datadog-agent.

**Describe what happened:**
https://github.com/DataDog/datadog-agent/blob/main/docs/README.md

Has as the first entry in the TOC:
Datadog Agent user documentation.

"Datadog Agent" is a link pointing to <https://github.com/DataDog/datadog-agent/blob/main/docs/agent/README.md>. This results in a HTTP 404 error.

As I don't really know where this should go, I'm opening an issue.

**Describe what you expected:**
Reading Datadog Agent documentation. 

**Steps to reproduce the issue:**
- Select "datadog-agent " from the main datadog GIT repository <https://github.com/DataDog>
- Select the "Docs" folder <https://github.com/DataDog/datadog-agent/tree/main/docs>
- This opens the Readme.md for the directory. <https://github.com/DataDog/datadog-agent/blob/main/docs/README.md>
- Click "Datadog Agent" (the first entry in the TOC.
- A 404 error results. "The main branch of datadog-agent does not contain the path 
docs/agent/README.md."

**Additional environment details (Operating System, Cloud provider, etc):**
N/A

**Comment by FlorentClarret** [comment]
Hello! Thanks for reporting! This was addressed by @ofek in #28747.
