### ISSUE TITLE
DD_AC_EXLUDE does not work

### ISSUE THREAD

**Issue by aboeglin** [DataDog/datadog-agent#2875]
**Describe what happened:**
I'm using version 6.4.2 as it seems it's the only one currently working fine with logs ( at least on kubernetes ). I wanted to remove the logs from the agent iself, and following the documentation, set the env variable DD_AC_EXLUDE with a value of "name:datadog-agent". After trying various values I was unable to prevent the logs of the agent to come through.

note: I also use the env variable DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL.

**Describe what you expected:**
I expected the logs of the agent not to be sent anymore.

**Additional environment details (Operating System, Cloud provider, etc):**
Cloud provider: digital ocean managed kubernetes ( v1.12 )

Am I supposed to do anything else ? Or am I using deprecated features somehow ?

**Comment by xvello** [comment]
Hi @aboeglin 

Logs collection only honors the `ac_include` and `ac_exclude` options on versions 6.5 and up.

For help on setting up the agent, please contact [our support team](https://www.datadoghq.com/support/) as this issue queue is intended to track bugs.

Regards

**Comment by aboeglin** [comment]
Somehow DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL behavior has changed in >=6.5 and isn't documented. Or it's somehow broken.
