### ISSUE TITLE
configcheck command doesn't use cmd_port value in config to query agent

### ISSUE THREAD

**Issue by Psykyck** [DataDog/datadog-agent#2904]
**Describe what happened:**
The `configcheck` command doesn't seem to be picking up the `cmd_port` in the agent configs if changed to a custom port. Running `configcheck` with the `cmd_port` set to a port other than `5001` returns:

```
Failed to query the agent (running?): Get https://localhost:5001/agent/config-check: dial tcp [::1]:5001: getsockopt: connection refused
Error: unexpected end of JSON input
Usage:
  agent configcheck [flags]

Flags:
  -h, --help      help for configcheck
  -v, --verbose   print additional debug info

Global Flags:
  -c, --cfgpath string   path to directory containing datadog.yaml
  -n, --no-color         disable color output
```

I ran `datadog-agent` status, and confirmed that the agent is up and running.

https://github.com/DataDog/datadog-agent/blob/03047b0354f25a3bd764b47f53b7e36fdb1bd9ee/pkg/flare/config_check.go#L23

**Describe what you expected:**
`configcheck` should query the agent on the configured `cmd_port` set in `datadog.yaml`

**Steps to reproduce the issue:**
1. Change `cmd_port` in `datadog.yaml` to a port other than the default of `5001`
2. Start the agent
3. Run `datadog-agent configcheck`

**Additional environment details (Operating System, Cloud provider, etc):**
Tested on EC2 instance running Amazon Linux and also on my machine locally running macOS Mojave

**Comment by mfpierre** [comment]
Hey @Psykyck thanks for raising this, indeed in some commands the URL was set before the actual parsing of the configuration.

Just made a PR to fix this in 6.10
