### ISSUE TITLE
proposal: DD_APM_ANALYZED_SPANS env var is a clunky way to enable analyzing spans

### ISSUE THREAD

**Issue by leoyu037** [DataDog/datadog-agent#2921]
Summary of conversation with Kirk Kaiser in the #apm Slack channel:

I think using an env var to enable collection of analyzed spans like below is a little clunky. In a microservices ecosystem deployed to a Kubernetes cluster, I’d have to update the agent daemonset configuration every time a new span/service is added to the ecosystem. It’d be nice if there were an option to enable/disable analysis of all spans like `DD_APM_ANALYZE_SPANS=true/false`. This could maybe be coupled with `DD_APM_SPAN_WHITELIST` and `DD_APM_SPAN_BLACKLIST` for more control.

**Comment by stevenhaohuitan** [comment]
@gbbr any update?

**Comment by provcristianmaluenda** [comment]
A better solution could be analyzing all the services and, instead of a whitelist, Datadog can have a blacklist for those not desired services.

**Comment by burningion** [comment]
Hey everyone!

We've now launched a new way to configure your Trace Search and Analytics via environment variables based upon this feedback:

https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#trace-search-analytics

Happy to hear any further feedback. Thanks again everyone for the suggestions and comments.

**Comment by provcristianmaluenda** [comment]
@burningion I read the link, but it is not clear to me how should I config the analyzed spans. Do I still need to set the var DD_APM_ANALYZED_SPANS with all my services in Kuberenetes?

**Comment by andreamaruccia** [comment]
> Hey everyone!
> 
> We've now launched a new way to configure your Trace Search and Analytics via environment variables based upon this feedback:
> 
> https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#trace-search-analytics
> 
> Happy to hear any further feedback. Thanks again everyone for the suggestions and comments.

As far I've understood we still need to configure the agent to forward the spans received by the client like this: https://docs.datadoghq.com/tracing/trace_search_and_analytics/agent_trace_search/?tab=agent630
How does this then solve the problem above?

**Comment by jb-sean** [comment]
@andreamaruccia, I got it working by configuring the tracing clients, not the agents. So that means I no longer set the envvar `DD_APM_ANALYZED_SPANS` on the agent. Instead I just [set it up globally by initializing my Node.js tracing clients](https://docs.datadoghq.com/tracing/trace_search_and_analytics/?tab=nodejs#automatic-configuration) with the config `{ analytics: true }`.
