### ISSUE TITLE
cmd/trace-agent: log_file ignored during initialization

### ISSUE THREAD

**Issue by lucasm-iRonin** [DataDog/datadog-agent#2922]
Hello,
We're using trace-agent through [heroku-buildpack-datadog](https://github.com/DataDog/heroku-buildpack-datadog). I've noticed that some logging configuration is ignored. 
The buildpack provides `log_file` and `apm_config.log_file` settings through yaml file:

```yml
...
apm_config:
    log_file: /app/.apt/var/log/datadog/datadog-apm.log
```

ENV variable in the [datadog.sh](https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L19) file:

```
export DD_LOG_FILE="$DD_LOG_DIR/datadog.log"
```

However when `trace-agent` starts it tries to create `/var/log/datadog` directory:

```
seelog internal error: mkdir /var/log/datadog/: read-only file system
```

I'm not very familiar with the trace agent codebase but I've noticed that [SetupDefaultLogger](https://github.com/DataDog/datadog-trace-agent/blob/ea7b315ba07388b6da5099aa88d3fa61531be10d/cmd/trace-agent/main.go#L56) is called before [SetupLogger](https://github.com/DataDog/datadog-trace-agent/blob/ea7b315ba07388b6da5099aa88d3fa61531be10d/cmd/trace-agent/main.go#L131).

**Comment by gbbr** [comment]
It's been a while since this was opened and I forgot to follow up. This is now fixed. Tested with 6.13.0. Closing. Please feel free to re-open if you're still encountering trouble.
