### ISSUE TITLE
proposal: allow older traces (traces with root too far in past skipped)

### ISSUE THREAD

**Issue by BrendanBall** [DataDog/datadog-agent#2933]
We're having a problem with long child spans where they end up not getting sent to Datadog for some reason. We get the error in the logs: `ERROR (agent.go:141) - skipping trace with root too far in past`. This only happens for long living child spans, ie. the child span might be over 1s.

We've just implemented distributed tracing in python using flask. We're using python and a patched version of dd-trace-py to make distributed tracing work with python flask. see PR https://github.com/DataDog/dd-trace-py/pull/331. We're manually passing the `trace_id` and current `span_id` as the headers when doing requests to other services. All of this seems to be working well and the traces in datadog are coming through correctly. 

Can you give us some insight into why this might happen and if it's possibly a bug somewhere?

**Comment by gbbr** [comment]
This is now fixed in #493 and #3846
