### ISSUE TITLE
[Question] Where is the config documentation for the pre-sample cpu limit?

### ISSUE THREAD

**Issue by jbonzo** [DataDog/datadog-agent#2934]
I was reading the release changes for v5.14.0/06-05-2017 and the first improvement mentions [this PR](https://github.com/DataDog/datadog-trace-agent/pull/240) and says this is a configurable feature but I can't seem to find documentation on the name of the configuration. A point in the right direction would be very helpful.

**Comment by ajgajg1134** [comment]
I don't believe this configuration is still relevant on the latest versions of the datadog-agent. The trace-agent exposes `DD_APM_MAX_CPU_PERCENT`. However you may wish to _instead_ just use a cpu limit in your container orchestrator (e.g. k8s).
