### ISSUE TITLE
[BUG] MacOS 15: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by theogravity** [DataDog/datadog-agent#29578]
**Agent Environment**
MacOS 15

**Describe what happened:**
Running `datadog-agent status` gives `Error: Get "https://localhost:5001/agent/status?format=text": http: server gave HTTP response to HTTPS client`

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/533a7715-54e2-4794-b9a6-2af729d20f4f">

DD Agent UI shows `Not logged in. Please ensure that your GUI session has not expired. (Agent replied with: missing accessToken)`

![image](https://github.com/user-attachments/assets/4dab442b-9386-4e2b-9cfe-c356ea0ab7f8)

I did verify that my config file at ` ~/.datadog-agent/datadog.yaml` has an API key set

I also tried the uninstall steps and reinstalled without any luck.

**Describe what you expected:**
Should get status

**Steps to reproduce the issue:**
Executed install script with 

`DD_API_KEY=... DD_SITE="datadoghq.com" bash -c "$(curl -L https://install.datadoghq.com/scripts/install_mac_os.sh)"`

This installed the v7 agent.

`datadog-agent status` after startup has completed

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by sgnn7** [comment]
Hi @theogravity ,
Thank you for reporting this issue. Can you provide us with the exact version of the Agent that had these symptoms?

**Comment by misteriaud** [comment]
Hi @theogravity ,
Regarding the issue with accessing the UI, could you confirm if you tried launching it in one of the following ways?
- From the Agent's menu bar extras icon by selecting "Open Web UI"
- Using the terminal command: datadog-agent launch-gui
Also, could you let us know which web browser you're currently using?

**Comment by misteriaud** [comment]
Hi @theogravity,
I wasn't able to reproduce the behaviour you are mentioning. 
Could you provide us more details on how to reproduce it please.

**Comment by sgnn7** [comment]
Hi @theogravity,
As we have not received any further details on how to reproduce this issue, I'll close the ticket but feel free to reopen it if needed.
