### ISSUE TITLE
[BUG] Image `datadog/serverless-init:1.2.9` was removed

### ISSUE THREAD

**Issue by larskristianhaga** [DataDog/datadog-agent#29709]
Image `datadog/serverless-init:1.2.9` seems like to have been removed from DockerHub, removed from changelog, and removed the GitHub tag. All without notice.
Why? This effectively kills all our new deployments.

This is how the changelog page looked on the 26. September:
![image](https://github.com/user-attachments/assets/10186369-0eb1-4ba2-85b3-c672158b88e3)

And today the tag `datadog/serverless-init:1.2.9` is purged, and a new tag appeared `datadog/serverless-init:1`. Why go downwards in version? There also exists a version `datadog/serverless-init:1.0.0`. Whats the difference between the new `1` and the old `1.0.0`?

Changelog page:
https://hub.docker.com/r/datadog/serverless-init

**Comment by nina9753** [comment]
The `serverless_init:1` tag is the major version tag that doesn’t include breaking changes. Essentially, it's the same as ' LATEST` but within the major version. This is different from 1.0.0, which is an old version tag that will not be updated. `v1.2.9 `was accidentally deleted. Thank you for raising this issue with us. The [v1.2.9 tag](https://hub.docker.com/layers/datadog/serverless-init/1.2.9/images/sha256-7249278633f2bf4059106f4b0f359e489d1daeb773a64d6222bb22b08f8e2a1c?context=explore) and [v1.2.9-alpine](https://hub.docker.com/layers/datadog/serverless-init/1.2.9-alpine/images/sha256-f976e0abfab728f50bd6378ba21b43d6f641e0523e9594a59f32a04c3864f6fe?context=explore) tag has been added back
