### ISSUE TITLE
[BUG] Warnings for DD_GIT_COMMIT_SHA and DD_GIT_REPOSITORY_URL environment variables after upgrading to Agent 7.57.2

### ISSUE THREAD

**Issue by GabDug** [DataDog/datadog-agent#30123]
**Agent Environment**
`Agent 7.57.2 - Commit: 38ba0c7 - Serialization version: v5.0.130 - Go version: go1.22.7`

**Describe what happened:**

After an upgrade to Agent 7.57.2 in our EKS cluster, we noticed some warnings when the agent starts:

```
Unknown environment variable: DD_GIT_COMMIT_SHA
Unknown environment variable: DD_GIT_REPOSITORY_URL
```

Although these warnings are benign and do not impact the functionality, they create unnecessary noise in our logs, making it harder to monitor the health of our fleet of agents.

**Describe what you expected:**

We expected no warnings for environment variables [present in the base image of the agent](https://github.com/DataDog/datadog-agent/blob/main/Dockerfiles/agent/Dockerfile#L115).

> Note: We build a custom image for our agents, where we do not add, delete, or modify any environment variables; we only apply patches to certain integrations.

**Steps to reproduce:**

1. Deploy an EKS cluster with Datadog Agent version 7.57.2, deployed with the Helm chart.
2. Observe the agent logs upon startup.
3. Note the warnings related to `DD_GIT_COMMIT_SHA` and `DD_GIT_REPOSITORY_URL`.

**Additional environment details (Operating System, Cloud provider, etc):**

ENV present on the images:

```
DOCKER_DD_AGENT=true
DD_GIT_REPOSITORY_URL=https://github.com/DataDog/datadog-agent
DD_GIT_COMMIT_SHA=38ba0c7858eab5c07d8818f084fc6abdb99e6c51
...
```

Thanks and have a great day!

**Comment by hlascelles** [comment]
It is not yet in the charts as of 3.83.0.

**Comment by pgimalac** [comment]
👋 7.60.0 still hasn't been released, but it should happen soon.

**Comment by hlascelles** [comment]
Chart 3.88.0 has agent 7.61.0 👍.
