### ISSUE TITLE
[BUG] Incorrect source status upon replacement of a source in a tailer

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#30241]
When a `LogSource` gets replaced in a `Tailer`, the new `LogSource`'s `LogStatus` gets stuck in `IsPending`. This is presented to users in the output of `agent check`, which causes confusion.

The only place where `LogSource` is replaced is [here](
https://github.com/DataDog/datadog-agent/blob/b77289c264adb96c736ce399b56bf4e608905ad8/pkg/logs/launchers/file/launcher.go#L288-L290).
The only place where the `LogSource` status is updated is [in Tailer.Start](https://github.com/DataDog/datadog-agent/blob/b77289c264adb96c736ce399b56bf4e608905ad8/pkg/logs/tailers/file/tailer.go#L236).

Here's an example of what `agent check` displays in such cases (note the `Status: Pending` line):
```
  post--qa/post--post-jobalerts-cmhqa-cb666445c-fnnxq/main
  --------------------------------------------------------
    - Type: file
      Identifier: ac2e1ebc8c3f8c17a113fc57dc865d94ffb78d0f4cb06716d3356620aa6c5657
      Path: /var/log/pods/post--qa_post--post-jobalerts-cmhqa-cb666445c-fnnxq_caaa42a2-74bb-42f4-8f58-30b398a2e15f/main/*.log
      Service: postdaemon
      Source: java
      Status: Pending
        1 files tailed out of 1 files matching  
      Bytes Read: 297770   
      Pipeline Latency:
        Average Latency (ms): 0
        24h Average Latency (ms): 0
        Peak Latency (ms): 0
        24h Peak Latency (ms): 0
```

**Comment by vickenty** [comment]
Hi @deadok22, thank you for opening the issue. This problem will be resolved in the upcoming 7.60.0 release. Please let me know if you have any further concerns.
