### ISSUE TITLE
Rabbitmq autodiscovery

### ISSUE THREAD

**Issue by anatolyrossinsky** [DataDog/datadog-agent#3039]
Autodiscovery for datadog agent in kubernetes will be very nice thing to have. Is it planned to implement?

**Comment by xvello** [comment]
Hello @anatolyrossinsky 

We do support [Rabbitmq](https://docs.datadoghq.com/integrations/rabbitmq/) and [Autodiscovery in k8s](https://docs.datadoghq.com/agent/autodiscovery/?tab=kubernetes#setting-up-check-templates)
The check does require credentials though, that you'll need to provide in a configuration template. Please refer to our [Autodiscovery documentation](https://docs.datadoghq.com/agent/autodiscovery), and do not hesitate to [reach out to our support](https://www.datadoghq.com/support/) for any question on the setup.

**Comment by anatolyrossinsky** [comment]
i did all annotations and `agent configcheck -v` show plenty different autodiscovery templates including redis etc.. but not rabbitmq

**Comment by BeyondEvil** [comment]
Did you ever solve this @anatolyrossinsky ?

I have the same issue.
