### ISSUE TITLE
[DCA] Metrics casted to int

### ISSUE THREAD

**Issue by dturn** [DataDog/datadog-agent#3043]
**Describe what happened:**

When using an external metric the value reported to the HPA is always an integer. It looks like it's happening here https://github.com/DataDog/datadog-agent/blob/master/pkg/util/kubernetes/hpa/datadogexternal.go#L124. This is an issue when the metric is expressed as a value between 0 and 1. 

**Describe what you expected:**

I'd expect the metric to be allowed to be `400m`, not `0` or `1`

**Steps to reproduce the issue:**

Create an hpa with a metric that has a value between 0 and 1

```
 > kubectl --context XXXX  -n cluster-services get configmaps datadog-custom-metrics -o yaml             

apiVersion: v1
data:
  external_metric-trivial-hpa-app-production-tracking-hpa-raindrops.utilization: '{"metricName":"raindrops.utilization","labels":{"cluster-name":"XXX"},"ts":1550187600,"hpa":{"name":"tracking-hpa","namespace":"trivial-hpa-app-production","uid":"bc8b5a01-3081-11e9-a1cb-42010a8e0155"},"value":0,"valid":true}'
kind: ConfigMap
metadata:
  annotations:
    custom-metrics.datadoghq.com/last-updated: "2019-02-14T23:41:17Z"
  creationTimestamp: "2018-11-08T23:05:05Z"
  name: datadog-custom-metrics
  namespace: cluster-services
  resourceVersion: "176865987"
  selfLink: /api/v1/namespaces/cluster-services/configmaps/datadog-custom-metrics
  uid: bb03a9ce-e3aa-11e8-9805-42010a8e00df
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by CharlyF** [comment]
@dturn - Thanks for opening this.
Indeed this is an issue we're aware of. 
I am scheduling some work in our backlog to address it.

Thanks for the report!
Best,
.C

**Comment by dturn** [comment]
@CharlyF This looks fixed, but hasn't be released. Do you have an eta for a new version of the cluster agent?

**Comment by CharlyF** [comment]
Yes, We are working on a few more things we want to have in 1.3.0, but we should be freezing the code next week. If QA goes well, it will be GA a few days thereafter.

**Comment by DylanLovesCoffee** [comment]
hey @dturn! Thanks for initially opening up this issue. The release of v1.3.0 of the cluster-agent should solve this. I'm closing this issue here, but let us or support@datadoghq.com know if you run into any bumps in the road. Cheers!
