### ISSUE TITLE
Feature Request: Scrape Kubernetes PVC metrics from Kubelet

### ISSUE THREAD

**Issue by wmorgan6796** [DataDog/datadog-agent#3056]
**Additional environment details (Operating System, Cloud provider, etc): Kubernetes 1.11, AWS, Debian

Currently the only way for the agent to get any disk metrics for a host the daemonset is deployed on is for any mounted disks in the host to be mounted within the agent container and then monitored as if the disk were mounted on a physical host. This doesn’t work for persistent volumes in Kubernetes as those disks mounts are sequestered from the host user and inaccessible to the agent as it doesn’t have the necessary permissions. These metrics for all pvcs mounted on a host are accessible through the kubelet and can monitored by hitting the kubelet /metrics endpoint. Those metrics should be exported to datadog automatically so that persistent volumes can be correctly monitored and alerted on. The existing workaround is to add a Prometheus check and limit it to just the volume metrics, but I would argue this is something that should be done automatically already especially with the current limits on the Prometheus check.

**Comment by irabinovitch** [comment]
@wmorgan6796 Thank you for reaching out.  Could you help confirm which agent version you are running at the moment? The kubernetes integration currently collects the following metrics. They were added to the kublet check in https://github.com/DataDog/integrations-core/pull/2256

kubelet.volume.stats.available_bytes
kubelet.volume.stats.capacity_bytes
kubelet.volume.stats.used_bytes
kubelet.volume.stats.inodes
kubelet.volume.stats.inodes_free
kubelet.volume.stats.inodes_used

Are there any other stats . you'd like to see for volumes? I'd also be interested in learning more about any challenges you might be seeing in the OpenMetrics check so we can help address those.

**Comment by irabinovitch** [comment]
@wmorgan6796 Our support team mentioned you connected with them and confirmed these were the metrics you are looking for.  I'm going to close this issue out, but if you run into any issues please re-open. I'm also happy to connect to discuss your OpenMetrics feedback if you'd like. My email is ilan@datadoghq.com.
