### ISSUE TITLE
datadog-agent container healthcheck

### ISSUE THREAD

**Issue by oussemos** [DataDog/datadog-agent#3148]
I found many [discussions](https://github.com/DataDog/datadog-agent/pull/1055) around healthcheck implementation, but I'm not sure if it's already implemented or not ?

**Additional environment details (Operating System, Cloud provider, etc):**

I'm running a v5 agent as a service on ECS, I'm going to upgrade to v6 and want to do things the right way.

**Comment by hkaj** [comment]
Hi @oussemos thanks for reaching out. Yes the docker image of agent v6 comes with a healthcheck as you can see [here](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/Dockerfile#L119-L120). It calls the health command of the agent which you can test by running `docker exec -it <agent-container-name> agent health`.

Please let us know if you have any other question.

**Comment by efenderbosch** [comment]
@hkaj that link is now 404. Did it get moved?

**Comment by RohanKurane** [comment]
I am facing a similar issue where the container running the datadog daemon is unhealthy. How can I debug this and fix ?

**Comment by hkaj** [comment]
Yeah sorry @efenderbosch  i forgot to pin to a permalink. Here's the healthcheck [definition,](https://github.com/DataDog/datadog-agent/blob/b18ca83298238ad4643cd482e6977e4e6e7c6c26/Dockerfiles/agent/amd64/Dockerfile#L162-L163) and its [implementation](https://github.com/DataDog/datadog-agent/blob/7.16.1/Dockerfiles/agent/probe.sh)

@RohanKurane you can look at these files and run the health command yourself to check which component of the agent goes unhealthy. If that doesn't help, feel free to reach out to [support](https://www.datadoghq.com/support/)!

**Comment by efenderbosch** [comment]
@RohanKurane if you are running AWS ECS, we just added this to our task definition:

```json
    "healthCheck": {
        "retries": 3,
        "command": [
          "CMD-SHELL",
          "agent health"
        ],
        "timeout": 5,
        "interval": 30,
        "startPeriod": 15
      }
```

ECS will just start a new one.

**Comment by mewc** [comment]
if you run the agent locally, you can test this there as well, but yes the above works

**Comment by jamesarosen** [comment]
The [official docs for this container](https://docs.datadoghq.com/containers/docker/?tab=standard#misc) discuss the `DD_HEALTH` environment variable option, but that's it. It would be nice to have the recommended `agent health` approach documented there.
