### ISSUE TITLE
traces not appearing in the datadog UI

### ISSUE THREAD

**Issue by fommil** [DataDog/datadog-agent#3172]
We are writing a datadog client for the Haskell programming language https://github.com/symbiont-io/haskell-datadog/blob/master/library/Datadog/Agent.hs

We are using datadog-agent version 6.10.1

In one of our manual QA tests we see our service "standard-node-name" appear in the datadog ui, but no spans or traces appear.

Below are some examples of JSON payloads that we are sending to the `/v0.3/traces` endpoint. Could you please confirm if these payloads are valid? Did we misinterpret the spec at https://docs.datadoghq.com/api/?lang=python#tracing or the validation logic that follows from `pkg/trace/api/api.go` of your source code?

```json
[
  [
    {
      "duration": 800971,
      "meta": {
        "query": "\"SELECT value FROM kv WHERE key = ?\""
      },
      "name": "SQL:QUERY",
      "resource": "time",
      "type": "web",
      "service": "standard-node-name",
      "span_id": 1203080099300928760,
      "start": 1553018501760708008,
      "trace_id": 10995988795583270949
    }
  ],
  [
    {
      "duration": 600747,
      "meta": {
        "query": "\"SELECT since_transaction_index,protocol_version FROM protocol_version\""
      },
      "name": "SQL:QUERY_",
      "resource": "time",
      "type": "web",
      "service": "standard-node-name",
      "span_id": 11653417584296745794,
      "start": 1553018501762573374,
      "trace_id": 10995988795583270949
    }
  ]
]
```

``` json
[
    [
        {
            "duration": 800971,
            "name": "SQL:QUERY",
            "resource": "/time",
            "type": "web",
            "service": "txe-positive",
            "span_id": 120308009,
            "start": 1553018501760708008,
            "trace_id": 10995988
        }
    ]
]
```

**Comment by gbbr** [comment]
When you are sending these traces, are you seeing anything related in the trace-agent logs? It helps adding `log_level: debug`, and for your own investigations, even `log_level: trace` could be helpful (but that's super spammy).

**Comment by fommil** [comment]
I don't have easy access to restart the agent with different config so I'm looking into running something locally to debug. But when I looked through the source code of the agent I noticed that there is not a lot of logging when things are silently dropped so I was thinking about adding some more to aid my debugging.

**Comment by gbbr** [comment]
When traces are being dropped, this is something we want to know. Can you please point out the places or situations where you say that traces are being "silently dropped"?

**Comment by fommil** [comment]
My notes from reading the source are:

```
-- Clients post a list of traces. The datadog-agent (based on version
-- e34402aeae95a619303c0cb624ba5b3908f5c358) silently rejects invalid traces
-- under any of the following conditions:
--
-- * if there is a trace ID discrepancy between 2 spans
-- * if two spans have the same span_id
-- * if it is empty
-- * if trace_id or span_id is 0
-- * if service is empty or longer than 100 chars after applying
--   `normalizeTag` rules (tl;dr letters and colons are safe)
-- * if name is empty, doesn't have any alphabetic chars, or is longer than
--   100 chars after applying `normMetricNameParse` rules (tl;dr underscores
--   only allowed in certain places)
-- * if type is empty or longer than 100 chars after attempting to correct
--   any UTF-8 errors.
-- * if the span duration is less than 0 or longer than 10 minutes
-- * if the resource is not valid UTF-8 and cannot be fixed. The upstream
--   server has a 5000 character limit.
-- * if the start is before 2000-01-01
--
-- and will silently rewrite invalid data, e.g. the normalisation routines, when
-- ParentID == TraceID == SpanID the parent is reset to 0.
```

I have attempted to model these criteria in the Haskell types, so we should never be sending anything that breaks these rules.

**Comment by gbbr** [comment]
To my knowledge, the trace-agent _never_ drops traces silently. If it does, it's a bug we need to fix. For the cases where traces are dropped based on your list, the error is logged [here](https://github.com/DataDog/datadog-agent/blob/abf0da8d0e6b98f20b0137fda5f9729ad16a9d36/pkg/trace/api/api.go#L260).

**Comment by gbbr** [comment]
There is also a metric in the Datadog application which shows how many traces are dropped. Not sure if it helps you but thoughts I'd mention it. It's called `datadog.trace_agent.receiver.traces_dropped`. If you aren't seeing errors in the log, it should mean everything is well.

There is also `datadog.trace_agent.receiver.traces_received`

**Comment by fommil** [comment]
When I say "silently" I mean the caller never hears about it through the protocol. As an engineer on one service in a microservice platform, I don't have easy access to change the debug levels in a system wide agent, or even to see the logs, or even to know where it's running.

**Comment by gbbr** [comment]
That's correct. The reason behind it is that we don't want to make the HTTP transactions as short as possible. When you connect through HTTP the agent will just confirm that it has received a valid msgpack payload and then respond. We don't want (nor need) to keep connections idle to confirm that everything was processed correctly.

If you want to experiment, you can do so locally by running a local version of the trace-agent.

**Comment by fommil** [comment]
That's highly unusual in my world, where invalid payloads should expect a non-20x response.

Does it only support msgpack? I've been sending JSON.

**Comment by gbbr** [comment]
> That's highly unusual in my world, where invalid payloads should expect a non-20x response.

A payload is valid if it can be decoded.

> Does it only support msgpack? I've been sending JSON.

Yes, you can send JSON too.

Once more, I think you'll have quite a hard time writing your tracer without running against a local version of the trace-agent.

**Comment by fommil** [comment]
Re local agent: yes, I know. I'm doing that to debug this issue but that doesn't help debugging missing traces in a restricted live environment. I think I would prefer it if the server respected HTTP error codes rather than trying to exit early. A fire and forget approach would be more ideally suited to a UDP protocol.

**Comment by fommil** [comment]
btw, `DD_LOG_LEVEL` is not documented, but is :100: much more convenient to use.

**Comment by fommil** [comment]
well, I guess this is the answer...


```
[ TRACE ] 2019/03/25 17:49:34 http: panic serving 127.0.0.1:54848: unhandled content type "application/json;charset=utf-8"
[ TRACE ] goroutine 99 [running]:
[ TRACE ] net/http.(*conn).serve.func1(0xc000498000)
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/net/http/server.go:1746 +0xd0
[ TRACE ] panic(0xa39080, 0xc0001eaa40)
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:513 +0x1b9
[ TRACE ] github.com/DataDog/datadog-agent/pkg/trace/api.decodeReceiverPayload(0x7f5108032160, 0xc000141d40, 0xbe1c80, 0xc000141d60, 0xb26f51, 0x4, 0xc0001d7d80, 0x1e, 0x4ef4a8, 0xc000143eec)
[ TRACE ] 	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/trace/api/api.go:429 +0x2ff
[ TRACE ] github.com/DataDog/datadog-agent/pkg/trace/api.getTraces(0xb26f51, 0x4, 0xbe7da0, 0xc00018c0e0, 0xc000114200, 0xc, 0xc0003b8258, 0x448601, 0x2)
[ TRACE ] 	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/trace/api/api.go:403 +0x89c
[ TRACE ] github.com/DataDog/datadog-agent/pkg/trace/api.(*HTTPReceiver).handleTraces(0xc000228230, 0xb26f51, 0x4, 0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/trace/api/api.go:217 +0xa7
[ TRACE ] github.com/DataDog/datadog-agent/pkg/trace/api.(*HTTPReceiver).handleTraces-fm(0xb26f51, 0x4, 0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/trace/api/api.go:98 +0x5c
[ TRACE ] github.com/DataDog/datadog-agent/pkg/trace/api.(*HTTPReceiver).httpHandleWithVersion.func1(0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/trace/api/api.go:190 +0xc8
[ TRACE ] github.com/DataDog/datadog-agent/pkg/trace/api.(*HTTPReceiver).httpHandle.func1(0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/trace/api/api.go:176 +0xf6
[ TRACE ] net/http.HandlerFunc.ServeHTTP(0xc0002885c0, 0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/net/http/server.go:1964 +0x44
[ TRACE ] net/http.(*ServeMux).ServeHTTP(0x10924a0, 0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/net/http/server.go:2361 +0x127
[ TRACE ] net/http.serverHandler.ServeHTTP(0xc0002965b0, 0xbe7da0, 0xc00018c0e0, 0xc000114200)
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/net/http/server.go:2741 +0xab
[ TRACE ] net/http.(*conn).serve(0xc000498000, 0xbe84a0, 0xc00002ab40)
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/net/http/server.go:1847 +0x646
[ TRACE ] created by net/http.(*Server).Serve
[ TRACE ] 	/root/.gimme/versions/go1.11.5.linux.amd64/src/net/http/server.go:2851 +0x2f5
```

**Comment by fommil** [comment]
i.e. looks like you don't handle JSON afterall...

**Comment by fommil** [comment]
BTW, to reproduce this problem with the haskell client library you can start the docker agent with

```
docker run --name datadog \
  -p 8126:8126 \
  --network host \
  -e DD_API_KEY=${DD_API_KEY} \
  -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
  -v /proc/:/host/proc/:ro \
  -e DD_APM_ENABLED=true \
  -e DD_LOG_LEVEL=debug \
  datadog/agent:6.10.3-logs-api-key-rc.1
```

and then run this script (if you don't have a `cabal` and `ghc` installed, you can use https://www.haskell.org/ghcup/ to get it, I'm using `ghc-8.4.4`):

```haskell
#! /usr/bin/env cabal
{- cabal:
build-depends: base, datadog-tracing, http-client, servant-client
-}

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications  #-}

module Main where

import           Control.Monad
import           Data.Typeable
import           Datadog.Agent
import           Network.HTTP.Client hiding (Proxy)
import           Servant.Client

main :: IO ()
main = do
  mgr <- newManager defaultManagerSettings
  base <- parseBaseUrl "http://localhost:8126"
  let http = client (Proxy @ Traces3)
      env  = mkClientEnv mgr base
      traces = [ (Trace
                  [ Span "tester" "span" "" 10995988795583270949 1203080099300928760 Nothing 1553018501760708008 800971 Nothing Nothing Nothing (Just "web")
                  ])
               ]
  res <- runClientM (http traces) env
  putStrLn (show res)
```

**Comment by fommil** [comment]
The problem is apparently addressed in the referenced PR. I am going to workaround it.

**Comment by gbbr** [comment]
@fommil it seems you've caught a bug. We usually don't set "charset" in our tracer's "Content-Type" header so we never ran into this. I'll fix this. If you want to send JSON you can just remove "charset" for now, but I do recommend switching to msgpack as it's much smaller in size, and faster.

**Comment by fommil** [comment]
cool, thanks @gbbr ! It is not easy to change the charset in this framework so it is best that I focus on the msgpack support. I need it to capture the messages from our other services in our mock agent anyway.

**Comment by gbbr** [comment]
Opened #3202 to fix that problem. We'll release it in 6.11.0 next week (if all our internal testing goes well). Thanks for surfacing it and please keep me in the loop with any other problems you encounter and I'm happy to help.

If you need quicker answers, Slack is also a good option.
