### ISSUE TITLE
Init script is broken in 6.10.2.  Agent information, status, etc are unavailable (Can't open /lib/lsb/init-functions)

### ISSUE THREAD

**Issue by dvishniakov** [DataDog/datadog-agent#3181]
**Output of the info page (if this is a bug)**
```
/etc/init.d/datadog-agent: 15: .: Can't open /lib/lsb/init-functions
```

**Describe what happened:**
All init script commands, including `status` command are broken in 6.10.2, but it was working in 6.10.1
There is no `lsb` folder in `/lib`:
```
$ sudo docker exec -it $DD_CONTAINER_ID ls /lib/
init  systemd  terminfo  udev  x86_64-linux-gnu
```

**Describe what you expected:**
Normal expected output

**Steps to reproduce the issue:**
on the host machine:
```
DD_CONTAINER_ID=$(sudo docker ps -q --latest --filter volume=/opt/dd-agent/conf.d --format "{{.ID}}")
sudo docker exec -it $DD_CONTAINER_ID /etc/init.d/datadog-agent status
```

**Additional environment details (Operating System, Cloud provider, etc):**
EC2 in Amazon
```
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                   
1764d676351f        datadog/agent:6.10.2             "/init"             7 minutes ago       Up 7 minutes (healthy)
```

**Comment by xvello** [comment]
Hello @dvishniakov,

As described in https://docs.datadoghq.com/agent/guide/agent-commands/?tab=agentv6 the containerized agent command for the status page is `docker exec -it <container_name> agent status`.

As the dockerized agent uses it's own supervisor (s6), the upstart/systemd based `/etc/init.d` script is not supported in this image. Please note that restarting the agent within a container is not supported, you should restart the whole container.

If you have more questions about operating the agent, please don't hesitate to reach our support team, at https://www.datadoghq.com/support/

**Comment by dvishniakov** [comment]
@xvello , great, that works. I want to note that the command I've supplied before worked even in 6.10.1. 
The only change noted in 6.10.2 is "Fix a race condition in Autodiscovery leading to some checks not
being unscheduled on container exit", so it was confusing why the existing command stopped working. Is it possible to add a line to the release notes about this?
Thank you
