### ISSUE TITLE
Need to redeploy HPA after any cluster agent restart

### ISSUE THREAD

**Issue by nicholas-devlin** [DataDog/datadog-agent#3213]
**Describe what happened:**

I modified a configuration in the cluster agent yaml, but when I restarted it was not connected to the Horizontal Pod Autoscaler anymore. I had to go and redploy my hpa config

**Describe what you expected:**
I expect the cluster agent to be able to restart and still connect to the hpa

**Steps to reproduce the issue:**
- restart the cluster agent
- hpa is no longer connected

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by CharlyF** [comment]
Thanks for opening this @nicholas-devlin !
We identified an issue in the lifecycle that can occur if the Cluster Agent is running with the leader election enabled (or a Node Agent used to be the leader upon transitioning to the deployment of the Cluster Agent) but the External Metrics Provider is enabled for the first time thereafter.

If an HPA on External Metrics is already present, then the Cluster Agent (with it's informer) will List the HPAs (to extract the metric(s) that should be queried to Datadog) and keep a local cache for a certain period of time (30 seconds). 
Now, only the leader can write in the ConfigMap that we use to store the External Metrics data, and for a Cluster Agent that is not the leader, the cache is flushed after the 30s.
Lastly, the Leader Election Lease is set at 90s by default.

Thus, if a Cluster Agent is not yet the leader, it will flush the cache prior to taking the leadership and therefore won't store any data in the ConfigMap.
If you do delete/recreate your HPA though, the Cluster Agent, that is now the leader will get the notification, parse through the HPA, query Datadog and store the metric in the ConfigMap and expose it (if it is valid obviously).

A temporary fix should be to set `external_metrics_provider.batch_window` to 120s in the datadog.yaml, this also exists as an environment variable `DD_EXTERNAL_METRICS_PROVIDER_BATCH_WINDOW`.

We are nevertheless working on this at them moment to improve the lifecycle and make it more resilient.

Thank you for opening this and apologies for the headache.
Best,
.C

**Comment by nicholas-devlin** [comment]
should be solved in 1.3.0 according to @CharlyF
