### ISSUE TITLE
Env variable to set `log_format_json` in the configuration file

### ISSUE THREAD

**Issue by krish7919** [DataDog/datadog-agent#3301]
An easy way to set the log format using an environment variable, say, `DD_LOG_FORMAT`.

For example, my use case is wrt the Kubernetes cluster, and it was working fine for many thing by default. But just for a few options (prometheus metrics export, json log format, tls configuration, etc), I have to copy the `.example` files, mount them as a ConfigMap, modify the default `helm` chart to set the right values before access to them.

I believe Datadog can have a better user experience when supplying such simple options rather than have a file modification event hook built-in during every change.

**Comment by krish7919** [comment]
This is also useful to alert when Datadog itself is failing using a log metric or some other way. For example, when I encountered this error `Unable to detect the kubelet URL automatically`, I had to find that manually. A better way for me would be to hook that up to CloudWatch or something else.

**Comment by kipit** [comment]
Are you looking for [something](https://github.com/DataDog/datadog-agent/blob/3fa1fc4653e51e2d5d498719e20090d28e64a595/pkg/config/config.go#L147) like
```yaml
# In your Helm charts values...
#...
datadog:
  #...
  env:
    - name: DD_LOG_FORMAT_JSON
      value: "true"
  #...
```
?

**Comment by krish7919** [comment]
Yes, precisely

**Comment by krish7919** [comment]
Hmm, can we use `log_format_json` directly? 
I don't find that in the docs, but I will try.

**Comment by kipit** [comment]
> Hmm, can we use log_format_json directly?

You don't have to, in a `Helm` context, environnement variable will do the _trick_.

**Comment by krish7919** [comment]
This is working great, thanks @kipit !
