### ISSUE TITLE
Live process dd_url not taken into account

### ISSUE THREAD

**Issue by unloadedroe** [DataDog/datadog-agent#3314]
Hi

The agent has been configured to use:

```yaml
site: datadoghq.eu
dd_url: https://app.datadoghq.eu
```
but the agent keeps trying to publish to the datadoghq.com site.

I can see in the logs:
```bash
2019-04-16 14:41:07 ERROR (collector.go:222) - unexpected response from https://process.datadoghq.com/api/v1/collector. Status: 403 Forbidden
```

and in the datadog console (web console) I have the following message: `No Agents reporting!`

The agent version is 6.0.0-1 and it has been installed using the Ansible role https://github.com/DataDog/ansible-datadog in an EC2 instance running Amazon Linux 2.

Could you please advise ?

Thank you

**Comment by arbll** [comment]
Hi @unloadedroe, 

Can you confirm that the version you installed is 6.0.0 ? This version of the Agent does not have support for the European instance.

Cheers,
Arthur

**Comment by unloadedroe** [comment]
@arbll Thank you very much. I updated the version and now it is working. Sorry for the inconveniences.
