### ISSUE TITLE
datadog api key pod to pull secret from AWS Parameter Store 

### ISSUE THREAD

**Issue by marcincuber** [DataDog/datadog-agent#3388]
Question related to Datadog API key which is used as part of [kubernetes daemonset](https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/).

Currently the only documented ways of passing `DD_API_KEY` is to use Kubernetes secrets to or environment variable.

Is there a way to use AWS SSM i.e. parameter store? So rather then specifying `DD_API_KEY` in my daemonset yaml, I would like to specify env variable such as;
```- name: DD_API_KEY_SSM
            value: "/dev/datadog-key"
```

Of course such thing may require use of kube2iam or in case of EKS I think updating IAM role with sufficient permissions would work as well.

**Comment by hkaj** [comment]
Hi @marcincuber 
Thanks for reaching out. I like this idea. It looks simple to implement using the [secret management](https://github.com/DataDog/datadog-agent/blob/master/docs/agent/secrets.md) feature. It may even work directly with the [secret helper script](https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/agent/secrets-helper). Could you try this and let us know if it works? We can document this use case if it does, and improve the script to support SSM if it doesn't.

**Comment by marcincuber** [comment]
Unfortunately, I am not clear how to implement this. Do you how any examples or internal configs that could help me out?

**Comment by dileepfrog** [comment]
@hkaj Am I understanding correctly that the only way to accomplish this is to create a custom Datadog Agent Docker image that mounts an executable capable of reading from SSM?

**Comment by semenodm** [comment]
i don't think you need to do this, if you are using ECS. Following works perfectly well
```
datadog_agent_container_definition = {
    name = "datadog-agent"
    image = "datadog/agent:7.23.1"
    essential = true,
    secrets = [
      {
        name: "DD_API_KEY",
        valueFrom: "arn:aws:ssm:${var.region}:${local.account_id}:parameter/datadog_api_key"
      }
    ]
    environment = [
      {
        name: "ECS_FARGATE",
        value: "true"
      }
    ]
  }
```
