### ISSUE TITLE
Cluster agent clusterchecks command can print sensitive information unredacted

### ISSUE THREAD

**Issue by Firehed** [DataDog/datadog-agent#3397]
**Describe what happened:**
Ran `agent clustercheck` on my cluster agent instance

**Describe what you expected:**
Passwords (and similar sensitive connection info) would be redacted from the output, either by removing the line entirely or printing a redaction message in their place.

**Steps to reproduce the issue:**
Configure a postgres K8S service via autodiscovery (this config method is probably not important)
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    ad.datadoghq.com/service.check_names: '["postgres"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: |-
      [{
        "host": "%%host%%",
        "password":"your-secret-password",
        // snip
```

Run the `agent clustercheck` command

Observe the password rendered in plaintext to the terminal in the corresponding postgres check instance

**Additional environment details (Operating System, Cloud provider, etc):**

GKE; Cluster agent v1.2.0

**Comment by hkaj** [comment]
Hi @Firehed 
Thanks for the report. We have a scrubber that masks this kind of info, but it looks like we don't call in the clustercheck command. We should fix that.

I'll add that to our backlog, but if you or someone else reading this has time to tackle it soon, here's the util you can use to do it: https://github.com/DataDog/datadog-agent/blob/master/pkg/util/log/strip.go

Thanks again

**Comment by ahmed-mez** [comment]
Hi @Firehed 

Thank you for reporting this.
Actually, Agent commands are allowed to show sensitive information as they're all authenticated. The flare however, should never report sensitive data and this is why we're scrubbing credentials using a redacting writer https://github.com/DataDog/datadog-agent/blob/master/pkg/flare/writer.go#L18

Thanks!

**Comment by Firehed** [comment]
I think that's reasonable, but it also seems inevitable that someone will eventually copy+paste that output into a Github issue and leak sensitive credentials.

Ultimately it's up to Datadog on what to do here, but IMO unless there's a very concrete need to show those credentials it would be better to redact them from terminal output too.

**Comment by hkaj** [comment]
We've decided not to scrub it from the terminal output. The only case when this output gets written to disk is when submitting a flare, and the flare command scrubs credentials from every string it writes to disk.

Terminal output is convenient, so we'll keep it unless we hear about concrete security concerns about it.

Thanks again for the report @Firehed
