### ISSUE TITLE
Container Logs Missing - End Of Container Logs Not Captured/Sent To Datadog

### ISSUE THREAD

**Issue by blaines** [DataDog/datadog-agent#3455]
This appears to be a bug of buffers with Docker and the datadog agent logging mechanism.

**Describe what happened:**

We are missing some logs in the Datadog UI because the Datadog Agent failed to capture them.

**Describe what you expected:**

Full log output :)

**Steps to reproduce the issue:**

This one is tricky, but it can be reproduced by sending a bunch of output (over 4KB) from a container, killing it, and comparing the docker logs with the datadog logs. A multi line log configuration is required.

What happens is the agent stops reading the log buffer too soon, and some information is never processed through to Datadog.

I believe the problem lies in this portion of code: https://github.com/DataDog/datadog-agent/blob/2cfefd27891a2b31120c82842ae1bc93617c8491/pkg/logs/input/docker/tailer.go#L165-L169

If the multi line aggregated chunk of logs is sufficiently large, some information will likely be lost. In production, we've seen hundreds, sometimes thousands of lines missing from the end of a container log.

**Additional details**
I made a docker container that ran this script:
```
#!/bin/sh
iii=0
while [ 1 ]
do
  iii=$(($iii+1))
  if [ $(( $iii % 200 )) -eq 0 ]; then
  echo $(date '+%Y-%m-%d %H:%M:%S') newline
  fi
  value=$(($(date +%s%N)/1000000))
  echo $value $iii
  echo $value | sha512sum
done
```
Dockerfile:
```
FROM ubuntu

COPY log.sh .

ENTRYPOINT ["sh", "log.sh"]
```

Used a multi_line docker run configuration as follows:
```
docker run -d -l com.datadoghq.ad.logs='[{"log_processing_rules":[{"type": "multi_line","name": "new_log_start_with_date","pattern": "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
```

**Comment by le-he-hoo** [comment]
Hey @blaines 

Thanks for all the details here.  We are taking a look and will follow-up.

**Comment by le-he-hoo** [comment]
Just following up to confirm that I was able to reproduce.  Thanks again for flagging this.

**Comment by blaines** [comment]
I'm working with the team on ways to resolve this short term

**Comment by brockoffdev** [comment]
Seeing very similar issues on our end as well.

In our case, we are also not only seeing multiline logs not make it, but other logs as well. Not sure if this buffer issue may be causing a problem for downstream logs on the same node as well?

**Comment by le-he-hoo** [comment]
Hey @blaines,
Just wanted to leave a note that a fix will be included in agent 6.12.0.

**Comment by le-he-hoo** [comment]
@brockoffdev This issue is specific to multi-line logs in a particular scenario.  I'd encourage you to open a support ticket with support@datadoghq.com and our support team will be able to take a look!

**Comment by NBParis** [comment]
Hello @blaines Just wanted to let you know that the Agent 6.12 is now officially released and contains the fix.

Please let us know if you have any questions.
