### ISSUE TITLE
Status Object

### ISSUE THREAD

**Issue by gmmeyer** [DataDog/datadog-agent#348]
When I made the status command, I just shoved everything into a map. [As noted during review](https://github.com/DataDog/datadog-agent/pull/315#discussion_r123386474), this should probably be a struct instead.

We deferred on making it into a struct for the moment: there's likely to be some churn in the status command and it's easier to churn everything with the `map[string]interface{}` I have there. But, once things are solidified, we should make this into a type. It's safer to ensure we know what we're getting (at least to some extent).

**Comment by djmitche** [comment]
Outdated at this point (status is mostly handled with strings and templates now)
