### ISSUE TITLE
Datadog Agent v6 Package is huge, and contains files that probably shouldn't be included

### ISSUE THREAD

**Issue by SecurityInsanity** [DataDog/datadog-agent#3542]
**Describe what happened:**

We started installing the datadog-agent v6 from the deb repo; specifically is what is in our sources list:

```
https://apt.datadoghq.com/ stable 6
```

After including a change to install the datadog-agent in our finalized docker image, we realized our image ballooned from 400mb to ~900mb. This is a huge jump for something we only use to monitor our one app (envoy). We also noticed by poking around in the file tree at: `/opt/datadog-agent/` There seem to be a lot of dependencies that really should only be used in a development settings. Some examples of these include:

Linting for python (shouldn't it have already passed linting at this point?):

```
/opt/datadog-agent/bin/pylint
/opt/datadog-agent/bin/epylint
```

Native build tools (are we really live compiling C on our boxes?):

```
/opt/datadog-agent/embedded/bin/automake
/opt/datadog-agent/embedded/bin/autoconf
/opt/datadog-agent/embedded/bin/compile_et
/opt/datadog-agent/embedded/share/aclocal
/opt/datadog-agent/embedded/share/autoconf
/opt/datadog-agent/embedded/share/pkgconfig
```

I'm sure you can find more example of things that are embedded that are probably never used. Moreover it looks like it includes every package it could ever need in build + deploy (keeping it's own copy of python/openssl/etc.)

**Describe what you expected:**

* I expected the final package to be smaller by default so it doesn't blow up my image size.
* I didn't expect it to be adding tools to my system that increase the scope of things I have to watch from a security perspective that are not used.
* I would hope for the ability to build my own version of the package that could utilize system dependencies + only include the deps needed for a specific extension (or set of extensions).

**Steps to reproduce the issue:**

* Install the package from the debian repo.

**Additional environment details (Operating System, Cloud provider, etc):**

OS: Ubuntu 18.04
Cloud provider: AWS

**Comment by SecurityInsanity** [comment]
We're closing this because datadog says they're tracking it internally.

**Comment by piotrekkr** [comment]
> We're closing this because datadog says they're tracking it internally.

What do you mean? Is there a way to slim datadog install? When I Install Datadog inside docker image it size is like +1 GB :/

**Comment by Mythra** [comment]
Hey @piotrekkr ,

When I created this issue I was working for a company that bought datadog, and our support rep had assured us it was on their internal roadmap to be completed, and we could follow up with them through our normal support process at the time.

I mainly commented that for others to know I was just going to contact them there because the response time was better for us.

Unfortunately I no longer work at a company that has DD so I can't tell you what happened , or if there's a solution 😢 sorry!

**Comment by piotrekkr** [comment]
Thank you for your reply. Seems to me that right now it is not possible :( One solution would be to use Datadog agent docker image.

**Comment by tmccombs** [comment]
The v7 package is still really big. /opt/datadog-agent uses up 795M on my ubuntu 20.04 systems. For comparison, /usr only uses 2.6G. So the datadog agent is roughly a third of the size of the rest of my system. Is there any work to make this smaller?

**Comment by lexicalunit** [comment]
Simply installing dd-agent is HUGE:
```shell
du -hs /opt/datadog-agent
788M	/opt/datadog-agent
```

There's **a whole python3.8 installation** in there! 😮 This has made my container image waaaay too big. Is there a solution for this?

For reference this is what I did in my `Dockerfile`:
```
FROM python:3.9-slim

# datadog (https://app.datadoghq.com/account/settings#agent/debian)
RUN echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/99no-install-recommends
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && curl -o /install_script.sh -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh \
    && chmod +x /install_script.sh \
    && DD_API_KEY="fake" DD_INSTALL_ONLY="true" DD_AGENT_MAJOR_VERSION=7 bash -c /install_script.sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
   
[...]
```

**Comment by piotrekkr** [comment]
For now to overcome this huge image issue with GCP we could remove agent from image and then
1. change app so it will pass all logs to container stdout
2. in Compute Engine use datadog agent image as kind of "sidecar" container that can access docker logs (using cloud-init and startup script that is running datadog agent container on instance start)
3. In Cloud Run do not use datadog at all but use log sink to pass logs to datadog intake endpoint directly

**Comment by lexicalunit** [comment]
That's useful for deployment situations where you can have multiple containers running either on the same machine or networked machines. In my case I am able to deploy a container. A single container. Any dependencies must be included in that container.

Since my container already includes python, it seems like there no reason for dd-agent to install a separate python installation. The same goes for any of the "embedded" software in the dd-agent.

It would be nice to be able to install JUST the dd-agent and NONE of the embedded elements. Just document what those embedded dependencies are and let us install them ourselves as needed. Like if there's features I don't need I shouldn't have to install them... right? I think that's a fairly reasonable approach.

**Comment by tmccombs** [comment]
Could this issue be re-opened? Three years later it is still very much a problem. I'd really rather not have my metrics agent using up more disk space than any other package on the system, including the main application. By a lot.

**Comment by besteman** [comment]
Please open this!

**Comment by tmccombs** [comment]
This is getting worse. The size of the v7 package is now up to 1.1GB. Could this be re-opened please?

**Comment by besteman** [comment]
@tmccombs 💯

**Comment by Nllii** [comment]
why is the agent  HUGE?

**Comment by piotrekkr** [comment]
AFAIK you can now try https://registry.hub.docker.com/r/datadog/serverless-init like in [here](https://docs.datadoghq.com/serverless/google_cloud_run/). Idk if this can be used outside of serverless but seems like it should be possible.

I checked size:
```dockerfile
# dockerfile
FROM ubuntu
COPY --from=datadog/serverless-init:1 /datadog-init /app/datadog-init
```
build:
```
docker build -f dockerfile -t datadog-init:dev .
``
result:
```
$ docker run -it --rm datadog-init:dev du -h /app/datadog-init
33M     /app/datadog-init
```
so this one seems small

**Comment by cfstras** [comment]
Please reopen.
`docker inspect gcr.io/datadoghq/agent:7 | jq '.[0].Size / 1024/1024'` lists 1301 MiB - that's unexpectedly high for a container I'd like to run on every single VM instance.

**Comment by piotrekkr** [comment]
@cfstras You can try using [serverless-init](https://registry.hub.docker.com/r/datadog/serverless-init) it should work even with VMs. You can install it inside actual application image as a entrypoint and then configure using env vars like `DD_API_KEY`, `DD_SERVICE` and so on. This should be fine unless you need some feature that only is available in standalone agent.

**Comment by cfstras** [comment]
@piotrekkr thanks for the hint. I've considered and tried serverless-init, but I ran into multiple issues. It doesn't help that there's virtually no documentation available.

I did just find the source though: https://github.com/DataDog/datadog-agent/blob/main/cmd/serverless-init/main.go, so maybe I will give it another shot.

**Comment by piotrekkr** [comment]
> @piotrekkr thanks for the hint. I've considered and tried serverless-init, but I ran into multiple issues. It doesn't help that there's virtually no documentation available.
> 
> I did just find the source though: [`main`/cmd/serverless-init/main.go](https://github.com/DataDog/datadog-agent/blob/main/cmd/serverless-init/main.go?rgh-link-date=2024-07-25T13%3A43%3A12Z), so maybe I will give it another shot.

@cfstras Do you have some specific issues with this tool? I use it everywhere in GCP and I did not get many issues (beside one update that caused logs to not be sent with but it was rolled back). Works okay and I managed to make it send traces, logs and so on with PHP and python containers.

**Comment by cfstras** [comment]
Mainly that it doesn't like being debugged (exits immediately without error messages if you try to use it with bash instead of your worker process), and when you misconfigure it it just exits without any error message as well. But let's not spam this thread any further ;)

**Comment by tmccombs** [comment]
The very limited documentation for it also says it is only supported for Google Cloud Run and Azure Container Apps, neither of which I use.

**Comment by piotrekkr** [comment]
@cfstras Maybe you don't have this script executable like I had once. I've created issue for this [here](https://github.com/DataDog/datadog-agent/issues/27083). 

@tmccombs Idk about only those selected cloud services but at least logs work for me even on localhost when running docker container. Imho serverless-init with logs should work on any cloud or service that can run containers. You can give it a try, should not be much work.

**Comment by tmccombs** [comment]
I use the agent for metrics, not logs.
