### ISSUE TITLE
system-probe fails in agent Dockerfile

### ISSUE THREAD

**Issue by ddspell** [DataDog/datadog-agent#3591]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
dd_agent_1  | starting system-probe
dd_agent_1  | foreground: fatal: unable to exec system-probe: No such file or directory
dd_agent_1  | system-probe exited with code 111, signal 0, restarting in 2 seconds

**Describe what you expected:**
Expected system-probe to start successfully.
system-probe did not get installed in the build using the agent Dockerfile.

**Steps to reproduce the issue:**
Build an image using the agent Dockerfile.
Start a container using the image.
Check the docker logs to see the failure.

**Additional environment details (Operating System, Cloud provider, etc):**
Built image using datadog-agent_6.11.2-1.amd64.deb.

**Comment by sfluor** [comment]
Hi 👋 , thanks you for the report ! It should be fixed when https://github.com/DataDog/datadog-agent/pull/3673 is in 🙂

**Comment by sfluor** [comment]
It should be fixed now 👍 , sorry for the trouble !
