### ISSUE TITLE
Datadog aganet is unable start when i use systemctl restart datadog-agent.service

### ISSUE THREAD

**Issue by sandhyamohanty29** [DataDog/datadog-agent#3596]
Hi,

After enabling "logs_enabled: true: in /etc/datadog-agent/datadog.yaml , and adding below attached parameter, i tried to restart datadog -agent on centos 7. but its not coming up. it fails with below error.

![datadog](https://user-images.githubusercontent.com/38972550/58661750-45973e80-8346-11e9-987d-97a61be9b1f3.PNG)

[root@centos-s-1vcpu-1gb-ams3-01 python.d]# systemctl enable datadog-agent.service
[root@centos-s-1vcpu-1gb-ams3-01 python.d]# systemctl start datadog-agent.service
[root@centos-s-1vcpu-1gb-ams3-01 python.d]# systemctl status datadog-agent.service
● datadog-agent.service - "Datadog Agent"
   Loaded: loaded (/usr/lib/systemd/system/datadog-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2019-05-30 20:06:51 UTC; 4s ago
  Process: 6989 ExecStart=/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid (code=exited, status=255)
 Main PID: 6989 (code=exited, status=255)

May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: datadog-agent.service: main process exited, code=exited, status=255/n/a
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: Unit datadog-agent.service entered failed state.
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: datadog-agent.service failed.
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: datadog-agent.service holdoff time over, scheduling restart.
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: Stopped "Datadog Agent".
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: start request repeated too quickly for datadog-agent.service
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: Failed to start "Datadog Agent".
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: Unit datadog-agent.service entered failed state.
May 30 20:06:51 centos-s-1vcpu-1gb-ams3-01 systemd[1]: datadog-agent.service failed.

note: i am using datadog-agent-6.11.2-1.x86_64 version

**Comment by le-he-hoo** [comment]
Hey @sandhyamohanty29 
I recommend reaching out to support@datadoghq.com so they can look into it a bit more closely.  That way, you'll be able to share your logs and configuration files that you wouldn't necessarily want to post publicly.  

Typically, support will request sending a [flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6), but if you're not able to do so because the agent is encountering an issue that prevents it from running, the team will help identify which configuration files and agent logs will be useful for troubleshooting. Thanks!

**Comment by sangmeshcp** [comment]
hitting the same issue. @le-he-hoo  is this something being worked on ?

**Comment by shivamsinha15** [comment]
having he same issue

**Comment by vladan-me** [comment]
In my case, the issue was that I forgot to delete blank space before
`logs_enabled: true`
Basically, yaml file was not parsed due to error and the line can't start with a blank space.

**Comment by pgmabv99** [comment]
removing of blank space helped. go figure

**Comment by piamaria** [comment]
I have the same issue on HAProxy servers. I have` haproxy.yaml.example `in` /etc/datadog-agent/confd.d/` which I copied to haproxy.yaml.
Do I need to create `haproxy.d `in conf.d then copy `haproxy.yaml` to `conf.d/haproxy.d/`?
Where can I find this line `logs_enabled: true` ?

**Comment by sgnn7** [comment]
> In my case, the issue was that I forgot to delete blank space before
> `logs_enabled: true`
> Basically, yaml file was not parsed due to error and the line can't start with a blank space.

@vladan-me Just a note here that [there is a PR open](https://github.com/DataDog/datadog-agent/pull/7287) for improvements around YAML parsing issues planned for 7.27+ so this should be easier to pinpoint in the future by checking the logs.

**Comment by kmiklas** [comment]
Why don't you just use JSON?

yaml is so picky... it causes a lot of unnecessary headaches.

**Comment by piamaria** [comment]
> Why don't you just use JSON?
> 
> yaml is so picky... it causes a lot of unnecessary headaches.

json? how? by converting yaml to json?

**Comment by piamaria** [comment]
> > In my case, the issue was that I forgot to delete blank space before
> > `logs_enabled: true`
> > Basically, yaml file was not parsed due to error and the line can't start with a blank space.
> 
> @vladan-me Just a note here that [there is a PR open](https://github.com/DataDog/datadog-agent/pull/7287) for improvements around YAML parsing issues planned for 7.27+ so this should be easier to pinpoint in the future by checking the logs.

As I picked this one from another person, I think he didn't install dd agent properly

**Comment by keira-claudette** [comment]
Is there a way to verify the .yaml file after tweaking some configurations? My problem was also solved by deleting the space.

**Comment by rajibbrunel** [comment]
Yeah any kind of space or line make issue

**Comment by bkm71A** [comment]
I have the same issue:
Jan 05 08:01:18 0127-192329-dw152r6r-10-141-74-8 systemd[1]: datadog-agent.service: Scheduled restart job, restart counter is at 5.
Jan 05 08:01:18 0127-192329-dw152r6r-10-141-74-8 systemd[1]: Stopped Datadog Agent.
Jan 05 08:01:18 0127-192329-dw152r6r-10-141-74-8 systemd[1]: datadog-agent.service: Start request repeated too quickly.
Jan 05 08:01:18 0127-192329-dw152r6r-10-141-74-8 systemd[1]: datadog-agent.service: Failed with result 'exit-code'.
Jan 05 08:01:18 0127-192329-dw152r6r-10-141-74-8 systemd[1]: Failed to start Datadog Agent.

**Comment by Kahbeer42** [comment]
When input sudo systemctl start datadog-agent this is what I am getting-
Failed to start datadog_agent.service: Unit datadog_agent.service not found.

**Comment by walosha** [comment]
For anyone facing this issue, it is a problem with the datadog.yaml file and it hard for me to debug. i had to run 
`cat datadog.yaml`
copied the file on my vscode and in a matter of sec my vscode yaml linter figured what the issue was . I hope it helps!

**Comment by Kahbeer42** [comment]
What is the issue I don't understand how you are able to solve it
