### ISSUE TITLE
Unable to get disk metrics for /host/proc/sys/fs/binfmt_misc

### ISSUE THREAD

**Issue by endinthesky** [DataDog/datadog-agent#3600]
Seeing similar errors to #3329

**Describe what happened:**

```
(pkg/collector/py/datadog_agent.go:148 in LogMessage) | (disk.py:114) | Unable to get disk metrics for /host/proc/sys/fs/binfmt_misc: [Errno 40] Too many levels of symbolic links: '/host/proc/sys/fs/binfmt_misc'
```
Huge amounts of these messages on startup/trace messages sent

**Describe what you expected:**

No error

**Additional environment details (Operating System, Cloud provider, etc):**

datadog-agent:latest (6.11.2)

I notice this only happens in a high load environment. Is there anyway to prevent this without changing the config yaml?

Also would be great to know what causes this - why does it only happen under load?

**Comment by DylanLovesCoffee** [comment]
hey @endinthesky! Thanks for opening up this issue. The best way to stop these logs from populating would be to configure the disk check's configuration yaml to blacklist those mount points (as mentioned in the issue you referenced). There's some more information in our doc [here](https://docs.datadoghq.com/agent/faq/host-metrics-with-the-container-agent/#permission-denied-errors) as well. I'm not sure how this might be related to high load environments at the moment, but it may be worth opening a [support ticket](https://docs.datadoghq.com/help/#pagetitle) if you want to investigate this further.

**Comment by Simwar** [comment]
A solution has been provided by @xlucas here: https://github.com/DataDog/datadog-agent/issues/3329#issuecomment-492030202 as well as the issue has been already reported.

Thanks!
