### ISSUE TITLE
Pull in latest integrations-core to fix Apache TLS validation errors

### ISSUE THREAD

**Issue by NoodlesNZ** [DataDog/datadog-agent#3744]
I'm trying to use a fix that was applied in `integrations-core` in April 2019 (https://github.com/DataDog/integrations-core/pull/2475). I'm using the `6.11.3-1` version of the datadog-agent RPM, but I don't see this fix yet in `/embedded/lib/python2.7/site-packages/datadog_checks/apache/apache.py`.

I'm not sure the process here, but I would like to get this fix into production so I can cut down on the amount of noise from datadog agent.

**Comment by DylanLovesCoffee** [comment]
hey @NoodlesNZ - thanks for that contribution! Looks like it was released with [1.6.0](https://github.com/DataDog/integrations-core/blob/master/apache/CHANGELOG.md#160--2019-05-02) in the Apache check, so you can likely run the `datadog-agent integration install datadog-apache==1.6.0` [command](https://github.com/DataDog/datadog-agent/blob/master/docs/agent/integration.md#install) on the agent. Let me know if that works for you.

**Comment by NoodlesNZ** [comment]
Hi, @DylanLovesCoffee I'll give that a go, but I was hoping to get this integration version bundled into the RPM. Will this be bundled into the 6.12 release?

**Comment by DylanLovesCoffee** [comment]
Hey @NoodlesNZ, sorry! Forgot to mention that at the current moment datadog-apache v1.6.0 should be packaged in with v6.12.0 of the agent.

**Comment by NoodlesNZ** [comment]
Thanks, I'll look out for the 6.12.0 RPM when that's built/released.
