### ISSUE TITLE
Unable to fetch logs on google GKE because log files are not where they are expected to be

### ISSUE THREAD

**Issue by rslinckx** [DataDog/datadog-agent#3822]
**Describe what happened:**
Enabling datadog logging for kuberernetes through containers log files on google GKE does not work because the file layout seems different than what the agent expects

**Describe what you expected:**
The agent is looking for file matching /var/log/pods/$POD_UUID/$CONTAINER_NAME.log

See: https://github.com/DataDog/datadog-agent/blob/master/pkg/logs/input/kubernetes/launcher.go#L226

an example path: /var/log/pods/c079422d-e3cb-11e7-8643-000c29573710/calico-node_0.log

On google GKE, the files seem to have a different pattern:

/var/log/pods/kube-system_calico-node-hbdhm_c079422d-e3cb-11e7-8643-000c29573710/calico-node/0.log

Something like /var/log/pods/$POD_NAMESPACE_$POD_NAME_$POD_UUID/$CONTAINER_NAME/x.log

I couldn't find any official source where this path layout is defined, but in any case i'm unable to use datadog-agent to tail those logs, and I have to fallback to docker socket to read logs, with the limitations it incurs.

This repository about customizing log collections in stackdriver/fluentd seem to include this path layout: https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/blob/master/kubernetes/fluentd-configmap.yaml

**Additional environment details (Operating System, Cloud provider, etc):**

Google GKE 1.13

**Comment by hkaj** [comment]
Thanks for the report @rslinckx ! We identified this issue a few days ago and are going to address it asap. It turns out the current path will likely change again soon because it produces directory names that are too long. We will keep monitoring this and try our best to support all 3 paths.
Sorry for the inconvenience.
cc @NBParis

**Comment by xlucas** [comment]
Side note: this pattern may change again since it introduced a bug (https://github.com/kubernetes/kubernetes/issues/80042).
