### ISSUE TITLE
ARM Datadog for monitoring Kubernetes

### ISSUE THREAD

**Issue by efazati** [DataDog/datadog-agent#3839]
**Describe what happened:**
I have a cluster of Kubernetes on an ARM machine ( Nvidia Jetson TX2) that I want to run Datadog agent on it, but I didn't find any Arm docker image to run that

**Describe what you expected:**
I tried to build my docker image for Arm and I followed this instruction https://github.com/DataDog/datadog-agent and docker file
It needs `.deb` file, but I didn't find any pre-build `.deb` file for Arm or any manual to show me how to port `datadog-agent-6` package to arm 

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
I'm using Nvidia Jetson TX2

**Comment by albertvaka** [comment]
Hi @efazati,

We are working on ARM packages targeting 64 bit ARM, so that could work for you once it is released. If you can, could you let me know which version of glibc is present on that board? You can see that by running `ldd --version`.

Albert

**Comment by efazati** [comment]
@albertvaka Thanks
This is my glibc version
```
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
```
When do you think you will release arm package?

**Comment by albertvaka** [comment]
Unfortunately we don't have a release date yet. 

However, if you are interested, I can put you in touch with a product person at DataDog so we can let you know when we have more info on release dates, betas, etc. 

Drop me a line at albert.vaca@datadoghq.com if you are interested.

**Comment by xlucas** [comment]
ARM docker images are being released, starting with 6.15.1. See https://hub.docker.com/r/datadog/agent/tags 😉 .

**Comment by ajaufura** [comment]
Hi @xlucas 
I have used the datadog/agent:latest image on my raspberrypi (Raspberry Pi 4 Model B Rev 1.1, aarch64)
Unfortunately, I am not having metrics on the dashboard for my docker containers only. Any suggestions?
Here is my docker compose file : 

----------------
version: '3'

services:
  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    restart: always
    environment:
      - DD_API_KEY=<my key here>
      - DD_SITE=datadoghq.eu
      - DD_HOSTNAME=raspberrypi
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      #- DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_SYSTEM_PROBE_ENABLED =true
      - DD_PROCESS_AGENT_ENABLED=true

      - DD_CONTAINER_EXCLUDE=image:gcr.io/datadoghq/agent*
      - DD_CONTAINER_EXCLUDE_METRICS=image:gcr.io/datadoghq/agent*
      - DD_CONTAINER_EXCLUDE_LOGS=image:gcr.io/datadoghq/agent*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /etc/passwd:/etc/passwd:ro
      - /sys/kernel/debug:/sys/kernel/debug
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    security_opt:
      - apparmor:unconfined
