### ISSUE TITLE
Forwarder blocks when trying to stop while retry queue is big

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/datadog-agent#388]
Follow-up to #363 (explains why the agent can't stop cleanly)

**Steps to reproduce the issue:**
1. Forwarder has a very large retry queue
2. Try to stop the agent
3. The forwarder is blocked on trying to stop the retries (when trying to write to the stopRetry channel https://github.com/DataDog/datadog-agent/blob/252e5f9f90178edf7ec90a5642b14f85d5596ba9/pkg/forwarder/forwarder.go#L208)

See attached file for (shortened) list of goroutines on an agent experiencing this (obtained with `delve`): [delve_goroutines.txt](https://github.com/DataDog/datadog-agent/files/1154241/delve_goroutines.txt)

**Comment by masci** [comment]
Does this still apply after merging https://github.com/DataDog/datadog-agent/pull/432?

**Comment by olivielpeau** [comment]
This should be fixed indeed (this particular issue may have been fixed even before #432 actually).

Anyway, closing 👍
