### ISSUE TITLE
Agent6 version recommended in README does not exist

### ISSUE THREAD

**Issue by selinaleung** [DataDog/datadog-agent#3898]
In the suggested version number of agent6 from this section of the [readme](https://github.com/DataDog/chef-datadog#downgrade-from-an-installed-agent-v6-to-an-agent-v5), the tag does not exist as a release in this repo.

**Comment by OlivierGaca** [comment]
Hello @selinaleung,

Thank you for reporting this issue. 
What is your operating system? The version `5.32.0-1` exists as msi, rpm and deb files.

**Comment by hush-hush** [comment]
Hi @selinaleung,

Agent version 5 lives in a different repository (here: https://github.com/DataDog/dd-agent, tag from the example in the chef repo https://github.com/DataDog/dd-agent/releases/tag/5.32.0). You should use the latest version of Agent 5: 5.32.4 if possible.

I'm closing this issue but feel free to reopen it if needed !

Thanks.
