### ISSUE TITLE
[cluster-agent] Valid metric with values in DD but zero value from cluster agent 

### ISSUE THREAD

**Issue by salmaanrizvi** [DataDog/datadog-agent#3945]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.
==============================
Datadog Cluster Agent (v1.2.0)
==============================

  Status date: 2019-07-26 17:30:29.567125 UTC
  Pid: 1
  Logs:
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog-cluster.yaml
    conf.d: /etc/datadog-agent/conf.d

  Clocks
  ======
    System UTC time: 2019-07-26 17:30:29.567125 UTC

  Hostnames
  =========
    ec2-hostname: ip-10-105-67-135.us-west-2.compute.internal
    hostname: i-04bcc217ad9b6ab6c
    instance-id: i-04bcc217ad9b6ab6c
    socket-fqdn: datadog-cluster-agent-7fbb475d4-8l8jr
    socket-hostname: datadog-cluster-agent-7fbb475d4-8l8jr
    hostname provider: aws
    unused hostname providers:
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

  Leader Election
  ===============
    Leader Election Status:  Running
    Leader Name is: datadog-cluster-agent-7fbb475d4-8l8jr
    Last Acquisition of the lease: Tue, 23 Jul 2019 07:25:37 UTC
    Renewed leadership: Fri, 26 Jul 2019 17:30:27 UTC
    Number of leader transitions: 19 transitions

  Custom Metrics Server
  =====================
    ConfigMap name: kube-system/datadog-custom-metrics

    External Metrics
    ----------------
      Total: 1
      Valid: 1
      hpa:
      - name: api-payment-test-hpa
      - namespace: service-payment
      - uid: 5e8d722a-afca-11e9-8b9a-0ae159aa9fb8
      labels:
      - environment: dev-us-west-2
      metricName: api_payment_incoming_resource_filter_by_legacy_failure
      ts: 1.56416217e&#43;09
      valid: true
      value: 0

  Cluster Checks Dispatching
  ==========================
    Status: Leader, serving requests
    Active nodes: 32
    Check Configurations: 0
      - Dispatched: 0
      - Unassigned: 0

=========
Collector
=========

  Running Checks
  ==============

    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Total Runs: 19,703
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 25,292
      Service Checks: Last Run: 3, Total: 59,100
      Average Execution Time : 182ms

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 19,702
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 8,484
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 47,888
    TimeseriesV1: 19,702

  API Keys status
  ===============
    API key ending with 28e55: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 28e55
```

Curling the metric directly yields the same:
```
[10:34:38] ~ $ kc get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/service-payment/api_payment_incoming_resource_filter_by_legacy_failure" | jq
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/service-payment/api_payment_incoming_resource_filter_by_legacy_failure"
  },
  "items": [
    {
      "metricName": "api_payment_incoming_resource_filter_by_legacy_failure",
      "metricLabels": {
        "environment": "dev-us-west-2"
      },
      "timestamp": "2019-07-26T17:34:39Z",
      "value": "0"
    }
  ]
}
```

As well as the configmap:
```
[10:34:38] ~ $ kc describe cm -n kube-system datadog-custom-metrics
Name:         datadog-custom-metrics
Namespace:    kube-system
Labels:       <none>
Annotations:  custom-metrics.datadoghq.com/last-updated: 2019-07-26T17:59:22Z

Data
====
external_metric-service-payment-api-payment-test-hpa-api_payment_incoming_resource_filter_by_legacy_failure:
----
{"metricName":"api_payment_incoming_resource_filter_by_legacy_failure","labels":{"environment":"dev-us-west-2"},"ts":1564163910,"hpa":{"name":"api-payment-test-hpa","namespace":"service-payment","uid":"5e8d722a-afca-11e9-8b9a-0ae159aa9fb8"},"value":0,"valid":true}
Events:  <none>
```

However, in the Metrics Explorer, I can see the metric being posted 

<img width="1048" alt="Screen Shot 2019-07-26 at 10 35 13 AM" src="https://user-images.githubusercontent.com/1084185/61970270-4688cd00-af91-11e9-93c4-1512e7f34fff.png">

**Describe what happened:**

I was able to go through the example to setup a dummy nginx server, register the cluster agent as the source for external metrics and scale an HPA off of nginx's requests per second metric, but when turning to custom application metrics posted to DD, the external metrics serve is always responding with a value of 0 and therefore having no affect.

**Describe what you expected:**
I am able to see the metric with correct values posted in the metrics explorer on the DD dashboard and I expected the cluster agent to be reporting the same value, but instead it always reports zero.

Here is the HPA yaml:

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-payment-test-hpa
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-payment
  metrics:
  - type: External
    external:
      metricName: api_payment_incoming_resource_filter_by_legacy_failure
      metricSelector:
        matchLabels: 
          environment: dev-us-west-2
      targetValue: 2
```

**Additional environment details (Operating System, Cloud provider, etc):**

Running on AWS EKS, and kc version:

```
[11:13:09] ~ $ kc version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by CharlyF** [comment]
Hey @salmaanrizvi thanks for opening this issue!
My guess is that the value is actually inferior to 1. Looking at the screenshot of the metric you sent, as you clicked on the "view as a count" you see the metric `.as_count()` but if you uncheck the box the value would be < 1.
Now, as you are using the Cluster Agent 1.2.0, we did not support milliquantities so 0.5 would be exposed as 0.
This was implemented in the version 1.3.0 https://github.com/DataDog/datadog-agent/pull/3090
But I recommend using the latest version 1.3.2.

If you can confirm that the value of the metric, not computing as a count, is > 1 and that updating the Cluster Agent does not help, feel free to reach out to [our Solution team](mailto:support@datadoghq.com).

Best,
.C

**Comment by salmaanrizvi** [comment]
Hi Charly-

Thanks for that quick reply. Your intuition was right, it was below 1 when looking at it as a rate. Would that be documented anywhere? Also, what marks a metric as valid as reported by the cluster agent? Is there a list documented list of supported metric types that the cluster agent can report back to the HPA for autoscaling? I think I saw gauges in beta, but is everything else valid?

**Comment by CharlyF** [comment]
👋 
Glad to hear!

> Would that be documented anywhere? 

I am not sure where to find the specific doc for this button, but I believe [this doc](https://docs.datadoghq.com/graphing/faq/why-is-a-counter-metric-being-displayed-as-a-decimal-value/#pagetitle) should shed some light on the matter.

> What marks a metric as valid as reported by the cluster agent?

The timestamp of the last datapoint, by default anything older than 5 minutes (configurable) is considered too old and therefore will not be exposed to the HPA controller.
This is to avoid incorrect scaling events.

>  Is there a list documented list of supported metric types that the cluster agent can report back to the HPA for autoscaling? 

All metrics can be used, but no custom method (such as as_count etc) can be used. The metric you are using seems to be a custom one, so it is only a matter of changing int's type, either in the app or in the code where you generate it. See [here](https://docs.datadoghq.com/developers/metrics/#modify-a-metric-s-type) for more details

>I think I saw gauges in beta, but is everything else valid?

It is probably a different feature because as said above, all metrics types are supported, but they can't be transformed on the fly. Were you thinking about [metrics without limits](https://www.datadoghq.com/blog/dash-2019-new-feature-roundup/#metrics-without-limits) maybe ?

**Comment by salmaanrizvi** [comment]
Thanks for all that info - all of it was super helpful.

> > I think I saw gauges in beta, but is everything else valid?
> 
> It is probably a different feature because as said above, all metrics types are supported, but they can't be transformed on the fly. Were you thinking about [metrics without limits](https://www.datadoghq.com/blog/dash-2019-new-feature-roundup/#metrics-without-limits) maybe ?

I've been reading a lot of docs so things are getting mixed up but I actually think I was referring to [distributions](https://docs.datadoghq.com/graphing/metrics/distributions/)

**Comment by CharlyF** [comment]
Sounds good! Glad to hear that you are all set.
I'm going to close this but feel free to reach out anytime.

Best,
.C
