### ISSUE TITLE
No logs from short-lived (non-Kubernetes) containers

### ISSUE THREAD

**Issue by masterful** [DataDog/datadog-agent#3955]
I've been having difficulty retrieving logs from short-lived containers. I recognize there's been some effort recently to improve this situation for Kubernetes based systems in #3372 - however, for those not on Kubernetes (like my team) our containers are still not showing logs. #3930 will help slightly, but for truly short-lived containers it's still possible for them to be missed.

Is it possible to look into scheduling at least one log collection for dead containers? From the discussion in #3930 it sounds like it should be feasible, but will need some investigation. I thought I'd open a ticket to ensure discussion happens in a more appropriate thread 😄 

**Steps to reproduce the issue:**
I have the datadog agent to forward logs for all containers that have a service defined, and use the following command on an ECS instance to mimic a short-lived container:
```bash
docker run \
  --label "com.datadoghq.ad.logs=[{\"source\": \"testing\", \"service\": \"testing\"}]" \
  --label "com.amazonaws.ecs.cluster=staging" \
  --label "com.amazonaws.ecs.container-name=testing" \
  alpine \
  ping -c1 google.com
```
Changing the command to `ping -c10 google.com` causes the logs to be picked up and collected, but a truly short-lived container does not have its logs collected 😢.

The current workaround is to have a script as the entrypoint/command for our containers that executes a `sleep` at the end so that regardless of exit status, the logs have a chance to be picked up. This is obviously far from ideal, though.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS ECS

**Comment by NBParis** [comment]
Hello @masterful ,

Thanks for submitting this. This is true that currently for pure docker environment the lowest time interval [the Datadog Agent can set is currently 1 second](https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/?tab=dockersocket#short-lived-containers) and therefore any container that has a slower life time could be missed (currently you have to change the parameter to 1s until the PR you linked gets merged).

Adding a sleep to your container is indeed a workaround but as you say, it's far from ideal and we can all agree on this.

We are currently looking at how we collect Docker logs and how we could improve it to collect logs from dead container. 

We will make sure to update that thread with our findings. But feel free to let us know if you have any ideas or suggestions.
