### ISSUE TITLE
Json output not formatted correctly when message contains json

### ISSUE THREAD

**Issue by ncrothe** [DataDog/datadog-agent#3978]
**Describe what happened:**
We're running DataDog agent on kubernetes and have enabled `DD_LOG_FORMAT_JSON:                        true` to output DataDog's log in json format for further processing by FluentD.
We are getting json output, but some records are invalid json due to missing encoding of json inside the message string.

An example event:
`{"agent":"core","time":"2019-08-07 11:43:07 UTC","level":"ERROR","file":"pkg/collector/runner/runner.go","line":"294","func":"work","msg":"Error running check prometheus: [{"message": "HTTPConnectionPool(host='prometheus-server', port=80): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8ae60c7290>: Failed to establish a new connection: [Errno -2] Name or service not known',))", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py\", line 884, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/prometheus/base_check.py\", line 109, in check\n    ignore_unmapped=True,\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/prometheus/mixins.py\", line 398, in process\n    for metric in self.scrape_metrics(endpoint):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/prometheus/mixins.py\", line 362, in scrape_metrics\n    response = self.poll(endpoint)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/prometheus/mixins.py\", line 533, in poll\n    endpoint, headers=headers, stream=False, timeout=self.prometheus_timeout, cert=cert, verify=verify\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nConnectionError: HTTPConnectionPool(host='prometheus-server', port=80): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8ae60c7290>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n"}]"}`

**Describe what you expected:**
Valid json output that can be processed further.

**Steps to reproduce the issue:**
- Deploy latest cluster agent
- Make log events happen that have json in their message (no clear repro)

**Additional environment details (Operating System, Cloud provider, etc):**
We're running datadog/agent:latest-jmx with DD_LOG_FORMAT_JSON enabled. Container is running in kubernetes on AWS EKS.

**Comment by dabcoder** [comment]
Hello @ncrothe, thanks for reporting this issue. We're working on fixing this, apologies for the inconvenience in the meantime.

**Comment by hush-hush** [comment]
Hi @ncrothe,

I opened a PR to fix this [here](#4004). This should be available in the next release `6.14.0`.
