### ISSUE TITLE
[Question | Feature] If datadog agent can report which exactly ip addresses are currently blocked by AWS WAF.

### ISSUE THREAD

**Issue by apolegoshko** [DataDog/datadog-agent#4108]
Hi there!

Related to [this](https://docs.datadoghq.com/integrations/amazon_waf/) documentation I didn't find the metric/parameter which is responsible for reporting which exactly ip address(es) is(are) currently blocked by AWS WAF and report it to Datadog.

Could you please advice if it is even possible to report info about currently blocked ip address to Datadog ?

The initial idea is to create a dashboard with currently blocked by AWS WAF ip addresses.

Thanks.

**Comment by olivielpeau** [comment]
Hi @apolegoshko,

The AWS WAF is not Agent-based but crawler-based, so please refer your questions to support@datadoghq.com. For reference, the official Agent-based integrations are available in the [integrations-core](https://github.com/DataDog/integrations-core) repo.

To answer your question, reporting info about currently-blocked IP addresses is not supported by the integration out-of-the-box as AWS WAF Cloudwatch metrics do not expose this information (see https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html).
That said, there is a tutorial on the AWS docs, where there is a sample Lambda function that publishes a custom metric to CloudWatch, which includes IP addresses blocked https://docs.aws.amazon.com/waf/latest/developerguide/tutorials-4xx-blocking.html.

For any further question, feel free to send an email to support@datadoghq.com. I'll go ahead and close this issue.
