### ISSUE TITLE
Alibaba metadata collection attempt on AWS hosts.

### ISSUE THREAD

**Issue by michaelpporter** [DataDog/datadog-agent#4316]
**Describe what happened:**
We have repeated errors in our Darktrace logs that Datadog tries to get Alibaba metadata on AWS hosts. [code link](https://github.com/DataDog/datadog-agent/blob/4b7c7b8213d0848115d565940b86e1e915c1274b/pkg/util/alibaba/alibaba.go#L20)

**Describe what you expected:**
Detect once which host we are on, or a flag to limit metadata checks to provider. 

**Steps to reproduce the issue:**
All installs on our hosts have the issue

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu and Amazon Linux on AWS

**Comment by shermdog** [comment]
Hi @michaelpporter 

I believe this should be resolved as of [7.20.0 / 6.20.0](https://github.com/DataDog/datadog-agent/blob/master/CHANGELOG.rst#7200--6200) with the `cloud_provider_metadata` setting.

Please let me know if this resolves your issue

**Comment by michaelpporter** [comment]
Thank you, we will test it out when we can.
