### ISSUE TITLE
K8S pod logs are not tagged

### ISSUE THREAD

**Issue by calvinbui** [DataDog/datadog-agent#4320]
**Describe what happened:**
Short-lived cronjob pods (less than 10 seconds) and deployment pods are sometimes not tagged correctly in Datadog.

In this example below, I have a cronjob that runs every 2 mins but only half of the pods have the correct tags such as "Pod Name" and other labels I'm setting. It is not specific to any node.

![image](https://user-images.githubusercontent.com/3604363/66974521-0d22b200-f0e7-11e9-8ac8-4d2795689aa7.png)

Incorrect:
![image](https://user-images.githubusercontent.com/3604363/66974926-77882200-f0e8-11e9-930c-9a485ef80962.png)

Correct:
![image](https://user-images.githubusercontent.com/3604363/66974934-7eaf3000-f0e8-11e9-8549-7f356cdbbfc1.png)

For deployments, logs may be tagged correctly for roughly ~12 log entries.

I have switched between the Docker socket and K8S File method of log collection and both have this issue. The Docker socket is worse and sometimes misses the logs completely.

**Describe what you expected:**

All logs to be captured and tagged correctly. We can miss issues that happen in production.

**Steps to reproduce the issue:**

Run a short-lived cronjob from Kubernetes and watch the logs coming in.

**Additional environment details (Operating System, Cloud provider, etc):**

- Datadog Agent 6.14.1
- Google Kubernetes Engine

Pod YAML
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ad.datadoghq.com/snapshot.logs: '[{"source":"kubernetes","service":"campaigns"}]'
...
spec:
  containers:
  - name: snapshot
```

Environment variables:
```
DD_APM_ENABLED: "false"
DD_COLLECT_KUBERNETES_EVENTS: "false"
DD_EXCLUDE_PAUSE_CONTAINER: "false"
DD_KUBERNETES_POD_LABELS_AS_TAGS: '{"environment":"environment","process":"process","service":"service"}'
DD_LEADER_ELECTION: "false"
DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE: "true"
DD_LOGS_ENABLED: "true"
KUBERNETES: "true"
```

**Comment by zbutt-muvaki** [comment]
i am experiencing the exact same issue! settings are identical... 

agent version is

```
Agent 6.15.1 - Commit: 44c5066 - Serialization version: 4.14.0 - Go version: go1.12.9
```

**Comment by calvinbui** [comment]
@zbutt-muvaki datadog/agent-dev:6-15-1-logs fixed the issue.
