### ISSUE TITLE
docker image for datadog/agent:6.15.0-jmx missing ?

### ISSUE THREAD

**Issue by grosser** [DataDog/datadog-agent#4381]
https://hub.docker.com/r/datadog/agent/tags?page=1&name=jmx

... should be automatically created when a new tag is pushed ?

**Comment by olivielpeau** [comment]
Hi @grosser, sorry for the confusion here, the `6.15.0` tag you saw was pushed to test our internal build systems, but would not trigger an actual release. The 6.15.0 release is still in the RC phase at the moment.

You can follow the actual stable releases of the Agent by [watching the releases](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository) on the present Github repo, or by looking at the [releases Github page](https://github.com/DataDog/datadog-agent/releases) (this page also shows all the _tags_ on the repo, so you'll want to only look at the tags that have release notes attached, for example: https://github.com/DataDog/datadog-agent/releases/tag/6.14.1).

Hope this helps, I'll go ahead and close the issue but feel free to follow up here if you have any questions or comments, thanks!
