### ISSUE TITLE
DD Agent autodiscovery not scraping Prometheus/opentracing metrics from application

### ISSUE THREAD

**Issue by themac13** [DataDog/datadog-agent#4382]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
We have an application that exposes metrics at :80/metrics running in AKS

We annotate the deployment of the application deployment 

    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '443'
        ad.datadoghq.com/appName.check_names: '["openmetrics"]'
        ad.datadoghq.com/containerName.init_configs: '[{}]'
        ad.datadoghq.com/containerName.instances: '[{"prometheus_url": "http://%%host%%:%%port%%/metrics","namespace": "containerName","metrics": {["http*","dotnet*","process*"]},"health_service_check": "true","tags": ["env:prod","region:eastus","branch:master"],"send_distribution_buckets": "true","send_histogram_buckets": "true","send_monotonic_counter": "true"}]'

The metrics is being detected my prometheus deployment via autodiscovery, and I can browse them fine. However, it is not detected by the DD agent in the checks and not sent to DD. 

We also annotated our nginx ingress controller and that too is not discovered by DD agent.

**Describe what you expected:**

Metrics should be autodiscovered and sent to DD.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

DD deamonset deployment:
```

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      serviceAccountName: datadog-agent
      containers:
      - image: datadog/agent:latest
        imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            # Custom metrics via DogStatsD - uncomment this section to enable custom metrics collection
            # hostPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            # Trace Collection (APM) - uncomment this section to enable APM
            hostPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_LOG_LEVEL
            value: "debug"
          - name: DD_EXTRA_CONFIG_PROVIDERS
            value: "endpointschecks"
          - name: DD_APM_NON_LOCAL_TRAFFIC
            value: "true"
          - name: DD_PROCESS_AGENT_ENABLED
            value: "true"
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: api-key
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: KUBERNETES
            value: "true"
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_APM_ENABLED
            value: "true"
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          - name: DD_AC_EXCLUDE
            value: "name:datadog-agent"
        resources:
          requests:
            memory: "768Mi"
            cpu: "400m"
          limits:
            memory: "768Mi"
            cpu: "400m"
        volumeMounts:
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: pointerdir
            mountPath: /opt/datadog-agent/run
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 60
          periodSeconds: 35
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointerdir
        - hostPath:
            path: /etc/passwd
          name: passwd
```

Am I missing out something? Should I did not specify any custom checks, because from my understanding that autodiscovery will discover the metrics based on the annotations? Am I missing a setting somewhere? I wasn't able to get a clear answer from DD support so I thought of posting here to get additional eyes on this. 

Thanks in advance!

**Comment by DylanLovesCoffee** [comment]
Hey @themac13, the first thing I would confirm is that where you have `appName` and `containerName` in your annotations, _both_ the "container identifiers" match up with `.spec.containers[0].name`. So it should look something like the following if your container name was `aks-app`:

```yml
annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '443'
    ad.datadoghq.com/aks-app.check_names: '["openmetrics"]'
    ad.datadoghq.com/aks-app.init_configs: '[{}]'
    ad.datadoghq.com/aks-app.instances: '[{"prometheus_url": "http://%%host%%:%%port%%/metrics","namespace": "containerName","metrics": {["http*","dotnet*","process*"]},"health_service_check": "true","tags": ["env:prod","region:eastus","branch:master"],"send_distribution_buckets": "true","send_histogram_buckets": "true","send_monotonic_counter": "true"}]'
```

Alternatively, running `kubectl exec -it <datadog-agent-pod> agent configcheck` should allow you to see if that check is autodiscovered at all, and if the agent was able to successfully resolve the configuration.

**Comment by themac13** [comment]
Hi, 

Yes, they are all matching. metadata.name, .spec.container.name, and lastly labels.name too.

I ran that command on the master node of the daemon set, and I can confirm that no I do not see the app or the metrics or openmetrics or even prometheus.

**Comment by DylanLovesCoffee** [comment]
Thanks for checking @themac13. Could you open up a [support ticket](https://docs.datadoghq.com/help/) and send the following: 
- a debug log level [flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6#pagetitle) (you'll want to pass in `DD_LOG_LEVEL=debug` to the agent Daemonset first and allow it to run for several minutes to collect logs
- the full application manifest where you've applied those autodiscovery annotations

It'll be useful to the support engineer if you reference this Github issue in the ticket as well so they have the full context :)

**Comment by themac13** [comment]
I do have a ticket open but I have not gotten any fix for it.

266563

I sent another flare, to see if anything else helps.

Lukman

**Comment by DylanLovesCoffee** [comment]
Thanks Lukman. When possible, some debugging on the agent side that might help: 

1. `kubectl exec -it <datadog-agent> bash` 
2. `tail -f /var/log/datadog/agent.log | grep <aks-deploy-container-name>`

If there are any JSON parsing errors, it should be raised by the agent to indicate such.

**Comment by themac13** [comment]
I found the issue, should be | instead of /. Documentation was misleading

**Comment by erikkri** [comment]
where did you replace / with | ? In the url?

**Comment by DylanLovesCoffee** [comment]
@erikkri The reference to changing `/` to `|` is within the pod annotations. The pipe symbol indicates multi-line in YAML: 
```
ad.datadoghq.com/aks-app.check_names: /
```
V
```
ad.datadoghq.com/aks-app.check_names: |
```
