### ISSUE TITLE
cluster-agent component does not appear to support ENC[] Secrets

### ISSUE THREAD

**Issue by wilreichert** [DataDog/datadog-agent#4407]
I've successfully implemented the Secrets Management process described [here](https://docs.datadoghq.com/agent/guide/secrets-management/) on our agents running in kubernetes. Its currently using our Hashi Vault backend to supply the API_KEY as confirmed by the following

```
$ k exec -i -t -n datadog datadog-lklp5 -- agent secret
=== Checking executable rights ===
Executable path: /scripts/secrets_backend.py
Check Rights: OK, the executable has the correct rights

Rights Detail:
file mode: 100700
Owner username: root
Group name: root

=== Secrets stats ===
Number of secrets decrypted: 1
Secrets handle decrypted:
- datadog_api_key: from datadog.yaml
```

Unfortunately now the cluster-agent is failing with the following error:
```
2019-11-05 01:38:27 UTC | CLUSTER | ERROR | (pkg/forwarder/transaction.go:179 in Process) | API Key invalid, dropping transaction for https://1-3-2-app.agent.datadoghq.com/api/v1/check_run?api_key=ENC[datadog_api_key]
```

Additionally there is no 'agent' subcommand on the cluster-agent cli.

My primary question is "Does the cluster agent support decoding secrets via the ENC notation?" My feeling based on digging though github is no but I'd like official confirmation.

If it is supported is there any documentation which describes the specific configuration for the cluster agent to make it work?

If it is not supported on the cluster agent what is the recommended configuration? We do use several annotation based cluster checks which I believe require the cluster agent to work properly.

**Comment by CharlyF** [comment]
Hey @wilreichert - Thanks for opening this!
We should support this indeed, I will sync with the team so we can confirm the issue and fix it if necessary.
We will post an update here as soon as possible.
Best,
.C

**Comment by djtecha** [comment]
Is this still an outstanding issue? Just waded through the complex documents to get cluster_agent running for mysql checks only to find I can't protect the password?

**Comment by CharlyF** [comment]
Hi @djtecha - Apologies for the delay. Yes this is supported I forgot to close the issue. 
We also added [this](https://github.com/DataDog/datadog-agent/pull/4639) to provide an example/boilerplate, but you can use any executable with the var:

```
- name: DD_SECRET_BACKEND_COMMAND
  value: /readsecret.sh
- name: DD_SECRET_BACKEND_ARGUMENTS
  value: /etc/secrets
```

I am going to close this, but feel free to re-open if you encounter any issue.

Best,
.C
