### ISSUE TITLE
[AD] port/deprecate Agent5 SD features

### ISSUE THREAD

**Issue by xvello** [DataDog/datadog-agent#443]
Here's a list of the features / edge cases found in the Agent5 codebase. I think we should aim for sanity over feature parity, but listing them all will allow us to better communicate on what we deprecate. This issue can be closed once all tracking cards are created.

Please directly update the issue itself to strike items when ported or deprecated.

# Common
- ✅ ~~[Docker inspect caching](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L39)~~ 
- ✅ [Optional template tokens](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345):
  - ✅ [%%pid%%](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L165)
  - [%%host[n]%%](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L173)
    - ✅ [extract IP from docker networks](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345)
    - [extract IP from K8 pod info](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345)
    - [extract IP from Rancher 1.x container label](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345)
  - [%%port[n]%%](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L243)
  - 🔥 [%%container-name%%](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L341)
  - 🔥 [%%tags%%](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345) : `node_name`, `pod_name`, `kube_container_name` : should we rename / split up / deprecate ?
- [Reload changed containers](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L125): two use cases:
  - 🔥 ~~used by `docker_daemon.py` for new and deleted containers → superseeded by DockerListener~~ 
  - used by `kubernetes.py` to refresh `kube_service` tags → study alternatives
  - not used when K/V store templates are updated, full reload
- [Full AD reload and re-match](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_sd_backend.py#L26) mechanism. Used for [reload after k/v store changes](https://github.com/DataDog/dd-agent/blob/5.16.x/agent.py#L343)
- ✅ [Container tags from docker + orchestrators](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345)
- [Support several instances of one check per template](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L345)
- ✅ [Pluggable detection backend](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_sd_backend.py) → `ServiceListener` interface
- [Keep track of the template source (file/annotation/template)](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L290) for display in `checkconf`
- `is_jmx` [only work for file templates, not annotations / k/v store](https://trello.com/c/5ZPGCpym/285-jmx-service-discovery-doesnt-support-isjmx-true), should be solved

## Auto_conf mode
- ✅ [Templates as yaml files]()
- [Templates in Kubernetes annotations](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L212) and [in Docker labels](https://github.com/DataDog/dd-agent/pull/3451) : overrides template file lookup
- [Providing a `com.datadoghq.sd.check.id` docker label to override image name](https://github.com/DataDog/dd-agent/blob/5.16.0/utils/service_discovery/sd_docker_backend.py#L27)
- [Matches short image name only (no prefix / tag)](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L231), should be changed to long-or-short

## K/V store mode

- ✅ [Pluggable k/v store sources](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/config_stores.py) → `ConfigProvider` interface
- [Support several checks in one template](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L226)
- [Fallback to auto_conf templates if k/v does not match](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L129)
- [Lookups long name, then short image name (no prefix / tag)](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L320). Final lookup order is k/v-long, autoconf-long, k/v-short, autoconf-short
- Annotations are [ignored in k/v mode](https://github.com/DataDog/dd-agent/blob/5.16.x/utils/service_discovery/abstract_config_store.py#L274), should that still be the case?

**Comment by masci** [comment]
@xvello this seems outdated, can we close?

**Comment by xvello** [comment]
Indeed, added a backlog item for the last one: rancher IP

**Comment by andrewlouis93** [comment]
@xvello Used to use the following in a check's tag list to extract `pod_name`

>  %%tags%% : node_name, pod_name, kube_container_name : should we rename / split up / deprecate ?

Reading through the v6 codebase trying to grok what the alternative in v6 looks like - do you have any input?
