### ISSUE TITLE
DataDog intermittent failure when install using PowerShell script

### ISSUE THREAD

**Issue by chinkung** [DataDog/datadog-agent#4463]
**Output of the info page (if this is a bug)**
```
No output since DataDog installation failure
```

**Describe what happened:**
Installation finish with **Failed to create DD user**  error some time (This part from MSI installation verbose log)

> CA: FinalizeInstall:  Initialized.   
CA: FinalizeInstall:  Creating/opening subkey installRollback   
CA: FinalizeInstall:  Creating/opening subkey uninstallStatus   
CA: FinalizeInstall:  checking if this is a domain controller   
CA: FinalizeInstall:  machine is type SV_TYPE_WORKSTATION   
CA: FinalizeInstall:  machine is type SV_TYPE_SERVER   
CA: FinalizeInstall:  checking to see if the user is already present   
CA: FinalizeInstall:  checking to see if the service is installed   
CA: FinalizeInstall:  Requested service does not exist   
CA: FinalizeInstall:  custom action initialization complete.  Processing   
CA: FinalizeInstall:  Took 1 passes to generate the password   
CA: FinalizeInstall:  entered createuser   
CA: FinalizeInstall:  Calling NetUserAdd.   
CA: FinalizeInstall:  NetUserAdd. 2245   
CA: FinalizeInstall:  Failed to create DD user   
CustomAction FinalizeInstall returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Describe what you expected:**
Installation finish without any error (This part from MSI installation verbose log)

> CA: FinalizeInstall:  Initialized.	
CA: FinalizeInstall:  Creating/opening subkey installRollback	
CA: FinalizeInstall:  Creating/opening subkey uninstallStatus	
CA: FinalizeInstall:  checking if this is a domain controller	
CA: FinalizeInstall:  machine is type SV_TYPE_WORKSTATION	
CA: FinalizeInstall:  machine is type SV_TYPE_SERVER	
CA: FinalizeInstall:  checking to see if the user is already present	
CA: FinalizeInstall:  checking to see if the service is installed	
CA: FinalizeInstall:  Requested service does not exist	
CA: FinalizeInstall:  custom action initialization complete.  Processing	
CA: FinalizeInstall:  Took 2 passes to generate the password	
CA: FinalizeInstall:  entered createuser	
CA: FinalizeInstall:  Calling NetUserAdd.	
CA: FinalizeInstall:  NetUserAdd. 0	
CA: FinalizeInstall:  Got SID from ...
CA: FinalizeInstall:  Privilege added	
CA: FinalizeInstall:  Privilege added	
CA: FinalizeInstall:  Privilege added	
CA: FinalizeInstall:  Privilege added	
CA: FinalizeInstall:  Got account from sid from BUILTIN	
CA: FinalizeInstall:  Attempting to add to group Performance Monitor Users	
CA: FinalizeInstall:  Added ddagentuser to Performance Monitor Users	
CA: FinalizeInstall:  Got account from sid from BUILTIN	
CA: FinalizeInstall:  Attempting to add to group Event Log Readers	
CA: FinalizeInstall:  Added ddagentuser to Event Log Readers	
CA: FinalizeInstall:  User profile set to: C:\Users\ddagentuser	
CA: FinalizeInstall:  attempting to install services	
CA: FinalizeInstall:  Installing services
.
.
.

**Steps to reproduce the issue:**
1. Install DataDog using this command in PowerShell
```
$DDInstallationFile = "$env:TEMP\ddagent.msi"

Invoke-WebRequest -Uri "https://s3.amazonaws.com/ddagent-windows-stable/datadog-agent-6-latest.amd64.msi" -OutFile $DDInstallationFile

Start-Process -Wait msiexec -ArgumentList "/qn /i $DDInstallationFile" -NoNewWindow
```

**Additional environment details (Operating System, Cloud provider, etc):**
Windows Server 2016 Datacenter on AWS, build using Packer by HashiCorp, connect to instance via WinRM to perform installation by PowerShell

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue happens randomly when run on the same Windows AMI

**Comment by william-chen-iress** [comment]
We are experiencing this intermitten failure too. Any possible solution?

**Comment by chinkung** [comment]
I generate random password myself to make it meet with host's password policy and override password via DataDog MSI installation parameter

```
$DDInstallationFile = "$env:TEMP\ddagent.msi"
Add-Type -AssemblyName System.Web
do {
    $password=[System.Web.Security.Membership]::GeneratePassword(30,10)
}
until ($password -match '\d' -And $password -cmatch '[a-z]' -And $password -cmatch '[A-Z]')
Start-Process -Wait msiexec -ArgumentList "/qn /i $DDInstallationFile DDAGENTUSER_PASSWORD=$password"
```

**Comment by william-chen-iress** [comment]
Thanks @chinkung. After add generate password logic, the problem seems disappeared.

**Comment by clarkb7** [comment]
closing since I think this has been fixed.

If `DDAGENTUSER_PASSWORD` option is not provided then the installer attempts to create a random password, but some password policies are more restrictive and the random password may not be sufficient.

[< v7.47 password generator ](https://github.com/DataDog/datadog-agent/blob/bcd2c468b838dbc29ec78a23b9fc174fd6ec8f99/tools/windows/install-help/cal/usercreate.cpp#L4)
In Dec 2020 the minimum length was changed from 12 to 16 to help accommodate password policies with larger minimums. https://github.com/DataDog/datadog-agent/pull/6994

[>= v7.47 password generator](https://github.com/DataDog/datadog-agent/blob/7.49.x/tools/windows/DatadogAgentInstaller/CustomActions/ProcessUserCustomActions.cs#L38-L44) generates a very long password (>128 characters)
