### ISSUE TITLE
Mongo check deprecation messages

### ISSUE THREAD

**Issue by mihaialdoiu** [DataDog/datadog-agent#4470]
Hi,

I'm seeing these deprecation messages in the agent logs with the latest agent version 6.15.0:

`2019-11-21 12:05:34 UTC | CORE | WARN | (pkg/collector/python/check.go:201 in Configure) | could not get a 'mongo' check instance with the new api: __init__() takes at least 4 arguments (4 given)
2019-11-21 12:05:34 UTC | CORE | WARN | (pkg/collector/python/check.go:217 in Configure) | passing `agentConfig` to the constructor is deprecated, please use the `get_config` function from the 'datadog_agent' package (mongo).`

How can this be fixed?

Relevant agent status information:

> Getting the status from the agent.

===============
Agent (v6.15.0)
===============

  Status date: 2019-11-21 12:20:17.035476 UTC
  Agent start: 2019-11-21 12:05:33.021960 UTC
  Pid: 11931
  Go Version: go1.12.9
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: info

mongo (1.12.0)
    --------------
      Instance ID: mongo:b23f55cf42b63f65 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/mongo.d/conf.yaml
      Total Runs: 59
      Metric Samples: Last Run: 4,693, Total: 276,887
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 59
      Average Execution Time : 311ms

**Comment by priyesh2609** [comment]
Hi @mihaialdoiu , Did you find the solution for this problem?

**Comment by mx-psi** [comment]
Hi @priyesh2609, updating the Agent to a more recent version or updating the mongo check to `1.14.0` or newer (see [mongo check changelog](https://github.com/DataDog/integrations-core/blob/master/mongo/CHANGELOG.md#1140--2020-04-04)) should remove the error.

I am closing this issue and transferring it to `integrations-core` repo, but feel free to raise any further problems.
