### ISSUE TITLE
Update Kubernetes Manifest Example

### ISSUE THREAD

**Issue by groodt** [DataDog/datadog-agent#4488]
**Describe what happened:**
The datadog-agent example manifest is different to the manifest provided in the documentation.

See:
https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/agent.yaml
vs.
https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/?tab=k8sfile

This makes it difficult to use manifest generation tools such as kustomize or jsonnet with the manifest in source control. It is also misleading which is the most appropriate example to be using.

Will you accept a PR to correct the example YAML in github?

**Describe what you expected:**
The documentation and example manifests to be kept in sync.

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback, we are going to fix this issue. :) 

Best,
Pierre

**Comment by l0k0ms** [comment]
Hello, 

We updated the manifest displayed in the public documentation, i'm going to close this issue for now.

If you have any questions or feedback, feel free to ask it in this thread :)

Best regards,
Pierre

**Comment by groodt** [comment]
Thanks @l0k0ms
