### ISSUE TITLE
System Probe failing to start

### ISSUE THREAD

**Issue by omerlh** [DataDog/datadog-agent#4489]
**Output of the info page (if this is a bug)**
```
(see at the end of the issue)
```

**Describe what happened:**
I tried to enable network performance monitoring using the chart, this is my values.yaml:
```yaml
datadog:
  apiKey: <>
  appKey: <>a04ff
  leaderElection: true
  collectEvents: true
clusterAgent:
  enabled: 
rbac:
  create: true
kubeStateMetrics:
  enabled: false 
systemProbe:
  enabled: false
daemonset:
  useDedicatedContainers: true
```
When deploying this to Kubernetes, I noticed the agents are failing to start with the following error:

```
Error: failed to start container "system-probe": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "setup user: operation not permitted": unknown
```

**Describe what you expected:**
Agent started successfully and network performance metrics are reported.

**Steps to reproduce the issue:**
1. Enable sys probe using the chart

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes 1.12.7 running on Azure

Getting the status from the agent.

===============
Agent (v6.14.0)
===============

  Status date: 2019-11-24 06:54:17.357614 UTC
  Agent start: 2019-11-24 06:52:40.652170 UTC
  Pid: 334
  Go Version: go1.12.9
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -1.622ms
    System UTC time: 2019-11-24 06:54:17.357614 UTC

  Host Info
  =========
    bootTime: 2019-11-07 18:22:10.000000 UTC
    kernelVersion: 4.15.0-1041-azure
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 10.1
    procs: 70
    uptime: 396h30m33s

  Hostnames
  =========
    host_aliases: [369f5054-dddb-4dde-ba32-107f94f1baf6<>]
    hostname <>-vmss000005
    socket-fqdn: datadog-monitoring-j5v4s
    socket-hostname: datadog-monitoring-j5v4s
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: http://169.254.169.254/computeMetadata/v1/instance/hostname gave a response with length &gt; to 255

=========
Collector
=========

  Running Checks
  ==============
    
    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 7
      Metric Samples: Last Run: 6, Total: 36
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    disk (2.5.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 202, Total: 1,212
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 70ms
      
    
    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 1,356, Total: 8,070
      Events: Last Run: 0, Total: 1
      Service Checks: Last Run: 1, Total: 6
      Average Execution Time : 160ms
      
    
    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 5, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 78, Total: 414
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    kubelet (3.3.2)
    ---------------
      Instance ID: kubelet:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 1,494, Total: 8,907
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 24
      Average Execution Time : 1.231s
      
    
    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 91ms
      
    
    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 6, Total: 36
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 17, Total: 102
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
    
    network (1.11.4)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 7
      Metric Samples: Last Run: 217, Total: 1,519
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 4ms
      
    
    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 1, Total: 6
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 6
      Average Execution Time : 30ms
      
    
    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 7
      Metric Samples: Last Run: 1, Total: 7
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 6
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 3
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 15
    TimeseriesV1: 6

  API Keys status
  ===============
    API key ending with adf3a: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - adf3a

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 20,478
  Dogstatsd Metric Sample: 16
  Event: 2
  Events Flushed: 2
  Number Of Flushes: 6
  Series Flushed: 16,011
  Service Check: 106
  Service Checks Flushed: 106

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 15
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 831
  Udp Packet Reading Errors: 0
  Udp Packets: 16
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0

**Comment by gml3ff** [comment]
Hey Omer, 

Looks like you're missing the `systemProbe` is not set to `enabled` in your `datadog-values.yaml`. [The docs here explain how to enable NPM within your helm chart](https://github.com/helm/charts/tree/master/stable/datadog#enabling-system-probe-collection), but it basically boils down to two steps. 

1. Update your datadog-values.yaml file with the system-probe collection configuration:
```
systemProbe:
  (...)
  enabled: true

(...)

daemonset:
  useDedicatedContainers: true
```

2. Then upgrade your Datadog Helm chart:
`helm upgrade -f datadog-values.yaml <RELEASE_NAME> stable/datadog --recreate-pods`

Hope this helps!

**Comment by omerlh** [comment]
Sorry, I provided the wrong values.yaml - I changed `systemProbe.enabled` to false after I saw the error. The error I added is from the the `system-probe` container:
```
  system-probe:
    Container ID:  docker://f5f5bdf67613f0f3596d50b70e5b3655fd88ec5b54554cb6d58690768d0f0fc3
    Image:         datadog/agent:6.14.0
    Image ID:      docker-pullable://datadog/agent@sha256:dbb4dcbb875a1476ff66c9160db5967339671ab61195f86f06e2f88b4dfb534c
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/datadog-agent/embedded/bin/system-probe
      --config=/etc/datadog-agent/system-probe.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "setup user: operation not permitted": unknown
      Exit Code:    128
      Started:      Mon, 25 Nov 2019 19:47:23 +0200
      Finished:     Mon, 25 Nov 2019 19:47:23 +0200
    Ready:          False
    Restart Count:  4
    Environment:
      DD_LOG_LEVEL:  INFO
    Mounts:
      /etc/datadog-agent from sysprobe-config (rw)
      /host/proc from procdir (ro)
      /opt/datadog-agent/run from sysprobe-socket-dir (rw)
      /sys/kernel/debug from debugfs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from datadog-monitoring-token-4wzsm (ro)
```

**Comment by gml3ff** [comment]
Hey Omer, posted this in your support ticket, but can you please send us a flare? This will package up all your relevant log/config files and will help me a lot in debugging your issue. 

You can execute this command on any agent pod where you have NPM configured. 

`kubectl exec -it <datadog-agent-pod-name> agent flare 280821`

**Comment by omerlh** [comment]
I think I just did:
```
Your logs were successfully uploaded. For future reference, your internal case id is 280821
```

**Comment by vedsmand** [comment]
I am seeing the exact same issue as omerlh,
running as a daemonset on aws_eks

`.. Container image "datadog/agent:6.14.0" already present on machine
.. Created container system-probe
.. Error: failed to start container "system-probe": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "operation not permitted": unknown
.. Back-off restarting failed container `

**Comment by vedsmand** [comment]
the fix for me was to upgrade the chart version to v1.38.6 
There was a bug fix for it released recently, which resolved my issue

See link to Github here: https://github.com/helm/charts/pull/19127

**Comment by brycekahle** [comment]
@omerlh It looks like this issue was fixed by the Helm chart upgrade mentioned. If that isn't the case, please re-open this issue.

**Comment by mrvarmazyar** [comment]
Hello everyone,

I know this issue is an old one and it's already been fixed, but it seems it came back in this version: `3.6.3`
```
│ init-config Disabling the apiserver check as leader election is disabled                                                                                                                                                              │
│ init-config grep: /etc/datadog-agent/system-probe.yaml: No such file or directory                                                                                                                                                     │
│ init-config grep: /etc/datadog-agent/system-probe.yaml: No such file or directory
```

**Comment by brycekahle** [comment]
@mrvarmazyar That is likely a different issue. Can you open a new issue with more details?
