### ISSUE TITLE
Is It Possible to Hit K8s API Instead of Kubelet API

### ISSUE THREAD

**Issue by joshkurz** [DataDog/datadog-agent#4646]
I would like to deploy a datadog agent that can hit the k8s api, instead of the kubelet. The kubelet is not accessible in my case, however I still want to ship autodiscovered metrics from pods that contain the right annotations. 

I should only need one datadog agent running, that hits the k8s api to get all required resources. Then the just do the normal thing of getting metrics and shipping that the agent already does. I'd just like the drive the autodiscovery from the k8s api instead of the kubelet. 

Does this sound like a possibility?

**Comment by DylanLovesCoffee** [comment]
@joshkurz :wave: Autodiscovery in K8s is primarily driven by getting the pods list output of the Kubelet. On top of that, Kubernetes metrics are collected via the Kubelet as well by way of the `/metrics` endpoint. Maybe there's more we can help investigate such as why the Kubelet is not accessible in your scenario. Could you reach out to us via a [support ticket](https://docs.datadoghq.com/help/) and see what other options may be available?

**Comment by joshkurz** [comment]
@DylanLovesCoffee TY for the response. I have sent an email to support. I also wanted to update this public thread with the information about why we cannot access the kublet. 

This is for pods running in EKS Fargate. We do not have access to the kublet, and would like to utilize the k8s api for autodiscovery. We are ok with no k8s /metrics in this scenario and just utilizing annotated metrics.
