### ISSUE TITLE
readsecrets.py included in latest v7 of the agent docker image syntax error

### ISSUE THREAD

**Issue by blakeblackshear** [DataDog/datadog-agent#4650]
Looks like the included `/readsecrets.py is missing some parentheses.

**Output of the info page (if this is a bug)**
```
root@datadog-agent-7q22m:/# /readsecret.py /etc/secrets pg_password
  File "/readsecret.py", line 77
    print json.dumps(output)
             ^
SyntaxError: invalid syntax
```

**Describe what happened:**
Running bundled `readsecrets.py` in `:7` tag of the docker image fails with syntax error. Reverting to the `:6` tag resolves the issue.

**Describe what you expected:**
It to work like it it did in version 6.

**Steps to reproduce the issue:**
Use `/readsecrets.py` as specified in the datadog docs.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by mrpatrick** [comment]
Any update?  This is preventing us from migrating.

**Comment by xornivore** [comment]
👋 @mrpatrick @blakeblackshear, thank you for raising this, we should have a fix soon, I will update here for the ETA.
