### ISSUE TITLE
Agent version 6.13.0 is the last available on Ubuntu 6.14?

### ISSUE THREAD

**Issue by KoenDG** [DataDog/datadog-agent#4673]
I'd like to know if more recent versions are available to Ubuntu 16.04 or if 6.13 is the last one for Ubntu 16.04?

**Describe what happened:**

I ran `sudo apt-get update` and then tried upgrading the datadog-agent package. It remains on version 6.13.0

Running `apt-cache policy datadog-agent`  shows this:

```
$ apt-cache policy datadog-agent
datadog-agent:
  Installed: 1:6.13.0-1
  Candidate: 1:6.13.0-1
  Version table:
 *** 1:6.13.0-1 500
        500 https://apt.datadoghq.com stable/6 amd64 Packages
        100 /var/lib/dpkg/status
     1:6.12.1-1 500
        500 https://apt.datadoghq.com stable/6 amd64 Packages
     1:6.12.0-1 500
        500 https://apt.datadoghq.com stable/6 amd64 Packages
    ...
```

**Describe what you expected:**

The agent updating to the most recent version.

**Additional environment details (Operating System, Cloud provider, etc):**

The machine is Ubuntu 16.04.4

Kernel: 
```
$ uname -r
4.4.0-159-generic
```

I'm trying to update to the latest version because the "Network Performance" page mentions needing at least agent version 6.14

https://docs.datadoghq.com/network_performance_monitoring/installation/?tab=agent

I've contacted support and received some upgrade instructions, but those aren't working.

**Comment by olivielpeau** [comment]
Thanks for opening this @KoenDG, what's your support case ID? It'll likely be simpler to follow up there.

Have you checked that `sudo apt-get update` doesn't display any warning and error, and completes successfully?

**Comment by KoenDG** [comment]
Case ID is 292098

Running `sudo apt update` prints no errors and completes successfully.

**Comment by maxmalysh** [comment]
Same for me:
```
datadog-agent is already the newest version (1:6.13.0-1).
```
and:
```
root@api4:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by KoenDG** [comment]
@maxmalysh 

These instructions fixed it for me:

- Remove the current package list: `rm -rf /var/lib/apt/lists/apt.datadoghq.com*`
- Delete the datadog repo list: `/etc/apt/sources.list.d/datadog.list`
- Run: `apt update`

- Verify that `apt-cache policy datadog-agent` only returns the currently installed datadog-agent version.
- Then recreate the repo list: `echo 'deb https://apt.datadoghq.com/ stable 6' > /etc/apt/sources.list.d/datadog.list`
- Run: `apt update`
- Check `apt-cache policy datadog-agent` for available versions.
- Also check `apt list -a datadog-agent | head`

Some commands might need to be done differently due to needing sudo rights, depending on your setup. Like the creating of the list file.

Since this got fixed, I'll close this.

**Comment by maxmalysh** [comment]
Thanks, this worked!

Here is a copy-paste solution for people coming from search engines:
```
# Remove the current package list
rm -rf /var/lib/apt/lists/apt.datadoghq.com*
# Delete the datadog repo list
rm /etc/apt/sources.list.d/datadog.list
apt-get -qqy update
# Then recreate the repo list
echo 'deb https://apt.datadoghq.com/ stable 6' > /etc/apt/sources.list.d/datadog.list
# Install the latest datadog version
apt-get -qqy update
apt-get -qqy install datadog-agent
```

**Comment by KoenDG** [comment]
I'm just gonna go ahead and warn against the use of `-q` in `apt-get`. In case any beginners run into this, the manpage has the following to say:

> -q, --quiet
>     Quiet. Produces output suitable for logging, omitting progress indicators. More q's will produce more quiet up to a maximum of two. You can also use -q=# to set the quiet level, overriding the configuration file. **Note that quiet level 2 implies -y, you should never use -qq without a no-action modifier such as -d, --print-uris or -s _as APT may decided to do something you did not expect_.**
