### ISSUE TITLE
Support wildcards for `no_proxy` setting

### ISSUE THREAD

**Issue by andy-paine** [DataDog/datadog-agent#4739]
**Describe what happened:**
I used a wildcard hostname `*.datadoghq.com` as a list item in `no_proxy` setting. Requests to all subdomains (e.g. `6-11-2-app.agent.datadoghq.com`) used the proxy

**Describe what you expected:**
Requests to any subdomain of `datadoghq.com` should not use the proxy

**Steps to reproduce the issue:**
Use a wildcard domain in the no_proxy settings, observe agent attempting to reach that domain via the proxy

**Additional environment details (Operating System, Cloud provider, etc):**
The generally expected behaviour for `NO_PROXY` is to respect wildcards as per https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html so it was a bit confusing when the DD agent didn't

**Comment by olivielpeau** [comment]
Hi @andy-paine, thanks for opening this.

You're right, at the moment the `no_proxy` setting only supports exact matches. I'll create a card in our backlog to support partial matches as well, but feel free to open a PR implementing this if you'd like to contribute code as well.

Note that the convention we'll want to use will be (close to) the one that was implemented in agent integrations recently, see https://github.com/DataDog/integrations-core/pull/5081. It's similar to the one used by `curl`, and is slightly different from the one you linked to (for example, wildcards are not supported, but there are rules to match subdomains without requiring the use of wildcards).

**Comment by ryanooi** [comment]
Possible for `no_proxy` to support:
* Private IP subnets range (e.g. 10.0.0.0/8, 172.16.0.0/12) 
* Host IP (or `%%host%%` equivalent). Need to bypass host IP as the Datadog-Agent running in Kubernetes will [auto discover and perform health check](https://docs.datadoghq.com/agent/guide/agent-configuration-files/?tab=agentv6v7) on other services that running on same host.

**Comment by gh123man** [comment]
This should be resolved now with the PR linked above. 
See the go `httpproxy` docs here: https://godoc.org/golang.org/x/net/http/httpproxy#Config for supported matching.
