### ISSUE TITLE
datadog-agent with cluster-agent on Kubernetes is missing nodes/stats access

### ISSUE THREAD

**Issue by JayH5** [DataDog/datadog-agent#4863]
**Describe what happened:**
datadog-agent (v7.17.0) running on Kubernetes with cluster-agent following the docs results in warnings in the logs for datadog-agent:
```
2020-02-10 15:27:28 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:118 in LogMessage) | kubelet:d884b5186b651429 | (kubelet.py:368) | GET on kubelet s `/stats/summary` failed: 403 Client Error: Forbidden for url: https://10.4.101.20:10250/stats/summary?verbose=True
```

**Describe what you expected:**
There to not be warnings.

**Steps to reproduce the issue:**
Deploy datadog-agent and cluster-agent on Kubernetes according to the docs. As of datadog-agent v7.17.0, the resources that the datadog-agent should be configured with are:
https://github.com/DataDog/datadog-agent/blob/6eb25b4eb91991b09051882c258fcb726a5ab5b1/Dockerfiles/manifests/cluster-agent/rbac/rbac-agent.yaml#L8-L11

Note that this differs from the set of resources recommended when using datadog-agent **without** cluster-agent:
https://github.com/DataDog/datadog-agent/blob/6eb25b4eb91991b09051882c258fcb726a5ab5b1/Dockerfiles/manifests/rbac/clusterrole.yaml#L49-L53

**Additional environment details (Operating System, Cloud provider, etc):**
Amazon EKS: Kubernetes 1.13 on Amazon Linux 2

**Potential solution**
Add `nodes/stats` to the `ClusterRole` resources for the recommended RBAC configuration for the datadog-agent when using the cluster-agent.

**Comment by naguer** [comment]
Thanks @ahmed-mez you saved my day! I added the `node/stats` and now I don't have that problem, and my dashboard shows the correct information.

**Comment by Theoi-Meteoroi** [comment]
Ditto. Same here on Cluster-agent deploy.    Please test/fix this.

**Comment by ahmed-mez** [comment]
Hi all, thanks for reporting this and thanks @tonglil for the fix https://github.com/DataDog/datadog-agent/pull/5332 it's merged 🎉 

The issue is closed but let us know if you have any other questions!

Thanks.
