### ISSUE TITLE
Setting Windows agent API key in EU site

### ISSUE THREAD

**Issue by beloken** [DataDog/datadog-agent#4898]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
Invalid API key, too complicated to correct from datadoghq.com to datadoghq.eu after installation with the .msi. The installer removes 'site: ' setting from the datadog.yaml file during installation. Difficult to correct without turning to the docs and/or find the link to the example datadog.yaml in the repo.

**Describe what you expected:**
Checkbox or radio button for choosing endpoint in the installers API key window.

**Steps to reproduce the issue:**
Install Windows agent with a EU based account/API key.

**Additional environment details (Operating System, Cloud provider, etc):**
Windows Server 2016

**Comment by KSerrania** [comment]
Hi @beloken, 

Thanks for reporting this issue! We're currently working on adding the `site` parameter to the graphical Windows installer. Here is the relevant PR: https://github.com/DataDog/datadog-agent/pull/4858.

**Comment by KSerrania** [comment]
Hi @beloken,

I'll close this issue, as the option to specify the site parameter during the Windows install (implemented in #4858) is included in versions 6/7.18.0 and above of the Agent. Don't hesitate to re-open it if you face any new issues with this new feature.

**Comment by karthikeyansundararajan-agi** [comment]
Still facing the same issue.
