### ISSUE TITLE
Metrices from datadog

### ISSUE THREAD

**Issue by rahmatrh199** [DataDog/datadog-agent#4934]
Hi
Please help me out that ,how  we can get the monitored application metrices through datadog api.

**Comment by olivielpeau** [comment]
Hi @rahmatrh199, for general questions about Datadog, or issues using the product such as yours, please open a support case with our support team. See https://docs.datadoghq.com/help/ for your options to contact them.

The present issue tracker is not fit to track such questions/issues, so I'll go ahead and close this issue.
