### ISSUE TITLE
Agent tags config are not handled correctly

### ISSUE THREAD

**Issue by abebars** [DataDog/datadog-agent#4982]
**Output of the info page (if this is a bug)**
```
Hostnames
  =========
    hostname: ****************
    socket-fqdn: localhost
    socket-hostname: ****************
    host tags:















    hostname provider: os
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance, and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```

**Describe what happened:**
I am not sure if this actually an issue or I missed something in the documentation. but according to  
https://github.com/DataDog/datadog-agent/blob/257945c4f568411454f89d666f4dbed7eeac6e63/pkg/config/config_template.yaml#L64
tags should be listed in the yaml config as list 
```
# tags:
#   - environment:dev
#   - <TAG_KEY>:<TAG_VALUE>
```
To fix it config should be as string
```
# tags:
#   - "environment:dev"
#   - "<TAG_KEY>:<TAG_VALUE>"
```
However, this wouldn't work and will generate a list of whitespace
**Describe what you expected:**
I expected the tags to be assigned correctly However no tags were added.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by DylanLovesCoffee** [comment]
Hey @abebars thanks for reaching out here! Could you paste your config for the tags list here as well so we can take a look at it? Otherwise, feel free to create a [support ticket](https://docs.datadoghq.com/help/) for a quick response.

**Comment by abebars** [comment]
Hey @DylanLovesCoffee Here's a sample of the not working tags
```
tags:
- cloud_provider:aws
- aws:ec2
- role:app
- availability-zone:us-east-1b
- instance-type:t2.medium
- vpc-name: vpc-name
- env:dev
```

to make this work i just have to quote them to be treated as strings not Yaml Key-Value, Here's a working one 
```
tags:
- "cloud_provider:aws"
- "aws:ec2"
- "role:app"
- "availability-zone:us-east-1b"
- "instance-type:t2.medium"
- "vpc-name: vpc-name"
- "env:dev"
```

**Comment by bkruger99** [comment]
FWIW, this is broken when using helm as well.  When I follow the directions and pass in the same values, the agent picks up "[" and "]" and passes them up as part of the tags. This makes things sucky.

From the helm chart values.yaml 
```  ## @param tags  - list of key:value elements - optional
  ## List of tags to attach to every metric, event and service check collected by this Agent.
  ##
  ## Learn more about tagging: https://docs.datadoghq.com/tagging/
  #
  # tags:
  #   - <KEY_1>:<VALUE_1>
  #   - <KEY_2>:<VALUE_2>
```

My values:
```datadog:
  clusterName: redacted
  tags:
    - environment:redacted1
    - env:redacted2
```

What the agent sees:

```
  "host-tags": {
    "system": [
      "[environment:redacted1",
      "env:redacted2]",
      "cluster_name:redacted"
    ]
  },
```
