### ISSUE TITLE
  API Key Status: [ERROR] API Key is invalid 

### ISSUE THREAD

**Issue by nags28** [DataDog/datadog-agent#4998]
I am running my data dog agent in AWS ECS container the container is running properly but when i get inside the container and check the status of the agent i get below report , where API key is invalid. 

Calling 'info', instead...
2020-02-26 11:30:04,428 | INFO | dd.collector | utils.cloud_metadata(cloud_metadata.py:275) | Attempting to get OpenStack meta_data.json
2020-02-26 11:30:04,432 | INFO | dd.collector | utils.cloud_metadata(cloud_metadata.py:295) | Could not load meta_data.json, not OpenStack EC2 instance
2020-02-26 11:30:04,432 | INFO | dd.collector | utils.ddyaml(ddyaml.py:73) | monkey patching yaml.load...
2020-02-26 11:30:04,433 | INFO | dd.collector | utils.ddyaml(ddyaml.py:77) | monkey patching yaml.load_all...
2020-02-26 11:30:04,433 | INFO | dd.collector | utils.ddyaml(ddyaml.py:81) | monkey patching yaml.dump_all... (affects all yaml dump operations)
====================
Collector (v 5.32.6)
====================

  Status date: 2020-02-26 11:29:49 (14s ago)
  Pid: 27
  Platform: Linux-4.14.158-129.185.amzn2.x86_64-x86_64-with-debian-9.11
  Python Version: 2.7.17, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: Unknown ([Errno -8] Servname not supported for ai_socktype)
    System UTC time: 2020-02-26 11:30:04.435534

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: Not found

  Hostnames
  =========

    ec2-hostname: ip-172-31-9-236.ap-south-1.compute.internal
    local-ipv4: 172.31.9.236
    local-hostname: ip-172-31-9-236.ap-south-1.compute.internal
    socket-hostname: ip-172-31-9-236.ap-south-1.compute.internal
    public-hostname: ec2-13-235-67-157.ap-south-1.compute.amazonaws.com
    hostname: i-0cebfd164833d6a37
    instance-id: i-0cebfd164833d6a37
    public-ipv4: 13.235.67.157
    socket-fqdn: ip-172-31-9-236.ap-south-1.compute.internal

  Checks
  ======

    ntp (1.2.1)
    -----------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (2.1.0)
    ------------
      - instance #0 [OK]
      - Collected 38 metrics, 0 events & 0 service checks

    network (1.9.0)
    ---------------
      - instance #0 [OK]
      - Collected 33 metrics, 0 events & 0 service checks

    docker_daemon (1.10.2)
    ----------------------
      - instance #0 [OK]
      - Collected 52 metrics, 0 events & 1 service check

  Emitters
  ========

    - http_emitter [OK]

====================
Dogstatsd (v 5.32.6)
====================

  Status date: 2020-02-26 11:29:56 (8s ago)
  Pid: 20
  Platform: Linux-4.14.158-129.185.amzn2.x86_64-x86_64-with-debian-9.11
  Python Version: 2.7.17, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 5
  Packet Count: 32
  Packets per second: 0.7
  Metric count: 8
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.32.6)
====================

  Status date: 2020-02-26 11:30:01 (3s ago)
  Pid: 19
  Platform: Linux-4.14.158-129.185.amzn2.x86_64-x86_64-with-debian-9.11
  Python Version: 2.7.17, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 15
  Transactions received: 13
  Transactions flushed: 13
  Transactions rejected: 0
  API Key Status: [ERROR] API Key is invalid

======================
Trace Agent (v 5.32.6)
======================

  Pid: 18
  Uptime: 61 seconds
  Mem alloc: 2537320 bytes

  Hostname: i-0cebfd164833d6a37
  Receiver: 0.0.0.0:8126
  Endpoints:
    https://trace.agent.datadoghq.eu

  --- Receiver stats (1 min) ---

  --- Writer stats (1 min) ---

  Traces: 0 payloads, 0 traces, 0 bytes
  Stats: 0 payloads, 0 stats buckets, 0 bytes
  Services: 0 payloads, 0 services, 0 bytes

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by DylanLovesCoffee** [comment]
Hey @nags28 thanks for opening up this issue. Could you open a [support ticket](https://docs.datadoghq.com/help/) with our team so we can help investigate further?

**Comment by bibhubal** [comment]
Is there any solution to this issue?
