### ISSUE TITLE
Request: Provide packages for Archlinux

### ISSUE THREAD

**Issue by samip5** [DataDog/datadog-agent#5034]
Could the agent maintainers also maintain the AUR package for it or get it added to the extra repository for Archlinux?

AUR package: https://aur.archlinux.org/packages/datadog-agent (Out-of-date)

**Comment by albertvaka** [comment]
I'm the maintainer that package :) I'll try to update it as soon as 7.18 is released. It should work, but note it's not official nor there are any plans to support Arch officially.

**Comment by albertvaka** [comment]
Updated it to 7.17 for now :) Closing this issue.
