### ISSUE TITLE
Backwards incompatible changes in system.mem.cached calculation

### ISSUE THREAD

**Issue by Hsn723** [DataDog/datadog-agent#5038]
**Describe what happened:**
It seems that starting with https://github.com/shirou/gopsutil/commit/f9e238c38b5f16a36794dd2f0f751c7376c64a60 the value returned for `v.Cached` (used [here](https://github.com/DataDog/datadog-agent/blob/master/pkg/collector/corechecks/system/memory_nix.go#L88)) is not the `Cached` value of `/proc/meminfo` anymore but the sum of `Cached` and `SReclaimable` as evidenced in https://github.com/shirou/gopsutil/commit/f9e238c38b5f16a36794dd2f0f751c7376c64a60#diff-900773443586ebe33ca10abf62ec70c9R103

As a result, after an upgrade of some older clients we've seen `system.mem.cached` values jump several GBs, making this a non-trivial change in specification.

**Describe what you expected:**
Based on the source code for equivalent Agent v5 calculations for `system.mem.cached`, we expected its value to be calculated the same way.

Should the consensus be to keep using the `Cached` + `SReclaimable` calculation from https://github.com/shirou/gopsutil, I think a `system.mem.slab_reclaimable` gauge should be added to allow users to perform the inverse calculation themselves.

**Steps to reproduce the issue:**
Upgrade from Agent v5 to a fairly recent minor version of Agent v6/v7

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu Linux 16.04

**Comment by jared-gs** [comment]
I ran into this same issue with my dashboards when upgrading from 5.x -> 7.x

I've filed https://github.com/DataDog/datadog-agent/pull/6053 to add this gauge, so I can at least compensate for `SReclaimable` in my metrics.

**Comment by mx-psi** [comment]
I am closing this since this can be worked around using the new metric from #6053 (which will be available in 6.22/7.22 or greater). Feel free to reopen if further issues arise!
