### ISSUE TITLE
i386 support

### ISSUE THREAD

**Issue by dbalabka** [DataDog/datadog-agent#5070]
Do 6 and 7 versions support non-x64 architecture?

https://s3.amazonaws.com/apt.datadoghq.com/dists/stable/6/binary-i386/Packages

**Comment by dbalabka** [comment]
@KSerrania do I have a chance to get an answer to this question? It is blocking me to start using the logging because it is support only by >=6 version of the agent, but I can not install it on non-x64 Linux distribution.

**Comment by KSerrania** [comment]
Hi @dbalabka,

Thanks for opening this issue! We no longer support x86 architectures for Agent v6+. Building the Agent package on a x86 machine might work, but we haven't tested that.

Would you mind telling us your use case for using the Agent on a Linux x86 distribution?

**Comment by dbalabka** [comment]
This is historical issue and should be fixed. Unfortunately, it would be fixed in near future. 
Building DataDog agent from source is not an option, because there no guarantee that it will work.
Currently, I’m reviewing possibility to use other logs shipper.
