### ISSUE TITLE
It is  unclear how to configure datadog checks with helm values.

### ISSUE THREAD

**Issue by mikhailian** [DataDog/datadog-agent#5278]
**Helm values:**
```
datadog:
  confd:
      datadog.yaml: |
        kubelet_wait_on_missing_container: 1
```

**Agent status:**

```
agent status|grep kubelet
    kubelet (3.6.0)
      Instance ID: kubelet:xxxxxxxxxx[OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
```
**Agent config:**

```
$ agent config|grep kubelet_wait_on_missing_container
kubelet_wait_on_missing_container: 0
```

**What happened:**

Setting  `kubelet_wait_on_missing_container: 1`  in `datadog.yaml` did not impact the configuration of the kubelet check.

**Describe what you expected:**

I expected the kubelet check to be configured with `kubelet_wait_on_missing_container: 1`

It looks like kubelet configuration is defined only in `/etc/datadog-agent/conf.d/kubelet.d/conf.yaml` but I can not figure out how to put it there through the needle's eye of helm values. I searched Datadog documentation and Github issues and found no documentation whatsoever.

**What does not work 1:**
```
datadog:
  confd:
      kubelet.d/conf.yaml: |
        kubelet_wait_on_missing_container: 1
```
Even it it worked for confd, [this entrypoint script](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/entrypoint/89-copy-customfiles.sh#L4) disregards subfolders.

**What does not work 1:**

```
agents:
  customAgentConfig:
    kubelet_wait_on_missing_container: 1
```

The template does not seem to pass this value through, and even if it did, the value [would have landed](https://github.com/helm/charts/blob/master/stable/datadog/templates/datadog-yaml-configmap.yaml#L17) in `datadog.yaml` anyway.

**Comment by ian28223** [comment]
Looks like this is not an issue with the agent itself but with the helm chart.

Looking at the template, the [`customAgentConfig`](https://github.com/helm/charts/blob/master/stable/datadog/templates/datadog-yaml-configmap.yaml#L18-L20) appears to be on used only when [`useConfigMap`](https://github.com/helm/charts/blob/master/stable/datadog/templates/datadog-yaml-configmap.yaml#L1) is also set to `true`.

Another way you can set this is by adding the environment variable `DD_KUBELET_WAIT_ON_MISSING_CONTAINER`. See https://docs.datadoghq.com/agent/guide/environment-variables
Note though, if you use the envvar path, it would not be reflected in `agent config`.

**Comment by ian28223** [comment]
A request to update the documentation has been made to state the relationship between `customAgentConfig` and `useConfigMap`

**Comment by mikhailian** [comment]
The [useConfigMap](https://github.com/helm/charts/blob/master/stable/datadog/templates/datadog-yaml-configmap.yaml#L1) option **works**. The correct config is thus

```
agents:
  useConfigMap: true
  customAgentConfig:
     kubelet_wait_on_missing_container: 1
```
Thank you, @ian28223.
