### ISSUE TITLE
Setting use_dogstatsd to False Doesn't Disable DogStatD Listener

### ISSUE THREAD

**Issue by allistera** [DataDog/datadog-agent#5320]
We have had a number of users complain that they cannot start their services due to port clashing on 5000 with the Datadog Agent.

Looking at the Agent config this seems to be open for DogStatsd. 

**Describe what happened:**

Setting use_dogstatsd to 'false' doesn't disable the agent listening on port 5000 (The Dogstatsd port)

The only workaround is to change `dogstatsd_stats_port` option to something other than 5000. 

**Describe what you expected:**

Port 5000 to not be listened on if DogStatsD is disabled.

**Additional environment details **

RHEL 7.

**Comment by ian28223** [comment]
`use_dogstatsd` does disable Dogstatsd/DDAgent from listening on the default UDP port 8125 configureable via `dogstatsd_port: 8125`


What is running on port 5000 is the expvar server; setting `dogstatsd_stats_port` to something other than 5000 will not prevent the Agent from listening on port 5000. Instead, you can set `expvar_port: 0` to disable expvar server or set it to some other port number
