### ISSUE TITLE
Pushing metrics to multiple datadog accounts

### ISSUE THREAD

**Issue by suman-anand-grab** [DataDog/datadog-agent#5389]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:** 
We have a use case to push the data into multiple datadog accounts created as different organizations under datadog parent domain. Is there a way to achieve this by changing the datadog configuration.
One of the approaches suggested was to paste the dd_url and api_key in CSV format, which doesn't seem to reflect in both accounts.
If not, the other alternative would be to use the datadog agent api to push to a different account

**Describe what you expected:**
Expectation is that just by changing the configuration of datadog, we should be able to push to both accounts.

**Steps to reproduce the issue:**
Tried by passing the dd_url and api_key in CSV format by
dd_url: https://app.datadoghq.com,https://app.datadoghq.com
api_key: api_key1,api_key2
This doesn't seem to push the data to any of the accounts

**Additional environment details (Operating System, Cloud provider, etc):**
OS - Debian
Datadog agent version - 6

**Comment by olivielpeau** [comment]
Hi @suman-anand-grab!

For your request, please contact our [support team](http://docs.datadoghq.com/help/) and send them [troubleshooting information from one of your Agents](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7). Sending to multiple Datadog accounts has billing implications that our support team will be able to check with you.

I'll go ahead and close the issue, but feel free to comment here if you're running into further issues.
