### ISSUE TITLE
proposal: pkg/trace/sampler: track sampling decisions using metrics.

### ISSUE THREAD

**Issue by knusbaum** [DataDog/datadog-agent#5415]
We should track which traces are sampled by the sampler, and why.
This should be reported in a metric, which should be sliced by the service tag of the trace's root span.

Making this change will help us understand what's happening in the tracer when traces aren't making it through.

**Comment by knusbaum** [comment]
I've created a draft PR, #5416 which is a way we *might* want to gather the information from the sampler system. I'm not sure about modifying the interface, but since this is an application and not a library, I think it may be ok.

Once we change this, sampler metrics can be reported from one location, here:
https://github.com/DataDog/datadog-agent/blob/ef829292b6258a1988a47c0d28602d07f38d8bf8/pkg/trace/agent/agent.go#L249-L253

**Comment by knusbaum** [comment]
Regarding the actual metrics collection, I'm not sure how best to do that.
The metrics that are collected currently seem to be done using atomic integers, and published here:
https://github.com/DataDog/datadog-agent/blob/ef829292b6258a1988a47c0d28602d07f38d8bf8/pkg/trace/info/stats.go#L127

Adding this, where we want to add tags that will change per-trace, will require doing this metric a slightly different way than the others. 

One option is to keep `sync.Map` values, mapping tags to span counts. One mapping `service name, reason` -> `spans sampled count`, and one mapping `service name` -> `spans not sampled count`.  

During publish, we would iterate over the maps, attaching the tags to calls to `metrics.Count`.

This feels a little bit gross because of the mapping, but it is a pretty minimal solution.

**Comment by gbbr** [comment]
I left comments regarding the implementation approach in the PR.

Regarding the atomic values, you're right, there were some concerns there about performance in the past. I'm not sure that the sampler is such a hot path. Somewhere where spans get iterated over that'll definitely be a hot path, but one time per trace might be ok.

We should try to benchmark this (with a real statsd connection) before considering performance improvements. Find out how much TPS our biggest customer has and use double that as a reference.
