### ISSUE TITLE
Pause containers exclusion rules does not exclude containers from AKS new container registry

### ISSUE THREAD

**Issue by aleveille** [DataDog/datadog-agent#5459]
**Describe what happened:**
AKS pause containers hosted in the "aksrepos.azurecr.io/mirror" registry are not excluded from auto-discovery.

A lot of containers required for the inner working of AKS [have been moved](https://github.com/Azure/aks-engine/issues/1123) to the "aksrepos.azurecr.io/mirror" container registry. The auto-discovery exclusion rule for AKS have to be updated to include the pause container hosted in that registry.

**Describe what you expected:**
These pause containers should be excluded from the auto-discovery.
https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent

**Steps to reproduce the issue:**
Launch an AKS cluster in Azure and deploy a pod. The pause container is included in the auto-discovery perimeter.

**Additional environment details (Operating System, Cloud provider, etc):**
- AKS on Azure, presumably version 1.15+

**Comment by ahmed-mez** [comment]
Thanks @aleveille for reporting this and for the PR.
Closing the issue since https://github.com/DataDog/datadog-agent/pull/5460 is merged and will be in Agent 7.20.
