### ISSUE TITLE
Journald collector: filter not only by units but also by process

### ISSUE THREAD

**Issue by mazzy89** [DataDog/datadog-agent#5579]
This is a feature request.

As an engineer, I would also like to filter logs of journald not only by systemd units but also by the process. 

In our instance `sshd` does not run as a systemd unit but still we want to filter it.

it is possible in journalctl using the flag `_EXE=`

```sh
journalctl -b _EXE=/usr/sbin/sshd
```

**Comment by bobvanderlinden** [comment]
It would be nice if we could just add filter-matches for Datadog to use, instead of just matches with `_SYSTEMD_UNIT`.

**Comment by goakley** [comment]
I'm running into an issue where we'd like to collect all journal logs except for those with `SYSLOG_IDENTIFIER=[xxx]`, but there is no way to configure this in the journald collector.  These logs are not from systemd, so they do not have a `_SYSTEMD_UNIT` field set.
