### ISSUE TITLE
A way to disable default integrations on startup 

### ISSUE THREAD

**Issue by etherandrius** [DataDog/datadog-agent#5654]
Is there a way to completely disable the default integrations on startup ? Specifically `etcds` `auto_conf.yaml` and `ntps` `conf.yaml.defaults` files from being created ? 

Things I tried: 
- Having a file already on the pod (file gets overwritten when the pod starts)
- Deleting files from base image like [here](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/entrypoint/60-network-check.sh#L5) (we repackage the image in order to do this)

Context:
Agent is deployed as daemonSet.

**Comment by Simwar** [comment]
Hi @etherandrius 

You can simply mount an `emptyDir` (https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) in the `/etc/datadog-agent/conf.d/etcd.d` and `/etc/datadog-agent/conf.d/ntp.d` folders, if you want to get rid of all files in these folders.
Or, you can mount blank files from config map in place of the files you want to remove.

Simon

**Comment by etherandrius** [comment]
Thanks we ended up removing the integrations on the containers startups as follows 
`agent integration remove datadog-ntp -r -c /etc/datadog-agent/; agent integration remove datadog-etcd -r -c /etc/datadog-agent/; agent run -c /etc/datadog-agent/` 

But good to know for the future
