### ISSUE TITLE
Unable to import datadog-agent with go modules

### ISSUE THREAD

**Issue by sonofachamp** [DataDog/datadog-agent#5693]
**Describe what happened:**
```
→ go get github.com/DataDog/datadog-agent
go: github.com/DataDog/datadog-agent upgrade => v0.0.0-20200608211623-9779275bb30b
go get: github.com/DataDog/datadog-agent@v0.0.0-20200608211623-9779275bb30b requires
        github.com/benesch/cgosymbolizer@v0.0.0: reading github.com/benesch/cgosymbolizer/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Describe what you expected:**
Successful import of the go module

**Steps to reproduce the issue:**
Try to import `datadog-agent` using go modules.

**Additional environment details (Operating System, Cloud provider, etc):**
Go version: `go version go1.14.4 linux/amd64`
OS: Ubuntu 18.04

**Comment by ogaca-dd** [comment]
Hi @sonofachamp ,

DataDog Agent is not a library.
If you only want to send custom metrics, you can install [DogStatsd](https://docs.datadoghq.com/developers/dogstatsd/?tab=go) and use [Datadog Go](https://github.com/DataDog/datadog-go/) library.
If you want to collect metrics from an host and send custom metrics, you can install [the Agent](https://docs.datadoghq.com/agent/) and use  [Datadog Go](https://github.com/DataDog/datadog-go/) library.

If the previous explanations do not help, can you give us more details about what you want to accomplish?
