### ISSUE TITLE
Datadog 6.20.0 "disk" check not found

### ISSUE THREAD

**Issue by huguesalary** [DataDog/datadog-agent#5722]
**Describe what happened:**

We upgraded to datadog 6.20.0

**Describe what you expected:**

The disk check to be correctly reported. We lost the disk metrics on the datadog dashboard.

**Steps to reproduce the issue:**

```
datadog-agent check disk
Error: no valid check found
```

**Additional environment details (Operating System, Cloud provider, etc):**

Debian

**Comment by huguesalary** [comment]
Confirmed that reverting to datadog 6.19.2 fixes the issue

**Comment by mx-psi** [comment]
Hi, thanks for reporting this! This should be fixed on version 6.20.1 so I am closing this. If you are still having the issue feel free to reopen.
