### ISSUE TITLE
disk check is not configured in "7.20.0-rc.10"

### ISSUE THREAD

**Issue by cyplenochek** [DataDog/datadog-agent#5781]
according to dicumentation https://docs.datadoghq.com/integrations/disk/ system.disk metric does not require configuraion.
We see that etc/datadog-agent/conf.d/disk.d/conf.yaml.example exist, but metric system.disk is not collecting.
Please see the output below:
# agent version
Agent 7.20.0-rc.10 - Commit: 8a534e5 - Serialization version: 4.33.0 - Go version: go1.13.8
# agent check disk
Error: no valid check found

# cat etc/datadog-agent/conf.d/disk.d/conf.yaml.example
## All options defined here are available to all instances.
#
# init_config: {}

## Every instance is scheduled independent of the others.
#
instances:
.....

**Comment by CharlyF** [comment]
Hi @cyplenochek - Thanks for opening this issue.
We fixed this in the minor update `7.20.1` as you can see in [the changelog](https://github.com/DataDog/integrations-core/blob/master/AGENT_CHANGELOG.md#datadog-agent-version-7201).
Could you update your agent and let us know if that solves your issue ?

Best,
.C

**Comment by cyplenochek** [comment]
great, we upgraded version. confirmed, it fixed. Great job, @CharlyF !
