### ISSUE TITLE
Windows service integration: why it is alerting?

### ISSUE THREAD

**Issue by sadcomusa1** [DataDog/datadog-agent#5832]
Hello.

I am a rookie DataDog admin. Please, forgive me if this is obvious to everybody else.
I just created my first monitor that uses Windows Service integration.  There are 4 services running on the server that I want to monitor. Upon the monitor creation, immediately, it is sending alerts for all 4 services, although they are running and it should be reported as "green".

How do I fix my configuration or the monitor's settings?

![Windows_services_config](https://user-images.githubusercontent.com/67324090/85729794-1aa52880-b6c7-11ea-9d3b-4f2839fe5152.JPG)

![Windows_services](https://user-images.githubusercontent.com/67324090/85729406-cac66180-b6c6-11ea-8af8-d900524488f3.JPG)
?

Thank you.

**Comment by olivielpeau** [comment]
Hi @sadcomusa1, for this issue, could you get in touch with our support team by opening a support case with them (see https://docs.datadoghq.com/help/) and sending them your logs and Agent information with a "flare" (see [Windows instructions on Agent v7 and v6](https://docs.datadoghq.com/agent/basic_agent_usage/windows/?tab=agentv6v7#send-a-flare))?

For this kind of issues, our support team will be able to assist you more efficiently than on this Github issue. I'll go ahead and close this, but please follow up if you're unable to contact our support team or have an unrelated issue, thanks!
