### ISSUE TITLE
/ready endpoint always returns a HTTP 500 

### ISSUE THREAD

**Issue by aguthrie** [DataDog/datadog-agent#5846]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
datadog-cluster-agent `/ready` endpoint always return an HTTP 500 even though all healthchecks are passing

**Describe what you expected:**
datadog-cluster-agent `/ready` endpoint returns a HTTP 200 if all healthchecks are passing

**Steps to reproduce the issue:**
start the datadog-cluster-agent and make a request to the `/ready` endpoint:

```
~ curl -v 127.0.0.1:5555/ready
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5555 (#0)
> GET /ready HTTP/1.1
> Host: 127.0.0.1:5555
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 26 Jun 2020 22:23:00 GMT
< Content-Length: 252
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
{"Healthy":["healthcheck","tagger","ad-servicelistening","ad-config-provider-kubernetes-endpoints","ad-config-provider-kubernetes-services","collector-queue","clusterchecks-leadership","clusterchecks-dispatch","aggregator"],"Unhealthy":["healthcheck"]}
```

it return a 500 and shows the `healthcheck` as both Healthy and Unhealthy, which is odd.

this appears to be due to the fact that the readiness healthcheck is not running and is marked as unhealthy because it hasn't run in 30 seconds (https://github.com/DataDog/datadog-agent/blob/fc68d758a98e1d5b0aa77f70c696993286cab773/pkg/status/health/health.go#L131-L133). this is happening because the forwarder doesn't start the healthcheck if api key checking is disabled (https://github.com/DataDog/datadog-agent/blob/fc68d758a98e1d5b0aa77f70c696993286cab773/pkg/forwarder/forwarder_health.go#L81-L85) which happens here: https://github.com/DataDog/datadog-agent/blob/fc68d758a98e1d5b0aa77f70c696993286cab773/cmd/cluster-agent/app/app.go#L171-L175

this appears to have regressed in https://github.com/DataDog/datadog-agent/pull/5349

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by nesl247** [comment]
I actually just reported this to datadog the other day via a ticket.
