### ISSUE TITLE
version of go module

### ISSUE THREAD

**Issue by florianl** [DataDog/datadog-agent#5949]
Hi :)

I'm the maintainer of https://github.com/florianl/go-conntrack. On [1] I've noticed you are using the package.

I'm contacting you as I wanted to let you know in advance, that I will remove the git tag from the repository on September 1st 2020 - see [2].

I realized that tagging a git version on this project is not the best way to go. E.g. the git tag was not updated when new features where added, buges fixed or changes were made to the API.

Nonetheless you still can tag a version for your project using modules:
```
$ go get github.com/florianl/go-conntrack@master
$ go get github.com/florianl/go-conntrack@06743d3a59db
```
As this is a private project and I try to keep the management overhead at a minimum, I will also not use git tags in the future.

I'm sorry for the caused problems.

Cheers,
 Florian

[1] https://pkg.go.dev/github.com/florianl/go-conntrack?tab=importedby
[2] https://github.com/florianl/go-conntrack/issues/27

**Comment by albertvaka** [comment]
Thanks a ton for the heads up, Florian! 🙇 🙇 🙇
