### ISSUE TITLE
security-agent fails to start because health port is already used

### ISSUE THREAD

**Issue by cohandv** [DataDog/datadog-agent#6012]
root@datadog-agent-9bnmg:/# agent status
Getting the status from the agent.

===============
Agent (v7.21.0)
===============

  Status date: 2020-07-20 12:40:34.731379 UTC
  Agent start: 2020-07-20 12:38:44.624470 UTC
  Pid: 378
  Go Version: go1.13.11
  Python Version: 3.8.1
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 1.554ms
    System UTC time: 2020-07-20 12:40:34.731379 UTC

  Host Info
  =========
    bootTime: 2020-07-17 11:31:11.000000 UTC
    kernelArch: x86_64
    kernelVersion: 4.19.112+
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: bullseye/sid
    procs: 173
    uptime: 73h7m43s
    virtualizationRole: guest

  Hostnames
  =========
    host_aliases: [gke-osrm5-southamerica-qa-primary-e9e49e16-2azx.osrm-239913 gke-osrm5-southamerica-qa-primary-e9e49e16-2azx-osrm5-southamerica-qa]
    hostname: gke-osrm5-southamerica-qa-primary-e9e49e16-2azx.c.osrm-239913.internal
    socket-fqdn: datadog-agent-9bnmg
    socket-hostname: datadog-agent-9bnmg
    host tags:
      kube_cluster_name:osrm5-southamerica-qa
      cluster_name:osrm5-southamerica-qa
      gke-osrm5-southamerica-qa-f3faca86-node
      zone:us-central1-a
      instance-type:n1-standard-2
      internal-hostname:gke-osrm5-southamerica-qa-primary-e9e49e16-2azx.c.osrm-239913.internal
      instance-id:1144160572363519260
      project:osrm-239913
      numeric_project_id:97918365539
      google-compute-enable-pcid:true
      instance-template:projects/97918365539/global/instanceTemplates/gke-osrm5-southamerica-qa-primary-bcad4b2b
      cluster-location:us-central1-a
      gci-ensure-gke-docker:true
      gci-update-strategy:update_disabled
      kube-labels:cloud.google.com/gke-nodepool=primary,cloud.google.com/gke-os-distribution=cos
      cluster-name:osrm5-southamerica-qa
      cluster-uid:f3faca869c440419815b0322fdbdb08376c056885282fd56e3f1d815980e186d
      created-by:projects/97918365539/zones/us-central1-a/instanceGroupManagers/gke-osrm5-southamerica-qa-primary-e9e49e16-grp
      gci-metrics-enabled:true
    hostname provider: gce
    unused hostname providers:
      configuration/environment: hostname is empty

  Metadata
  ========
    cloud_provider: GCP
    hostname_source: gce

=========
Collector
=========

  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 6, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:31.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:31.000000 UTC

    disk (2.10.1)
    -------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 216, Total: 1,080
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 525ms
      Last Execution Date : 2020-07-20 12:40:23.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:23.000000 UTC

    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 616, Total: 3,696
      Events: Last Run: 0, Total: 1
      Service Checks: Last Run: 1, Total: 6
      Average Execution Time : 735ms
      Last Execution Date : 2020-07-20 12:40:30.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:30.000000 UTC

    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 5, Total: 25
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:22.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:22.000000 UTC

    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 195, Total: 1,035
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:29.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:29.000000 UTC

    kube_dns (2.4.1)
    ----------------
      Instance ID: kube_dns:8fd103a7aee084d1 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kube_dns.d/auto_conf.yaml
      Total Runs: 6
      Metric Samples: Last Run: 84, Total: 504
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 87ms
      Last Execution Date : 2020-07-20 12:40:24.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:24.000000 UTC

    kubelet (4.1.1)
    ---------------
      Instance ID: kubelet:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 655, Total: 3,254
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 20
      Average Execution Time : 1.924s
      Last Execution Date : 2020-07-20 12:40:23.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:23.000000 UTC

    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:28.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:28.000000 UTC

    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 5
      Metric Samples: Last Run: 6, Total: 30
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:20.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:20.000000 UTC

    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 17, Total: 102
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:27.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:27.000000 UTC

    network (1.17.0)
    ----------------
      Instance ID: network:5c571333f400457d [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 31, Total: 186
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 17ms
      Last Execution Date : 2020-07-20 12:40:34.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:34.000000 UTC

    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 1
      Metric Samples: Last Run: 1, Total: 1
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 5.154s
      Last Execution Date : 2020-07-20 12:39:14.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:39:14.000000 UTC

    prometheus (3.3.0)
    ------------------
      Instance ID: prometheus:datadog.cluster_agent:aa6eb85316218d62 [OK]
      Configuration Source: kubelet:docker://ef1f21a8069e35b9378d29448e9d336121bfaad1eda5ec3f5c440e2c70fc40fc
      Total Runs: 6
      Metric Samples: Last Run: 35, Total: 210
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 6
      Average Execution Time : 45ms
      Last Execution Date : 2020-07-20 12:40:33.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:33.000000 UTC

    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 6
      Metric Samples: Last Run: 1, Total: 6
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-20 12:40:26.000000 UTC
      Last Successful Execution Date : 2020-07-20 12:40:26.000000 UTC

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 7
    Connections: 0
    Containers: 0
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 3
    Metadata: 0
    Pods: 0
    Processes: 0
    RTContainers: 0
    RTProcesses: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 17
    TimeseriesV1: 7

  API Keys status
  ===============
    API key ending with 1ad63: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 1ad63

==========
Logs Agent
==========

  Logs Agent is not running

=========
APM Agent
=========
  Status: Running
  Pid: 380
  Uptime: 110 seconds
  Mem alloc: 10,169,304 bytes
  Hostname: gke-osrm5-southamerica-qa-primary-e9e49e16-2azx.c.osrm-239913.internal
  Receiver: 0.0.0.0:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    No traces received in the previous minute.
    Default priority sampling rate: 100.0%

  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes

=========
Aggregator
=========
  Checks Metric Sample: 10,308
  Dogstatsd Metric Sample: 660
  Event: 2
  Events Flushed: 2
  Number Of Flushes: 7
  Series Flushed: 8,930
  Service Check: 108
  Service Checks Flushed: 114

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 659
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 48,257
  Udp Packet Reading Errors: 0
  Udp Packets: 82
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0

=====================
Datadog Cluster Agent
=====================

  - Datadog Cluster Agent endpoint detected: https://10.106.13.53:5005
  Successfully connected to the Datadog Cluster Agent.
  - Running: 1.6.0+commit.c87ac8b

**Output of the info page (if this is a bug)**
```
2020-07-20 12:41:33 UTC | SECURITY | ERROR | (app/app.go:151 in start) | Error starting health port, exiting: listen tcp 0.0.0.0:5555: bind: address already in use
Error: Error starting health port, exiting: listen tcp 0.0.0.0:5555: bind: address already in use
Usage:
  datadog-security-agent start [flags]

Flags:
  -h, --help   help for start

Global Flags:
  -c, --cfgpath string   path to directory containing datadog.yaml
  -n, --no-color         disable color output

security-agent exited with code 255, signal 0, restarting in 2 seconds
starting security-agent
Error: Error starting health port, exiting: listen tcp 0.0.0.0:5555: bind: address already in use
Usage:
  datadog-security-agent start [flags]

Flags:
  -h, --help   help for start

Global Flags:
  -c, --cfgpath string   path to directory containing datadog.yaml
  -n, --no-color         disable color output

2020-07-20 12:41:36 UTC | SECURITY | ERROR | (app/app.go:151 in start) | Error starting health port, exiting: listen tcp 0.0.0.0:5555: bind: address already in use
security-agent exited with code 255, signal 0, restarting in 2 seconds
 ~ 
```

**Describe what happened:**
Using the procedure to install node-agent as DaemonSet in K8S, I get errors about a port already taken. Seems that security agent is fighting to use same port as the agent

**Describe what you expected:**
The process crashes and s6 keeps trying to start the security agent (at this point not really sure, whats the use case for this agent, I might need to disable it.

**Steps to reproduce the issue:**
1.- Follow this procedure to install your datadog agents into k8s `https://www.datadoghq.com/blog/monitoring-kubernetes-with-datadog/`
2.- Ensure the health port is conifgured (used to check liveness)

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by mx-psi** [comment]
Hi @cohandv, thanks for reporting this! This looks like a duplicate of #6002 which will be fixed in an upcoming release. Please, follow the other issue for further updates.

**Comment by ahmed-mez** [comment]
Closing this issue, please see https://github.com/DataDog/datadog-agent/issues/6002 thanks!
