### ISSUE TITLE
DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac/ folder no longer exists

### ISSUE THREAD

**Issue by adamf** [DataDog/datadog-agent#6073]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**

Per the docs, we've been using https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac/rbac-cluster-agent.yaml as the manifest for setting up the cluster-agent rbac. However, it appears this folder has disappeared in git. 

**Describe what you expected:**

The method described in the docs should stay supported; this has broken our builds. 

**Steps to reproduce the issue:**

```
kubectl create -f https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac/rbac-cluster-agent.yaml
error: unable to read URL "https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac/rbac-cluster-agent.yaml", server reported 404 Not Found, status code=404
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by adamf** [comment]
I'd suggest not using `master` as the branch for this file if the location is going to move; instead, this file should be pinned to the agent version with (perhaps) a tag or pinned to the specific git revision. Our monitoring infrastructure should not change in ways that breaks our whole infrastructure.

**Comment by adamf** [comment]
Is https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/agent-rbac.yaml the same as https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac/rbac-cluster-agent.yaml ?

**Comment by Simwar** [comment]
Hey @adamf 

The files were indeed deleted and replaced by another version which is now generated from our helm chart:
- https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac.yaml : for the node agent
- https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/agent-rbac.yaml for the cluster agent

We changed our docs accordingly to reflect this new change: https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=secret#step-1-configure-rbac-permissions

Thanks

**Comment by adamf** [comment]
Thanks @Simwar for the update; going forward, how should I protect against such changes in the future? Your docs suggest pinning to `master` but in doing so I lost that directory and DataDog has been off in my infrastructure for 4 days. Does DataDog have a plan to prevent future breakage?

**Comment by cohenyair** [comment]
Hi @adamf, to protect against such changes in the future we'd suggest one of the following approaches:
- Copy the manifests into your repo, and update them manually/periodically if necessary (the file content itself is backward compatible, so future proof)
- Use our helm charts directly, which will always generate the most up-to-date manifests (note that our [README](https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/manifests/cluster-agent) in the manifests folders explain how to generate them).

Kubernetes manifests in our Github are used as examples for documentation and are subject to changes, Datadog does not recommend to apply them directly from our git repository into the production environment. Having said that, we will also be more mindful and avoid such changes in the future as much as possible, as well as communicating such changes before they happen when possible.

**Comment by adamf** [comment]
Hi @cohenyair - Perhaps this issue should be updated to say "change https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=secret#step-1-configure-rbac-permissions to reflect that helm charts should be used" since the official documentation doesn't mention helm chart and tells the user to use the github-linked manifests.
