### ISSUE TITLE
system-probe panic: could not find a valid syscall name

### ISSUE THREAD

**Issue by dvukolov** [DataDog/datadog-agent#6418]
**Describe what happened:**
system-probe fails to start with a panic: "could not find a valid syscall name" when launching a new Docker container of Datadog-Agent on AWS Graviton2 (ARM64) instance. The following log messages are repeated every two seconds as system-probe tries to restart:

```
starting system-probe
panic: could not find a valid syscall name

goroutine 1 [running]:
github.com/DataDog/datadog-agent/pkg/security/probe.getSyscallFnName(0x227cca7, 0x6, 0x22785b6, 0x3)
	/go/src/github.com/DataDog/datadog-agent/pkg/security/probe/probe.go:87 +0x17c
github.com/DataDog/datadog-agent/pkg/security/probe.init()
	/go/src/github.com/DataDog/datadog-agent/pkg/security/probe/exec.go:23 +0x1158
system-probe exited with code 2, signal 0, restarting in 2 seconds
```

**Describe what you expected:**
system-probe starting normally and not panicking.

**Steps to reproduce the issue:**
Launch a new t4g.micro instance (free tier till December 2020) with Ubuntu 20.04 (arm64), install all system upgrades, Docker, and run Datadog Agent in a container:

```shell
$ docker run -d --name datadog-agent \
    -e DD_API_KEY=[...] \
    -e DD_LOGS_ENABLED=true \
    -e DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true \
    -e DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent" \
    -e DD_APM_ENABLED=false \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /proc/:/host/proc/:ro \
    -v /opt/datadog-agent/run:/opt/datadog-agent/run:rw \
    -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
    datadog/agent:latest
```

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu 20.04, AWS EC2 t4g.micro (arm64), Docker CE version 19.03.13.

Is there any way to get around this issue?

**Comment by kcmartin** [comment]
I have this same issue with the Datadog Agent 7.23.0 running in a Kubernetes cluster.

Out of the 4 containers, only 3 are starting, and checking the logs for the system-probe container reveals this error:

`panic: could not find a valid syscall name
goroutine 1 [running]:
github.com/DataDog/datadog-agent/pkg/security/probe.getSyscallFnName(0x21bd6bc, 0x6, 0x21bb5e9, 0x5)
	/go/src/github.com/DataDog/datadog-agent/pkg/security/probe/syscalls.go:341 +0x248
github.com/DataDog/datadog-agent/pkg/security/probe.init()
	/go/src/github.com/DataDog/datadog-agent/pkg/security/probe/exec.go:20 +0xcec`

**Comment by brycekahle** [comment]
@dvukolov @kcmartin Thanks for the bug report. We are looking into this.

**Comment by reyiyo** [comment]
Hi!
Is there any update on this issue? Or some workaround?

**Comment by brycekahle** [comment]
@reyiyo There is unofficial support for arm64 in the network tracer coming out in 7.26.0. We are still working on adding arm64 to our CI environment before we can call if official. I don't think any changes have been made to the runtime security product to support arm64 yet.

**Comment by brycekahle** [comment]
7.26.0 has been released. Please give it a try and let us know how it goes!

**Comment by brycekahle** [comment]
NPM is known to be working on `arm64` now
