### ISSUE TITLE
datadog process agent doesn't honor dd_url

### ISSUE THREAD

**Issue by flokli** [DataDog/datadog-agent#6455]
**Output of the info page (if this is a bug)**
```
===============
Agent (v6.11.2)
===============

  Status date: 2020-09-25 13:13:06.005929 BST
  Agent start: 2020-09-25 12:03:31.984635 BST
  Pid: 9393
  Python Version: 2.7.18
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 175µs
    System UTC time: 2020-09-25 13:13:06.005929 BST

  Host Info
  =========
    bootTime: 2020-06-23 09:28:11.000000 BST
    kernelVersion: 5.4.35
    os: linux
    platform: nixos
    platformVersion: &#34;20.09pre-git (Nightingale)&#34;
    procs: 200
    uptime: 2258h35m21s
```

**Describe what happened:**
I use `dd_url` to point datadog to the EU endpoint, by setting it to "https://app.datadoghq.eu".

The agent successfully sends data, but `datadog-process-agent` seems to try to authenticate with the US endpoint (for which the API credentials obviously don't work)

**Describe what you expected:**
I'd expect `datadog-process-agent` to also send to the EU, and try to connect to the EU endpoint if I set `dd_url` accordingly.

I'd also expect https://docs.datadoghq.com/integrations/process/ (and selecting "EU" on the right side to describe how the EU-specific settings should look like.

**Steps to reproduce the issue:**
Try to run the datadog process agent against your EU endpoint

**Additional environment details (Operating System, Cloud provider, etc):**
AWS. Also see "Host Info" above.

**Comment by olivielpeau** [comment]
Hi @flokli, to configure the Agent to send to the EU site, please leave `dd_url` unset in `datadog.yaml`, and instead set:

```yaml
site: datadoghq.eu
```

This will configure all agent components to send data to the EU site.

(mentioned in our docs [here](https://docs.datadoghq.com/agent/basic_agent_usage/?tab=agentv6v7#datadog-site))

I'll go ahead and close this, but if you're still having issues feel free to comment here or [contact support](https://www.datadoghq.com/support/)
