### ISSUE TITLE
Sum metrics with the same hostname for Datadog Agent instead of selecting the only one

### ISSUE THREAD

**Issue by kperchlicki** [DataDog/datadog-agent#6471]
**Describe what happened:**
In my company we have between 10 - 60 instances with unique datadog agent hostnames.
It results in beautiful charts with big amount of visible data.

That big amount of instances is producing a big amount of unique custom metrics which we are charged for.
We've decided to lost possibility of more grained analysis and we've set the same hostname for all of Datadog Agents. 

So we've lost the granularity and we wanted to  gain less amount of unique custom metrics which we are charged for. But the result was as it is described in here:

 `Note: When removing the host tag, you are removing a unique identifier for the submission of custom metrics. When two datapoints are submitted with the same timestamp/metric/tag combination and do not have unique identifiers, the last received/processed value overwrites the value stored. To avoid this edge case, ensure that no host is submitting the same exact metric/tag combination at any given timestamp.`

So we've seen only metrics from 1 instance instead of from 60 instances.

**Describe what you expected:**
Datadog should not bill for host tag or it should be possible to send data with the same hostname - and this should be treated as the same agent, the metrics should be summed up. 

**Steps to reproduce the issue:**
Start multiple Datadog Agents with the same hostname. Resulting count should be much lower than count for Datadog Agents with unique hostnames.

**Comment by kperchlicki** [comment]
Distribution metrics type solves that issue - closing

**Comment by atlas-comstock** [comment]
@crisperit I have tested it on my side recently, seems `Distribution metrics type` has the same issue.
