### ISSUE TITLE
Windows agent stop/start service commands inconsistency 

### ISSUE THREAD

**Issue by Cragdoo** [DataDog/datadog-agent#6569]
It there any particular reason the Windows agent stop/start commands are different

Stop command

agent.exe stopservice     (stops the agent within the service control manager)

Start command

agent.exe start-service   (starts the agent within the service control manager)

can we have either
stopservice
startservice

or

stop-service
start-service

**Comment by clarkb7** [comment]
fixed in https://github.com/DataDog/datadog-agent/pull/13870
