### ISSUE TITLE
loading OpenAPI spec for "v1beta1.external.metrics.k8s.io" failed with: OpenAPI spec does not exist

### ISSUE THREAD

**Issue by grosser** [DataDog/datadog-agent#6610]
in the kubernetes api server logs I see this message over and over ...
v1beta1.external.metrics.k8s.io points to datadog cluster agent (which is running)
is it maybe missing an openapi spec ? ... can we add a bogus spec to shut up the api server ?

**Comment by sudo-justinwilson** [comment]
I know in my case, I had an HPA that used external metrics, and was on the old `v1beta1.external.metrics` API. So you probably need to find the object that uses the deprecated API, and update it to the new API or delete it. 

This is what worked for me anyways..

**Comment by ugur-akkar** [comment]
Any update on this? I'm getting the same error from the API server.
`
E0525 14:25:08.608562       1 controller.go:116] loading OpenAPI spec for "v1beta1.external.metrics.k8s.io" failed with: OpenAPI spec does not exist
`
`
I0525 14:25:08.608594       1 controller.go:129] OpenAPI AggregationController: action for item v1beta1.external.metrics.k8s.io: Rate Limited Requeue.
`

**Comment by jeid64** [comment]
We get the same thing on EKS 1.20, it constantly happens.

**Comment by wd** [comment]
did have set the appkey? you need to set the appkey for that feature.

**Comment by grosser** [comment]
This is fixed for me in dca 1.14, so closing.
