### ISSUE TITLE
undefined: Asset while building from source

### ISSUE THREAD

**Issue by urosgruber** [DataDog/datadog-agent#6632]
I'm trying to build 7.19.2 but getting and error 

`src/github.com/DataDog/datadog-agent/pkg/status/render.go:132:19: undefined: Asset
`

I've read this is connected with go-bindata but I couldn't figure it out. Is there something I would need to run before `go build`?

**Comment by KSerrania** [comment]
Hi @urosgruber,

Thanks for the report! There are indeed some assets that need to be generated before building the Agent. We have an invoke task to do this: `invoke generate` (defined [here](https://github.com/DataDog/datadog-agent/blob/f6cbd32b3f6cdacac559ea4f8470590bf310ba6a/tasks/go.py#L377-L383)), which (in 7.19.2) does `go generate ./pkg/status`.

We recommend using our invoke tasks to build the Agent, as they're set up to do all the steps needed for the build. In your case, you can use `invoke deps` to fetch all needed go dependencies, and `invoke agent.build` to perform all necessary preliminary actions (such as the [go generate](https://github.com/DataDog/datadog-agent/blob/f6cbd32b3f6cdacac559ea4f8470590bf310ba6a/tasks/agent.py#L159-L160) part) & build the Agent binary (see [the code of the task](https://github.com/DataDog/datadog-agent/blob/f6cbd32b3f6cdacac559ea4f8470590bf310ba6a/tasks/agent.py#L82-L200) for details on what we do before building the Agent).

Note that using `invoke agent.build` will enable a default set of `go build` tags, which you can change by specifying the `--build-include` or `--build-exclude` parameters. See [our documentation](https://github.com/DataDog/datadog-agent/blob/7.19.2/docs/dev/agent_build.md#building-the-agent) for details.

For details on how to install `invoke`, see [our developer docs](https://github.com/DataDog/datadog-agent/blob/7.19.2/docs/dev/agent_dev_env.md#invoke--python-dependencies).

We'll update the developer docs in the near future to describe more precisely what are the current prerequisites to build the Agent binary.

**Comment by urosgruber** [comment]
Thanks @KSerrania  I think I found this after reading through tasks files. I'm working on a FreeBSD package and using invoke is not ideal. I'll close this since it's not an issue anymore.
