### ISSUE TITLE
Rename offensive default branch terminology from `master` to `main`

### ISSUE THREAD

**Issue by kebabman9001** [DataDog/datadog-agent#6670]
**Describe what happened:**
"master" is an offensive term, as it can be interpreted as being slavery-origin terminology. See https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns

**Describe what you expected:**
Branch should be called 'main'.

**Steps to reproduce the issue:**
Browse to https://github.com/DataDog/datadog-agent/

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by albertvaka** [comment]
Thanks for raising this issue @kebabman9001. This requires some changes to our internal tooling (since the `master` branch is hardcoded in several places), but it is something we want to do so we will get to it soon :)

**Comment by albertvaka** [comment]
Also, if we wait a bit it seems we can benefit from Github's "seamless renaming" [1] once that's implemented.

[1] https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by mx-psi** [comment]
This is now done
