### ISSUE TITLE
[system-probe] Error on different kernel name 

### ISSUE THREAD

**Issue by sebastian-rojas** [DataDog/datadog-agent#6672]
https://github.com/DataDog/datadog-agent/blob/19d1c63003ab4adf431891eeeace52f066636d56/pkg/ebpf/utils_linux.go#L77

Hello, 

Currently leveraging "OVH". They seem to have their own naming structure for the kernel. i.e., `uname -r
4.19-ovh-xxxx-std-ipv6-64` 

sys-probe is having the following error: 
```2020-11-02 02:00:15 UTC | SYS-PROBE | ERROR | (cmd/system-probe/loader.go:39 in Register) | new module `network_tracer` error: system-probe unsupported: could not get kernel version: got invalid release version "4.19-ovh-xxxx-std-ipv6-64" (expected format '4.3.2-1')```

**Comment by brycekahle** [comment]
@sebastian-rojas Sorry for the long delay, but this was fixed in 7.25.0

**Comment by ti-mo** [comment]
@sebastian-rojas Do you still have this machine around? Could I ask what the output of `uname -v` and `uname -a` is? (feel free to censor hostnames) Thanks!
