### ISSUE TITLE
OSGi components not getting started when the dd-java-agent-0.67.0.jar added

### ISSUE THREAD

**Issue by deelaka96** [DataDog/datadog-agent#6750]
Hi All,

We are using OSGI based products in our environment and we wanted to add data dog agent.
We have added the latest **dd-java-agent-0.67.0.jar** configured in our product and we have observed that a few of our OSGi components not getting activated. Ex:- Components in **Unsatisfied** state

`208	Unsatisfied		org.wso2.carbon.registry.info			org.wso2.carbon.registry.info(bid=566)`
`215	Unsatisfied		org.wso2.carbon.registry.task			org.wso2.carbon.registry.task(bid=583`

Also, we have observed a few imports added to our OSGi bundles.
`org.glassfish.grizzly.filterchain; version="1.7.0"<tyrus-standalone-client_1.7.0.wso2v1 [721]>
 com.google.common.util.concurrent; version="20.0.0"<com.google.guava_20.0.0 [36]>
 org.springframework.beans.factory.support; version="3.2.9.wso2v1"<spring.framework_3.2.9.wso2v1 [702]>
 org.springframework.context.support; version="3.2.9.wso2v1"<spring.framework_3.2.9.wso2v1 [702]>
 org.springframework.web.context; version="3.2.9.wso2v1"<spring.framework_3.2.9.wso2v1 [702]>`

Also, we did not observe this issue when we configure the **older version** of data dog java agent in our environment.

Can the data dog agent related to the above-mentioned behavior.

Highly appreciate your support on the issue soon.

Regards,
Deelaka

**Comment by mcculls** [comment]
Hi Deelaka, could you provide more details about which OSGi framework you're using? (to help us try and recreate the issue)

**Comment by mcculls** [comment]
Also this repository is for the main agent, not the different language support - the repository for the Java tracer agent is https://github.com/DataDog/dd-trace-java so I'd suggest re-opening this issue over there where we can continue the investigation - thanks

**Comment by mcculls** [comment]
Thanks for opening the other issue - going to close this one now and will post updates over there
