### ISSUE TITLE
DD Agent does not retry resource tags collection for containers on ECS

### ISSUE THREAD

**Issue by psviderski** [DataDog/datadog-agent#6758]
Hi,

We have a problem with Datadog StatsD metrics missing tags when a new ECS task or instance is started. This happens randomly with less than 1% of metrics. We run our services in containers in AWS ECS, with each Container Instance (i.e. EC2 instance) having 1 datadog agent as a daemon task. Containers send StatsD metrics through a socket to the datadog agent. The datadog agent is configured to collect AWS tags of the tasks and EC2 instances (`DD_ECS_COLLECT_RESOURCE_TAGS_EC2`).
it looks like when datadog agent starts it sometimes doesn't collect tags of AWS resources such as EC2 instances and ECS tasks. This happens rarely (<1% of the time) and unpredictably and persists until the agent is restarted.

There is a corresponding Datadog support ticket (#402133). I'm creating this GH issue to provide some more technical details. I've done a lot of experiments and checked the source code of the datadog agent and here is the explanation of what is going wrong and why we lose tags.

## Tags caching

First, I would like to clarify the Datadog agent behaviour. When a new container starts on the host the agent tries to get tags for this container entity. If it succeeds the tags for this container are cached in memory and never fetched again. If it fails it will retry to fetch tags later until it succeeds. Here is the corresponding source code: [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/tagger.go#L234-L280](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/tagger.go#L234-L280)
The caching part is crucial here, please correct me if I'm wrong.

## How ECS tags get fetched

Let's dig deep into how the ECS tags get fetched for a single container entity. The entry point is `ECSCollector.Fetch` method: [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L75](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L75)
What it does:

1. Calls the `/v1/tasks` endpoint on the ECS agent running on the underlying host to get a list of tasks and their containers running on the host.
2. Checks whether the setting to collect resource tags `ecs_collect_resource_tags_ec2` is enabled and the metadata endpoint in ECS exposes resource tags: [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L88](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L88)
3. Parses the response got in 1. and looks up the task and the target container. Creates a list of tags from this data, e.g. `task_name`, `ecs_container_name`, etc. [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_extract.go#L19](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_extract.go#L19)
4. If the collection of resource tags is configured and supported, calls additional handler `addTagsForContainer`: [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L116-L124](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L116-L124) to collect tags set on the ECS task and instance using the `/v3/<uuid>/taskWithTags` endpoint on the ECS agent. Then adds the received tags to the resulting list of tags.
5. If `addTagsForContainer` in 4. fails to get tags from ECS metadata endpoint, only logs a warning "Unable to get resource tags for container..." but does not return any errors: [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L118-L121](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/tagger/collectors/ecs_main.go#L118-L121)
6. Returns the resulting list of tags.

## Problems

1. The check whether the metadata endpoint in ECS exposes resource tags [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/util/ecs/detection.go#L83-L88](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/util/ecs/detection.go#L83-L88) can sometimes return `false`. This is possible just because it calls the `v3/<uuid>/taskWithTags` endpoint on the ECS agent which can fail with `Client.Timeout`. Note that at the moment the v1 and v3 client timeouts are 0.5 seconds and they are not configurable. This indeed sometimes happens in our case, especially on massive redeployments of all our ECS services or on datadog-agent restart. Apparently, the datadog agent tries to collect tags for all containers started/running on the host at once and this creates a sufficient load on the ECS agent (that serves the ECS metadata endpoints) to not being able to respond to each request in 0.5s. Note that the ECS agent in order to reply on `/taskWithTags` need to send at least 2 API calls to ECS API to get tags for the container instance and for the task, see: [https://github.com/aws/amazon-ecs-agent/blob/3776bee911c2267dedce46a9d2a17007f0bd73ae/agent/handlers/v2/response.go#L143-L163](https://github.com/aws/amazon-ecs-agent/blob/3776bee911c2267dedce46a9d2a17007f0bd73ae/agent/handlers/v2/response.go#L143-L163).
The logic of `HasEC2ResourceTags()` check is such that if it returned `false` at least once, the result is cached indefinitely: [https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/util/ecs/detection.go#L138](https://github.com/DataDog/datadog-agent/blob/666c775b3b0b408bc8ba4593f420fd526cd841a1/pkg/util/ecs/detection.go#L138)
This means that after it fails once all metrics for all new containers on the host will be missing ECS tags because `addTagsForContainer` won't be called, see 4. This is obviously very bad.\
\
The fix prepared by the Datadog engineering team for us partially resolves this problem: [https://github.com/DataDog/datadog-agent/compare/7.23.x...7.23-ecs-ec2-tags-expiry](https://github.com/DataDog/datadog-agent/compare/7.23.x...7.23-ecs-ec2-tags-expiry). In case of failure the check result will be cached for 5 minutes meaning that all new containers will be missing ECS tags for only 5 minutes given that the next check in 5 minutes passes. This is better than it was before but still not ideal.

2. Another problem is item 5. If `addTagsForContainer` in 4. fails to get tags for a particular container from the ECS metadata endpoint (ECS agent running on the underlying host), e.g. due to client timeout, only the generic tags got in 3. are used and cached for the container. The agent will never retry to get ECS tags for that container again. We can see a lot of related logs confirming this behaviour:
    ```
    (pkg/tagger/collectors/ecs_main.go:124 in addTagsForContainer) | Unable to get resource tags for container 8bd7b34e144be4f1793e49914ad38066260bb0108af9341d70036e9eecc00dd5: failed to get task with tags from metadata v3 API: Get "[http://169.254.170.2/v3/645db862-98f2-4116-b342-564414e09994/taskWithTags](http://169.254.170.2/v3/645db862-98f2-4116-b342-564414e09994/taskWithTags)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
    ```
    I think this behavior is wrong. If the user configured collection of resource logs by setting `DD_ECS_COLLECT_RESOURCE_TAGS_EC2`, the agent should collect them no matter what. If it fails it should retry later until succeeds.

## Workaround

I've implemented a few fixes/workarounds for both of these problems in my branch. You can see the changes here: [https://github.com/psviderski/datadog-agent/compare/7.23.x..pavel/7.23.1-ecs-tags-pavel-fix](https://github.com/psviderski/datadog-agent/compare/7.23.x..pavel/7.23.1-ecs-tags-pavel-fix). They are pretty simple:

1. Made the `HasEC2ResourceTags` check to always pass without calling `/taskWithTags` as I'm sure that the metadata endpoint in our ECS clusters exposes resource tags.
2. Increased the default timeouts for v1 and v3 ECS clients 0.5s → 5s.
3. Made the `addTagsForContainer` handler that collects tags for containers propagate an error if it fails to get tags from the ECS metadata endpoint. This error makes the `ECSCollector.Fetch` method to fail which forces the agent to not cache the incomplete tags for a container and retry tags collection later until it succeeds.

1 addresses the first problem. 2 and 3 address the second problem.

We have been running the datadog agent built from my branch for several days in our `dev` cluster and it seems to solve the issue with missing tags. We plan to test it in a bigger production cluster next week.

My change doesn't pretend to be merged to the upstream repo as is. I hope it can help you implement proper fixes for the problems I pointed out. Please let me know if you don't agree with something or need any additional information. I'm happy to raise a PR if you are happy with some of my changes or can tell me what to change.

**Comment by koreissm** [comment]
Hey @psviderski 
Thank you for opening this issue with all these details. We're currently working on it and we will provide updates directly in the ticket if that's okay with you.

**Comment by xornivore** [comment]
Hi @psviderski, thank you for such a detailed investigation and the PR. Let me hash out some ideas with my team based on your suggestions. Will get back to you shortly. We may have a couple of follow-up questions in the support ticket.

**Comment by xornivore** [comment]
Hi @psviderski a couple of clarifications on the investigation and the PR:
a) We can possibly make the ECS api client timeout configurable, I am curious to hear if just increasing the timeout in combination with the changes from [7.23-ecs-ec2-tags-expiry](https://github.com/DataDog/datadog-agent/compare/7.23.x...7.23-ecs-ec2-tags-expiry) solves the problem in your environment.
b) On the tags expiry logic:
> When a new container starts on the host the agent tries to get tags for this container entity. If it succeeds the tags for this container are cached in memory and never fetched again.
We do refresh tags again when they expire in the ECSCollector, this is driven by the calls to the collector, so one potential issue is with a steady state when there aren't any new containers created and their tags are cached, since ECSCollector is a fetch only one, we would not be triggering this expiry. It is likely that's what you are seeing.
c) Adding retry logic around `HasEC2ResourceTags` - it probably makes sense to move it to be inside the initialization of `ECSCollector` since it will never change, but we cannot get rid of this check entirely since we have to support older ECS agent version.
d) Regarding the change to return the error [here](https://github.com/psviderski/datadog-agent/compare/7.23.x..pavel/7.23.1-ecs-tags-pavel-fix#diff-90c61af6df3468a7868aec7344837c926185a94f02b5db0fa7ad0fc0e888791cR47), this affects the logic for updating tags on expiry. However we are currently discussing another option where we can report a `TaggerInfo` (with incomplete tags due to failure to fetch resource tags) but skip caching it in the tag store.

**Comment by psviderski** [comment]
@xornivore Thank you for getting back to me.
a)
> We can possibly make the ECS api client timeout configurable, I am curious to hear if just increasing the timeout in combination with the changes from 7.23-ecs-ec2-tags-expiry solves the problem in your environment.
I doubt that it will fully resolve the issue as we are still getting the following logs on our custom datadog agent version after increasing the timeout to 5s:
```
(pkg/tagger/collectors/ecs_main.go:124 in addTagsForContainer) | Unable to get resource tags for container 8bd7b34e144be4f1793e49914ad38066260bb0108af9341d70036e9eecc00dd5: failed to get task with tags from metadata v3 API: Get "[http://169.254.170.2/v3/645db862-98f2-4116-b342-564414e09994/taskWithTags](http://169.254.170.2/v3/645db862-98f2-4116-b342-564414e09994/taskWithTags)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
This means that there will be containers with missing tags for at least 5 minutes given the next attempt to invalidate the cache and fetch tags is triggered and it succeeds. I think proper retries at the upper level still need to be implemented to not cache incomplete data.

b) Thanks for clarifying the behaviour of the `ECSCollector` cache.

c) Agreed that it makes sense to do this check only once on the collector initialization.

d) 
>Regarding the change to return the error here, this affects the logic for updating tags on expiry.

Can you please clarify how it affects specifically, what will happen if `Fetch` returns an error propagated from the `addTagsForContainer` handler? Isn't this essentially a reset to the initial state when a container has just started?

>However we are currently discussing another option where we can report a TaggerInfo (with incomplete tags due to failure to fetch resource tags) but skip caching it in the tag store.

This sounds interesting 👍

**Comment by xornivore** [comment]
Hi @psviderski , I apologize it too a while to get back to you on this. 

Short term, we have the following two changes available in Datadog Agent 7.25:
https://github.com/DataDog/datadog-agent/pull/6865
https://github.com/DataDog/datadog-agent/pull/6828

While understandably it won't completely resolve the problem it should minimize these issues.

Regarding the ECS agent serving requests with 5s latency - I would recommend investigating this issue on the AWS.

Regarding c) unfortunately this becomes problematic with live updates of ECS Agent, if it gets updated and restarts and we store this property indefinitely and the agent will not be able to leverage the new endpoints.

Longer term we plan to investigate using [ECS container metadata files](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html) instead of ECS Agent metadata API to overcome some of these issues. It is quite early to say when we can provide a solution using this approach but I will update this issue here when we do.

**Comment by psviderski** [comment]
FYI, AWS released `v4/taskWithTags` endpoint that fixed an issue with returning an error when ecs agent fails to fetch tags from ECS API: https://github.com/aws/amazon-ecs-agent/issues/2728#issuecomment-767693723. This is not directly related to this issue but might be considered for longer-term changes/refactoring.

@xornivore Is there any chance we can incorporate this patch into the upstream that forces the DD agent to retry fetching tags if it fails?
https://github.com/psviderski/datadog-agent/commit/0e48b04685161a09baf416845d59078e480c3cd1#diff-90c61af6df3468a7868aec7344837c926185a94f02b5db0fa7ad0fc0e888791cR19-R48

We still quite regularly see the following logs:
```
PROCESS | WARN | (pkg/tagger/collectors/ecs_main.go:122 in addTagsForContainer) | Unable to get resource tags for container 527e8e37a77c808ec1517bcf8432d1b7760d412a021e6535a1d8906d1b637b73: failed to get task with tags from metadata v3 API: Get "http://169.254.170.2/v3/30f1da32-b417-4c5d-b175-4099f796b9c0/taskWithTags": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
<img width="1308" alt="Screen Shot 2021-04-14 at 12 07 32 pm" src="https://user-images.githubusercontent.com/783910/114645579-16f99580-9d1d-11eb-816b-b0041c555856.png">

**Comment by clamoriniere** [comment]
Hello @psviderski ,

Thank you for pinging us on this issue with the results of your investigations.
Unfortunately, we don't have yet implement the client to support the AWS API v4.
About the patch, I think I got the idea, But we should be careful when it returns an error [here](https://github.com/psviderski/datadog-agent/commit/0e48b04685161a09baf416845d59078e480c3cd1#diff-90c61af6df3468a7868aec7344837c926185a94f02b5db0fa7ad0fc0e888791cR47) because it will block the creation/update of the others tags. I would prefer that it keeps a list of errors that appended during the for loop, and at the end of the function if the list of errors is not empty it returns an error.
I can create a card in our backlog to implement the fix that I describe based on your patch. Or you can open a PR if you would like.
WDYT?

**Comment by psviderski** [comment]
This sounds good to me however I didn't dive deep into the codebase so I don't have the full context to well understand the consequences of a particular change. I'd be very happy if you can implement it properly.

**Comment by boh-dan** [comment]
Hi @clamoriniere, it seems that the fix provided by @juliogreff leads to another problem that causes sever tag loss. We already had this problem and did our own investigation, please take a look at this issue https://github.com/DataDog/datadog-agent/issues/8341
