### ISSUE TITLE
Missing apostrophes in tags

### ISSUE THREAD

**Issue by przemolb** [DataDog/datadog-agent#6767]
I have been looking at the example DD agent config file and it seems that there are missing apostrophes in the tags section:
https://github.com/DataDog/datadog-agent/blob/ddf35c194d4837c9091bb145066a1868a4c4d924/pkg/config/config_template.yaml#L68

**Comment by olivielpeau** [comment]
Hi @przemolb, in this example adding apostrophes is semantically identical YAML:

```yaml
tags:
  - environment:dev
  - <TAG_KEY>:<TAG_VALUE>
```
is semantically the same as:
```yaml
tags:
  - "environment:dev"
  - "<TAG_KEY>:<TAG_VALUE>"
```

(that said, if there were a whitespace after `<TAG_KEY>:`, apostrophes would be required to interpret it as a string).

Hope this clarifies things, I'll go ahead and close this.
