### ISSUE TITLE
datadog agent is running but that host is not showing up in Datadog UI Console

### ISSUE THREAD

**Issue by chakreshkolluru** [DataDog/datadog-agent#6786]
Datadog agent is running in the system but that is not being displayed in Infrastructure Hosts and also metrics are not present.

I feel the data is not being sent to site.

I'm not able to find out the issue.

Can any one help me with this issue.

**Comment by olivielpeau** [comment]
Hi @chakreshkolluru,

For your request, please contact our [support](http://docs.datadoghq.com/help/) and send them your [logs](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare).
Thanks.
