### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by roryodonnell** [DataDog/datadog-agent#679]
I'm not sure if it's my issue or not, but I'm new to GO and had issues following the README.md instructions.

I cloned the beta 6 repo into %GOPATH as instructed and the system would not build.

To correct, I cloned into $GOPATH/src/github.com/DataDog

Hope that helps someone else

**Comment by masci** [comment]
@roryodonnell thanks for reporting! 
The instructions should be more clear indeed, I'll fix the README

**Comment by roryodonnell** [comment]
No probs - thanks for the rapid reponse
