### ISSUE TITLE
Collect new EC2 network performance metrics

### ISSUE THREAD

**Issue by bscanlan** [DataDog/datadog-agent#6957]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-network-performance.html

AWS announced a few new metrics that are collectable via ethtool. It'd be great if the agent natively supported collecting these instead of having to add them myself.

**Comment by bkabrda** [comment]
Hi 👋 thanks for opening an issue for it. I did this in https://github.com/DataDog/integrations-core/pull/8331 which should be released with agent 7.26.0. I'm closing this issue as there is nothing more to be done here.
