### ISSUE TITLE
tracing-agent: API key sanitization

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#6961]
There are many places in Datadog Agent code base where API key is read from config structs. It is sanitized in [some cases](https://github.com/DataDog/datadog-agent/blob/570ac79334d1e0306485335ad8073481c9954159/pkg/trace/config/apply.go#L154), but [not others](https://github.com/DataDog/datadog-agent/blob/570ac79334d1e0306485335ad8073481c9954159/pkg/trace/config/apply.go#L125). That costed me quite some time debugging (see #6960). I wonder if this is intentional or should be fixed? It seems like centralizing the API key reads would be a good solution, but I'm reluctant to do the change because it'd touch a lot of files and is thus unlikely to get accepted.

**Comment by knusbaum** [comment]
We should probably be sanitizing the key whenever we use it, or maybe we should sanitize it when reading the config.
