### ISSUE TITLE
trace-agent: Change the log level at runtime

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#6962]
It appears to be impossible to change tracing-agent's log level at runtime. Datadog Agent has this feature and it'd be great if it got ported to tracing-agent as well.

Changing the log level in containerized environments is a lot of pain. In my particular case the instance was a part of a Kubernetes DaemonSet with over 100 nodes in the cluster. I failed to come up with anything expedient other than changing the log level for the entire cluster. It was an OK thing to do in QA, but doing that in production would be very risky and costly.

**Comment by andrewsouthard1** [comment]
Hey @deadok22 - thanks reaching out regarding this request. The use of this feature is definitely clear and something we have on our backlog. We won't be able to prioritize this in the short term however we'll leave this open and welcome any community PR to resolve.
