### ISSUE TITLE
opentelemetry exporter support for .net application

### ISSUE THREAD

**Issue by sumantfordev** [DataDog/datadog-agent#7092]
currently opentelemetry support for using datadg asa exporter is supported in python, go and nodejs. I wanted to check if its possible in any other way to export .net applications traces to datadog, Probably some how using OpenTelemetry Protocol?

**Comment by mx-psi** [comment]
Hi @sumantfordev, to export traces from .NET applications to Datadog you can use the OpenTelemetry .NET SDK to send traces to the OpenTelemetry Collector Contrib, which will send them to Datadog. That is, you need to set up:

1. The [OpenTelemetry .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet#getting-started). You can follow the docs [here](https://opentelemetry.io/docs/net/getting-started/). You can use the [.NET OTLP exporter](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.OpenTelemetryProtocol) to export to the Collector.
2.  The [OpenTelemetry Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib). You can follow our docs [here](https://docs.datadoghq.com/tracing/setup_overview/open_standards/#opentelemetry-collector-datadog-exporter).

I hope that helps!
