### ISSUE TITLE
Add APM obfuscation env vars

### ISSUE THREAD

**Issue by sbward** [DataDog/datadog-agent#7183]
**Describe what happened:**

There are several APM obfuscation options that are not available as env vars:
```
apm_config.obfuscation.elasticsearch.enabled
apm_config.obfuscation.elasticsearch.keep_values
apm_config.obfuscation.elasticsearch.obfuscate_sql_values
apm_config.obfuscation.mongodb.enabled
apm_config.obfuscation.mongodb.keep_values
apm_config.obfuscation.mongodb.obfuscate_sql_values
apm_config.obfuscation.sql_exec_plan.enabled
apm_config.obfuscation.sql_exec_plan.keep_values
apm_config.obfuscation.sql_exec_plan.obfuscate_sql_values
apm_config.obfuscation.sql_exec_plan_normalize.enabled
apm_config.obfuscation.sql_exec_plan_normalize.keep_values
apm_config.obfuscation.sql_exec_plan_normalize.obfuscate_sql_values
apm_config.obfuscation.http.remove_query_string
apm_config.obfuscation.http.remove_paths_with_digits
apm_config.obfuscation.remove_stack_traces
apm_config.obfuscation.redis.enabled
apm_config.obfuscation.memcached.enabled
```

**Describe what you expected:**

We need to use these options in containerized environments where we use env vars to configure the agent.
The env var names should probably follow the pattern `DD_APM_OBFUSCATION_*`.
For example, `DD_APM_OBFUSCATION_REMOVE_STACK_TRACES` would correspond to `apm_config.obfuscation.remove_stack_traces`.

**Steps to reproduce the issue:**

Attempting to use env var names for obfuscation doesn't set the option.

For example, in a Fargate task, the following doesn't work.
```
"environment": [
        {
                "name": "DD_APM_OBFUSCATION_REMOVE_STACK_TRACES",
                "value": "true"
        },
        // ... other env vars ...
],
```

**Additional environment details (Operating System, Cloud provider, etc):**

We use Fargate but this applies for any environment where env vars are preferred over `datadog.yaml`

**Comment by sujeets-toast** [comment]
I configures the datadog with ecs fargate. But in url digits value replaced by ?
How I can disabled the remove_paths_with_digits using ecs fargate datadog in aws.
What is the environment variable name.

**Comment by dsambugaro** [comment]
Any updates on that?

**Comment by ammmr** [comment]
Do you have any work on this issue?

**Comment by nebula28** [comment]
Any update on this?

**Comment by ajgajg1134** [comment]
Sorry for the delay here, this issue was resolved in this PR: https://github.com/DataDog/datadog-agent/pull/17695
