### ISSUE TITLE
How to disable collect Infrastructure host metrics

### ISSUE THREAD

**Issue by 4n70w4** [DataDog/datadog-agent#7195]
Hi! I found question on https://www.datadoghq.com/pricing/?product=log-management#log-management

> Can I subscribe to Log Management without using Datadog Infrastructure or APM?
> Having all your infrastructure, APM, and log data under one roof is something we definitely encourage, but you can also subscribe only to Datadog’s Log Management. Learn how to configure only log collection here.

with link https://docs.datadoghq.com/logs/faq/can-the-datadog-agent-be-used-to-send-only-logs/

But this page is no longer available and a redirect to https://docs.datadoghq.com/agent/ is no answer to the question. 

So How use Log Management without using Datadog Infrastructure and disable collect Infrastructure host metrics?

**Comment by olivielpeau** [comment]
Hi @4n70w4, thanks for reporting this!

This docs page has moved to https://docs.datadoghq.com/logs/guide/how-to-set-up-only-logs, I'll follow up to make sure the link at https://www.datadoghq.com/pricing/?product=log-management#log-management is updated.

**Comment by olivielpeau** [comment]
The link in the FAQ entry of https://www.datadoghq.com/pricing/?product=log-management#log-management has been updated accordingly, so closing this issue, thanks again @4n70w4!
