### ISSUE TITLE
Unable to use EKS IAM roles for service accounts due to credential loading override

### ISSUE THREAD

**Issue by nairb774** [DataDog/datadog-agent#7225]
**Describe what happened:**

In an effort to remove all policies from the Instance Profile running our EKS cluster, I discovered that the `ec2:DescribeTags` permission is needed by the Datadog Agent to determine the tags on the currently running host. Normally I would provision a IAM role for the Kubernetes ServiceAccount that the Datadog Agent is running under via the [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) feature and attach the relevant policies to that role. Unfortunately this isn't possible as the Datadog Agent is acquiring and explicitly proving credentials only sources from the instance profile: https://github.com/DataDog/datadog-agent/blob/4b0e5f7cbc648166d2af6b9c09cea68bbd21bc77/pkg/util/ec2/ec2_tags.go#L48

This means that when the pod is started, and the `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` environment variables are injected into the container, the agent fails to make use of that role and subsequently has no access to the relevant AWS APIs that it wants.

**Describe what you expected:**

To be able to configure the AWS SDK used by the Datadog Agent in the same way as every other application that uses the AWS SDK. Looking at the code, it is entirely possible that setting the `Credentials` attribute of the Session could just be dropped: https://github.com/DataDog/datadog-agent/blob/4b0e5f7cbc648166d2af6b9c09cea68bbd21bc77/pkg/util/ec2/ec2_tags.go#L48 One of the default locations that the AWS SDK looks for credentials is in the EC2 metadata among a number of other places. There would be an additional positive effect of less custom code in the agent. It might even be possible to replace the code talking to the Instance Metadata service with the package available in the AWS SDK that provides this interface: https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/

**Steps to reproduce the issue:**

Fastest way is to remove `AmazonEKS_CNI_Policy` from the worker node role following the instructions provided at https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

**Additional environment details (Operating System, Cloud provider, etc):**

A mostly normal AWS EKS cluster following the additional steps described in https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html This is where EKS nodes were previously picking up the `ec2:DescribeTags` permissions, and going forward it seems that they are suggesting that people not configure the CNI policy on nodes any more, which means some of the tagging/detection features that this code is intending to provide are likely going to break unexpectedly: https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html

**Comment by gregsymons** [comment]
The section of code discussed here is also implicated in #6171 and (probably) #7002 . Even though the cluster agent isn't trying to get these particular tags yet (the first bug listed in #7002), once it does, it will fail to detect the cluster name for the same reason we're seeing here, I suspect.

These bugs make working with the canned Kubernetes dashboards challenging.

**Comment by groodt** [comment]
We are seeing this issue as well. Is there any ETA on a fix for this?

**Comment by olivielpeau** [comment]
Thanks @nairb774 and @gregsymons for the additional context here, this limitation (of the Datadog Agent) will be addressed by https://github.com/DataDog/datadog-agent/pull/8141

**Comment by chrispsplash** [comment]
FYI this won't work unless your config forces IMDS for tag collection.  I'm using cluster agent 1.22.0 and finally got it working with this config file:
```
cloud_provider_metadata:
      - aws
collect_ec2_tags_use_imds: true
collect_ec2_tags: true
ec2_prefer_imdsv2: true
```
