### ISSUE TITLE
persistent installation failures on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by shaochieh** [DataDog/datadog-agent#7256]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
was trying a new installation on my ubutu 1804 vm (virtualbox). keep hitting this error:

```
Get:1 https://apt.datadoghq.com stable/7 amd64 datadog-agent amd64 1:7.25.0-1 [205 MB]
Err:1 https://apt.datadoghq.com stable/7 amd64 datadog-agent amd64 1:7.25.0-1
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:f67f6b7b8eb8d404f2bc43d2cc8011ea4347c3e0edae107514b91d36f2928ffd
   - SHA1:1d833f433a7886e13c8e2f394e3b331900f73d8f [weak]
   - MD5Sum:563e073a8dcc2d2e4b57b2f262aecd31 [weak]
   - Filesize:204954718 [weak]
  Hashes of received file:
   - SHA256:23c62624528490e213d581dcd634456fca3e1e172265bfd435ef07b6e1cc2fec
   - SHA1:d4583e8ea78de2c07dca8a59af52678047216549 [weak]
   - MD5Sum:b2a047678d9fb81b4220e70fb7d60e35 [weak]
   - Filesize:204954718 [weak]
  Last modification reported: Thu, 14 Jan 2021 18:21:28 +0000
Fetched 205 MB in 41s (4940 kB/s)
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch https://apt.datadoghq.com/pool/d/da/datadog-agent_7.25.0-1_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:f67f6b7b8eb8d404f2bc43d2cc8011ea4347c3e0edae107514b91d36f2928ffd
    - SHA1:1d833f433a7886e13c8e2f394e3b331900f73d8f [weak]
    - MD5Sum:563e073a8dcc2d2e4b57b2f262aecd31 [weak]
    - Filesize:204954718 [weak]
   Hashes of received file:
    - SHA256:5f97a4d22d1bcdab87229d2c7bead079ab6e71cfbc4a0c383326e81599805160
    - SHA1:5cba05c902c3d641a74c0b862e85852f7ef5aaca [weak]
    - MD5Sum:5297b3d8b430f7bb5e53d204caf66137 [weak]
    - Filesize:204954718 [weak]
   Last modification reported: Thu, 14 Jan 2021 18:21:28 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
**Describe what you expected:**
the installation script should be thru

**Steps to reproduce the issue:**
was just following the documentation
https://app.datadoghq.com/signup/agent#ubuntu

```
DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=e42b86501ad0d04d810e2dccf39e3796 DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
```
even tried with prepending ```sudo``` and appending ```--alow``` and still got the same error.

appending ```DD_INSTALL_ONLY=true``` wouldn't work, either.

**Additional environment details (Operating System, Cloud provider, etc):**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

$ pwd
/etc/apt
$ cat sources.list.d/datadog.list
deb https://apt.datadoghq.com/ stable 7

steps I tried before executing the convenient script:
sudo rm -rf /var/lib/apt/lists/*
sudo find /var/lib/apt/lists/ -name "*datadog*" -delete
sudo apt-get clean
sudo apt-get update (--fix-missing)
sudo apt-get upgrade
```
i  might try another one with clean ubuntu 1604 or AWS Linux

**Comment by shaochieh** [comment]
AWS Linux is thru without issues.

**Comment by shaochieh** [comment]
could not install docker-ce, either. maybe something wrong with my local ubuntu vm. proceeding with fresh 1604 install.

**Comment by sgnn7** [comment]
Hey @shaochieh, thank you for contributing to DataDog!

I tried downloading that exact file here and got the expected checksum:
```
$ sha256sum ~/Downloads/datadog-agent_7.25.0-1_amd64.deb
f67f6b7b8eb8d404f2bc43d2cc8011ea4347c3e0edae107514b91d36f2928ffd datadog-agent_7.25.0-1_amd64.deb
```

This matches exactly the `expected file` hash of `f67f6b7b8eb8d404f2bc43d2cc8011ea4347c3e0edae107514b91d36f2928ffd`. Because of this, I think that your hunch that the problem may be related to the VM is highly likely.

With that in mind, I will close this issue but in the case that the problem lies somewhere on the DataDog network/hosting side (unlikely but plausible), please reopen this issue and we will look into it.

Thanks!
Srdjan

**Comment by shaochieh** [comment]
you're right.... installation with 16.04 is blissful. let's just keep an eye on it. was struggling with 18.04 vm installation anyway like virtualbox addition and stuff.
