### ISSUE TITLE
ARM64 version of DataDog cluster-agent isn't published

### ISSUE THREAD

**Issue by korbin** [DataDog/datadog-agent#7295]
**Describe what happened:**
When deploying DataDog to a new EKS cluster running AWS Graviton2 instances, the DataDog `cluster-agent` pod does not start with an exec format error.

https://hub.docker.com/r/datadog/cluster-agent does not appear to have an arm64 image (datadog/agent has many architectures!)

**Describe what you expected:**

I expected cluster-agent to be published as an arm64 container image.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.18 - m6g instances

**Comment by L3n41c** [comment]
The `datadog/cluster-agent` `1.11.0` has been published few days ago and this version has been released for both `amd64` and `arm64`.
