### ISSUE TITLE
datadog agent build fails due to missing include paths

### ISSUE THREAD

**Issue by nostaw-kgm** [DataDog/datadog-agent#7326]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
I'm trying to build the datadog agent on a Raspberry Pi running 32-bit Ubuntu Server 20.04 (armhf architecture). 

I followed the directions for cloning and building per the readme.md. When I run the invoke agent.build command I see the build stops with an error indicating it can't find a header file. Did a little triage work and it appears the problem is the build doesn't have the include paths set right to pick up the file from the directory it's located in.

Here is the build output:
`
ubuntu@ubuntu:/space/datadog-agent$ invoke agent.build --build-exclude=systemd  --python-runtimes 3
-- Configuring done
-- Generating done
-- Build files have been written to: /space/datadog-agent/rtloader/build
make: Entering directory '/space/datadog-agent/rtloader/build'
make[1]: Entering directory '/space/datadog-agent/rtloader/build'
make[2]: Entering directory '/space/datadog-agent/rtloader/build'
make[2]: Leaving directory '/space/datadog-agent/rtloader/build'
[ 25%] Built target datadog-agent-rtloader
make[2]: Entering directory '/space/datadog-agent/rtloader/build'
make[2]: Leaving directory '/space/datadog-agent/rtloader/build'
[100%] Built target datadog-agent-three
make[1]: Leaving directory '/space/datadog-agent/rtloader/build'
make: Leaving directory '/space/datadog-agent/rtloader/build'
make: Entering directory '/space/datadog-agent/rtloader/build'
make[1]: Entering directory '/space/datadog-agent/rtloader/build'
make[2]: Entering directory '/space/datadog-agent/rtloader/build'
make[2]: Leaving directory '/space/datadog-agent/rtloader/build'
[ 25%] Built target datadog-agent-rtloader
make[2]: Entering directory '/space/datadog-agent/rtloader/build'
make[2]: Leaving directory '/space/datadog-agent/rtloader/build'
[100%] Built target datadog-agent-three
make[1]: Leaving directory '/space/datadog-agent/rtloader/build'
Install the project...
-- Install configuration: ""
-- Up-to-date: /space/datadog-agent/dev/lib/libdatadog-agent-three.so
-- Up-to-date: /space/datadog-agent/dev/lib/libdatadog-agent-rtloader.so.0.1.0
-- Up-to-date: /space/datadog-agent/dev/lib/libdatadog-agent-rtloader.so.1
-- Up-to-date: /space/datadog-agent/dev/lib/libdatadog-agent-rtloader.so
-- Up-to-date: /space/datadog-agent/dev/include/datadog_agent_rtloader.h
-- Up-to-date: /space/datadog-agent/dev/include/rtloader_types.h
-- Up-to-date: /space/datadog-agent/dev/include/rtloader_mem.h
make: Leaving directory '/space/datadog-agent/rtloader/build'
templates.go
templates.go
go generate ran successfully
# github.com/DataDog/datadog-agent/pkg/collector/python
pkg/collector/python/aggregator.go:18:10: fatal error: datadog_agent_rtloader.h: No such file or directory
   18 | #include <datadog_agent_rtloader.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`
I tried editing pkg/collector/python/aggregator.go so that it had a fully qualified path to the file and the build failed with a different include file missing which is why I believe the problem is missing include path setting somewhere.

**Describe what you expected:**
Expected the build to work.

**Steps to reproduce the issue:**
Clone the repository from github, follow the directions to build the agent as shown above.

**Additional environment details (Operating System, Cloud provider, etc):**
Raspberry Pi running 32-bit Ubuntu Server 20.04 (armhf architecture)

**Comment by mokemoko** [comment]
I encountered the same problem.
In my case, it seems that `CGO_CFLAGS` was not set correctly because I cloned the source code into the wrong path without following the documentation. (Described below)

````
Checkout the repo: git clone https://github.com/DataDog/datadog-agent.git $GOPATH/src/github.com/DataDog/datadog-agent.
````

Also, the `CGO_CFLAGS` setting seems to be controlled by the `embedded_path` / `rtloader_root` options, so you might want to try changing those values.

**Comment by sgnn7** [comment]
Hey @nostaw-kgm, @mokemoko,
This is indeed due to the unexpected checkout path. The project was initially a non-go-module project and most of the build scripts still use the expectation that it is checked out in `~/go/src/github.com/DataDog/datadog-agent` I believe. If you want to build the source from a different path, you can change some of those CGO lines in `aggregator.py` to make it build ([the lines that need changing](https://github.com/DataDog/datadog-agent/blob/main/pkg/collector/python/aggregator.go#L18-L20)):
```diff
-#include <datadog_agent_rtloader.h>
+#include "datadog_agent_rtloader.h"
- #cgo !windows LDFLAGS: -ldatadog-agent-rtloader -ldl
+#cgo !windows LDFLAGS: -L${SRCDIR}/../../../rtloader/build/rtloader -ldatadog-agent-rtloader -ldl
-#cgo windows LDFLAGS: -ldatadog-agent-rtloader -lstdc++ -static
+#cgo windows LDFLAGS: -L${SRCDIR}/../../../rtloader/build/rtloader -ldatadog-agent-rtloader -lstdc++ -static 
+#cgo CFLAGS: -I "${SRCDIR}/../../../rtloader/include"  -I "${SRCDIR}/../../../rtloader/common"
```

I'll close this issue for now as it has been resolved it seems but feel free to reopen if needed.
