### ISSUE TITLE
How do we customize the Admission Controller webhook timeout?

### ISSUE THREAD

**Issue by diranged** [DataDog/datadog-agent#7387]
(this is a copy of https://github.com/DataDog/datadog-operator/issues/220, but put into the right repo)

**Describe what happened:**
The Admission Controller MutatingWebhookConfiguration is created with a 30s timeout. I would like to be able to lower this down to 1 or 2 seconds. We ran into an issue over the weekend where a mistake in a NetworkPolicy caused the APIServer->DatadogOperator API calls to fail. They took 30s to time out, which then slowed the entire APIServer down. That ultimately lead to a high rate of registration failures for new nodes joining our clusters. All of our other WebhookConfigurations have low timeouts set.

```
Name:         datadog-webhook
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1
Kind:         MutatingWebhookConfiguration
Metadata:
...
  Resource Version:  42875294
  Self Link:         /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/datadog-webhook
  UID:               deda10ff-ca41-4e2b-bf3c-ed02bac00af6
Webhooks:
  Admission Review Versions:
    v1beta1
  Client Config:
     Ca Bundle:  LS0t...
    Service:
      Name:        datadog-admission-controller
      Namespace:   datadog-operator
      Path:        /injecttags
      Port:        443
  Failure Policy:  Ignore
  Match Policy:    Exact
  Name:            datadog.webhook.tags
  Namespace Selector:
  Object Selector:
    Match Expressions:
      Key:       admission.datadoghq.com/enabled
      Operator:  NotIn
      Values:
        false
  Reinvocation Policy:  Never
  Rules:
    API Groups:
      
    API Versions:
      v1
    Operations:
      CREATE
    Resources:
      pods
    Scope:          *
  Side Effects:     None
  Timeout Seconds:  30
Events:             <none>
```

**Describe what you expected:**
I would like to be able to configure the timeout here and lower it to meet our operational needs. This configuration is not exposed currently (as far as I can tell) in the Datadog Operator or DatadogAgent CRD.

**Additional environment details (Operating System, Cloud provider, etc):**

Datadog Operator v0.4.0, EKS Kubernetes 1.18

**Comment by ahmed-mez** [comment]
Hi @diranged , it's possible to configure the admission controller timeout since Cluster Agent 1.12 https://github.com/DataDog/datadog-agent/pull/7855, Note that in Cluster Agent 1.13 the default value has become 10 seconds https://github.com/DataDog/datadog-agent/pull/8121

Closing the issue but let me know if you have further questions. Thanks!
