### ISSUE TITLE
Update files in Dockerfiles/manifests/

### ISSUE THREAD

**Issue by shigeya-dd** [DataDog/datadog-agent#7555]
**Describe what happened:**
Files in [Dockerfiles/manifests](https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/manifests) are automatically generated from the [helm chart](https://github.com/DataDog/helm-charts/tree/master/charts/datadog).

Current generated files are based on version 2.5.4 of the helm chart, while current version is 2.9.6. They have not incorporated recent fixes.

**Describe what you expected:**
Re-generate manifest files from the latest helm chart.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by L3n41c** [comment]
Fixed by #7461.
