### ISSUE TITLE
invoke system-probe.nettop  failed

### ISSUE THREAD

**Issue by qiffang** [DataDog/datadog-agent#7747]
I want to run nettop for testing, but it failed to run `system-probe.nettop `

**Output of the info page (if this is a bug)**
```
go: finding module for package github.com/DataDog/datadog-agent/pkg/ebpf/nettop
no matching versions for query "latest"
```

**Describe what happened:**

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by brycekahle** [comment]
Hi! We will get this fixed, but in the meantime, if you change `ebpf` to `network` here: https://github.com/DataDog/datadog-agent/blob/3a9f2559a616e2bdad04986541999609fce83166/tasks/system_probe.py#L297
that should fix it for you.
