### ISSUE TITLE
trace-agent: Treat 408 (Request Timeout) as a retriable error

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#7890]
Assuming the requests on `/api/v0.2/traces` and `/api/v0.2/stats` are idempotent, would it be reasonable to treat 408 (Request Timeout) as a retriable error? 

Currently, the agent does not retry sending the payloads upon 408s, logs messages like "Trace writer payload rejected by edge", and increments the `datadog.trace_agent.trace_writer.errors` metric. The status code of 408 may or may not indicate data loss, but the log message and the metric clearly say the data is lost. I have monitoring set up for these and it's unfortunate that it trips on 408s.

**Comment by gbbr** [comment]
You're right. I made a PR, we'll squeeze it in before the freeze tomorrow and it'll be part of the next release.
