### ISSUE TITLE
Datadog agent setup wizard ended prematurely

### ISSUE THREAD

**Issue by knanaiah001** [DataDog/datadog-agent#7932]
Hi Team ,

I'am facing below issue while installing Datadog agent in my system. Installation is failing with dialog box "Datadog agent setup wizard ended prematurely" even with valid API key. Could check on this?
Operating system  :win 10, 64 bit

![datadog](https://user-images.githubusercontent.com/68857336/115399597-0443fc80-a206-11eb-826f-c4cb84b94f49.PNG)

**Comment by olivielpeau** [comment]
Hi @knanaiah001, for your issue please [open a support ticket with our support team](https://www.datadoghq.com/support/) and share your windows installer logs (see [docs](https://docs.datadoghq.com/agent/basic_agent_usage/windows/?tab=gui#installation-log-files)) on the support ticket.

I'll go ahead and close this issue, let me know if you have any questions with these steps, thanks!
