### ISSUE TITLE
APM Agent CPU rate-limiting appears inconsistent

### ISSUE THREAD

**Issue by liamdawson** [DataDog/datadog-agent#8068]
```
===============
Agent (v7.27.0)
===============

  Status date: 2021-05-04 01:31:17.694 UTC (1620091877694)
  Agent start: 2021-05-04 01:28:32.211 UTC (1620091712211)
  Pid: 381
  Go Version: go1.14.12
  Python Version: 3.8.5
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Host Info
  =========
    kernelArch: x86_64
    kernelVersion: 4.14.123-111.109.amzn2.x86_64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: bullseye/sid

  Metadata
  ========
    cloud_provider: AWS
    hostname_source: aws
```

**Describe what happened:**

I found warning messages from the DataDog Agent saying:

```log
2021-05-04T01:00:16Z service/datadog:RLLAESRYMXM/3b60d20d9642 2021-05-04 01:00:16 UTC | TRACE | WARN | (pkg/trace/api/api.go:641 in watchdog) | CPU threshold exceeded (apm_config.max_cpu_percent: 50): 23
2021-05-04T01:00:26Z service/datadog:RLLAESRYMXM/3b60d20d9642 2021-05-04 01:00:26 UTC | TRACE | WARN | (pkg/trace/api/api.go:641 in watchdog) | CPU threshold exceeded (apm_config.max_cpu_percent: 50): 23
```

**Describe what you expected:**

That the CPU threshold wouldn't be exceeded if the right-hand value was lower than `apm_config.max_cpu_percentage`

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

Docker agent, running in ECS (on EC2).

Agent task configuration:

<details>
<pre>
{
  "ipcMode": null,
  "containerDefinitions": [
    {
      "dnsSearchDomains": [],
      "environmentFiles": [],
      "entryPoint": [],
      "portMappings": [
        {
          "hostPort": 8125,
          "protocol": "udp",
          "containerPort": 8125
        },
        {
          "hostPort": 8126,
          "protocol": "tcp",
          "containerPort": 8126
        }
      ],
      "command": [],
      "linuxParameters": {
        "capabilities": null,
        "sharedMemorySize": null,
        "tmpfs": [],
        "devices": [],
        "maxSwap": null,
        "swappiness": null,
        "initProcessEnabled": null
      },
      "cpu": 100,
      "environment": [
        {
          "name": "DD_API_KEY",
          "value": "..."
        },
        {
          "name": "DD_APM_ENABLED",
          "value": "true"
        },
        {
          "name": "DD_DOGSTATSD_NON_LOCAL_TRAFFIC",
          "value": "true"
        },
        {
          "name": "DD_LOG_LEVEL",
          "value": "INFO"
        },
        {
          "name": "DD_PROCESS_AGENT_ENABLED",
          "value": "true"
        },
        {
          "name": "DD_TAGS",
          "value": "\"...\""
        }
      ],
      "resourceRequirements": null,
      "ulimits": [
        {
          "name": "nofile",
          "softLimit": 1024000,
          "hardLimit": 1024000
        }
      ],
      "dnsServers": [],
      "mountPoints": [
        {
          "readOnly": null,
          "containerPath": "/host/sys/fs/cgroup/",
          "sourceVolume": "volume-0"
        },
        {
          "readOnly": null,
          "containerPath": "/host/proc/",
          "sourceVolume": "volume-1"
        },
        {
          "readOnly": null,
          "containerPath": "/var/run/docker.sock",
          "sourceVolume": "volume-2"
        }
      ],
      "workingDirectory": null,
      "secrets": [],
      "dockerSecurityOptions": [],
      "memory": 256,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "datadog:latest",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": [],
      "hostname": null,
      "extraHosts": [],
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "systemControls": [],
      "privileged": true,
      "name": "datadog"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "compatibilities": [
    "EC2"
  ],
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.privileged-container"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.22"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [],
  "networkMode": null,
  "cpu": null,
  "revision": 5,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": [
    {
      "fsxWindowsFileServerVolumeConfiguration": null,
      "efsVolumeConfiguration": null,
      "name": "volume-0",
      "host": {
        "sourcePath": "/sys/fs/cgroup/"
      },
      "dockerVolumeConfiguration": null
    },
    {
      "fsxWindowsFileServerVolumeConfiguration": null,
      "efsVolumeConfiguration": null,
      "name": "volume-1",
      "host": {
        "sourcePath": "/proc/"
      },
      "dockerVolumeConfiguration": null
    },
    {
      "fsxWindowsFileServerVolumeConfiguration": null,
      "efsVolumeConfiguration": null,
      "name": "volume-2",
      "host": {
        "sourcePath": "/var/run/docker.sock"
      },
      "dockerVolumeConfiguration": null
    }
  ]
}
</pre>
</details>

---

I found these lines when looking for context on the error message: https://github.com/DataDog/datadog-agent/blob/27a7638e6e6b18815bc5bcc7ce15d92147d9e0d7/pkg/trace/api/api.go#L638-L643

If I read that correctly, it's determining if it should rate-limit by comparing the configuration setting `r.conf.MaxCPU` (0.5) to the current `wi.CPU.UserAvg` (23), which would almost always cause rate-limiting? If that's not the case, why is it (only) `r.conf.MaxCPU*100` in the log message?

**Comment by jspc** [comment]
We're also seeing this, which we found when we noticed missing spans during an issue (which is the one time we don't want to be losing spans).

Does anybody have any resolution?

**Comment by liamdawson** [comment]
I'm still encountering this issue with the Datadog agent v7.30.1. This is a diagram of the self-reported CPU usage, then of the Datadog process view of the agent container's CPU usage (which, if I understand the UI correctly, is % of container limited CPU? The docs were unclear to me)

![image](https://user-images.githubusercontent.com/760143/131466264-40c98ac5-2153-4a0c-975b-557f67ab152b.png)

You can see that the second graph doesn't change considerably, and yet the Datadog agent suddenly reports immense CPU usage out of what's available. As a result, that agent is now dropping 95% of the traces being provided to it, which is problematic.

I've deployed it using [the recommended ECS service limits](https://docs.datadoghq.com/resources/json/datadog-agent-ecs.json): 100 CPU shares, 512MB of memory.

**Comment by jonas-paul** [comment]
We too see that the self-reported datadog.trace_agent.cpu_percent metric, which is used for rate limiting, is extremely volatile (first graph, note that the scale is logarithmic). It has absolutely no correlation with aws.ecs.service.cpuutilization metric from the AWS CloudWatch (second graph). The third graph shows that this causes rate limiting to alternate frequently between 1 and 0.05 for all agents. This makes tracing-based metrics useless because they become severely incomplete. It happens with both 7.27.0 and 7.30.1 agent versions.
![dd_cpu](https://user-images.githubusercontent.com/6959587/132500428-4ebcc837-32f3-41e6-8ecd-24d55b853527.png)

**Comment by ajgajg1134** [comment]
Hello all, Just wanted to chime in that version 7.37.0 includes a fix for the warning messages not showing the correct CPU usages. (We were incorrectly only applying `*100` to a single number and not both)
