### ISSUE TITLE
agent collect MYSQL metrics

### ISSUE THREAD

**Issue by freemindLi** [DataDog/datadog-agent#8118]
Excuse me, how does the datadog agent collect MySQL related indicators? I see that the docs says it comes with it https://docs.datadoghq.com/integrations/mysql/?tab=host#pagetitle, but I don't see the related process when I look at the datadog source code. Yes, the datadog I deployed can't collect MySQL related indicators, so I'll ask if it's the wrong configuration or other reasons?
![image](https://user-images.githubusercontent.com/59459626/117531110-80667e80-b013-11eb-9e62-c26b6c5e20bc.png)

**Describe what happened:**

**Describe what you expected:**

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by freemindLi** [comment]
![image](https://user-images.githubusercontent.com/59459626/117533748-1fde3e00-b021-11eb-85f5-c2b9d16a012e.png)
![image](https://user-images.githubusercontent.com/59459626/117533766-2f5d8700-b021-11eb-9455-876a03ec5c71.png)

**Comment by olivielpeau** [comment]
Hi @freemindLi, the MySQL integration is implemented in Python and its source code is available in the [integrations-core](https://github.com/DataDog/integrations-core/tree/master/mysql) repository.

Please make sure you've installed an official version of the Agent (following the [in-app instructions](https://app.datadoghq.com/account/settings#agent)).

If the agent `status` command doesn't provide more information, please open a ticket with our [support team](https://www.datadoghq.com/support/) and send them an [agent flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7#pagetitle).

I'll go ahead and close this issue, but please comment here if you're running into issues with these steps, thanks!

**Comment by freemindLi** [comment]
![image](https://user-images.githubusercontent.com/59459626/117640375-8d23d780-b1b7-11eb-99eb-8e882e4fe6f9.png)
hi @olivielpeau ,when II execute " invoke agent.build --build-exclude=systemd" This error occurred！Need your help，thank！

**Comment by freemindLi** [comment]
Hi @djova @olivielpeau ，execute me，how to import this module?
![image](https://user-images.githubusercontent.com/59459626/117910952-7a241b00-b30f-11eb-9ee3-045c8aac842f.png)

**Comment by djova** [comment]
> how to import this module?

It should already be included in the agent if you've installed an official version. How did you install the agent?
