### ISSUE TITLE
Documentation around Docker Labels for tagging is incorrect.

### ISSUE THREAD

**Issue by rhyas** [DataDog/datadog-agent#819]
https://docs.datadoghq.com/guides/tagging/ notes that Docker Labels are automatically propagated as tags, but this is not the case with the integration. Currently with the integration, you must white-list labels to be used as tags. 

Personally, I'd love to see the Integration fixed to match the documentation, rather than the other way around. Having to whitelist labels on every docker host is a huge pain.

**Comment by xvello** [comment]
Hi @rhyas,

Automatic collection will not be implemented, as that could lead to extremely noisy taglists in some orchestrators and schedulers. This is why whilelisting them is required, as it was in agent5.

Thanks for the input, I'm forwarding it to our technical writers so they can update the documentation.


Regards

**Comment by Overbryd** [comment]
I upgraded to Agent version >= 6 and now all my metrics are missing the `cluster-name` tag.

Unfortunately, after sifting through all documentation, I have no idea where the agent version < 6 got the label beforehand.

So I have no idea how to whitelist this label, as it is vitally important to distinguish our GKE clusters with that label. They are running the same applications (staging/production) and therefore this label was a very helpful dimension.

Can your technical writers maybe also list some very common GKE, Kubernetes and or Docker labels that are useful dimensions?

After this upgrade I am kind of lost on how to restore a good whitelist for my clusters.

**Comment by xvello** [comment]
hi @Overbryd , 6.2.1 addresses this issue https://github.com/DataDog/datadog-agent/pull/1702 , could you please confirm 6.3.0 / 6.2.1 restores that host tag?

**Comment by Overbryd** [comment]
Hi, I will need to test that.
Let me check this week.

Xavier Vello <notifications@github.com> schrieb am Do. 21. Juni 2018 um
18:34:

**Comment by Overbryd** [comment]
I am now running 6.3.2 and I am having no more issues with `cluster-name` not being set.

Thanks!

**Comment by xvello** [comment]
Great to hear! Closing the issue

**Comment by Overbryd** [comment]
Hi,

The agents are reporting `cluster-name` for me.
