### ISSUE TITLE
When will the updated MSK integration ship?

### ISSUE THREAD

**Issue by NobodysNightmare** [DataDog/datadog-agent#8219]
Hey there,

I see that the version of `amazon_msk` currently shipped with the agent is 1.4.1 (from January 2021). In the meantime, two newer versions of this integration got a changelog entry: https://github.com/DataDog/integrations-core/blob/master/amazon_msk/CHANGELOG.md

(These are from March and April)

However, the latest agent (released in May) is still using version 1.4.1 from January. Is there anything that's holding the upgrade to version 1.6.0 of Amazon Kafka back?

We are keenly awaiting the new metrics introduced in 1.5.0 :)

**Comment by olivielpeau** [comment]
Hi @NobodysNightmare, version 1.6.0 of the Amazon MSK integration was released with Agent v7.28.0 that just went out today (see the integration changelog [here](https://github.com/DataDog/integrations-core/blob/master/AGENT_CHANGELOG.md#datadog-agent-version-7280), which was updated today as well).

If you have any feedback on the integration, feel free to open an issue in the [integrations-core](https://github.com/DataDog/integrations-core/) repo (or open a support ticket with our support team).

I'll go ahead and close this issue, but let me know if you have further questions!
