### ISSUE TITLE
install_script.sh started to fail due to sudo permission

### ISSUE THREAD

**Issue by xike41** [DataDog/datadog-agent#8250]
Our Packer baking pipeline started to fail 2 days ago when installing Datadog agent by using https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh, the error log:

> 2021-05-26T14:29:49Z:     amazon-ebs: cat: /tmp/DATADOG_APT_KEY_CURRENT.public: Permission denied
2021-05-26T14:29:49Z:     amazon-ebs: gpg: WARNING: unsafe ownership on homedir '/home/ubuntu/.gnupg'
2021-05-26T14:29:49Z:     amazon-ebs: gpg: no valid OpenPGP data found.

I think this was caused by the latest change, however shall I expect a `sudo cat "/tmp/${key}"` on this line https://github.com/DataDog/datadog-agent/blob/218703bbb1d01aa46e58f746d0169791f137e4d0/cmd/agent/install_script.sh#L363 ?

**Comment by mx-psi** [comment]
Hey @xike41, thanks for reporting this! I opened #8257 to fix it.

While still supported, we no longer recommend using the Github URL for the install script; we instead recommend using https://s3.amazonaws.com/dd-agent/scripts/install_script.sh which should be more stable.
