### ISSUE TITLE
DD-(Forwarder|Collector|Dogstatsd)-Version headers

### ISSUE THREAD

**Issue by GeorgeErickson** [DataDog/datadog-agent#829]
It'd be nice to add version headers for parity with agent5 and tagging of datadog internal metrics.

- [`DD-Forwarder-Version`](https://github.com/DataDog/dd-agent/blob/2ac28118c5816532aa8ae70fd156cb383d1d4d0a/ddagent.py#L191)
- [`DD-Collector-Version`](https://github.com/DataDog/dd-agent/blob/6d7d5afe387b1349c4893110d2e821a6359d2cf0/emitter.py#L282)
- [`DD-Dogstatsd-Version`](https://github.com/DataDog/dd-agent/blob/e1ee203d34d9d8388027b6f62fa8bbad4774f733/dogstatsd.py#L326)

**Comment by olivielpeau** [comment]
Not sure whether we should keep these 3 different headers or move to a single `DD-Agent-Version` header.

In Agent6 the collector and dogstatsd don't create their own payloads anymore, all the data that comes from them are serialized together and then sent by the forwarder. So if we kept all 3 headers, we'd end up always setting them all, and to the same version. So a `DD-Agent-Version` header would probably make more sense.

**Comment by GeorgeErickson** [comment]
`DD-Agent-Version` works for me, just need to update propjoe once it starts being sent.

**Comment by olivielpeau** [comment]
The version header has been added in #1122, and is currently included in the agent 6 builds that run on our staging infra. Will be part of the `rc.1` release.

cc @GeorgeErickson
