### ISSUE TITLE
Add Env var called `DD_APM_RECEIVER_SOCKET` to not conflict with `DD_DOGSTATSD_SOCKET`

### ISSUE THREAD

**Issue by smitthakkar96** [DataDog/datadog-agent#8371]
Since the sockets are supported for both StatsD and APM setting DD_AGENT_HOST would break either DogStatd or APM as they both have different paths. As per the helm chart the socket paths are as followed /var/run/datadog/apm.socket and /var/run/datadog/dsd.socket. Also support for sending APM traces via Sockets is not clearly documented (can create a separate issue if needed)

**Comment by gbbr** [comment]
Hi there 👋🏻 `DD_APM_RECEIVER_SOCKET` already exists ([link](https://github.com/DataDog/datadog-agent/blob/c06b6c8663747467dad0bbdcb00f6474c806aae2/pkg/config/apm.go#L79)). Does that solve your problem?
