### ISSUE TITLE
public.ecr.aws/datadog/agent:7.29.1 missing

### ISSUE THREAD

**Issue by bchew** [DataDog/datadog-agent#8620]
Latest 7.29.1 is not available at https://gallery.ecr.aws/datadog/agent but available at Docker Hub https://hub.docker.com/r/datadog/agent/tags?page=1&ordering=last_updated

**Comment by celenechang** [comment]
Hi @bchew , thank you for reporting and apologies for the trouble. The issue has been fixed and the image can now be found on ECR.
