### ISSUE TITLE
Why don't we enable Kubernetes State Metrics Core for the manifests?

### ISSUE THREAD

**Issue by grezar** [DataDog/datadog-agent#8623]
*This is not a bug report but a proposal.*

Hi, there. I'm a Kubernetes user and of course using datadog-agent to monitor my cluster.
Lately, kube-state-metrics (v2+) has been integrated as Kubernetes State Metrics Core with datadog cluster-agent.
https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm

And, it would be great (for non-Helm Charts user like me) if the datadog cluster-agent's manifests found [here](https://github.com/DataDog/datadog-agent/tree/main/Dockerfiles/manifests/cluster-agent) supports it.
To do so,  the following value has to be enabled on Helm and commit regenerated manifests to this repository.
```
kubeStateMetricsCore:
    enabled: true
```

What do you think about this proposal?

Thank you.

**Comment by kaitlavs** [comment]
This makes sense. Thanks for bringing this to our attention. We will create a documentation request for this internally. 

For now, you can enable this by adding the following to your DCA deployment by creating a configmap for the check with the following data: https://github.com/DataDog/helm-charts/blob/f74f7b00ae52103fcfe5b2a1c432749274e28460/charts/datadog/templates/cluster-agent-confd-configmap.yaml#L20-L44 

Mounting that configmap to the DCA deployment:

```
(...)
          volumeMounts:
            - name: confd
              mountPath: /conf.d
      volumes:
        - name: confd
          configMap:
            name: <configmap_name>

```

And adding these permissions to the DCA clusterrole: https://github.com/DataDog/helm-charts/blob/f74f7b00ae52103fcfe5b2a1c432749274e28460/charts/datadog/templates/cluster-agent-rbac.yaml#L213-L278 

Finally, disable the legacy check in the node agent using the env var:

```
          - name: DD_IGNORE_AUTOCONF
            value: "kubernetes_state"
```

Let me know if this is helpful!

**Comment by grezar** [comment]
Hi, @kaitlavs 
Finally, I got the updated manifest using Helm with `kubeStateMetricsCore` enabled by myself.

So I'm not in hurry anymore about this issue 👍🏼
