### ISSUE TITLE
Valid EKS cluster name fails validation

### ISSUE THREAD

**Issue by oblogic7** [DataDog/datadog-agent#8716]
```
2021-07-09 05:09:01 UTC | CORE | ERROR | (pkg/util/kubernetes/clustername/clustername.go:77 in getClusterName) | "black_usw2_uat_k8s" isn’t a valid cluster name. It must be dot-separated tokens where tokens start with a lowercase letter followed by lowercase letters, numbers, or hyphens, and cannot end with a hyphen nor have a dot adjacent to a hyphen and "ip-10-50-81-184.us-west-2.compute.internal-black_usw2_uat_k8s" must not exceed 255 chars
```

According to [EKS API documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#:~:text=Required%3A%20No-,name,-The%20unique%20name), cluster names may contain underscores.  [The pattern that is used for validating the cluster name appears to be crafted for GKE.  ](https://github.com/DataDog/datadog-agent/blob/d2453867d1c34de5da717b9246473acf7c938ce8/pkg/util/kubernetes/clustername/clustername.go#L37)

This appears to be the cause of issues we have with the pre-built Kubernetes dashboards not displaying cluster information when filtering by cluster name.  The values for cluster_name filter on the dashboards appear to be populating via the AWS integration which handles the underscores in the name just fine.  See support request #516773 for details.

**Comment by clamoriniere** [comment]
Hello, 
This check wasn't only introduced from GKE. here his the initial [PR](https://github.com/DataDog/datadog-agent/pull/4492) that introduced a check that verify we no "underscore" is present in the cluster-name

> Motivation
> If somebody tries to put an underscore in the cluster_name, the hostname built by the kubelet hostname provider is not RFC1123 valid and, as such, is rejected as a potential hostname.

Maybe AWS EKS is patching the cluster-name for sending it to the kubelet, how they are not using this information to name the node.

Could you please send us, some kubernetes node name (`kubectl get nodes`) from a cluster with an underscore in its name? 🙇

**Comment by clamoriniere** [comment]
Closing this issue because there has been no update for 2 years.
