### ISSUE TITLE
Snowflake integration with Datadog agent 6.30.0 is broken

### ISSUE THREAD

**Issue by mvgijssel** [DataDog/datadog-agent#8895]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

===============
Agent (v6.30.0)
===============

  Status date: 2021-08-16 14:36:45.611 UTC (1629124605611)
  Agent start: 2021-08-16 13:57:51.755 UTC (1629122271755)
  Pid: 3.957129e+06
  Go Version: go1.15.13
  Python Version: 3.8.10
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 1
  Log Level: warn

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 39µs
    System time: 2021-08-16 14:36:45.611 UTC (1629124605611)

  Host Info
  =========
    bootTime: 2021-07-28 14:15:10 UTC (1627481710000)
    kernelArch: x86_64
    kernelVersion: 5.8.0-1041-aws
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 20.04
    procs: 140
    uptime: 455h42m46s

  Metadata
  ========
    cloud_provider: AWS
    hostname_source: container

=========
Collector
=========

  Running Checks
  ==============

    snowflake (3.0.3)
    -----------------
      Instance ID: snowflake:xxx [WARNING]
      Configuration Source: file:/etc/datadog-agent/conf.d/snowflake.d/airflow.yaml
      Total Runs: 29
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 29
      Average Execution Time : 1m7.697s
      Last Execution Date : 2021-08-16 14:36:35 UTC (1629124595000)
      Last Successful Execution Date : 2021-08-16 14:36:35 UTC (1629124595000)

      Warning: Unable to connect to Snowflake: 250003: Failed to execute request: 'SSLSocket' object has no attribute 'connection'
```

**Describe what happened:**
Datadog agent version 6.30.0 breaks the integration with Snowflake probably related to this Snowflake connector issue https://github.com/snowflakedb/snowflake-connector-python/issues/324. 

After downgrading the Datadog agent to 6.29.1 using https://docs.datadoghq.com/agent/faq/agent-downgrade-minor/?tab=chef#debianubuntu the Snowflake integration is back to a working condition. 

**Describe what you expected:**
I expected the new version 6 of the Datadog agent to work with the Snowflake integration.

**Steps to reproduce the issue:**
1. Install Datadog Agent 6.30.0
2. Configure settings in `/etc/datadog-agent/conf.d/snowflake.d/`
3. Restart datadog agent

**Additional environment details (Operating System, Cloud provider, etc):**

- AWS EC2 machine
- Ubuntu 20.04.2 LTS (Focal Fossa)

**Comment by hithwen** [comment]
While a new agent version is released with https://github.com/DataDog/integrations-core/pull/9905
The issue can be mitigated with the following:

- On Agent 7 or Agent 6 with python 3:
 - Linux: `/opt/datadog-agent/embedded/bin/pip install snowflake-connector-python==2.5.1`
 - Windows: `%PROGRAMFILES%\Datadog\"Datadog Agent"\embedded<PYTHON_MAJOR_VERSION>\python -m pip install snowflake-connector-python==2.5.1`

- On Agent 6 with python 2:
 - Linux: `/opt/datadog-agent/embedded/bin/pip install requests ==2.23.0`
 - Windows: `%PROGRAMFILES%\Datadog\"Datadog Agent"\embedded<PYTHON_MAJOR_VERSION>\python -m pip install requests ==2.23.0`

**Comment by mvgijssel** [comment]
Thanks for the **very** quick resolution ❤️

**Comment by FlorianVeaux** [comment]
For anyone looking at this, agent 7.30.1 and 6.30.1 have just been released and resolve the issue.
