### ISSUE TITLE
Serverless: Lambda alias invocations do not pick up AWS tags

### ISSUE THREAD

**Issue by liveFreeOrCode** [DataDog/datadog-agent#8980]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**

A stack was created with a single hello world lambda.  The lambda was tested twice from the AWS UI.  Once, the function was tested directly, and the other time the alias was tested.  The tags that were defined on the function were not picked up in the alias trace. Also, the service header on the span reverted back to `aws.lambda` rather than the defined `service` tag.

**Describe what you expected:**

I expected the spans and the tags to match

**Steps to reproduce the issue:**

### Define the stack

**./bin/test_datadog_enhanced.ts**
```ts
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { TestDatadogEnhancedStack } from '../lib/test_datadog_enhanced-stack';

const app = new cdk.App();
new TestDatadogEnhancedStack(app, 'TestDatadogEnhancedStack', {
  /* If you don't specify 'env', this stack will be environment-agnostic.
   * Account/Region-dependent features and context lookups will not work,
   * but a single synthesized template can be deployed anywhere. */

  /* Uncomment the next line to specialize this stack for the AWS Account
   * and Region that are implied by the current CLI configuration. */
  // env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },

  /* Uncomment the next line if you know exactly what Account and Region you
   * want to deploy the stack to. */
  // env: { account: '123456789012', region: 'us-east-1' },

  /* For more information, see https://docs.aws.amazon.com/cdk/latest/guide/environments.html */
});
```

**./lib/handler/helloWorld.ts**
```ts
export const handler = async (event: any, context: any) => {
  return "Hello world";
};
```

**./lib/test_datadog-enhanced-stack.ts**
```ts
import { NodejsFunction } from "@aws-cdk/aws-lambda-nodejs";
import { Construct, Stack, StackProps, Tags } from "@aws-cdk/core";
import { Datadog } from "datadog-cdk-constructs";

export class TestDatadogEnhancedStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    Tags.of(this).add("env", "datadog-test");
    Tags.of(this).add("service", "datadog-test");

    const fn = new NodejsFunction(this, "Function", {
      entry: "./lib/handler/helloWorld.ts",
      functionName: "datadog-test",
      memorySize: 512,
    });

    fn.currentVersion.addAlias("live");

    const dd = new Datadog(this, "Datadog", {
      nodeLayerVersion: 61,
      extensionLayerVersion: 10,
      apiKey: "api-key",
    });

    dd.addLambdaFunctions([fn]);
  }
}
```

### Deploy the stack

```bash
yarn cdk deploy
```

### Test the function

![image (1)](https://user-images.githubusercontent.com/12355170/130618354-d27802c5-c53d-475a-b5ae-0919d48c5bdf.png)

### Test the alias

![image (2)](https://user-images.githubusercontent.com/12355170/130618378-ae6b76ee-fe7c-4f3e-9eea-ba1181d2d3e0.png)

### Compare the spans

![image (3)](https://user-images.githubusercontent.com/12355170/130618406-23b94e4b-2e63-4837-8320-2fe4c4710417.png)

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by liveFreeOrCode** [comment]
I also tried adding the ENV vars as well, and it doesn't help

```ts
      environment: {
        DD_ENV: "datadog-test-env",
        DD_SERVICE: "datadog-test-env",
        DD_VERSION: "1.0.0-env",
      },
```

**Comment by tianchu** [comment]
Thanks for submitting this issue @liveFreeOrCode! It sounds like a bug on our side when resolving Lambda tags on our backend using the `function_arn`. Since tags can only be apply at the function level, we should probably ignore the qualifier when resolving tags.

For Datadog folks, original slack conversation https://datadoghq.slack.com/archives/CFDPB83M4/p1629808055144900?thread_ts=1629734278.136100&cid=CFDPB83M4.

@DarcyRaynerDD, this does seem to be an important issue, let's prioritize it? Since we already have the `function_version` as a separate attribute, the easiest fix (a small breaking change though) is probably to remove the qualifier from `function_arn`? Can we also check wether this affects tags resolution on enhanced metrics?

**Comment by liveFreeOrCode** [comment]
Fixed via https://github.com/DataDog/datadog-agent/pull/9863
