### ISSUE TITLE
Spurious agent failures when initializing aggregator in serverless lambda environment

### ISSUE THREAD

**Issue by kgrover** [DataDog/datadog-agent#8987]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
We see spurious failures, one in every ~thousand invocations, from the datadog agent in an AWS Lambda environment. These errors lead to the lambda function invocation failing and cause a downstream internal server error response, since this lambda backs a gateway endpoint.

The full logs from this invocation (pulled from Cloudwatch logs) is:
```

START RequestId: 64ea99ad-8232-4bc0-9b4f-976ea586e2ce Version: 7 

{ "m": "aws.lambda.enhanced.invocations", 
"v": 1, 
"e": 1629864362, 
"t": [ "region:us-east-1", "account_id:<redacted>", 
"functionname:<redacted>", "executedversion:7", "resource:<redacted>:live", 
"cold_start:false", "memorysize:512", "runtime:python3.8", 
"datadog_lambda:v3.43.0", "dd_lambda_layer:datadog-python38_3.43.0" ] }

panic: assignment to entry in nil map

goroutine 134 [running]:
github.com/DataDog/datadog-agent/pkg/aggregator.sketchMap.getOrCreate(...)
/Users/maxime.david/dd/datadog-agent/pkg/aggregator/sketch_map.go:63
github.com/DataDog/datadog-agent/pkg/aggregator.sketchMap.insert(0xc00032a2a0, 0x6125c180, 0x26dee67422b41302, 0x406c400000000000, 0x3ff0000000000000, 0x0)
/Users/maxime.david/dd/datadog-agent/pkg/aggregator/sketch_map.go:34 +0x15a
github.com/DataDog/datadog-agent/pkg/aggregator.(*TimeSampler).addSample(0xc000354cc0, 0xc0003de380, 0x41d84970610b9581)
/Users/maxime.david/dd/datadog-agent/pkg/aggregator/time_sampler.go:63 +0xe5
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).addSample(...)
/Users/maxime.david/dd/datadog-agent/pkg/aggregator/aggregator.go:433
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).run(0xc000354c60)
/Users/maxime.david/dd/datadog-agent/pkg/aggregator/aggregator.go:754 +0xacc
 
created by github.com/DataDog/datadog-agent/pkg/aggregator.InitAggregatorWithFlushInterval.func1
/Users/maxime.david/dd/datadog-agent/pkg/aggregator/aggregator.go:176 +0x97

END RequestId: 64ea99ad-8232-4bc0-9b4f-976ea586e2ce

REPORT RequestId: 64ea99ad-8232-4bc0-9b4f-976ea586e2ce	Duration: 2024.52 ms	Billed Duration: 2025 ms	Memory Size: 512 MB	Max Memory Used: 226 MB

RequestId: 64ea99ad-8232-4bc0-9b4f-976ea586e2ce Error: exit status 2Extension.Crash

```

**Describe what you expected:**
Agent does not crash or cause the AWS Lambda function to exit unexpectedly.

**Steps to reproduce the issue:**
- Install datadog lambda layers to Lambda environment via AWS SAM

**Additional environment details (Operating System, Cloud provider, etc):**

- Using the AWS SAM installation instructions/macro to install the datadog lambda layers (python layer + extension layer)

```
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKey:<redacted>
      pythonLayerVersion: 43
      extensionLayerVersion: 9
      service: <redacted>
      env: <redacted>
```

Within the function, I'm importing 
```
from datadog_lambda.metric import lambda_metric
from datadog_lambda.wrapper import datadog_lambda_wrapper
```

I'm using the `@datadog_lambda_wrapper` decorator around my lambda handler, and one log-point of a custom metric (using `lambda_metric`) in the file.

I'm also running this function with 4 provisioned concurrent executions.

**Comment by kgrover** [comment]
Hi @nhinsch thank you for the response, appreciate it! I've just updated to extension layer version 10. I'll respond here when I have a stack trace from that version.

**Comment by kgrover** [comment]
Hi @nhinsch this has happened a few times since I upgraded to Lambda Extension layer version 10. Here's the stack trace:

```


==2021-09-11T15:19:23.102Z==  START RequestId: f247b1d4-c4f6-4d6a-a188-5898c7d207a0 Version: 6

==2021-09-11T15:19:23.105Z==
 {
    "m": "aws.lambda.enhanced.invocations",
    "v": 1,
    "e": 1631373563,
    "t": [
        "region:us-east-1",
        "account_id:[REDACTED]",
        "functionname:[REDACTED]",
        "executedversion:6",
        "resource:[REDACTED]:live",
        "cold_start:false",
        "memorysize:512",
        "runtime:python3.8",
        "datadog_lambda:v3.43.0",
        "dd_lambda_layer:datadog-python38_3.43.0"
    ]
}

[..some log statements from the lambda..]

INFO [dd.trace_id=6400095095735082402 dd.span_id=9317020523644487699]

== 2021-09-11T15:19:23.120Z==
panic: assignment to entry in nil map
goroutine 133 [running]:
github.com/DataDog/datadog-agent/pkg/aggregator.sketchMap.getOrCreate(...)
/tmp/dd/datadog-agent/pkg/aggregator/sketch_map.go:63
github.com/DataDog/datadog-agent/pkg/aggregator.sketchMap.insert(0xc0002ed050, 0x613cc8e4, 0x62dd9ea1d143c7a2, 0x4080000000000000, 0x3ff0000000000000, 0x1)
/tmp/dd/datadog-agent/pkg/aggregator/sketch_map.go:34 +0x15a
github.com/DataDog/datadog-agent/pkg/aggregator.(*TimeSampler).addSample(0xc00030ca00, 0xc000352420, 0x41d84f323975c28f)
/tmp/dd/datadog-agent/pkg/aggregator/time_sampler.go:63 +0x116
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).addSample(...)
/tmp/dd/datadog-agent/pkg/aggregator/aggregator.go:448
github.com/DataDog/datadog-agent/pkg/aggregator.(*BufferedAggregator).run(0xc00030c9a0)
/tmp/dd/datadog-agent/pkg/aggregator/aggregator.go:773 +0xaac
created by
github.com/DataDog/datadog-agent/pkg/aggregator.InitAggregatorWithFlushInterval.func1
/tmp/dd/datadog-agent/pkg/aggregator/aggregator.go:187 +0x97

== 2021-09-11T15:19:25.138Z ==

END RequestId: f247b1d4-c4f6-4d6a-a188-5898c7d207a0
REPORT RequestId: f247b1d4-c4f6-4d6a-a188-5898c7d207a0	Duration: 2034.29 ms	Billed Duration: 2035 ms	Memory Size: 512 MB	Max Memory Used: 204 MB	XRAY TraceId: 1-613cc8fb-347cdbd9024ae95e239275e3	SegmentId: 4198f09800169eb0	Sampled: true
RequestId: f247b1d4-c4f6-4d6a-a188-5898c7d207a0 Error: exit status 2Extension.Crash

```

I've left the timestamps in here; this crash happened ~20ms after the start of the function, and we got the `END` logline ~2 seconds later. Please let me know how I can provide more information!

**Comment by kgrover** [comment]
One point of clarification: we're seeing this crash (intermittently) in at least two functions. I mentioned in the first example that I was wrapping the handler in `datadog_lambda_wrapper` and was also emitting a custom metric using `lambda_metric`. In the above example (most recently), I'm doing _neither_. The actual python code for the function has no mention of datadog; I believe everything is being captured via the layer & extension added with the SAM transform.

**Comment by kgrover** [comment]
@nhinsch and @maxday anything we can do our end to debug these failures, or workarounds you'd suggest in the meantime?

**Comment by mbergal** [comment]
We have the same problem, happens not only on startup.

![image](https://user-images.githubusercontent.com/167835/134620556-3cd44d20-0cf3-4a0d-89bc-12fd5692ada3.png)

**Comment by kirooshu** [comment]
Same issue as @Vesquen above, we get the `fatal error: concurrent map read and map write` in `github.com/DataDog/datadog-agent/pkg/metrics.ContextMetrics.AddSample`. I can provide more information if needed but we are using `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:11` currently (same problem with the `x86_64` version of the Lambda Extension)

**Comment by DarcyRaynerDD** [comment]
👋  Hi, in v12 of the Lambda Extension and later, we have a fix for this issue https://github.com/DataDog/datadog-agent/pull/9507/files . We recommend you upgrade, and let us know if you see any further issues.
