### ISSUE TITLE
[dogstatsd6] Limit mem consumption (& drop packets) when aggregator is behind

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/datadog-agent#913]
**Describe what happened:**

When the agent6 dogstatsd receives a high number of points per second such that it makes the aggregator lag behind, it still tries to submit to the aggregator all the points it receives, which can make dogstatsd use an unbounded amount of memory (and goroutines).

One very telling symptom is that the goroutine count increases indefinitely, all the goroutines submitting points to the aggregator will wait on a `chan send` here: https://github.com/DataDog/datadog-agent/blob/master/pkg/dogstatsd/server.go#L155

(and there's no bound on the number of goroutines that can wait on the `chan send` since we create one goroutine per network packet)

**Describe what you expected:**

The dogstatsd should drop packets when the aggregator is behind.

**Steps to reproduce the issue:**

Hammer dogstatsd with a high number of packets (say >100K points per second).

The mem usage and the goroutine count will increase indefinitely.

**Comment by olivielpeau** [comment]
@xvello is looking into improving dogstatsd throughput in general, one of the improvements is to avoid creating one goroutine per UDP/UDS packet, which should incidentally solve this issue

**Comment by xvello** [comment]
https://github.com/DataDog/datadog-agent/pull/952

**Comment by olivielpeau** [comment]
Fixed in #952
