### ISSUE TITLE
HPA on several metrics with the same name

### ISSUE THREAD

**Issue by alsyia** [DataDog/datadog-agent#9203]
Hey everybody,

I'm trying to scale a deployment with an HPA based on two metrics with the same name but different labels (messages waiting in two different pubsub subscriptions). As far as I can tell this is not supported yet (see https://github.com/DataDog/datadog-agent/blob/main/pkg/util/kubernetes/apiserver/controller_util.go#L184). There is this [old issue](https://github.com/DataDog/datadog-agent/issues/3872) by @andysnowden describing the exact same problem.

I have two questions:
* Is there a place where I can upvote the feature request or see its status? This is an important feature for us.
* What are the possible workarounds? @DylanLovesCoffee told to the old issue author that it's possible to define an HPA per metric, but wouldn't the recommendations conflict? Will Kube choose the highest one in this case?

I saw that having a secondary HPA with the secondary metric kind of fixes the bug, but just like @andysnowden we don't have a reference to point the secondary HPA to.

Thanks! :)

**Comment by vboulineau** [comment]
Hi @alsyia,

This should be supported by using `DatadogMetric` CRD: https://docs.datadoghq.com/agent/cluster_agent/external_metrics/?tab=helm#autoscaling

As explained [in the documentation](https://docs.datadoghq.com/agent/cluster_agent/external_metrics/?tab=helm#migration), you don't need to create `DatadogMetric` CR, activating the feature is enough to make this work.

**Comment by alsyia** [comment]
Hi @vboulineau,

Thanks, we will try this when we can!
