### ISSUE TITLE
[logs] systemd journal input

### ISSUE THREAD

**Issue by sj26** [DataDog/datadog-agent#948]
We setup our system services to log to the [systemd journal](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html). There are many good reasons — it's how services on a systemd system should be logging, it doesn't require logrotating and doesn't run out of disk space, it stores rich logs by default with strong provenance, etc. At the moment we're ingesting these into CloudWatch Logs using [journald-cloudwatch-logs](https://github.com/saymedia/journald-cloudwatch-logs). It'd be really nice if the datadog log agent could also ingest from the systemd journal.

I'd be willing to work on a PR if merging would be considered. 🤗

**Comment by NBParis** [comment]
Hello @sj26,

Thanks a lot for your request. 
Being able to tail log directly from Journald in the Agent is something we are looking at and is definitely on our roadmap.

Until this is done, our suggestion is to use Rsyslog to forward those logs directly to your Datadog platform as explained [here](https://help.datadoghq.com/hc/en-us/articles/115005086506-How-to-Send-Logs-to-Datadog-via-External-Log-Shippers).

I have added your name to the request for tracking and I'll make sure to let you know as soon as this feature is available.

Thanks,
Nils

**Comment by NBParis** [comment]
Hello,

The feature has been released and is available in the version 6.3 of the Datadog Agent.
Find here our documentation for the journald integration: https://docs.datadoghq.com/integrations/journald/

Don't hesitate to reach out to support@datadoghq.com if you have any question.
