### ISSUE TITLE
Request: logs in JSON format

### ISSUE THREAD

**Issue by jonmoter** [DataDog/datadog-agent#971]
We're ingesting all of our logs into an ELK-like stack using Fluentd. It's much easier for us to handle logs when each entry is a JSON hash, rather than a string that needs parsing.

Ideally, have a flag in the agent configuration to specify a JSON log format.

**Comment by masci** [comment]
Hi @jonmoter thanks for reaching out.
The logging library we're using does support JSON output so this might be rather easy to implement. Adding to the backlog.

**Comment by masci** [comment]
Implemented in https://github.com/DataDog/datadog-agent/pull/1124 it's available in 6.0 already, closing.
