### ISSUE TITLE
Please also build docker dogstatsd image for arm64

### ISSUE THREAD

**Issue by kenaniah** [DataDog/datadog-agent#9784]
The agent's docker image is built for both amd64 and arm64, but the dogstatsd is currently only built for amd64.

Could you please build & publish an arm64 version of the image as well? Looking to run dogstatsd on AWS graviton instances.

**Comment by kenaniah** [comment]
@KSerrania for visibility...

**Comment by albertvaka** [comment]
Hi! Indeed, we don't currently publish arm64 versions of dogstatsd images. We will track this as a feature request, and consider it for future releases. In the meantime, maybe it would work for you to use the full Agent image and disable the default monitoring (if you only need dosgatsd)?

**Comment by kenaniah** [comment]
@albertvaka in going through the datadog docs, I wasn't able to find how I would configure & use the agent docker image in a way that reflects how we're currently using dogstatsd. That was the first thing I tried (and to no avail), but the docs that are available seem to be incomplete for this use case.

**Comment by odidev** [comment]
I am also looking to use **dogstatsd** image in **arm64**. As it is not available, I have successfully built the image for arm64 platform, using the command  `inv dogstatsd.image-build` in my arm64 local server.

I have tried building multiarch images using **docker buildx** command, but it requires dogstatsd binary to be built first, so I have built binary using command `invoke agent.build --build-include=zstd,etcd,python` . 

To build both amd64 and arm64 images with buildx command, binaries need to be built for both platforms along with building images. We may have to add binary build steps in dockerfile if we need to use buildx. If not, we need to build separately with different tags for each platform (like dogstatsd-arm64).

May I know how you are publishing images to dockerhub?
If interested, I can add binary steps in dockerfile and raise a PR. Please let me know your opinion on the same.

**Comment by albertvaka** [comment]
We are adding arm64 dogstatsd images in this PR: https://github.com/DataDog/datadog-agent/pull/10574
