### ISSUE TITLE
Monitor container graceful exits

### ISSUE THREAD

**Issue by Nevon** [DataDog/datadog-agent#9785]
**Describe what happened:**
We provide a service runtime platform for a large Datadog customer, running tens of thousands of Docker containers belonging to hundreds of teams and services. We would like to be able to monitor the exit status of the containers to determine which services are not shutting down gracefully when containers are rescheduled or redeployed.

I was hoping to use the `docker.exit` check or the Docker events to do this, but it looks like the exit code is never exposed as a tag on anything, and the check is hard-coded to be critical on anything other than exit code 0. https://github.com/DataDog/datadog-agent/blob/67ad9186a0561b25829315428a26a21e853022ee/pkg/collector/corechecks/containers/docker/docker_events.go#L64-L66

This is a fairly reasonable expectation, but what we've found is that quite a lot of applications following [the semi-standard approach](https://tldp.org/LDP/abs/html/exitcodes.html) of exiting with 128+_n_, where _n_ is the signal that caused the application to exit. In our case, we send a sigterm (15) to signal the container to exit, so a container might gracefully exit with 128+15.

Since no event nor the check seem to actually expose the exit code, I don't know yet if there are other common patterns we have to take into account, but having the check hardcoded to 0 makes it useless for our purposes.

**Describe what you expected:**

I see a few possible solutions:

**Making the check configurable**: Allow a configuration of the condition determining if the check is critical or not. If this was a list of exit codes as an instance configuration of the check, this would mean that we could either have a fixed list (`[0, 128+15]`) or could even configure this per-container.

**Tag Docker events with `exitCode`**: If the Docker events had the `exitCode` as a tag, we could build whatever monitors we wanted on top of them. The event already contains the `exitCode` attribute, since that's what's used by the check, it's just not added as a tag when the event is sent to Datadog. Events, being far more flexible than checks, would mean that we could actually start to aggregate this to figure out how often containers are exiting non-gracefully and possibly identify if there are other patterns than 128+n we need to take into consideration.

**Expose container exits as a metric**: This would be the dream. If the agent reported a counter of container exits with the `exitCode` as a tag, it would be trivial to do all of the above.

**Comment by clamoriniere** [comment]
Hi @Nevon 

Thanks for opening this issue to describe the use case, and the attended behaviour.

We made some test, and we can confirm that the [exit code (128+ sig number)]( https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html) is something we should support. 

We will work to address it in the next agent version "7.33.0". We are still discussing it is make sens to support other exit code.

About For the exit code in the Datadog docker event, it is something that we in our roadmap, but it requires prerequisite work on how we transform and send the docker event. It will be addressed in a more long-term timeline.

**Comment by Nevon** [comment]
I agree that probably having metrics with the required event tags is probably the best solution. I don't necessarily see the issue with a metric that "disappears", since you could do a sum rollup, but you can do the same by counting the number of events, so it's fine either way.

> do you think it is worth implementing a new docker AD label to support per container exit-code configuration, or it is OK to support by default 0,143 as OK code?

I can't really tell yet, because the events don't have the exit code, so I have no way of seeing what exit codes containers are exiting with. But from what I know right now 0 and 143 are the only "expected successful" exit codes we know of from services running on our platform. Changing that if-statement to check for both 0 and 143 instead of just 0 is a trivial change, so I don't see a reason to delay that in favor of a more complex solution.

My input would be that if getting the exit code as a tag on the event is something that's actually on the roadmap to happen in the not too distant future, then there's no point in introducing the relative complexity of a configuration option for this, since it's much easier to create a monitor with custom logic based on the events.
