### ISSUE TITLE
About seelog internal error: close /var/log/datadog/system-probe.log: file already closed

### ISSUE THREAD

**Issue by orz-nil** [DataDog/datadog-agent#9952]
**Output of the info page (if this is a bug)**
```
2021-11-18 07:22:18 UTC | SYS-PROBE | WARN | (pkg/util/log/log.go:541 in func1) | Unknown key in config file: runtime_security_config.debug
seelog internal error: rename /var/log/datadog/system-probe.log /var/log/datadog/system-probe.log.1: operation not permitted
2021-11-18 07:22:18 UTC | SYS-PROBE | WARN | (pkg/util/log/log.go:541 in func1) | Unknown key in config file: system_probe_config.conntrack_max_state_size
seelog internal error: close /var/log/datadog/system-probe.log: file already closed
```

**Describe what happened:**
renameat2 not in `system-probe-seccomp.json` `syscalls` . 
When the log `/var/log/datalog/system-probe.log` size > 11M, the process system-probe will rename it. but operation not permitted. 
at this time the file `/var/log/datadog/system-probe.log` has been closed. So after that, every time the process has new log, will get the error `seelog internal error: close /var/log/datadog/system-probe.log: file already closed`.

**Describe what you expected:**
fix the bug, add 'renameat2' to syscalls. or just print the log to stdout in docker container.

**Steps to reproduce the issue:**
just add `/var/log/datadog/system-probe.log` file size to 11MB. 
system-probe will try to rotate log.

**Additional environment details (Operating System, Cloud provider, etc):**
ENV:
- kubernetes version: 1.19.15
- datadog version: 7.27.0
- OS: Ubuntu 20.04.3 LTS

**Comment by brycekahle** [comment]
This is fixed in the latest Helm chart
